### ISSUE TITLE
Placeholder (%) fail to compile

### ISSUE THREAD

**Issue by jeffpatzer** [sass/libsass#101]
We have this CSS:

``` scss
///////////////////////
//   global styles   //
///////////////////////
%html {
  width:100%;
  height:100%;
}

%document {
  width:100% !important;
  min-height:100%;
  background:$background-color;
  margin:0;
  padding:0;
}

%hr {
  border:0;
  border-bottom:1px solid $border-color;
  margin:$gutter auto;
  clear:both;
}

%img {
  max-width:100%;
  border:none;
}

@if $tags {
  $elements: html hr img;
  @for $i from 1 through length($elements) {
    #{nth($elements, $i)} {
      @extend %#{nth($elements, $i)};
    }
  }
  html, body {
    @extend %document;
  }
  a img {
    @extend %img;
  }
}

@if $classes {
  $names: html document hr img;
  @for $i from 1 through length($names) {
    .#{nth($names, $i)} {
      @extend %#{nth($names, $i)};
    }
  }
}
```

This does not compile
