### ISSUE TITLE
& interpolation in attribute selector doesn't work

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1016]
Related to https://github.com/sass/libsass/issues/978

```scss
.foo {
  [baz="#{&}"] {
    foo: bar;
  }
}
```

Expected output

```css
.foo [baz=".foo"] {
  foo: bar;
}
```

Output in Libsass 3.2.0-beta.4

```css
.foo [baz=""] {
  foo: bar;
}
```

Specs added https://github.com/sass/sass-spec/pull/318
