### ISSUE TITLE
CSS escapes

### ISSUE THREAD

**Issue by emagnier** [sass/libsass#102]
I'm using the font-icons method (via the `@media` rule) which display a specific character (the icon) via the CSS `content` property in a pseudo class (`:before`/`:after`).

For some special characters my tool adds a backslash before it, which is valid and compiles well with the official ruby compiler:

``` css
[data-icon='test-1']:before {
    content:'\\';
}

[data-icon='test-2']:before {
    content:'\'';
}

[data-icon='test-3']:before {
    content:"\"";
}
```

But with Libsass I get this error message:
`error reading values after '\\';`

I also made a search about this and discovered the CSS escape can be use in the selectors:

``` css
.\E9motion { ... }
.\E9 dition { ... }
.\0000E9dition { ... }
```

These selectors represent the word `émotion` and `édition`.
More details here: http://www.w3.org/International/questions/qa-escapes
