### ISSUE TITLE
Block comment after numbers throws error

### ISSUE THREAD

**Issue by mzgol** [sass/libsass#1021]
The following SCSS:
```scss
div {
    top: 10px - 2 * 5px /* arrow size */;
}
```
causes an error:
```
>> error reading values after /
>>   Line 2  Column 25  app/modules/components/base/item-panel/item-panel-sidebar/_item-panel-sidebar.tmp.scss
```
node-sass `3.0.0-beta.4`. Ruby Sass parses it fine.

This is similar to #890.
