### ISSUE TITLE
Incorrect indentation in a comment

### ISSUE THREAD

**Issue by mgol** [sass/libsass#1026]
The following SCSS:

``` scss
div {
    a {
        /**
         * a
         * multiline
         * comment
         */
        top: 10px;
    }
}
```

libsass from node-sass `3.0.0-beta.4` turns into:

``` css
div a {
  /**
         * a
         * multiline
         * comment
         */
  top: 10px; }
```

Latest Ruby Sass gives:

``` css
div a {
  /**
   * a
   * multiline
   * comment
   */
  top: 10px; }
```
##
