### ISSUE TITLE
A lost rule when extending inside a double for loop

### ISSUE THREAD

**Issue by mzgol** [sass/libsass#1029]
The following SCSS:
```scss
@for $i from 1 through 2 {
    %shift-#{$i - 1} {
        margin-left: $i * 1px;
    }
    .week-start-#{$i} {
        @for $j from 1 through 2 {
            .month-start-#{$j} {
                @extend %shift-#{($j - $i - 1) % 2};
            }
        }
    }
}
```
libsass from node-sass `3.0.0-beta.4` turns into:
```css
.week-start-1 .month-start-2, .week-start-2 .month-start-1 {
  margin-left: 1px; }
```
Latest Ruby Sass gives:
```css
.week-start-1 .month-start-2, .week-start-2 .month-start-1 {
  margin-left: 1px; }

.week-start-1 .month-start-1, .week-start-2 .month-start-2 {
  margin-left: 2px; }
```

**Comment by mgreter** [comment]
This could be related to https://github.com/sass/libsass/issues/592

**Comment by mzgol** [comment]
Spec submitted: https://github.com/sass/sass-spec/pull/300

**Comment by mgreter** [comment]
This seems to be related to how we eval `Selector_Placeholder` ... seems to involve refactoring!

**Comment by mgreter** [comment]
Analized the test today and found out that the underlying problem is quite simple to solve.
This issue is caused by a discrepancy in the modulo operator, as in this example:

```css
foo { test: #{-1 % 2}; }
foo { test: -1; } // libsass
foo { test: 1; } // ruby sass
```

@xzyfer I will cherry pick this fix and PR it separately later, so this can be included in 3.2.5!
