### ISSUE TITLE
Investigate when (not) to insert the double linefeed

### ISSUE THREAD

**Issue by mgol** [sass/libsass#1030]
Note: this will probably be fixed by ruby sass itself!

Libsass & Ruby Sass in many cases insert a double linefeed, e.g. after a block. There are differences in various edge cases, though, like what I reported in #1028. This requires investigation to what is the exact algorithm to generate those newlines.

An issue opened by advice from @mgreter.

**Comment by mzgol** [comment]
Spec submitted: https://github.com/sass/sass-spec/pull/299

**Comment by mgreter** [comment]
I think I got a little further here (I actually missed that `@support` is indented in your example)

```scss
div {
  top: 10px;
  @supports (will-change: transform) {
    will-change: transform;
  }
}

div {
  @supports (will-change: transform) {
    will-change: transform;
  }
  bottom: 10px;
}

div {
  @supports (will-change: transform) {
    will-change: transform;
  }
  @supports (will-change: transform) {
    will-change: transform;
  }
}
```

Ruby sass will output this:
```css
div a {
  top: 10px; }
  @supports (will-change: transform) {
    div a {
      will-change: transform; } }
div a {
  bottom: 10px; }
  @supports (will-change: transform) {
    div a {
      will-change: transform; } }
@supports (will-change: transform) {
  div a {
    will-change: transform; } }
@supports (will-change: transform) {
  div a {
    will-change: transform; } }
```

So it seems that ruby sass adds indentation only if the original block contains some other declarations. It is quite likely that this also indicates when to insert a double linefeed!
