### ISSUE TITLE
Parameter value as color name

### ISSUE THREAD

**Issue by yonidor** [sass/libsass#1036]
Hi,
I encountered a weird issue:
I wrote a spritesheet generation framework with scss, and somewhere i have a mixin looking like this:
```
@mixin icons-sprite($icon-name){
	@if $icon-name == 'all-vip' {
		@include all-vip();
	}
	@else if $icon-name == 'gold' {
		@include gold();
	}
	@else if $icon-name == 'platinum' {
		@include platinum();
	}
}
```

Problem is that when i call the mixin like this `@include icons-sprite(gold)`, it does not fulfill the if statement, but when i use `@include icons-sprite(platinum)`, it does work.

I guess it is related to the fact that gold is a name of a color in libsass, thus it does not parse it well, but i want to know if a fix for this case is possible.

**Comment by mgreter** [comment]
Please try to provide runable code sample. Otherwise it is tedious to reconstruct the missing bits!

Anyway, your correct with your observation, but that's also how ruby sass does it. So I'm going to close this, but will add a spec test, so we catch if ruby sass ever decides to change its behavior here!

```CSS
@mixin all-vip() {
  test: vip;
}
@mixin gold() {
  test: gold;
}
@mixin platinum() {
  test: platinum;
}

@mixin icons-sprite($icon-name){
    @if $icon-name == 'all-vip' {
        @include all-vip();
    }
    @else if $icon-name == 'gold' {
        @include gold();
    }
    @else if $icon-name == 'platinum' {
        @include platinum();
    }
}

div {
  @include icons-sprite("platinum");
  @include icons-sprite("all-vip");
  @include icons-sprite("gold");
}
div {
  @include icons-sprite(platinum);
  @include icons-sprite(all-vip);
  @include icons-sprite(gold);
}
```

Ruby Sass 3.4.13:
```CSS
div {
  test: platinum;
  test: vip;
  test: gold; }

div {
  test: platinum;
  test: vip; }
```
