### ISSUE TITLE
Parent selector next to anything causes error

### ISSUE THREAD

**Issue by stol** [sass/libsass#1042]
Hello,

I have the following problem, when trying to work with libsass and BEM syntax. The following code work with ruby sass but not with libsass.

Real world example :

```scss
// real world exa
.component{
    color: red;
    &--foo&--bar {
        color: blue;
    }
}

// outputs "invalid selector after --foo"

// Expected result: 

.component{
    color: red;
}
.component--foo.component--bar{
    color: blue;
}
```

Basic example:

```scss
.test{
    .selector& {
        color: blue;
    }
}

// outputs "invalid selector after .selector"

// Expected result: 
.selector.test{
    color: blue;
}

```

Thank you for the hard work !
