### ISSUE TITLE
Error with `&` selector interpolation in `@at-root` blocks

### ISSUE THREAD

**Issue by stol** [sass/libsass#1043]
Hello,

I have a different behaviour with & parent selector, between sass and libsass

```scss
.component{
    color: red;
    @at-root{
        #{&}--foo#{&}--bar {
            color: blue;
        }
    }
}

.test{
        .selector#{&} {
            color: blue;
        }
}
```

// libsass 3.4.0-beta.4 outputs: 
```css
.component {
  color: red; }
  .component--foo.component--bar {
    color: blue; }

.test .selector.test {
  color: blue; }
```

// Ruby sass outputs:
```css
.component {
  color: red; }
  .component .component--foo.component--bar {
    color: blue; }

.test .selector.test {
  color: blue; }
```

It works correctly when the interpolation is not inside `@at-root` blocks!

Thank you !

**Comment by ekskimn** [comment]
@xzyfer I don't think I have the rights to assign this issue to myself....would you mind assigning it to me?

**Comment by xzyfer** [comment]
@ekskimn looks like issues can only be assigned to core members

**Comment by ekskimn** [comment]
@xzyfer ah, got it =)

**Comment by mgreter** [comment]
@ekskimn you may add the `WIP` tag, so we know that someone may already working on it!

**Comment by xzyfer** [comment]
This still fails the spec.

**Comment by xzyfer** [comment]
Apologies, it looks like my local sass-spec is having issues.

**Comment by xzyfer** [comment]
This fix was a false positive due to https://github.com/sass/sass-spec/pull/380. The spec still fails.

**Comment by tedw** [comment]
I noticed another issue with `&` interpolation in `@at-root` blocks:

```scss
.foo {
  @at-root button#{&} {
    color: red;
  }
}

// Generated CSS has an additional selector prepended
.foo button.foo {
  color: red;
}
```
This wasn't a problem in `3.2.2`, only `3.2.3` and later.

I thought it made sense to include this here, but I'm happy to submit a separate issue if you prefer.

Thanks!
