### ISSUE TITLE
variables in font shorthand not expanded

### ISSUE THREAD

**Issue by twhid** [sass/libsass#106]
This seems like an issue only when there is a comma following the variable in font shorthand. The case is handled properly in direct font-family rules.

Test input:

``` scss
$a: "my-string";
$b: my-string;

.test1 {
    font: 12px/18px $a, sans-serif;
    font-family: $a, sans-serif;
}

.test2 {
    font: 12px/18px $b, sans-serif;
    background: $b url($a) repeat; 
    font-family: $b, sans-serif;    
}
```

Expected (Ruby Sass) output:

``` css
.test1 {
  font: 12px/18px "my-string", sans-serif;
  font-family: "my-string", sans-serif; }

.test2 {
  font: 12px/18px my-string, sans-serif;
  background: my-string url("my-string") repeat;
  font-family: my-string, sans-serif; }
```

Bad (sassc/libsass) output:

``` css
.test1 {
  font: 12px/18px $a, sans-serif;
  font-family: "my-string", sans-serif; }

.test2 {
  font: 12px/18px $b, sans-serif;
  background: my-string url("my-string") repeat;
  font-family: my-string, sans-serif; }
```
