### ISSUE TITLE
@elseif is not recognized

### ISSUE THREAD

**Issue by mzgol** [sass/libsass#1060]
The following SCSS:
```scss
div {
    @if true {
        display: block;
    } @elseif true {
        display: flex;
    }
}
```
is translated via libsass `3.2.0-beta.5` to:
```css
div {
  display: block; }

@elseif true {
  div {
    display: flex; } }
```
Ruby Sass translates it to:
```css
div {
  display: block; }
```
Changing `@elseif` to `@else if` resolves the issue.
