### ISSUE TITLE
libsass preserves new lines in nested style more often than Ruby Sass does

### ISSUE THREAD

**Issue by mzgol** [sass/libsass#1061]
Related: #552.

The following SCSS:
```scss
a {
    &.div,
    &.span {
        display: block;
    }
}
```
is generated by Sass 3.4.13 to the following CSS (when output style is set to nested):
```css
a.div, a.span {
  display: block; }
```

Meanwhile, libsass 3.2.0-beta.5 converts it to:
```css
a.div,
a.span {
  display: block; }
```

Note that `a` and `div` are in the same line in the Ruby Sass version.

There are cases when Ruby Sass does preserve new lines (like in the example from #552) so I'm not sure what's happening here.
