### ISSUE TITLE
Extending a %placeholder containing a parent reference produce incorrect output

### ISSUE THREAD

**Issue by timschoch** [sass/libsass#1063]
Hello
I'm not sure if this problem is new or related to a known one. & Selectors within a placeholder get ignored when the parent selector is generated on the fly. This is a simplyfied version of what we use to generate navigations. (eg. first level horizontally, second megamenu, third vertically, ...)

```sass
%submenu {
  &:hover > ul { display: block; }
}

ul.root {
  $nested: unquote( '' );
  @for $level from 1 through 3 {
    @if length( $nested ) > 1 {
      #{$nested} {
        > li { @extend %submenu; } 
      }
    } @else {
      > li { @extend %submenu; }
    }
    $nested: append( $nested, unquote( ' > li > ul' ) );
  }
}
```
This is what libsass renders
```css
ul.root > li:hover > ul {
  display: block;
}
```
And in comparission the sass output as I would expect it
```css
ul.root > li:hover > ul,
ul.root > li > ul > li:hover > ul,
ul.root > li > ul > li > ul > li:hover > ul {
  display: block;
}
```
Interestingly the behaviour changes when we add a class inside the loop
```scss
@for $level from 1 through 3 {
  @if length( $nested ) > 1 {
    #{$nested}.level#{$level} { // <- added level specific class
      > li { @extend %submenu; } 
     }
  } @else {
    > li { @extend %submenu; }
  }
   $nested: append( $nested, unquote( ' > li > ul' ) );
}

// renderes as expected
ul.root > li:hover > ul,
ul.root > li > ul.level2 > li:hover > ul,
ul.root > li > ul > li > ul.level3 > li:hover > ul {
  display: block;
}
```

And it's only the & Selector thats broken. If I add another selector to the placeholder the new one works.
```scss
%submenu {
  > a { color: blue; }
  &:hover > ul { display: block; }
}

// > a works
ul.root > li > a,
ul.root > li > ul > li > a,
ul.root > li > ul > li > ul > li > a {
  color: blue;
}
// &:hover doensn't
ul.root > li:hover > ul {
  display: block;
}
```
