### ISSUE TITLE
Tolerate no-space around comparison operator

### ISSUE THREAD

**Issue by am11** [sass/libsass#1068]
[Forwarding: https://github.com/sass/node-sass/issues/840]

Tested with latest master: 01352784469e685713654ebe457877a2f7abe3ff.

Given the input:

```scss
$on: false;
@if $on == false {
 s { a: ss }
}
```

LibSass generates:

```css
s {
  a: ss; }
```

If we remove a space right after `$on`:

```scss
$on: false;
@if $on== false {
 s { a: ss }
}
```

The generated output is same.

If we remove space both before and after `==`:

```scss
$on: false;
@if $on==false {
 s { a: ss }
}
```

It throws:
> error reading values after $on

If we remove space only before `false`:

```scss
$on: false;
@if $on ==false {
 s { a: ss }
}
```

It throws:
> error reading values after

(nothing after `after`)
