### ISSUE TITLE
Regression in selector interpolation

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1074]
The follow selector interpolation worked in 3.1.0 but fails with 3.2.0-beta.1 and above

```scss
$i: 1;
.foo#{-$i} { a:b }
```

3.2.0-beta.2 and above produce the following error
```
Error: invalid selector after .foo-
        on line 1 of test.scss
```

3.2.0-beta.1 also fails but reports a different line. A git bisect reports this regression was introduced in https://github.com/sass/libsass/commit/7877cfa872b036d55344db5d12ea908bb70f3705

The following variations work in all tested releases
```scss
$i: 1;
.foo-#{$i} { a:b }
.foo#{-1} { a:b }
.foo-#{1} { a:b }
```

Spec added https://github.com/sass/sass-spec/pull/309

Can you take a look @mgreter ?
