### ISSUE TITLE
Rest parameters not expanded with call

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1075]
The following fails in 3.2.0-beta.5

```scss
$args: ("color": #ff0000, "amount": 10%);
foo {
  bar: call(lighten, $args...);
}
```

with the following error

```
Error: required parameter $amount is missing in call to function lighten
        on line 3 of test.scss
>>   bar: call(lighten, $args...);
```

However using rest parameters without `call` works as expected

```scss
$args: ("color": #ff0000, "amount": 10%);
foo { 
  bar: lighten($args...);
}
```

The expected output is

```css
foo {
  bar: #ff3333; }
```

Specs added  https://github.com/sass/sass-spec/pull/310
