### ISSUE TITLE
Defaulting a mixin argument to a global variable of the same name doesn't behave the same as the official compiler

### ISSUE THREAD

**Issue by sorccu** [sass/libsass#108]
As requested by @chriseppstein in #92, I'm listing a few weird usage patterns that result in different behavior from the standard compiler.

I'll start by saying that I think this is a really stupid thing to do, but I did run into this issue while porting a large SCSS codebase to libsass.

The following snippet of SCSS:

``` scss
$a: red;

@mixin f($a: $a) {
  color: $a;
}

h1 {
  @include f;
}

h2 {
  @include f(blue);
}
```

Results in the following with the official compiler:

``` css
h1 {
  color: red; }

h2 {
  color: blue; }
```

But the following with libsass:

``` css
h1 {
  color: $a; }

h2 {
  color: blue; }
```
