### ISSUE TITLE
Issue with !default on globals within ruleset @imports

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1081]
Given the following, the final output of `foo` should always be `bar`

```scss
// input.scss
$foo: foo !global !default;

default {
  foo: $foo; }

$foo: bar;

after {
  foo: $foo;
  @import "import"; }
```
```scss
// _import.scss
import-before {
  foo: $foo; }

$foo: baz !global !default;

import-after {
  foo: $foo; }
```

However the `$foo: baz !global !default;` is clobbering the value of `$foo` even though it has the `!default` flag.

Spec added https://github.com/sass/sass-spec/pull/312
