### ISSUE TITLE
Variables in url() are not evaluated

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1087]
```scss
$foo: bar;
a {
  b: url($foo)
}
```

3.2.0-beta.5 

```css
a {
  b: url($foo); }
```

3.1.0 and Ruby Sass 3.4.12
```css
a {
  b: url(bar); }
```

A git bisect show that the regression was introduces in the latest beta in https://github.com/sass/libsass/commit/fd1814c58da94497142d929a5dd5be7c39d1ab70

Applying https://github.com/sass/libsass/pull/1085 which also addresses a regression in `url` from that commit doesn't fix the issue.

Spec added https://github.com/sass/sass-spec/pull/315
