### ISSUE TITLE
When extending a class included from another mixin, behavior differs from standard compiler

### ISSUE THREAD

**Issue by sorccu** [sass/libsass#109]
As requested by @chriseppstein in #92, I'm listing a few weird usage patterns that result in different behavior from the standard compiler.

I ran into this issue while porting a large SCSS codebase to libsass. I would never recommend anyone to do this, though. I had a hard time even coming up with a title for this issue.

The following SCSS:

``` scss
@mixin a {
  .foo {
    .zup {
      color: red;
    }
  }
}

@mixin b {
  @include a;
  #bar {
    @extend .foo;
  }
}

@include b;
```

Results in the following output with the standard compiler:

``` css
.foo .zup, #bar .zup {
  color: red; }
```

But the following with libsass:

``` css
.foo .zup {
  color: red; }
```

Essentially, the rules are lost in libsass.

**Additionally**, the following slightly different snippet:

``` scss
@mixin a {
  .foo {
    color: red;
  }
}

@mixin b {
  @include a;
  #bar {
    @extend .foo;
  }
}

h1 {
  @include b;
}
```

Results in this with the official compiler:

``` css
h1 .foo, h1 #bar {
  color: red; }
```

But the following with libsass:

``` css
h1 .foo, h1 h1 #bar {
  color: red; }
```
