### ISSUE TITLE
Deep @extend specificity problems - continuation

### ISSUE THREAD

**Issue by mzgol** [sass/libsass#1091]
Refs #592

The following SCSS:
```scss
.a {
    top: 0;
}

.b {
    .c {
        @extend .a;
    }
}

.d {
    > .e {
        @extend .a;
        @extend .c;
    }
}
```
is converted by Ruby Sass 3.4.13 to:
```css
.a, .b .c, .b .d > .e, .d > .e {
  top: 0; }
```
libsass 3.2.0-beta.5 produces:
```css
.a, .b .c, .d > .e {
  top: 0; }
```

EDIT: I simplified the test case.
