### ISSUE TITLE
Erroneous space inserted in { property: value-as-digit\9; }

### ISSUE THREAD

**Issue by atdrago** [sass/libsass#1098]
Adding a `\9` after a property value that ends in a digit adds an erroneous space before the `\`.

For example,
```sass
div { opacity: 1\9; }
```
Should output
```css
div { opacity: 1\9; }
```
But instead outputs
```css
div { opacity: 1 \9; }
```

Ruby sass compiles the value without the inserted space.

**Comment by xzyfer** [comment]
Thanks for the report @atdrago. Could you please also provide a test case in sass-spec? Here's a good example of one https://github.com/sass/sass-spec/pull/315.

@mgreter this is a regression from 3.1.0. I'll do a bisect shortly.

**Comment by atdrago** [comment]
Thanks for the response, @xzyfer. Added a PR sass/sass-spec#327

**Comment by xzyfer** [comment]
Specs added https://github.com/sass/sass-spec/pull/331. Turns out this regression is more server then first suspected.

```scss
div { 
    opacity: 1\9;
    width: 500px\9;
    color: #f00\9\0\;
}
```
Ruby Sass
```css
div {
  opacity: 1\9;
  width: 500px\9;
  color: #f00\9\0\;; }
```
Libsass 3.1.0
```css
div {
  opacity: 1\9;
  width: 500px\9;
  color: #f00 \9\0\;; }
```
Libsass 3.2.0-beta.5
```css
div {
  opacity: 1 \9;
  width: 500px \9;
  color: #f00\9\0\\; } // extra /
```
