### ISSUE TITLE
adjust-color() does not change anything

### ISSUE THREAD

**Issue by binarykitchen** [sass/libsass#1100]
```sass
linear-gradient(top, $header-button-background-color, adjust-color($header-button-background-color, $hue: -6deg, $lightness: -16, $saturation: -7));
```

Assuming $header-button-background-color is set to `#ffffff`, then I expect the above `adjust-color()` call to return `#d6d6d6` but it doesn't. It still returns the same, `#ffffff`. A bug? Or am I doing something wrong?

And yes, here the version I use (from gulp-sass within)

```
$ ./node-sass --version
2.1.1
```

**Comment by xzyfer** [comment]
I've boiled down your example to executable Sass.

```scss
$foo: #ffffff;
foo {
  bar: adjust-color($foo, $hue: -6deg, $lightness: -16, $saturation: -7);
}
```

Give this the output is as expected

```css
foo {
  bar: #d3d9d8; }
```

You can confirm this behaviour yourself on sassmeister - http://sassmeister.com/gist/66b7f11f8e72e620d85c

Node-sass 2.1.1 is using Libsass 3.1.0 which is the same as sassmeister (click the cog in the top right for more info) - https://github.com/sass/node-sass/blob/226861c6a186291f9e957697f1115e1ddb4a4202/package.json#L3-L4

***

I am currently unable to reproduce this issue. Can you please create an executable example that shows this issue in action on sassmeister? Without that we simply cannot make progress here.

**Comment by binarykitchen** [comment]
Ah, thanks for your work. After some debugging I found out that `$header-button-background-color` was set to `white` and that didn't work. But when I set that variable to `#fff`, then it worked. Weird.

**Comment by xzyfer** [comment]
Interesting, `white` is still a valid value for `adjust-color()`.

```scss
$foo: white;
foo {
  bar: adjust-color($foo, $hue: -6deg, $lightness: -16, $saturation: -7);
}
```

Ruby Sass
```css
foo {
  bar: #d6d6d6; }
```

Libsass
```css
foo {
  bar: #d3d9d8; }
```

*** 
There does however appear to be a difference in how we calculate the adjusted colour.
