### ISSUE TITLE
adjust-color() calculates differently from Ruby Sass

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1101]
Originally mentioned in https://github.com/sass/libsass/issues/1100#issuecomment-92555515

```scss
$foo: white;
foo {
  bar: adjust-color($foo, $hue: -6deg, $lightness: -16, $saturation: -7);
}
```

Ruby Sass
```css
foo {
  bar: #d6d6d6; }
```

Libsass
```css
foo {
  bar: #d3d9d8; }
```
