### ISSUE TITLE
Linebreaks are removed when a file is imported inside a media query

### ISSUE THREAD

**Issue by andfinally** [sass/libsass#1103]
We have a bunch of SCSS files which we import into a global.scss file. Some of them are imported inside media queries, for example:

```sass
@import "header";
@import "footer";
@import "forms";
@import "posts";

@media screen and (min-width: 480px) {
    @import "media-query-480";
}

@media screen and (min-width: 768px) {
    @import "media-query-768";
}
```

This gives us several separate CSS files and a concatenated one for prod. When I run gulp-sass, the line breaks between rules are preserved in the individual files, so in media-query-480.scss:

```sass
.entry-meta-date {
  display: block;
}

.entry-meta-date .day {
  display: inline;
}

.entry-meta-date-under {
  display: none;
}
```

becomes 

```css
.entry-meta-date {
  display: block; }

.entry-meta-date .day {
  display: inline; }

.entry-meta-date-under {
  display: none; }
```

but in the corresponding part of global.css it's

```css
 .entry-meta-date {
    display: block; }
  .entry-meta-date .day {
    display: inline; }
  .entry-meta-date-under {
    display: none; }
```

which is hard to read in a big CSS file. Not sure if this is a bug, but it's not the behaviour I'd expect.
