### ISSUE TITLE
Empty declarations sometimes being output

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1106]
```scss
.foo {
  foo: unquote(null); }
```
Ruby Sass 3.4.12
```css
// no output
```
Ruby Sass 3.4.12
```css
DEPRECATION WARNING: Passing null, a non-string value, to unquote()
will be an error in future versions of Sass.
        on line 2 of test.scss
```
Libsass 3.1.0
```css
.foo { }
```
Libsass 3.2.0-beta.5
```css
.foo {
  foo: ;}
```

Spec added https://github.com/sass/sass-spec/pull/329

**Comment by xzyfer** [comment]
Still seeing this in 3.0.0-beta.6. I'll work on a reduced test case today.

**Comment by xzyfer** [comment]
```scss
$foo: red;
$bar: unquote(null);

.baz {
    foo: $foo;
    foo: $bar; }

.bax {
    foo: $bar; }

.bay {
    foo: $foo; }
```

Ruby Sass
```css
.baz {
  foo: red; }

.bay {
  foo: red; }
```

Libsass 3.1.0
```css
.baz {
  foo: red; }

.bax { }

.bay {
  foo: red; }
```

Libsass 3.2.0-beta.6
```css
.baz {
  foo: red;
  foo: ;}

.bay {
  foo: red; }
```

**Comment by xzyfer** [comment]
This appears to be due a difference in `unquote`

```scss
foo { 
  bar: type-of(unquote(null)) }
```
Ruby Sass
```css
foo {
  bar: null; }
```
Libsass
```css
foo {
  bar: string; }
```

**Comment by xzyfer** [comment]
Although the current patch solves the issue of not showing empty rulesets, due to https://github.com/sass/libsass/issues/1124 in the special case of `unquote(null)` this breaks if there another non-null declaration in the ruleset.

```scss
$foo: null;
foo {
  a: $foo;
  b: $foo; }
bar {
  a: b;
  b: unquote($foo); }
```
Ruby Sass
```css
bar {
  a: b; }
```
Libsass 3.1
```css
bar {
  a: b; }
```
Libsass 3.2.0-beta.6
```css
bar {
  a: b;
  b: ;}
```
