### ISSUE TITLE
Excessive whitespace IE filter syntax

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1107]
I've marked this as regression since the behaviour has changed negative (for the user) but since it's only whitespace I've assigned it 3.2.1.

```scss
.foo {
  filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(
        src="#{foo}",
        sizingMethod='scale');
}
```
Ruby Sass
```css
.foo {
  filter: progid:DXImageTransform.Microsoft.AlphaImageLoader( src="foo", sizingMethod='scale'); }

```
Libsass 3.1.0
```css
.foo {
  filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(
        src="foo",
        sizingMethod='scale'); }
```
Libsass 3.2.0-beta.5
```css
.foo {
  filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(         src="foo",         sizingMethod='scale'); }
```
Spec added https://github.com/sass/sass-spec/pull/330
