### ISSUE TITLE
str-slice failing when slicing from last character

### ISSUE THREAD

**Issue by HugoGiraudel** [sass/libsass#1123]
```scss
$string: 'Hello world!';

// Expected: last character of string
// Ruby Sass 3.4 [OKAY] returns "!"
// LibSass 3.1   [FAIL] returns ""
.foo {
  content: str-slice($string, str-length($string));
  content: str-slice($string, -1);
}
```

Ref: http://sassmeister.com/gist/622a760397796db2fb74.
