### ISSUE TITLE
to-upper-case strings being double-quoted in 3.2.0-beta.6

### ISSUE THREAD

**Issue by sndrs** [sass/libsass#1127]
using `node-sass@3.0.0-beta.7` on OS X, the following SCSS:

```scss
$s: to-upper-case('abcd');

p {
    content: '#{$s}';
    content: '#{unquote($s)}';
    content: '#{$s + unquote("efg")}';
    content: '#{$s + unquote("")}';
}
```
produces this CSS:

```css
p {
  content: '"ABCD"';
  content: '"ABCD"';
  content: '"ABCD"efg';
  content: "ABCD"; 
}
```

I would have expected:

```css
p {
  content: 'ABCD';
  content: 'ABCD';
  content: 'ABCDefg';
  content: 'ABCD'; 
}
```

I think this is a bug? Or have I just misunderstood?

**Comment by xzyfer** [comment]
I can confirm this is a regression in 3.2.0. Libsass 3.1.0 produced the expect output.

**Comment by xzyfer** [comment]
Specs added https://github.com/sass/sass-spec/pull/341

**Comment by xzyfer** [comment]
A git bisect shows this regression was introduced in https://github.com/sass/libsass/commit/7877cfa872b036d55344db5d12ea908bb70f3705

**Comment by mgreter** [comment]
I get the expected result?
```css
p {
  content: "ABCDE";
  content: "ABCDE";
  content: "ABCDEefg";
  content: "ABCDE"; }
```
```
# psass -v
psass 0.4.0 (perl sass/scss compiler)
  libsass: 3.2.0-beta.6-4-g8963
  sass2scss: 1.0.3
```

**Comment by xzyfer** [comment]
I get the reported result on master

```css
p {
  content: '"ABCD"';
  content: '"ABCD"';
  content: '"ABCD"efg';
  content: "ABCD"; }
```

```
➜  libsass git:(master) ✗ sassc -v
sassc: 3.2.0-beta.2
libsass: 3.2.0-beta.6-4-g8963
sass2scss: 1.0.3
```
