### ISSUE TITLE
varargs with zero arguments

### ISSUE THREAD

**Issue by chriseppstein** [sass/libsass#1130]
This code should compile:

```scss
@function foo($args...) {
  @return bar($args...);
}

@function bar() {
 @return "hi";
}

.foo {
  result: foo();
}
```

to:

```css
.foo {
  result: "hi";
}
```

But instead I get the following error even in the latest libsass code:

```
function bar only takes 0 arguments; given 1 on line 2 at column 11
```
