### ISSUE TITLE
variables losing zeros

### ISSUE THREAD

**Issue by rodneyrehm** [sass/libsass#1140]
Sorry for the weird title, I'm not sure how to even describe this properly.

given the input

```scss
$line-height: 20px; div {line-height: $line-height;}
```

I get the output

```css
div {
  line-height: 2px; }
```

note how `20px` turned into `2px`. I see the same behavior for `0.1px` turning into `px`.

---

I've tracked the issue down to `sass_option_set_precision(ctx_opt, 0);` being the culprit. Not setting a precision, or setting any precision other than `0` works. I *think* I remember reading something about `0` being the libsass default. But I can't support that by linking to code. Judging from [sass_context.cpp](https://github.com/sass/libsass/blob/3.2.0/sass_context.cpp#L549) and [inspect.cpp](https://github.com/sass/libsass/blob/3.2.0/inspect.cpp#L420) I'd assume the default is `5`.

I'm not sure if this is an issue with code, the documentation, or me being daft (again).

**Comment by mgreter** [comment]
Valid, see the same with perl-libsass:
```
# psass --precision 0 test.scss
div {
  line-height: 2px; }
# psass -v
psass 0.4.0 (perl sass/scss compiler)
  libsass: 3.2.0
  sass2scss: 1.0.3
```

IMO it should be quite trivial to fix this "edge" case!
Got any expected behavior for negative precision :smile:  ?

**Comment by xzyfer** [comment]
Fixed in [3.2.1](https://github.com/sass/libsass/releases/tag/3.2.1)

**Comment by rodneyrehm** [comment]
Your fix may have gone a tiny bit too far. In 3.2.1 for `precision: 0`, the following code

```scss
$foo: 123px; .m { width: $foo; }
```

compiles to

```css
.m {
  width: 123.0px; }
```

I don't think adding `.0` is a good idea.

**Comment by xzyfer** [comment]
Are right, yes that's a bug, but it doesn't change the semantic of the code which certainly an improvement.

**Comment by rodneyrehm** [comment]
Oh, it even got worse:

```scss
$foo: 123.4px; .m { width: $foo; }
```

compiles to

```css
.m {
  width: 123.0px; }
```

so now we're actually losing precision
