### ISSUE TITLE
Ordinal arguments error for function wrapper with variable arguments

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1142]
Please see below for the issue. The function `test(...)` should be called with three arguments: `3, null, 5` and return `'result'`.

**TEST**
```scss
@function test($a, $b, $c) {
    @return 'result';
}

@function test-wrapper($foo, $bar: null, $args...) {
    @return call(test, $args...);
}

.test {
    content: test-wrapper(1, 2, 3, null, 5);
}
```

**EXPECTED**
```scss
.test {
    content: 'result';
}
```

**ACTUAL**
```scss
// Libsass 3.2.0-beta.6
// => Error: ordinal arguments must precede variable-length arguments

// Ruby Sass 3.4.12
.test {
    content: 'result';
}
```

**Comment by mgreter** [comment]
Seems to be fixed by #1130 (included in 3.2.0)
```css
.test {
  content: "result"; }
```
```
# psass -v
psass 0.4.0 (perl sass/scss compiler)
  libsass: 3.2.0
  sass2scss: 1.0.3
```
