### ISSUE TITLE
Variable concatenation with interpolation adds a space in between

### ISSUE THREAD

**Issue by ausi** [sass/libsass#1158]
Concatenating a variable with an interpolation like `$input#{$input}` shouldn’t add a space between them.

```scss
$input: literal;
.result {
  output: $input#{$input};
}
```

Should generate this output, as RubySass does:

```css
.result {
  output: literalliteral; }
```

The actual output of LibSass 3.2.2 is:

```css
.result {
  output: literal literal; }
```

A complete test case of all combinations of `literal`, `$input`, `#{$input}`, `#{literal}`, `#{"literal"}` can be found here: [sass/sass-spec/tree/1a35b2b/spec/parser/interpolate/01_literal/07_variable_concatenation](https://github.com/sass/sass-spec/tree/1a35b2ba3782ffe34d10ac707b327a6cdd6b0362/spec/parser/interpolate/01_literal/07_variable_concatenation)

The correct behavior is described in https://github.com/sass/sass/issues/1704#issuecomment-94626433
