### ISSUE TITLE
Fractions retrieved from a map break in number comparison

### ISSUE THREAD

**Issue by ericam** [sass/libsass#1159]
Fraction number-comparisons are still broken when the fraction is retrieved from a map.

```scss
$numbers: (
  integer: 4,
  decimal: .25,
  fraction: 1/4, 
);

.test {
  @each $key in map-keys($numbers) {
    $number: map-get($numbers, $key);
    #{$key}: if($number > 0, true, false);
  }
}

// Expected Output
.test {
  integer: true;
  decimal: true;
  fraction: true; }

// Actual Output
// ERROR: may only compare numbers on line 10 at column 14
```

See the [SassMeister Demo](http://sassmeister.com/gist/343bdc4fca70f77007ca)
