### ISSUE TITLE
Quoted and unquoted colors in maps produces 'Duplicate key "transparent" in map'

### ISSUE THREAD

**Issue by AlbertoElias** [sass/libsass#1169]
In Ruby Sass, CSS colors in map keys are considered as colours as you can see [here](http://sassmeister.com/gist/911c0887c1fa588737da) instead of as strings. 

It seems to be the same in [Libsass](http://sassmeister.com/gist/58f494fbfad75e32358f), but if I do something similar as the first example, [link](http://sassmeister.com/gist/dd293c1cb143867f4391), when they're set as map keys, they're both considered strings, but if you `map-get`, they are considered as colors if they're not quoted.

I also tried using the recently released node-sass 3.0.0 that uses the stable Libsass 3.2.0 and it still happens.

**Comment by xzyfer** [comment]
Sorry, I'm confused. The example you've given fails on Ruby Sass 3.4.12.

```scss
$colors: (
	"transparent": #000000,
);

.c {
  color: map-get($colors, transparent);
  foo: type-of(map-get($colors, transparent));
}
```
Ruby Sass
```css
.c {
  foo: null; }
```
LibSass
```css
.c {
  foo: null; }
```

What behaviour are you expecting?

**Comment by xzyfer** [comment]
```scss
$colors: (
	transparent: #000000,
	"transparent"": #000000,
);
```
Ruby
```css
Invalid CSS after "	"transparent"": expected ":", was "": #000000,"
```
LibSass
```css
error reading values after "transparent" on line 3 at column 2
```

**Comment by xzyfer** [comment]
```scss
$colors: (
	transparent: #000000,
);

.c {
  color: map-get($colors, transparent);
  foo: type-of(map-get($colors, transparent));
}
```
Ruby
```css
.c {
  color: #000000;
  foo: color; }
```
LibSass
```css
.c {
  color: #000000;
  foo: color; }\
```

**Comment by xzyfer** [comment]
As far as I can tell the behaviour is the same as Ruby Sass.

**Comment by HugoGiraudel** [comment]
```scss
$map: (
  'red': 'foo',
   red: 'bar',
);

.foo {
  content: inspect($map);
}
```

Ruby Sass:

```scss
.foo {
  content: ("red": "foo", red: "bar");
}
```

LibSass:

```scss
Duplicate key "red" in map ("red": "bar"). on line 3 at column 14
```

Discussion: https://twitter.com/HugoGiraudel/status/596267826933014528

**Comment by kaelig** [comment]
Maybe this will help: http://sassmeister.com/gist/3e30a4ee6cab083648c9

```scss
$colors: (
	"transparent": #000000,
 	// transparent: #000000 // Uncomment this line and it fails to compile
);
```

**Comment by HugoGiraudel** [comment]
Also:

```scss
$map: (
   'red': 'bar',
);

.foo {
  content: type-of(nth(map-keys($map), 1));
}
```

Ruby Sass:

```scss
.foo {
  content: string;
}
```

LibSass:

```scss
.foo {
  content: color;
}
```

**Comment by HugoGiraudel** [comment]
LibSass is clearly doing something wrong. Or the behaviour is not correctly described in the spec, and basically nobody quite knows what should happen, but I'd find it sad I think. :D

**Comment by xzyfer** [comment]
Thanks for the clarification.

The issue appears to be specific to setting map keys. AFAIK we, correctly, treat colour stings as colours. Marked this for the next small release.

**Comment by HugoGiraudel** [comment]
Cool, thanks for the quick feedback @xzyfer. :)

**Comment by AlbertoElias** [comment]
Yes, in the second link I posted, you can see that colour strings are treated like colours. But in map keys, they're not, and that's why an error is thrown in my third example if you uncomment the second key in the map (I forgot to mention that).

Thanks everyone for the very quick response!

**Comment by xzyfer** [comment]
This is also an interesting exception

```scss
$map: (
  'red': 'foo',
);

$map: map-set(red, 'bar');

.foo {
  content: inspect($map);
}
```
Ruby and LibSass
```css
.foo {
  content: map-set(red, "bar"); }
```

Makes perfect sense considering the string `'red'` will be cast to a colour object. This may actually be a bug in Ruby Sass.

**Comment by HugoGiraudel** [comment]
What is `map-set`? :x

**Comment by xzyfer** [comment]
Ah my bad, too many langauges.

```scss
$map: (
  'red': 'foo',
);

$map: map-merge($map, (red: 'bar'));

.foo {
  content: inspect($map);
}
```
Ruby and LibSass
```css
.foo {
  content: ("red": "foo", red: "bar"); }
```

The inconsistency here does kinda bug me, I wonder what the rationale is here.

**Comment by xzyfer** [comment]
I've looked into this further and it appears I'm mistake. As far as I can tell Ruby Sass will always treat a quoted colour as a String. This is the crux of our issue.

```scss
.foo {
  a: type-of("red");
  b: type-of(red);
}
```
Ruby Sass
```css
.foo {
  a: string;
  b: color; }

```
LibSass
```css
.foo {
  a: color;
  b: color; }
```

**Comment by HugoGiraudel** [comment]
> As far as I can tell Ruby Sass will always treat a quoted colour as a String.

I can confirm that. Actually there is no such thing as *quoted colour*  in Ruby Sass. A quoted value is a string, no matter what it contains. So `'red'` will never be evaluated as a color, no matter where, no matter how.

**Comment by kaelig** [comment]
I wouldn't recommend to do this but there is a workaround:

```scss
$map: (
  'transparent': foo,
  rgba(0, 0, 0, 0): foo
);

// Both work
$foo: map-get($map, transparent);
$foo: map-get($map, 'transparent');
```

**Comment by AlbertoElias** [comment]
Yes, I used @kaelig´s workaround for my [second example](http://sassmeister.com/gist/58f494fbfad75e32358f) and it works fine

**Comment by xzyfer** [comment]
Thanks everyone. This is a tricky one, the colour ones always are. We'll aim to get this in the next small release. A sass-spec will really speed up the process *hint hint* :smile:

**Comment by chriseppstein** [comment]
CSS cheats by using property specific parsing rules so they can disambiguate when a color is a color etc. SassScript has to work the same everywhere in a document so we basically have to choose to treat color identifiers as colors everywhere.

**Comment by mgreter** [comment]
Here come my findings. See this scss example:
```css
$map1: ( red: 'literal' );
$map2: ( 'red': 'quoted' );
$map3: ( #{re}#{d}: 'interpolated' );

foo {
  content: inspect($map1);
  content: inspect($map2);
  content: inspect($map3);
}

$merge1: map-merge($map1, $map2);
$merge2: map-merge($map1, $map3);
$merge3: map-merge($map2, $map3);

bar {
  content: inspect($merge1);
  content: inspect($merge2);
  content: inspect($merge3);
}
```

Results in:
```css
foo {
  content: (red: "literal");
  content: ("red": "quoted");
  content: (red: "interpolated"); }

bar {
  content: (red: "literal", "red": "quoted");
  content: (red: "literal", red: "interpolated");
  content: ("red": "interpolated"); }
```

As you can see, the interpolated value has the same key as the quoted string, although they have different output. This makes sense, since both are internally strings. Colors seems to be color key, no matter what. The following example show a bit more what I mean:
```css
baz {
  content: inspect(( yellow: 'bar' ));
  content: inspect(( 'yellow': 'bar' ));
}
```
output nested:
```css
baz {
  content: (yellow: "bar");
  content: ("yellow": "bar"); }
```
output compressed (reformatted):
```css
baz {
  content:(#ff0: "bar");
  content:("yellow": "bar") }
```
You can see that keys get the same output representation like all other Sass Values.
