### ISSUE TITLE
& + '' needs to be wrapped in parentheses

### ISSUE THREAD

**Issue by kaelig** [sass/libsass#1170]
```scss
el {
  @if (& + '' == 'el') {
    content: "It works!";
  }
}
```

Throws:

```
invalid selector after '' on line 2 at column 14
```

See: http://sassmeister.com/gist/f19f7aa4e0fbacde9549

The simplest fix (as suggested by @HugoGiraudel) is to wrap `& + ''` in parenthesis: `(& + '')`.
