### ISSUE TITLE
Output for nested lists on inspect and declaration differ

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#1178]
input.css
```css
$foo: ((4, 5), 6, (7 8) 9);

bar {
  a: $foo;
  f: 1 2 3 + $foo;
  b: 1, 2, 3 + (2 ($foo));
  x: inspect($foo);
}
```

expected:
```
foo {
  a: 4, 5, 6, 7 8 9;
  f: 1 2 34, 5, 6, 7 8 9;
  b: 1, 2, 32 4, 5, 6, 7 8 9;
  x: (4, 5), 6, (7 8) 9; }
```

libsass:
```
bar {
  a: 4, 5, 6, 7 8 9;
  f: 1 2 34, 5, 6, 7 8 9;
  b: 1, 2, 32 4, 5, 6, 7 8 9;
  x: 4, 5, 6, 7 8 9; }
```

I already have a local branch that solves this ...
