### ISSUE TITLE
Variable values starting with "not" are interpreted as expressions

### ISSUE THREAD

**Issue by paweltin** [sass/libsass#1199]
Example:
```scss
$foo: not-allowed; //$foo = false
$bar: notfalse; //$bar = true
$foobar: notnottrue; //$foobar = true
```
It differs from other implementations of SCSS.

**Comment by paweltin** [comment]
There is however a workaround for this issue:
```scss
$foo: unquote("not-allowed");
```

**Comment by xzyfer** [comment]
Can you please confirm which version of Libsass you're using? I believe
this issue has been fixed for a while.

**Comment by xzyfer** [comment]
Output from Libsass 3.2.0
```scss
$foo: not-allowed;
$bar: notfalse;
$foobar: notnottrue;

a {
  foo: $foo;
  bar: $bar;
  foobar: $foobar;
}
```
```css
a {
  foo: not-allowed;
  bar: notfalse;
  foobar: notnottrue; }
```
