### ISSUE TITLE
invalid operands for multiplication

### ISSUE THREAD

**Issue by linnett** [sass/libsass#1201]
The following code errors on compile:
```scss
@for $i from 1 through $numberOfColumns {
        .col-#{$i}-#{$numberOfColumns} {
            $columnWidth: (100% - (($margin * 2) * $numberOfColumns)) / $numberOfColumns;
            width: ($i * $columnWidth) + (($margin * 2) * ($i - 1));
        }
    }
```
The error is: 'invalid operands for multiplication'.
This code used to work in another version of SASS compiling. Any ideas?

**Comment by xzyfer** [comment]
Sounds like you're on a old version of Libsass. Please update.

**Comment by linnett** [comment]
I'm using gulp-sass v 2.0.0. deps: 

```
"gulp-util": "^3.0",
"node-sass": "^3.0.0",
"object-assign": "^2.0.0",
"through2": "^0.6.3",
"vinyl-sourcemaps-apply": "~0.1.1"
```

**Comment by xzyfer** [comment]
@linnett can you please give the output of the following commands

```
npm -v              
node -v
node -p process.versions
node -p process.platform
node -p process.arch
./node_modules/.bin/node-sass --version
```

**Comment by xzyfer** [comment]
For reference, running Libsass 3.2.0

```scss
$numberOfColumns: 2;
$margin: 5%;
$columnWidth: 20px;

@for $i from 1 through $numberOfColumns {
  .col-#{$i}-#{$numberOfColumns} {
    $columnWidth: (100% - (($margin * 2) * $numberOfColumns)) / $numberOfColumns;
    width: ($i * $columnWidth) + (($margin * 2) * ($i - 1));
  }
}
```
```css
.col-1-2 {
  width: 40%; }

.col-2-2 {
  width: 90%; }
```
