### ISSUE TITLE
Converts unicode incorrectly

### ISSUE THREAD

**Issue by maxlapides** [sass/libsass#1203]
```scss
#test {
    content: "\f00c";
}
```

compiles to:

```css
#test {
    content: "\f00c";
}
```

But...

```scss
#test {
    $symbol: "\f00c";
    content: $symbol;
}
```

compiles to:

```css
#test {
  content: "";
}
```

What's going on here? Thanks :)
