### ISSUE TITLE
`#{0/0}` incorrectly returns `Infinity`

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1206]
Originally mentioned in #1162.

```css
foo {
  bar: #{0/0}; }
```
Ruby Sass
```css
foo {
  bar: 0/0; }
```
Libsass
```css
foo {
  bar: Infinity; }
```

Spec added https://github.com/sass/sass-spec/pull/384.
Spec for #1162 is also relevant.
