### ISSUE TITLE
invalid operands for multiplication - once again

### ISSUE THREAD

**Issue by DenisMir** [sass/libsass#1207]
At the moment I am using the following setup: grunt-sass@1.0.0, node-sass@3.1.0 and libsass@3.2.4 and getting once again the "invalid operands for multiplication". This error was not there with libsass@3.2.0-beta6. I can't even give you the correct error description since it errors out with `Line 36  Column 13` which is a normal comment block.

**Comment by xzyfer** [comment]
@DenisMir I'm sorry but without a copy-pastable code sample we cannot begin to investigate this issue. Please take the time to find what part of your code is causing this issue.

**Comment by DenisMir** [comment]
@xzyfer 
I have tried to hunt down the issue. I'm pretty sure I got it now but it is pretty weird. 

I have some function which is reading a modular scale value from a map. 

```scss
@function ms-get-scale-ratio($pos) {
  @if not $modular-scale {
    @warn 'Please define a modular scale map in your config.';
  } @else {
    $key: scale-#{$pos};
    @debug 'Trying to get ratio for position #{$pos} with key #{$key}';
    $ratio: map-get($modular-scale, $key);
    @debug 'Found ratio is #{$ratio}';
    @return $ratio;
  }
}
```

The modular scale map is something like that: 

```scss
$modular-scale: (
  scale-0: 1.2,
  scale-1: 1.3,
  scale-2: 1.4,
  scale-3: 1.5,
  scale-4: 1.6
);
```

Now when I'm looking at the debug log I'm getting some correct pairs of log which look like:

```
Trying to get ratio for position 2 with key scale-2
Found ratio is 1.4
```

But I'm also getting something like:

````
Trying to get ratio for position "2" with key scale-"2"
Found ratio is
```

The `"2"` is breaking the code here. With no ratio value I'm getting the `invalid operands for multiplication`   which is ok.

I hope that I could help you finding the issue. Please adjust the title according to the correct malfunction. At the moment I'm not quite sure what is going on here. If you need more information just drop me a message.

**Comment by DenisMir** [comment]
@xzyfer Do you need more information from me to be able to identify the bug?

**Comment by xzyfer** [comment]
@DenisMir the quickest way for use to address this issue is if you create a http://sassmeister.com gist showing the problem.

We simply don't have the time to reconstruct the code to test every bug.

**Comment by DenisMir** [comment]
@xzyfer No problem. I will try to reproduce the bug there. I haven't seen it since using `node-sass@3.1.2` in `grunt-sass`.

**Comment by HugoGiraudel** [comment]
Reduced test case:

```scss
$modular-scale: (
  'scale-0': 1.2
);

@function get($pos) {
  @return map-get($modular-scale, scale-#{$pos});
}

$bp-key: 'scale-0';
$bp-index: str-slice($bp-key, 7);
$ratio: get($bp-index);

.foo {
  content: $bp-key;
  content: $bp-index;
  content: $ratio;
}
```

## Expected

```css
.foo {
  content: "scale-0";
  content: "0";
  content: 1.2;
}
```

## Actual

```css
.foo {
  content: "scale-0";
  content: "0";
}
```
