### ISSUE TITLE
Comments in selectors throwing errors

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1208]
Originally mentioned in https://github.com/sass/libsass/issues/1122#issuecomment-101677327

```scss
foo {
  &.bar, /* */
  &.baz {
    color: red;
  }
}
```
Ruby Sass
```css
foo.bar, foo.baz {
  color: red; }
```
Libsass
```css
Error: invalid selector after ,
        on line 3 of test.scss
>>   &.bar, /* */
   --------^
```

Removing the `&`, or the nesting resolves the issue. AFAIK this is the minimal test case.
