### ISSUE TITLE
@at-root and #{&} produces incorrect output [$10]

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1210]
```scss
@mixin box-sizing-border {
  @at-root {
    #{&} {
      *, *:before, *:after { 
        box-sizing: inherit; }
    } } }

foo {
  @include box-sizing-border; }
```
Ruby Sass
```css
foo *, foo *:before, foo *:after {
  box-sizing: inherit; }
```
Libsass 3.2.4
```css
foo foo *, foo foo *:before, foo foo *:after {
  box-sizing: inherit; }
```

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/382

**Comment by iparr** [comment]
Also struggling a little with this issue.

I've been using it (perhaps unwisely) *without* mixins, for example in this example where the `global-logo` will only adapt a hover color when it is a link (as opposed to a heading, or span):

```
.global-logo {

	@at-root a#{&} {
		&:hover {
			background-color: red;
		}
	}
}
```

This is the one thing stopping me utilising libsass fully on some of my websites so I'm going to watch keenly for a fix!

**Comment by blackfalcon** [comment]
Regardless of use with mixin or not, the issue persists when trying to create a combination selector based off the parent in the Sass using a child selector. In this example, the desired output from rubySass is not the same as libSass.

```scss
.parent {
  width: 100%;
  @at-root .child#{&} {
    width: 50%;
  }
}
```

**rubySass**
```
.parent {
  width: 100%;
}
.child.parent {
  width: 50%;
}
```

**libSass**
```
.parent {
  width: 100%;
}

.parent .child.parent {
  width: 50%;
}
```

Give it a run in [SassMeister](http://sassmeister.com/gist/30b476b8d88c5be1413f) to see.
