### ISSUE TITLE
Regression in parsing @at-rules

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1214]
This regression was introduced 3.2.4.

```scss
@mixin keyframes($animation-name) {
  @keyframes $animation-name {
    @content;
  }
}

@include keyframes(bounce) {
  0%, 20%, 50%, 80%, 100% {transform: translateY(0);}
  40% {transform: translateY(-30px);}
  60% {transform: translateY(-15px);}
}
```
Ruby Sass
```css
@keyframes $animation-name {
  0%, 20%, 50%, 80%, 100% {
    transform: translateY(0); }
  40% {
    transform: translateY(-30px); }
  60% {
    transform: translateY(-15px); } }
```
Libsass 3.2.4
```
Error: invalid selector after
        on line 2 of test.scss
>>   @keyframes $animation-name {
   ------------^
```

Spec added: https://github.com/sass/sass-spec/pull/387
