### ISSUE TITLE
Integer truncation -- regression between 3.1 and 3.2 (and different from ruby sass)

### ISSUE THREAD

**Issue by asottile** [sass/libsass#1216]
**EDIT** This post has been edited to reflect the actual worldstate and not the erroneous state when I originally created the ticket.  I had some wackiness in my environment which mislead me :(

Input:
```scss
a { width: 3.0px }
```

Output (libsass 3.1):
```css
a {
  width: 3px; }
```

Output (libsass 3.2.4):
```css
a {
  width: 3.0px; }
```

Ruby sass 3.4.12:
```css
a {
  width: 3.0px; }
```
