### ISSUE TITLE
Quoting difference in media query expression

### ISSUE THREAD

**Issue by cvrebert** [sass/libsass#1218]
Environment:
```
$ sass -v
Sass 3.4.13 (Selective Steve)
$ sassc -v
sassc: 3.2.1
libsass: 3.2.4
sass2scss: 1.0.3
```
Input:
```scss
// foo.scss
@media screen and ("min-width:0") {
    .bar {
        width: 12px;
    }
}
```

Ruby Sass Output:
```css
@media screen and (min-width: 0) {
  .bar {
    width: 12px; } }

```
SassC/libsass Output:
```css
@media screen and ("min-width:0") {
  .bar {
    width: 12px; } }
```

Note the quotes in the libsass output.
