### ISSUE TITLE
Nested media query logic sometimes broken in 3.2

### ISSUE THREAD

**Issue by callumacrae** [sass/libsass#1224]
I believe this was caused by #800.

Updating to libsass 3.2 broke some stuff with nested media queries in my styling. Here is a gist with the SCSS, and the 3.1 and 3.2 output: https://gist.github.com/callumacrae/c38f95172c2a8c7aebe4

I have no idea what is going on, and I can't contribute a failing test case because I don't know C.

**Comment by xzyfer** [comment]
Please a copy pastable sample that reproduces the issue you're describing. Use sassmeister.com. As it stands we cannot progress this issue because we cannot reproduce it with the code supplied.

**Comment by callumacrae** [comment]
```sass
@media all and (max-width: 768px) {
  @media only screen and (min-device-pixel-ratio: 2), only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi) {
    body .div {
      color: blue;
    }
  }
}
```

Output:

```css
@media {
  body .div {
    color: blue;
  }
}
```

Expected output:

```css
@media only screen and (min-device-pixel-ratio: 2) and (max-width: 768px), only screen and (-webkit-min-device-pixel-ratio: 2) and (max-width: 768px), only screen and (min-resolution: 192dpi) and (max-width: 768px) {
  body .div {
    color: blue;
  }
}
```

**Comment by xzyfer** [comment]
Please use http://sassmeister.com in the future. This code provided produces no output in Sass. Technically the bug here is that we produce any output at all.

**Comment by xzyfer** [comment]
No output is produced because `all` and `screen only` are incompatible and cannot be merged in a semantically accurate way.

```scss
@media all and (max-width: 768px) {
  @media only screen {
    a { b: c; }
  }
}
```
