### ISSUE TITLE
Whitespace in values is rendered in output

### ISSUE THREAD

**Issue by indrekpaas** [sass/libsass#1230]
Using `compressed` mode
```css
div {
  transition-property:
    border-color,
    box-shadow,
    color;
}
```
renders
```css
div{transition-property:border-color,     box-shadow,     color}
```
with LibSass [(demo)](https://gist.github.com/indrekpaas/440a327d27555034cf2d), as opposed to
```css
div{transition-property:border-color, box-shadow, color}
```
with Ruby Sass [(demo)](https://gist.github.com/indrekpaas/712fd6a6cd209daeb7ae).
