### ISSUE TITLE
PUA code literal rendering

### ISSUE THREAD

**Issue by indrekpaas** [sass/libsass#1231]
Using `compressed` mode
```scss
div::before {
  content: #{"\""+\e600+"\""};
}
```
renders a literal character
```css
div::before{content:}
```
with LibSass [(demo)](https://gist.github.com/indrekpaas/7e125d0873e3e8c2bce7), as opposed to
```css
div::before{content:"\e600"}
```
with Ruby Sass [(demo)](https://gist.github.com/indrekpaas/c37322e7bb873e4edaf1).
