### ISSUE TITLE
Block comments should be preserved in "static" at rules

### ISSUE THREAD

**Issue by jamiehutber** [sass/libsass#1233]
When using @'s it appears to fail.

```scss                  
@-moz-keyframes animatetoptop /* Firefox */ line 429
{
from {width:0%}
to {width:100%}
}
```
I'll get the following error.
```
[16:36:40] gulp-notify: [Compile Error] stylesheets\apps\tmm\_results.scss
429:17  top-level directive must be terminated by ';'
```

I'm using gulp-sass: 2.0.1

**Comment by xzyfer** [comment]
I am unable to reproduce this specific error. However I have noticed we incorrectly remove the comment.

Libsass
```scss
@-moz-keyframes animatetoptop line 429
{
  from {
    width: 0%; }
  to {
    width: 100%; } }
```
Ruby Sass
```css
@-moz-keyframes animatetoptop /* Firefox */ line 429 {
  from {
    width: 0%; }
  to {
    width: 100%; } }
```

**Comment by mgreter** [comment]
The adjancent string is parsed literally and the comment node is part of it. Related to At_Rule parsing (I already did some improvements for values). This sample shows the behavior:

```css
@-moz-keyframes        animatetoptop       /* Firefox */         line 429   {
from {width:0%}
to {width:100%}
}
```

ruby sass:
```css
@-moz-keyframes animatetoptop       /* Firefox */         line 429 {
  from {
    width: 0%; }
  to {
    width: 100%; } }
```

Related to https://github.com/sass/libsass/issues/1263
