### ISSUE TITLE
Unexpected behaviour with @at-root

### ISSUE THREAD

**Issue by HugoGiraudel** [sass/libsass#1236]
Bug found by Jaime Caballero: https://twitter.com/jaicab_/status/602583391515574273.

## Test case

```scss
@mixin test {
  $selector-list: &;                 // (.a .b,)
  $selector: nth($selector-list, 1); // (.a .b)
  $first: nth($selector, 1);         // .a
  $second: nth($selector, 2);        // .b
  $add: 'dummy';
  
  @at-root #{$first} #{$add} #{$second} {
    @content;
  }
}


.a .b {
  @include test {
    color: red;
  }
}
```

## Expected result

```css
.a dummy .b {
  color: red;
}
```

## Actual result (LibSass 3.2.4)

```css
.a .b .a dummy .b {
  color: red;
}
```
