### ISSUE TITLE
libsass not subtracting value from percent correctly

### ISSUE THREAD

**Issue by nicholascloud** [sass/libsass#1238]
-  gulp-sass@^1.3.3
    - node-sass@^2.0.1
        - libsass@3.1.0
- gulp-ruby-sass@^1.0.5

In my project I compiled the SCSS with both gulp-sass (libsass) and gulp-ruby-sass. In one of my mixins, the number 2 is subtracted the percentage output of a SASS function. The gulp-ruby-sass library calculates the final percentage correctly, but the output from gulp-sass leaves the "- 2" in the generated CSS:

![gulp-sass vs gulp-ruby-sass](https://i.imgur.com/OWxdQId.png)

gulp-sass output is on the left, gulp-ruby-sass output is on the right. The SCSS that generates the final percentage value is:

![subtracting number from percentage output](https://i.imgur.com/P3P1yoN.png)

The `flex-grid` function comes from an (older?) version of Bourbon:

```scss
@function flex-grid($columns, $container-columns: $fg-max-columns) {
  $width: $columns * $fg-column + ($columns - 1) * $fg-gutter;
  $container-width: $container-columns * $fg-column + ($container-columns - 1) * $fg-gutter;
  @return percentage($width / $container-width);
}
```

I assume this is an issue with libsass and not gulp-sass (or node-sass) directly, but if I am mistaken please let me know. The actual SCSS was developed by another party using ruby SASS, but I'd like to use plain Node.js libraries if possible.
