### ISSUE TITLE
maps should not be directly output into css

### ISSUE THREAD

**Issue by chriseppstein** [sass/libsass#1246]
maps, like numbers with complex units, are never a value that can be understood by css, so ruby sass gives an error when this is attempted.

The following sass file:

```scss
$m: (a: 1, b: 2);

.foo {
  interpolated: "#{$m}";
  direct: $m;
  inspected: inspect($m);
}
```

in libsass compiles to:

```css
.foo {
  interpolated: "(a: 1, b: 2)";
  direct: (a: 1, b: 2);
  inspected: (a: 1, b: 2); }
```

But an error should have been given. Only the third line, using the inspect function should have succeeded.
