### ISSUE TITLE
Deep @extend specificity problems - continuation of the continuation

### ISSUE THREAD

**Issue by mzgol** [sass/libsass#1248]
Refs #1091 #592

The following SCSS:
```scss
.a.b .c {
  top: 0;
}
.a {
  @extend .b;
}
.a .d {
  @extend .c;
}
```
is converted by Ruby Sass 3.4.14 to:
```css
.a.b .c, .a .c, .a.b .d, .a .d {
  top: 0; }
```
libsass 3.2.4 produces:
```css
.a.b .c, .a .c, .a .d {
  top: 0; }
```

The `.a.b .d` selector is missing, it's important due to CSS specificity.

EDIT: test case simplified.
