### ISSUE TITLE
Use the shortest colour representation in compressed mode

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1251]
When using named colours we're opting out of the compressed mode colour shortening.

```scss
a { b: yellow; }
```
Ruby Sass
```scss
a { b: #ff0; }
```
Libsass
```scss
a { b: yellow; }
```

Spec added https://github.com/sass/sass-spec/pull/400
