### ISSUE TITLE
Arglist as single argument

### ISSUE THREAD

**Issue by HugoGiraudel** [sass/libsass#1257]
## Test

```scss
.foo {
  color: invert(red...);
}
```

## Expected

```css
.foo {
  color: cyan;
}
```

## Actual

Nothing. It crashes.

## Observations

This may have the same underlying cause as #1171 and #1255.
