### ISSUE TITLE
Incorrect behaviour of unquote and list 

### ISSUE THREAD

**Issue by HugoGiraudel** [sass/libsass#1258]
Not sure if there is already a relevant open issue.

## Test

```scss
$list:   '(-webkit-min-device-pixel-ratio: 2)', '(min-resolution: 192dpi)'; 
$string: '(-webkit-min-device-pixel-ratio: 2),   (min-resolution: 192dpi)';

.foo {
  // I should not unquote a list, I know. But still.
  content: unquote($list);
  content: unquote($string);
}
```

## Expected

```css
.foo {
  content: "(-webkit-min-device-pixel-ratio: 2)", "(min-resolution: 192dpi)";
  content: (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi);
}
```

## Actual

```css
.foo {
  content: (-webkit-min-device-pixel-ratio: 2)", "(min-resolution: 192dpi);
  content: (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi);
}
```
