### ISSUE TITLE
Error: named arguments must precede variable-length argument

### ISSUE THREAD

**Issue by vaanwd** [sass/libsass#1259]
Hello! I have this error when i try to compile a simple scss file:
```sass
@import "compass"; // Compass 1.0.3

$red : red;

body {
  background-color: $red;
}

h1 {
  @include border-radius(5px);
}
```
and the output from sassc.exe is...
```
Error: named arguments must precede variable-length argument
        on line 152 of d:/Programming/SASS/include/compass/_support.scss
>> e for-legacy-browser($browser, $range..., $threshold: $threshold, $ranges: $br
   ------------------------------------------^
```

**Comment by xzyfer** [comment]
@vaanwd we do not use compass. Please track down the function causing the issue and produce a copy-pastable http://sassmeister.com gist that produces this error.

**Comment by HugoGiraudel** [comment]
Plus, you seem to be using an obsolete/custom/hacked version of Compass as the `for-legacy-browser(..)` function usually looks like this: https://github.com/Compass/compass/blob/stable/core/stylesheets/compass/_support.scss#L148.

**Comment by HugoGiraudel** [comment]
My bad, it comes from here: https://github.com/Compass/compass/blob/stable/core/stylesheets/compass/_support.scss#L152.

**Comment by HugoGiraudel** [comment]
There you have the bug

## Test

```scss
@mixin dummy($a, $b, $c, $d, $e: true) {
  content: $a $b $c $d $e;
}

.foo {
  @include dummy((1 2 3 4)..., $e: false);
}
```

## Expected

```css
.foo {
  content: 1 2 3 4 false;
}
```

## Actual

```
named arguments must precede variable-length argument on line 6 at column 32
```
