### ISSUE TITLE
Cannot join list with arglist

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1269]
**Test:**

```scss
@function push($list, $items...) {
  @return join($list, $items, $separator: auto);
}

.test {
  $list: push(1 2 3, 4, 5);
  list: inspect($list);
  value: nth($list, 4);
}
```

**Expected:** (works in Ruby Sass)

```scss
.test {
  list: 1 2 3 4 5;
  value: 4;
}
```

**Actual:** (crashes/compiles forever in LibSass 3.2.4)

Might be related to #1257 and #1171
