### ISSUE TITLE
Char escaping doesn't follow Sass 3.3 or 3.4 ways

### ISSUE THREAD

**Issue by kaelig** [sass/libsass#1271]
See http://sassmeister.com/gist/cd6d8d263d555bca6cf9

Neither of these things return the correct value in LibSass:
```scss
$character-code: f102;

test {

  /* Expected: "\f102" */

  /* Sass 3.4 */
  content: unquote("\"\\#{$character-code}\"");

  /* Sass 3.3 */
  content: str-slice("\x", 1, 1) + $character-code;

}
```
