### ISSUE TITLE
Error parsing interpolated value

### ISSUE THREAD

**Issue by stowball** [sass/libsass#1277]
The following code breaks in LibSass 3.2.5 with `error parsing interpolated value on line 5 at column 32`:

```scss
$ease-in-cubic: cubic-bezier(0.550, 0.055, 0.675, 0.190);
$transition: 0.2s #{$ease-in-cubic};

.foo {
  transition: background-color #{$transition}, box-shadow #{$transition};
}
```

It used to work in 3.2.2 and works in Ruby Sass 3.4.14.

If you wrap the first `#{$transition}` in an `()`, then it works:

```scss
$ease-in-cubic: cubic-bezier(0.550, 0.055, 0.675, 0.190);
$transition: 0.2s #{$ease-in-cubic};

.foo {
  transition: background-color (#{$transition}), box-shadow #{$transition};
}
```
