### ISSUE TITLE
Improper string concatenation w/string functions

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1279]
**TEST:**
```scss
@function capitalize($string) {
    $char: str-slice($string, 1, 1);

    @return to-upper-case($char) + str-slice($string, 2);
}

.test {
  test: capitalize('fred');
}
```

**EXPECTED:** (results per Ruby Sass 3.4.14)
```scss
.test {
  test: "Fred";
}
```

**ACTUAL:** (tested on LibSass 3.2.5)
```scss
.test {
  test: "F"red;
}
```
