### ISSUE TITLE
Type discrepancy for quoted colors (strings)

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1281]
**TEST:**
```scss
$string: "green"; // notice quotes

.test {
  type: type-of($string);
}
```

**EXPECTED:** (Ruby Sass)
```scss
.test {
  type: string;
}
```

**ACTUAL:** (LibSass 3.2.5)
```scss
.test {
  type: color;
}
```

On a similar note, `type-of(unquote("green"))` should also be a `string`.
