### ISSUE TITLE
Improper merging of unequal keys in map-merge

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1283]
**TEST:**
```scss
$map: ();

$map: map-merge($map, (1 2: 3));
$map: map-merge($map, (2 1: 3));

.test {
  test: inspect($map);
}
```

**EXPECTED:** (Ruby Sass)
```scss
.test {
  test: (1 2: 3, 2 1: 3);
}
```

**ACTUAL:** (LibSass 3.2.5)
```scss
.test {
  test: (1 2: 3);
}
```

I'll write specs for all these issues soon, I promise!
