### ISSUE TITLE
Apostrophes converted to escaped quotes, when interpolation used

### ISSUE THREAD

**Issue by marek-saji** [sass/libsass#1295]
I've encountered a bug when using interpolation to customize inlined SVGs:

```css
div
{
    $size: '10px';
    $color: '%23FF0000';
    background-image: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100% 100%' width='#{$size}' height='#{$size}'><circle cx='50%' cy='50%' r='50%' fill='#{$color}' /></svg>");
}
```

produces:

```css
div {
  background-image: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100% 100%' width='10px' height='10px\"><circle cx='50%' cy='50%' r='50%' fill=\"%23FF0000' /></svg>"); }
```

Note the `\"` in `height` and `fill` attributes.

I'm using libsass 3.2.4:

```
$ node-sass --version
node-sass       3.1.2   (Wrapper)       [JavaScript]
libsass         3.2.4   (Sass Compiler) [C/C++]
```

Minimal case producing the problem I've been able to reproduce:

```css
div
{
    $nothing: null;
    a: "#{$nothing}' %' '#{$nothing}";
}
```

which produces:

```css
div {
  a: "\" %' \""; }
```

**Comment by xzyfer** [comment]
Thanks @marek-saji I've confirmed this is a bug.

**Comment by xzyfer** [comment]
Specs added https://github.com/sass/sass-spec/pull/418

**Comment by marek-saji** [comment]
In case someone have the same problem and finds this issue — temporary workaround for my SVG problem is to use single interpolation:

```css
div
{
    $size: '10px';
    $color: '%23FF0000';
    background-image: url("data:image/svg+xml,#{ "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100% 100%' width='" + $size + "' height='" + $size + "'><circle cx='50%' cy='50%' r='50%' fill='" + $color + "' /></svg>" }");
}
```
