### ISSUE TITLE
@at-root with dynamic selector doesn't work

### ISSUE THREAD

**Issue by chriseppstein** [sass/libsass#1297]
```scss
.test .testa {
  @at-root #{"%foo"} {
    color: red;
  }
  @extend %foo;
}
```

Compiles to:

```css
.test .testa .testa {
  color: red;
}
```

Instead of the expected:

```css
.test .testa {
  color: red;
}
```

If `@at-root #{"%foo"}` is changed to `@at-root %foo` it works as expected but these two should be semantically identical.

cc: @eoneill
