### ISSUE TITLE
Interpolation error in classes starting with `-`

### ISSUE THREAD

**Issue by hagenburger** [sass/libsass#1301]
This won’t work in LibSass but does in Ruby Sass and is a valid CSS class:

``` scss
$name: "my-class";
 
.-#{$name} {
  content: "test";
}
```

Expected:

``` css
.-my-class {
  content: "test";
}
```

See tests:
http://sassmeister.com/gist/1ea1287c028efb70c95a
