### ISSUE TITLE
Selector replace doesn't respect specificity

### ISSUE THREAD

**Issue by ekskimn** [sass/libsass#1303]
When executing

```css
.simple {
  a: selector-replace('foo.bar', 'foo', 'foo[baz]');
}
```

i get `foo.bar` but i should get `foo.bar[baz]`
