### ISSUE TITLE
child selector get duplicated parent selector when assigning the parent selector

### ISSUE THREAD

**Issue by ekskimn** [sass/libsass#1304]
When I do:

```css
foo {
	a:&;
	>bar {
		b:&;
		>baz {
			c:&;
		}
	}
}
```

I get

```css
foo {
  a: foo; }
  foo > bar {
    b: foo foo > bar; }
    foo foo > bar > baz {
      c: foo foo foo foo > bar > bar foo foo > bar > baz; }
```
