### ISSUE TITLE
current master eats quotes

### ISSUE THREAD

**Issue by pilif** [sass/libsass#131]
Given

``` css
$foo: bar;

div {
    content: "foo #{$foo}"
}
```

current master (bb136e0aee2063dae2d5631a655ee20c1410a967)

produces

``` css
div {
  content: "foo bar; }
```

How is the process for producing automated testcases? I'd like to contribute a test for this.
