### ISSUE TITLE
Fails to evaluate variables and interpolants in media queries

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1322]
```scss
$foo: 400px;
$bar: "min-width:400px";
@import url(foo.css) (min-width:400px);
@import url(foo.css) (min-width:$foo);
@import url(foo.css) (min-width:#{$foo});
@import url(foo.css) ($bar);
@import url(foo.css) (#{$bar});
```
Ruby Sass
```scss
@import url(foo.css) (min-width: 400px);
@import url(foo.css) (min-width: 400px);
@import url(foo.css) (min-width: 400px);
@import url(foo.css) (min-width: 400px);
@import url(foo.css) (min-width: 400px);
```
LibSass 3.2.5
```scss
Error: top-level @import directive must be terminated by ';'
        on line 3 of test.scss
>> @import url(foo.css) (min-width:400px);
```

Spec added https://github.com/sass/sass-spec/pull/431

**Comment by xzyfer** [comment]
https://github.com/sass/libsass/pull/1324 fixes the error, but interpolation fails.

```scss
@import url(foo.css) (min-width: 400px);
@import url(foo.css) (min-width: $foo);
@import url(foo.css) (min-width: #{$foo});
@import url(foo.css) ($bar);
@import url(foo.css) (#{$bar});
```

**Comment by mgreter** [comment]
The error was that we did not evaluate the media queries in import statements. But there is another strange discrepancy. I would like to change the spec test to:

```css
$foo: 400px;
$bar: "min-width: 400px";
@import url(foo.css) (min-width:400px);
@import url(foo.css) (min-width:$foo);
@import url(foo.css) (min-width:#{$foo});
@import url(foo.css) ($bar);
@import url(foo.css) (#{$bar});
```

Just added a space, since libsass really just adds the string from the variable. It seems ruby sass does a re-interpretation when something is inserted there. See this example:

```css
$bar: "min-width: 2+400px";
@import url(foo.css) ($bar);
@import url(foo.css) (#{$bar});
```

Output:

```css
@import url(foo.css) (min-width: 2 (+400px));
@import url(foo.css) (min-width: 2 (+400px));
```

Not sure why ruby sass is doing that!??
