### ISSUE TITLE
Variable not expanded in url()

### ISSUE THREAD

**Issue by saper** [sass/libsass#1370]
Example code from https://github.com/sass/node-sass/issues/1042 reported by @chenxiaochun

````sass
@mixin ico-common($imgUrl){
    display: inline-block;
    background: url(i/$imgUrl);
    background-repeat: no-repeat;
}

@mixin ico-size($width,$height){
    width: $width;
    height: $height;
}

.test{
    @include ico-common("icon.png");

    @include ico-size(100px, 100px);
}
```

Ruby Sass output (https://github.com/sass/sass/commit/b4bbd962b3c91f6268d5fdfa3e96896d018020fc):

````css
.test {
  display: inline-block;
  background: url(i/"icon.png");
  background-repeat: no-repeat;
  width: 100px;
  height: 100px; }
````

libsass output as of 3.2.5-111-g5e94 (https://github.com/saper/libsass/commit/5e9437b320646b7ccdb24db03a1561ebc8aedd41):

````css
.test {
  display: inline-block;
  background: url(i/$imgUrl);
  background-repeat: no-repeat;
  width: 100px;
  height: 100px; }
````

not sure how useful is `url(i/"something.ico")` output, but that is what Ruby is doing.

If the Ruby Sass behaviour is undesired, please file an issue at https://github.com/sass/sass/issues

**Comment by chenxiaochun** [comment]
I am sorry it's my mistake.
It should't has the double quotation mark. But removed, the Ruby Sass will throw exception.

**Comment by saper** [comment]
so, can we close this?

**Comment by chenxiaochun** [comment]
OK, thank you very much.

**Comment by saper** [comment]
@xzyfer I wonder if this expansion issue is a duplicate of some other issue we already have? Or this a new thing and should be kept open?

**Comment by xzyfer** [comment]
Our `url()` has some big issues. I'm not sure how defined the behaviour exhibited above is but it's probably worth tracking. I'm not aware of a duplicate to this issue.

**Comment by mgreter** [comment]
With #1477 it renders now:

```css
.test {
  display: inline-block;
  background: url(i/icon.png);
  background-repeat: no-repeat;
  width: 100px;
  height: 100px; }
```
