### ISSUE TITLE
Issue with skel.scss

### ISSUE THREAD

**Issue by LoganLehman** [sass/libsass#1377]
You can see from this [issue](https://github.com/n33/skel/issues/142) that skel is having some problems being compiled using libsass specifically at these lines:

    // Modifiers.
			.container.\31 25\25		{ width: 100%; max-width: $width * 1.25; min-width: $width; }
			.container.\37 5\25			{ width: $width * 0.75; }
			.container.\35 0\25			{ width: $width * 0.5; }
			.container.\32 5\25			{ width: $width * 0.25; }

If it compiled using Ruby, it works fine however I need to use libsass for specific reasons. Is there any fix to this issue? According to the issue I linked to, skel relies on those escape chars somewhat heavily.

**Comment by xzyfer** [comment]
@LoganLehman thanks for the report. I can confirm this is fixed on master and will be the next version of LibSass.

```scss
$width: 10;
.container.\31 25\25        { width: 100%; max-width: $width * 1.25; min-width: $width; }
.container.\37 5\25         { width: $width * 0.75; }
.container.\35 0\25         { width: $width * 0.5; }
.container.\32 5\25         { width: $width * 0.25; }
```
LibSass master
```scss
.container.\31 25\25 {
  width: 100%;
  max-width: 12.5;
  min-width: 10; }

.container.\37 5\25 {
  width: 7.5; }

.container.\35 0\25 {
  width: 5; }

.container.\32 5\25 {
  width: 2.5; }
```
