### ISSUE TITLE
@extend loops output selectors in the wrong order

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1392]
``` scss
.foo {a: b; @extend .bar}
.bar {c: d; @extend .baz}
.baz {e: f; @extend .foo}
```

Ruby Sass

``` css
.foo, .baz, .bar { a: b; }
.bar, .foo, .baz { c: d; }
.baz, .bar, .foo { e: f; }
```

LibSass

``` css
.baz, .bar, .foo { a: b; }
.foo, .baz, .bar { c: d; }
.bar, .foo, .baz { e: f; }
```

Spec https://github.com/sass/sass-spec/tree/master/spec/libsass-todo-tests/180_test_basic_extend_loop
Spec https://github.com/sass/sass-spec/tree/master/spec/libsass-todo-tests/181_test_three_level_extend_loop
##

**Comment by mgreter** [comment]
Have seen this one already, IMO it only happens with circular extends ...

**Comment by xzyfer** [comment]
As pointed out by @andybenedict in https://github.com/sass/libsass/issues/1539 this can actually cause broken code when attribute selectors are involved.

```scss
.foo{
  &[disabled]{
    display: none;
  }
}

.bar {
  @extend .foo;
}
```
Libsass
```
.foo[disabled], [disabled].bar {
  display: none;
}
```

**Comment by mgreter** [comment]
@chriseppstein maybe you have any pointers as to how the ordering works?

**Comment by mgreter** [comment]
This is another interestingly similar issue:

```scss
.thing {
    color: red;
}
.thing[disabled] {
    @extend .thing;
    background: blue;
}
```

ruby sass:
```css
.thing, .thing[disabled] {
  color: red; }
.thing[disabled] {
  background: blue; }
```

libsass:
```css
.thing, .thing[disabled] {
  color: red; }
[disabled].thing {
  background: blue; }
```
