### ISSUE TITLE
Interpolation in propsets doesn't work

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1393]
```scss
div {
  back#{ground}: {
    imag#{e}: url(foo.png);
    pos#{it}ion: 50%;
  }
}
```
Ruby Sass
```scss
div {
  background-image: url(foo.png);
  background-position: 50%; }
```
LibSass
```scss
div {
  back#{ground}-image: url(foo.png);
  back#{ground}-position: 50%; }
```
Spec https://github.com/sass/sass-spec/pull/455
