### ISSUE TITLE
Difference in output of media query conditions with binary operations

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1398]
```css
@media screen and (hux: 3/4) {
  foo {
    bar: baz;
  }
}
```
Ruby Sass
```css
@media screen and (hux: 3 / 4) {
  foo {
    bar: baz; } }
```
LibSass
```css
@media screen and (hux: 3/4) {
  foo {
    bar: baz; } }
```
Spec https://github.com/sass/sass-spec/pull/458
