### ISSUE TITLE
Interpolation for feature queries not supported

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1400]
``` scss
$query: "(feature1: val)";
$feature: feature2;
$val: val;
@supports (#{$query} and ($feature: $val)) or (not ($feature + 3: $val + 4)) {
  foo {a: b}
}
```

Ruby Sass

``` scss
@supports ((feature1: val) and (feature2: val)) or (not (feature23: val4)) {
  foo {
    a: b; } }
```

LibSass

``` scss
Error: property "#{$query}" must be followed by a ':'
        on line 4 of test.scss
>> @supports (#{$query} and ($feature: $val)) or (not ($feature + 3: $val + 4)) {
```

Spec https://github.com/sass/sass-spec/tree/master/spec/libsass-todo-tests/scss-tests/128_test_supports_with_expressions
##
