### ISSUE TITLE
It would be nice to use a media-query assigned to a variable

### ISSUE THREAD

**Issue by thasmo** [sass/libsass#1412]
Currently when trying to use a media-query assigned to a variable the parser throws an error that it's not a valid selector.

Something like this doesn't work:
```scss
$mq: "@media (min-width: 320px)";
#{unquote($mq)} {
  p {
    color: red;
  }
}
```

**Comment by Panya** [comment]
It's also doesn't work in Ruby Sass. You should write it like this (without `@media` in a var):
```scss
$mq: "(min-width: 320px)";
@media #{$mq} {
  p {
    color: red;
  }
}
```
