### ISSUE TITLE
Falsey key for map removes value from map

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1416]
**TEST:**
```scss
$map: (
  true: 1,
  false: 0
);

.test {
  map: inspect($map);
  value: inspect(map-get($map, false));
}
```

**EXPECTED: (Ruby Sass)**
```css
.test {
  map: (true: 1, false: 0);
  value: 0;
}
```

**ACTUAL: (Libsass 3.2.5)**
```css
.test {
  map: (true: 1);
  value: null;
}
```
