### ISSUE TITLE
Interpolation in selector breaks @at-root directive

### ISSUE THREAD

**Issue by timswalling** [sass/libsass#1424]
The `@at-root` directive does not work as expected when the selector includes interpolation.

Consider the following example:

```sass
.parent {
  
  @at-root .child-one {
    color: green;
  }
    
  @at-root .#{""}child-two {
    color: red;
  }

}
```

In Ruby Sass (v3.4.14) this compiles as expected:

```css
.child-one {
  color: green;
}
.child-two {
  color: red;
}
```

In libsass (v3.2.5), the `@at-root` directive has no discernible effect when the selector contains interpolation:

```css
.child-one {
  color: green;
}

.parent .child-two {
  color: red;
}
```
