### ISSUE TITLE
Problem with @at-root and extending

### ISSUE THREAD

**Issue by lmartins** [sass/libsass#1429]
Hi, im having a problem which I believe is related to Libsass.
Im using the eq.js library, which declares a mixin making use of @at-root and extending features. The code for that can be viewed at:
https://github.com/Snugug/eq.js/blob/1.x.x/sass/_eq.scss#L25-L47

This mixin is used like this:

```scss
.loop--list{

    @include eq("large") {
        border: 1px solid red;
    }
```

Which is expected to output something like:
```css
.loop--list[data-eq-state$='"large"'] {
    border: 1px solid red
}
```

What happens instead is this:
```css
.loop--list .loop--list[data-eq-state$='"large"'] {
    border: 1px solid red
}
```

Thanks.
