### ISSUE TITLE
selector-nest removes child and sibling selector characters

### ISSUE THREAD

**Issue by mahtd** [sass/libsass#1434]
The new `selector-nest` function in master removes `>`, `+`, and `~` characters for selectors in the second parameter and on

Input:

```scss
$selector: selector-nest('.foo', '.bar > .baz');
#{$selector} {
    foo: bar;
}

$selector: selector-nest('.foo', '.bar ~ .baz');
#{$selector} {
    foo: bar;
}

$selector: selector-nest('.foo', '.bar + .baz');
#{$selector} {
    foo: bar;
}
```

Ruby Sass output:

```
$ sass --version
Sass 3.4.16 (Selective Steve)
$ sass nest-child-sibling.fail.scss
.foo .bar > .baz {
  foo: bar; }

.foo .bar ~ .baz {
  foo: bar; }

.foo .bar + .baz {
  foo: bar; }
```

libsass master output:

```
$ sassc --version
sassc: 3.2.5-14-g5c78
libsass: 3.2.5-170-g3548
sass2scss: 1.0.3
$ sassc nest-child-sibling.fail.scss
.foo .bar .baz {
  foo: bar; }

.foo .bar .baz {
  foo: bar; }

.foo .bar .baz {
  foo: bar; }
```

It should be noted that those characters aren't removed from the first parameter.

Input:

```scss
$selector: selector-nest('.foo > .bar', '.baz');
#{$selector} {
    foo: bar;
}

$selector: selector-nest('.foo ~ .bar', '.baz');
#{$selector} {
    foo: bar;
}

$selector: selector-nest('.foo + .bar', '.baz');
#{$selector} {
    foo: bar;
}
```

libsass master output:

```
$ sassc nest-child-sibling.pass.scss
.foo > .bar .baz {
  foo: bar; }

.foo ~ .bar .baz {
  foo: bar; }

.foo + .bar .baz {
  foo: bar; }
```
