### ISSUE TITLE
Media queries with only CSS comment as content aren't included in the output

### ISSUE THREAD

**Issue by indrekpaas** [sass/libsass#1437]
Input:
```scss
div {

  @media screen and (min-width: 37.5em) {
    /* asd */
  }

  @media screen and (min-width: 48em) {
    display: none;
  }
}
```

Expected result ([demo with Sass 3.4.14](http://sassmeister.com/gist/6eaab83c02af289936f1))
```css
@media screen and (min-width: 37.5em) {
  div {
    /* asd */
  }
}
@media screen and (min-width: 48em) {
  div {
    display: none;
  }
}
```

Actual result ([demo with libsass 3.2.5](http://sassmeister.com/gist/38efd1df8d16cfa4392a))
```css
div {
  /* asd */
}

@media screen and (min-width: 48em) {
  div {
    display: none;
  }
}
```
