### ISSUE TITLE
Rounding errors with mix() function

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1445]
INPUT:
```sass
a {
	color: mix(#f00, #00f);
	color: mix(#f00, #00f, 25%);
	color: mix(rgba(255, 0, 0, 0.5), #00f);
}
```

Ruby Sass 3.4.16
```css
a {
  color: purple;
  color: #4000bf;
  color: rgba(64, 0, 191, 0.75);
}
```

Libsass 3.2.4
```css
a {
  color: #7f007f;
  color: #3f00bf;
  color: rgba(63, 0, 191, 0.75);
}
```
