### ISSUE TITLE
Open curly brackets on new line produce different output then when in same line as selector

### ISSUE THREAD

**Issue by gligoran** [sass/libsass#1448]
For example, when the open curly brackets are in the same line as the selector:

```scss
.md-card {
    .md-info-card-highlight {
        background: red;
        color: blue;

        .ng-md-icon {
            color: green;
        }
    }
}
```

libSass produces this:

```css
.md-card .md-info-card-highlight {
  background: red;
  color: blue;
}
.md-card .md-info-card-highlight .ng-md-icon {
  color: green;
}
```

But is you put the curly brackets in their own line:

```scss
.md-card
{
    .md-info-card-highlight
    {
        background: red;
        color: blue;

        .ng-md-icon
        {
            color: green;
        }
    }
}
```

you get this:

```css
.md-card
.md-info-card-highlight {
  background: red;
  color: blue;
}

.md-card
.md-info-card-highlight
.ng-md-icon {
  color: green;
}
```

I'm not sure how valid this is in CSS, but I feel like both of these should produce the same result and that curly brackets position should not affect compiler result. Also using Sass 3.4.14 compiler both SCSS variations are compiled into the same result, with the whole selector being on the same line. Using output style nested produces similar results.

All these steps are reproduceable in http://sassmeister.com/. Use the gear-button to change compilers.
