### ISSUE TITLE
Should error when attempting to output an empty list or map

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1452]
```scss
foo {
  foo: foo(());
}
```
Ruby Sass
```
Error: () isn't a valid CSS value.
        on line 57 of test.scss
```
Libsass
```
foo {
  foo: foo(); }
```
