### ISSUE TITLE
Expanded variable in url() has the wrong quotes

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1480]
This issue addresses the remaining aspects of https://github.com/sass/libsass/issues/1370 that weren't directly addressed in #1477.

```scss
$image: "icon.png";
foo {
    foo: url(i/$image);
}
```
Ruby Sass
```scss
foo {
  foo: url(i/"icon.png"); }
```
LibSass
```scss
foo {
  foo: url(i/icon.png); }
```
