### ISSUE TITLE
Incorrectly doing a minus operation

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1486]
Originally reported in https://github.com/sass/node-sass/issues/1103

```scss
$num: 3;
foo {
    foo: -10px*$num -120px;
}
```
Ruby Sass
```scss
foo {
  foo: -30px -120px; }
```
LibSass
```scss
foo {
  foo: -150px; }
```
