### ISSUE TITLE
Called function get unexpected `arglist` parameters

### ISSUE THREAD

**Issue by cahnory** [sass/libsass#1488]
```scss
@function foo($arg1, $arg2) {
  @return type-of($arg2);
}

foo {
  foo: call('foo', one, two...);
}
```
Ruby Sass
```scss
foo {
  foo: string; }
```
LibSass
```scss
foo {
  foo: arglist; }
```

Demo: http://sassmeister.com/gist/08c30c195bc9918cb219
