### ISSUE TITLE
Graceful degradation for browsers which doesn't support comma separated rules with inconsistent selector

### ISSUE THREAD

**Issue by AndreyAntipov** [sass/libsass#1489]
Hello. Not quite sure about that thing is good idea and must be here and of-course implemented as core feature, but want to open propose  this idea as is. So, it's not a secret that some browsers, generally, ignore comma separated rules where present some inconsistent selector properties like shadow DOM. 

What if split up selectors like that and then store separately?

So, I would like that libsass parser take this nuance into consideration and produce compatibility for selectors like that by itself when it's required.

From:
```scss
 @mixin dashboardObjects__card--light
  {
    &:before
    {
      content: "";
      position: absolute;

      width: 100%;
      height: 100%;

      top: 0px;
      left: 0px;

      background: rgba(0, 0, 0, 0.2);
    }

  .card paper-card /deep/ .header, .card paper-card .header
  {
    @include dashboardObjects__card--light;
     /* other properties */
  }
```

To:
```css

  .card paper-card /deep/ .header:before, 
  {
      content: "";
      position: absolute;

      width: 100%;
      height: 100%;

      top: 0px;
      left: 0px;

      background: rgba(0, 0, 0, 0.2);
     /* other properties */
  }


.card paper-card .header:before
{
  content: "";
      position: absolute;

      width: 100%;
      height: 100%;

      top: 0px;
      left: 0px;

      background: rgba(0, 0, 0, 0.2);
     /* other properties */
}
``
