### ISSUE TITLE
New CSS filter functions conflict with built-in Sass functions

### ISSUE THREAD

**Issue by sorccu** [sass/libsass#151]
The following code:

``` scss
foo {
  -webkit-filter: grayscale(100%);
}
```

Results in the following with sass 3.2.10:

``` css
foo {
  -webkit-filter: grayscale(100%); }
```

But the following with libsass master (at 4dd61de67aa0284cd8da1e8f13e2f6b63b990041 currently):

```
/private/tmp/test/grayscale.scss:2: error: argument `$color` of `grayscale($color)` must be a color
Backtrace:
    /private/tmp/test/grayscale.scss:2, in function `grayscale`
    /private/tmp/test/grayscale.scss:2
```

This seems to be a conflict with the built-in grayscale function.
