### ISSUE TITLE
Dynamic percentages w/ interpolation incompatible with sass

### ISSUE THREAD

**Issue by sorccu** [sass/libsass#152]
Found this issue in one of our larger codebases.

The following code:

``` scss
@for $i from 1 through 3 {
  foo.bar#{$i} {
    background-size: #{$i * 10}% 100%;
  }
}
```

Results in the following with sass 3.2.10:

``` css
foo.bar1 {
  background-size: 10% 100%; }

foo.bar2 {
  background-size: 20% 100%; }

foo.bar3 {
  background-size: 30% 100%; }
```

But the following with libsass master (at 4dd61de67aa0284cd8da1e8f13e2f6b63b990041 currently):

```
/private/tmp/test/dynpercent.scss:2: error: invalid operands for modulo
```

Note that the for loop is not the problem, it works fine if used normally.
