### ISSUE TITLE
Minor issue parsing number units after double dash

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#1526]
Continued from #1405 and #1471

```scss
foo {
  bar: (1--em-2--em);
  baz: (1--em - 2--em);
}
```
