### ISSUE TITLE
IE-style dropshadow compilation error

### ISSUE THREAD

**Issue by sorccu** [sass/libsass#153]
Again, found while working on a larger SCSS codebase.

The following code:

``` scss
foo {
  filter: dropshadow(color=#ffffff, offx=0, offy=1, positive=1);
}
```

Results in the following with sass 3.2.10:

``` css
foo {
  filter: dropshadow(color=white, offx=0, offy=1, positive=1); }
```

But the following with libsass master (at 4dd61de67aa0284cd8da1e8f13e2f6b63b990041 currently):

```
/private/tmp/test/filter-dropshadow.scss:2: error: error reading values after color
```
