### ISSUE TITLE
`display` rule does not output in CSS inside a media-query with `float` rule

### ISSUE THREAD

**Issue by phoenixenero** [sass/libsass#1549]
I have no idea why this is happening but here:

```css
.primary-menu__dropdown-toggle {
	// ...

	@media ( max-width: 600px ) {
		float: right;
		display: block;
	}

	// ...
}
```

Expected output:

```css
@media ( max-width: 600px ) {
.primary-menu__dropdown-toggle {
		float: right;
		display: block;
	}
}
```

Output that i got:

```css
@media ( max-width: 600px ) {
.primary-menu__dropdown-toggle {
		float: right;
	}
}
```

Using gulp-sass 2.0.4
