### ISSUE TITLE
Throw an error on cross-media @extends

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1562]
Originally reported in https://github.com/sass/libsass/issues/712 and fixed in 3.2.0. This has since regressed.

```scss
.foo {
  content: 'foo'; }

@media print {
  .bar {
    @extend .foo; } }
```

Expected
```
You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .foo" on line 7.
```

Result
```scss
.foo, .bar {
  content: 'foo'; }
```
Spec added https://github.com/sass/sass-spec/pull/538
