### ISSUE TITLE
(Beta) Regression - call() discards items from list argument

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1566]
**TEST:**
```scss
@function foo($predicate) {
  @return call('bar', $predicate);
}

@function bar($predicate) {
  @return type-of($predicate);
}

test {
  test: foo(1 2 3);
}
```

**EXPECTED:** (LibSass 3.2.5, Ruby Sass)
```css
test {
  test: list;
}
```

**ACTUAL:** (Node-Sass 3.4.0 beta)
```css
test {
  test: number;
}
```
