### ISSUE TITLE
Error with comments between media queries

### ISSUE THREAD

**Issue by tiago** [sass/libsass#1567]
**test.scss**:
```scss
@media
screen,  /* something */
print {  /* whatever */
    body { line-height: 1.2 }
}
```
---
**Ruby Sass (3.4.18)**:
```css
@media screen, print {
  /* whatever */
  body {
    line-height: 1.2; } }
```
**SassC (3.3.0-beta1) with LibSass (3.3.0-beta2-2-g997c)**:
```bash
Error: media query expression must begin with '('
        on line 2 of test.scss
>> screen,  /* something */
   ------^
```

**Comment by saper** [comment]
Test written https://github.com/sass/sass-spec/pull/510

**Comment by nkovacs** [comment]
Is this related? 

```scss
a.asc:after {
    content: /*"\e113"*/ "\e151";
}

a.desc:after {
    content: /*"\e114"*/ "\e152";
}
```

Works fine with sass 3.4.14, breaks with libsass 3.2.5

**Comment by xzyfer** [comment]
@nkovacs no that is not related. Your issue is fixed in the 3.4.0-beta.

**Comment by mgreter** [comment]
More complete test case:
```scss
/* any */@media/* first */
/* screen */screen /*something */ , /* else */
/* not */not/* print */print /* final */ {  /* whatever */
    body { line-height: 1.2 }
}
```
