### ISSUE TITLE
Invalid output when semicolon is omitted in the last attribute

### ISSUE THREAD

**Issue by tiago** [sass/libsass#1568]
**test.scss**:
```scss
body {
    font-weight: bold; // test
    font-size: 10px // test
}
```
---
**Ruby Sass (3.4.18)**:
```css
body {
  font-weight: bold;
  font-size: 10px; }
```
**SassC (3.3.0-beta1) with LibSass (3.3.0-beta2-2-g997c)**:
```css
body {
  font-weight: bold;
  font-size: 10px // test; }
```
