### ISSUE TITLE
@extend in multiselector with multiple input types is not working

### ISSUE THREAD

**Issue by jorrit** [sass/libsass#1574]
#1532 seems to work, but I have another, similar, situation with multiple `input` selects that doesn't work with libsass 3.3.0-beta1:

```scss
.form-control {
color: red;
}

input[type="text"],
input[type="search"],
input[type="url"],
input[type="email"],
input[type="password"],
input[type="number"],
input[type="tel"],
input[type="date"],
input[type="range"],
textarea {
	@extend .form-control;
}
```

See http://libsass.ocbnet.ch/srcmap/#LmZvcm0tY29udHJvbCB7CmNvbG9yOiByZWQ7Cn0KCmlucHV0W3R5cGU9InRleHQiXSwKaW5wdXRbdHlwZT0ic2VhcmNoIl0sCmlucHV0W3R5cGU9InVybCJdLAppbnB1dFt0eXBlPSJlbWFpbCJdLAppbnB1dFt0eXBlPSJwYXNzd29yZCJdLAppbnB1dFt0eXBlPSJudW1iZXIiXSwKaW5wdXRbdHlwZT0idGVsIl0sCmlucHV0W3R5cGU9ImRhdGUiXSwKaW5wdXRbdHlwZT0icmFuZ2UiXSwKdGV4dGFyZWEgewoJQGV4dGVuZCAuZm9ybS1jb250cm9sOwp9

It used to work with 3.2.5.
