### ISSUE TITLE
Sass (indented) syntax should treat properties without spaces after the colon as a selector

### ISSUE THREAD

**Issue by cimmanon** [sass/libsass#1578]
In the official Sass compiler, the following code does not generate hover styles, but it does in Libsass:

```sass
.img-ornament
  -webkit-transition: all 0.5s ease
  -moz-transition: all 0.5s ease
  -ms-transition: all 0.5s ease
  -o-transition: all 0.5s ease
  transition: all 0.5s ease
  &:hover
    -webkit-transform:scale(0.75)
    -moz-transform:scale(0.75)
    -ms-transform:scale(0.75)
    -o-transform:scale(0.75)
    transform:scale(0.75)
```

When converted to SCSS, the official compiler treats it as this:

```scss
.img-ornament {
  -webkit-transition: all 0.5s ease;
  -moz-transition: all 0.5s ease;
  -ms-transition: all 0.5s ease;
  -o-transition: all 0.5s ease;
  transition: all 0.5s ease;
  &:hover {
    -webkit-transform:scale(0.75) {}
    -moz-transform:scale(0.75) {}
    -ms-transform:scale(0.75) {}
    -o-transform:scale(0.75) {}
    transform:scale(0.75) {}
  }
}
```

Without a space after the colon, there is no way to disambiguate a selector like `foo:not(.bar)` or `foo :not(.bar)` from property declarations that have a similar syntax like `foo: scale(0.75)`.
