### ISSUE TITLE
A single element comma separated list should be surrounded by `()` when inspected.

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1583]
Originally reported in https://github.com/sass/libsass/issues/1250#issuecomment-144943404

```scss
foo {
  string: inspect(&);
  length: str-length(inspect(&));
}
```
Ruby Sass
```scss
foo {
  string: (foo,);
  length: 6; 
}
```
LibSass 3.3.0-beta
```scss
foo {
  string: foo;
  length: 3; 
}
```

/cc @chetzof
