### ISSUE TITLE
Passing `@content` to `@at-root` allows properties outside of rules

### ISSUE THREAD

**Issue by lunelson** [sass/libsass#1585]
Passing a `@content` block to an `@at-root` rule allows properties to be written at the root without being inside any rule or directive:
```scss
@mixin bar() {
  @at-root { @content; }
}

.test {
  @include bar() {
    color: yellow;
    .nest2 {
      color: green;
    }
  }
}
```
expected:
```bash
Properties are only allowed within rules, directives, mixin includes, or other properties.
```
actual:
```css
color: yellow;
.test .nest2 {
  color: green; }
```
