### ISSUE TITLE
List items dropped when called in function with variable-length args

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1604]
**TEST:**
```scss
@function test($args...) {
  $all: ();

  @each $arg in $args {
    $all: append($all, $arg);
  }

  @return inspect($all);
}

test {
  args-1: test(1 2 3);
  args-2: test(1 2, 3 4);
  args-3: test(1, 2, 3); // control - this works in all versions
}
```

**EXPECTED:** (LibSass 3.2.5 and Ruby Sass 3.4.14)
```
test {
  args-1: (1 2 3);
  args-2: (1 2) (3 4);
  args-3: 1 2 3; 
}
```

**ACTUAL:** (LibSass 3.3.0-beta3)
```
test {
  args-1: 1;
  args-2: 1 3;
  args-3: 1 2 3;
}
```
