### ISSUE TITLE
Extra space outputted in compressed mode when trailing semicolon is omitted

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1612]
Note: this will probably be fixed in ruby sass itself!

Related to https://github.com/sass/libsass/pull/1611

``` css
c {
  b: "foo", bar;
  b: "foo", bar
}
```

Ruby Sass

``` css
c{b:"foo", bar;b:"foo",bar}
```

LibSass 3.3.0-beta3

``` css
c{b:"foo", bar;b:"foo", bar}
```

Spec added https://github.com/sass/sass-spec/pull/549
##
