### ISSUE TITLE
Incorrect output when using @at-root together with interpolation of &

### ISSUE THREAD

**Issue by LukasPrvy** [sass/libsass#1620]
**Source:**

```scss
[test] {
    position: absolute;
    
    @at-root body#{&} {
        position: static;
    }
}
```

**Expected result:**

```scss
[test] {
    position: absolute;
}

body[test] {
    position: static;
}
```

**LibSass:**

```scss
[test] {
    position: absolute;
}

[test] body[test] {
    position: static;
}
```
