### ISSUE TITLE
Regression with list items using call() on function with variable args after static args

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1622]
Sorry for the verbose bug title. This might be related to this: https://github.com/sass/libsass/issues/1604 but it is _not_ the same issue.

**TEST:**
```scss
@function foo($list) {
    @return call(bar, $list);
}

@function bar($list, $args...) {
    @return length($list);
}

test {
  test: foo(1 2 3);
}
```

**EXPECTED:** (LibSass 3.2.5 and Ruby Sass 3.4.14)
```css
test {
  test: 3;
}
```

**ACTUAL:** (with Node-Sass 3.3.0)
```css
test {
  test: 1;
}
```

Side note: I'm going to start writing basic unit tests for these in my Sassdash repo since they are all directly related to Sassdash functions, and discovered by their unit tests (~800).
