### ISSUE TITLE
Regression in outputting property list values

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1629]
```scss
foo {
  background: url(...) 2rem 3rem / auto 2rem;
}
```
LibSass 3.2.5
```scss
foo {
  background: url(...) 2rem 3rem/auto 2rem; }
```
LibSass 3.3.0
```scss
foo {
  background: url(...) 2rem 3rem/"auto" 2rem; }
```
Spec added https://github.com/sass/sass-spec/pull/558
