### ISSUE TITLE
Arguments empty when calling function with an empty list

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1634]
**TEST:**
```scss
$empty-list: ();

@function foo($args...) {
    @return call(bar, $args...);
}

@function bar($list) {
    @return length($list);
}

test {
  test: foo($empty-list);
}
```

**EXPECTED:**
```scss
test {
  test: 0;
}
```

**ACTUAL:** (via Node-Sass 3.3.1)
```bash
Error: required parameter $list is missing in call to function bar
```
