### ISSUE TITLE
Arglist passed as single argument for varargs improperly getting destructured

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1645]
Naming issues is hard.

**TEST:**
```scss
@function foo($a, $should-be-empty...) {
  @return length($should-be-empty);
}

@function bar($args...) {
  @return call(foo, $args...);
}

@function args($args...) {
  @return $args;
}

$a: args(1, 2, 3);

test {
  test: bar($a);
}
```

**EXPECTED:**
```scss
test {
  test: 0;
}
```

**ACTUAL:** (LibSass 3.3.1)
```scss
test {
  test: 2;
}
```

**Comment by mgreter** [comment]
I knew I saw this one before. Check the following example using a space separated list:

```scss
@function foo($a, $should-be-empty...) {
  @return length($should-be-empty);
}

@function bar($args...) {
  @return call(foo, $args...);
}

@function args($args...) {
  @return $args;
}

$a: args(1 2 3);

test {
  test: bar($a);
}
```

**EXPECTED:**
```css
test {
  test: 0;
}
```

**ACTUAL:** (LibSass master 3.3.1+)
```css
test {
  test: 0;
}
```

;)

**Comment by davidkpiano** [comment]
@mgreter I think your example works as expected because you're only passing in one argument to `args()`, instead of three, as in the previous example.

**Comment by mgreter** [comment]
yep, saw it too, thought nobody had seen it yet, already removed it ...

**Comment by ericam** [comment]
I just ran into [this issue today](http://sassmeister.com/gist/06cc198106af785c61f9), and wonder if it's the same thing?

```scss
$function: 'hsl';
$hue: 360;
$value: (30%, 40%);

.test {
  // This doesn't work in libsass (works in ruby sass)
  background-color: call($function, $hue, $value...);
  
  // This works great
  $call: join(($function, $hue), $value);
  color: call($call...);
}

// ERROR: required parameter $lightness is missing in call to function hsl on line 7 at column 21
```
