### ISSUE TITLE
All interpolation is unquoted

### ISSUE THREAD

**Issue by chriseppstein** [sass/libsass#1647]
The fix #1633 only unqoutes interpolation in selectors. This is incorrect. Interpolation always unquotes.

Ruby sass:

```scss
@foo #{"directive"} {
  .#{"foo"} { #{"foo-prop"}: #{"foo-val"}; }
}
```

output:

```css
@foo directive {
  .foo {
    foo-prop: foo-val; } }
```

**Comment by mgreter** [comment]
Do I understand correctly, that `#{#{'\"\'\"foo\"\'\"'}}` should result in `'"foo"'` then? Doesn't seem to be the case (I get `"'\"foo\"'"`)? AFAIR I implemented it so only interpolations into declarations do unquotes? I tried to understand these rules many times, but still fail the see the overall logic (specially with nested interpolations). Unquoting interpolation always doesn't seem right in all situations either.

At least the example you gave [seems to work correctly] [1] :confused: ??
```css
@foo directive {
  .foo {
    foo-prop: foo-val; } }
```

[1]: http://libsass.ocbnet.ch/srcmap/#QGZvbyAjeyJkaXJlY3RpdmUifSB7CiAgLiN7ImZvbyJ9IHsgI3siZm9vLXByb3AifTogI3siZm9vLXZhbCJ9OyB9Cn0=
