### ISSUE TITLE
selectors are not correctly parentized in respect to placeholders

### ISSUE THREAD

**Issue by tomgenoni** [sass/libsass#1654]
Using gulp/grunt-sass with libsass v3.3.1:

```
%foo {
  border: none;

  &__bar {
    display: block;
  }
}

.zoo {
  @extend %foo;
}
```
 Outputs

```
.zoo {
  border: none; }
  __bar.zoo {
    display: block; }
```

Expected output

```
.zoo {
  border: none; }
```

cc @danoc

**Comment by mgreter** [comment]
This looks like a ruby sass bug to me, please see this sample:

```scss
%foo {
  border: none;
  &bar {
    display: block;
  }
  &.bar {
    display: block;
  }
}

.zoo {
  @extend %foo;
  &baz {
    display: block;
  }
  &.baz {
    display: block;
  }
}
```

Results in ruby sass to:
```css
.zoo {
  border: none; }
  .bar.zoo {
    display: block; }

.zoobaz {
  display: block; }
.zoo.baz {
  display: block; }
```

From the semantics I don't see why libsass should be wrong here?

**Comment by danoc** [comment]
@mgreter – We only ran into this issue when using the BEM shorthand notation (`&--`) within a placeholder that is extended.

Ruby Sass behaved as we expected.

**Comment by mgreter** [comment]
What's the reason for having ...
```css
  &__bar {
    display: block;
  }
```
... when it is never output? I mean you seem to expect it to be never output?
Also you did not post anything with `&--` in your sample, so not sure how that's relevant.
The ruby sass behavior is definitely not consistent, so I consider it a bug on their side ATM.
Lets see if anyone from their side can give some insight here ...

**Comment by danoc** [comment]
@mgreter – I'll defer to @tomgenoni for the first question but I should have noted that both `&__` and `&--` produce similar results.

**Comment by mgreter** [comment]
As you can see in **my sample posted above**, the "prefix" doesn't matter at all.

**Comment by tomgenoni** [comment]
@mgreter This is just a reduced case to reproduce the bug. You see the expected output with an earlier version of Libsass and Ruby Sass at http://sassmeister.com/gist/4c34daba378d7269af35

**Comment by xzyfer** [comment]
@mgreter IMHO this is a bug. It's work noting that `&--` and `&__` had their own semantics. This behaviour was introduced in Ruby Sass 3.3.0.

>The parent selector, &, can be used with an identifier suffix. For example, &-suffix and &_suffix are now legal. The suffix will be added to the end of the parent selector, and will throw an error if this isn’t possible. & must still appear at the beginning of a compound selector – that is, .foo-& is still illegal.

Maybe @chriseppstein can give more information on the exact semantics.

**Comment by mgreter** [comment]
You all see that ruby sass is not consisten between `extend`, `regular selector`, `type selector` and `class selector`?

**Comment by chriseppstein** [comment]
`@extend` is applied after nesting is resolved. `&baz` creates a new class built from the classname represented by `&` so `@extend` doesn't match against it. If the parent selector is a placeholder, it creates a new placeholder that never gets extended and that is then dropped from the output.

Does this resolve the confusion?

**Comment by mgreter** [comment]
Not really, why does it work with `&.baz` then?

**Comment by mgreter** [comment]
OK, I think I need to repeat my sample from above, since I'm not sure you guys see the difference!?

```scss
.zoo {
  &baz {
    display: block;
  }
  &.baz {
    display: block;
  }
}
```
```css
.zoobaz {
  display: block; }
.zoo.baz {
  display: block; }
```

vs.

```scss
%foo {
  &bar {
    display: block;
  }
  &.bar {
    display: block;
  }
}
zoo {
  @extend %foo;
}
```

```css
zoo.bar {
  display: block;
}
```

This doesn't seem consistent!?
