### ISSUE TITLE
Properties with null values are printed

### ISSUE THREAD

**Issue by Nabellaleen** [sass/libsass#166]
``` CSS
.test {
  background-color: null;
  color: blue;
}
```

should return

``` CSS
.test {
  color: blue; }
```

but return

``` CSS
.test {
  background-color: ;
  color: blue; }
```
