### ISSUE TITLE
Regression - Unexpected string concatenation for selectors extending placeholders

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#1673]
**TEST:**
```scss
%foo {
  test: outer;

  &-inner {
    test: inner;
  }
}

.foo {
  @extend %foo;

  &.inner { @extend %foo-inner; }
}
```

**EXPECTED:** (Ruby Sass and LibSass 3.2.5)
```css
.foo {
  test: outer;
}

.foo.inner {
  test: inner;
}

```

**ACTUAL:** (with Node-Sass 3.4.x latest)
```css
.foo {
  test: outer;
}

-inner.foo {
  test: inner;
}
```
