### ISSUE TITLE
Interpolation shouldn't be allowed in IE filters outside of argument list

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1694]
Three parsing discrepancies to report here, all related to parsing of IE filter values.  These are probably trivial (especially the last two) but I figured I might as well report them anyway.

First, Ruby SASS does not permit interpolation to be used in `progid:` values outside of the argument list.  For example this is not allowed:

``` SASS
test {
  filter: progid:DXImageTransform.Microsoft.#{Alpha(opacity=20)};
}
```

Ruby SASS:

```
Error: Invalid CSS after "  filter: progid": expected ";", was ":DXImageTransfo..."
```

Libsass:

``` CSS
test {
  filter: progid:DXImageTransform.Microsoft.Alpha(opacity=20);
}
```

Second, Ruby SASS does not allow CSS escapes in `progid:` values either:

``` SASS
test {
  filter: progid:DXImageTransform.\Microsoft.Alpha(opacity=20);
}
```

Ruby SASS:

```
Error: Invalid CSS after "  filter: progid": expected ";", was ":DXImageTransfo..."
```

Libsass:

``` CSS
test {
  filter: progid:DXImageTransform.\Microsoft.Alpha(opacity=20);
}
```

Finally, it looks like Ruby treats escaped braces in the argument list as ordinary braces for the purpose of determining where the `progid:` value ends; Libsass does not:

``` SASS
test {
  filter: progid:DXImageTransform.Microsoft.Alpha(opacity=20\);
}
```

Ruby SASS:

``` CSS
test {
  filter: progid:DXImageTransform.Microsoft.Alpha(opacity=20\);
}
```

Libsass:

```
Error: unclosed parenthesis
```

If you add an unescaped brace to the end, Ruby SASS fails, and Libsass works, but it does not output the second brace.

``` SASS
test {
  filter: progid:DXImageTransform.Microsoft.Alpha(opacity=20\));
}
```

Ruby SASS:

```
Error: Invalid CSS after "...ha(opacity=20\)": expected ";", was ");"
```

Libsass:

``` CSS
test {
  filter: progid:DXImageTransform.Microsoft.Alpha(opacity=20\);
}
```
##
