### ISSUE TITLE
Strings in mixin arguments

### ISSUE THREAD

**Issue by DanPurdy** [sass/libsass#1696]
I apologise in advance for the format of this issue but this is the first time i've actually dug into the workings here after this issue came up with the latest update.

We have a breakpoint mixin which at it's most basic level takes a name of a breakpoint which would be defined in a map and then returns the correct breakpoint after merging a few maps together etc.

```scss
$mobile-first: false !default;

$break-large: 960px !default;
$break-medium: 768px !default;
$break-small: 480px !default;
$break-x-small: 320px !default;

$default-breakpoints: (
    large: $break-large,
    medium: $break-medium,
    small: $break-small,
    x-small: $break-x-small
);

$custom-breakpoints: () !default;

@mixin breakpoint($options...) {

/* snip! */

    @media #{$output} {
        @content;
    }
}

.test {
  @include breakpoint(large) {
    color: red;
  }
}
```

Expected behaviour and in `node-sass 3.3.3` /  `libsass 3.2.5`

```scss
@media (max-width: 960px) {
  .test {
    color: red; } }
```

Actual output in `node-sass 3.4.1` / `libsass 3.3.1`
```scss
@media (max-width: false) {
  .test {
    color: red; } }
```

====

We can also pass a range to that mixin which generates another issue

```scss
.test {
  @include breakpoint(large, medium) {
    color: red;
  }
}
```

Expected behaviour and in `node-sass 3.3.3` /  `libsass 3.2.5`

```scss
@media (max-width: 960px) and (min-width: 768px) {
  .test {
    color: red; } }
```

Actual output is just an error as below
```bash
Error: may only compare numbers
        on line 379 of stdin
>>   @include breakpoint(large, medium) {
   ----------------------^
```

So i'm not convinced the issue lies in just mixin arguments but im afraid Im not really sure where to look from here, if you need to see how the mixin works and related functions work in their entirety they can bef found here:

[mixins](https://github.com/loftdigital/echo-base/blob/develop/app/scss/echo-base/defaults/utilities/_mixins.scss#L166)
[functions](https://github.com/loftdigital/echo-base/blob/develop/app/scss/echo-base/defaults/utilities/_functions.scss)

Again apologies if this isn't too helpful but thanks anyway!

node versions tested v0.12.0 & v4.2.2
