### ISSUE TITLE
Syntax error results in a segmentation fault

### ISSUE THREAD

**Issue by lolmaus** [sass/libsass#1702]
I've just wasted four hours on fierce debugging, with hair pulling and nail biting and all.

The reason of the segmentation fault appeared to be a syntax error which I introduced after manually converting `.sass` to `.scss`.

Here's an example `scss` code that crashes libsass:

```scss
@at-root

  html {
    color: red;
  }
```

As you can see, `@at-root`'s curlies are missing.

Instead of crashing, libsass should report a syntax error.

**Comment by lolmaus** [comment]
For anyone wondering, I use `@at-root` like that to avoid polluting the global variable/mixin/function namespace.

**Comment by mgreter** [comment]
Please always include at least the version you are using!
Closing this since [I cannot reproduce it on latest master] [1].

[1]: http://libsass.ocbnet.ch/srcmap/#QGF0LXJvb3QKCiAgaHRtbCB7CiAgICBjb2xvcjogcmVkOwogIH0=

**Comment by lolmaus** [comment]
I'm sorry, I've included wrong code example.

This one should cause a segmentation fault:

```scss
@at-root

  @import 'foo';

  html {
    color: red;
  }
```

libsass 3.3.1, node-sass 3.4.1.
