### ISSUE TITLE
Functions named calc() or -*-calc() should not be called

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1706]
Ruby SASS always outputs function arguments literally when the called function's name is `calc()` or `-*-calc()`, even if a custom `@function` with one of those names has been defined.

As an aside, I have noticed that when `call()` is used (in both SASS and Libsass) the redefined functions *are* called.  This behavior would need to be preserved to prevent a regression.

Input SASS:
```SASS
@function calc($e) { @return custom; }
@function -foo-calc($e) { @return custom; }

.test {
	a: calc(1px * 1%);
	b: -foo-calc(2px * 2%);
	c: call(calc, 3px * 3%);
}
```

Ruby SASS Output (3.4.19):
```CSS
.test {
	a: calc(1px * 1%);
	b: -foo-calc(2px * 2%);
	c: custom;
}
```

Libsass Output (3.2.5):
```CSS
.test {
	a: custom;
	b: custom;
	c: custom;
}
```

**Comment by saper** [comment]
Ruby gives a warning:
DEPRECATION WARNING on line 1 of libsass-todo-issues/issue_1706/input.scss:
Naming a function "calc" is disallowed and will be an error in future versions of Sass.
This name conflicts with an existing CSS function with special parse rules.

DEPRECATION WARNING on line 2 of libsass-todo-issues/issue_1706/input.scss:
Naming a function "-foo-calc" is disallowed and will be an error in future versions of Sass.
This name conflicts with an existing CSS function with special parse rules.

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/608

**Comment by LPGhatguy** [comment]
I would promote this bug's fix being delayed until after #1776 is also resolved -- as it stands this bug is the best way to sidestep the issue.

**Comment by mgreter** [comment]
Started some initial progress, but fixing all different cases will take a bit longer.

My WIP 3.4 branch currently yields (had to reduce seconds args to numbers)

```css
.test {
  a: calc(1px * 1);
  b: custom;
  c: calc(9px); }
```

**Comment by xzyfer** [comment]
IIRC Ruby Sass opts out of evaluating arguments for certain special functions like calc. I think this is ideal approach. https://github.com/sass/sass/blob/stable/lib/sass/scss/parser.rb#L932

There is ongoing discussion in Ruby Sass about how to best handle calc - https://github.com/sass/sass/issues/818

**Comment by lunelson** [comment]
I noticed the following today with 3.3.4: anything starting with calc seems to be skipped:
```scss
@function calcfoo() { @return 'hello world'; }
@function barcalc() { @return 'hello world'; }

.test {
  out: calc-foo();
  out: calcfoo();
  out: barcalc();
}
```
```css
.test {
  out: calc-foo();
  out: calcfoo();
  out: "hello world"; }
```

**Comment by lunelson** [comment]
So is this the spec then? I have a group of functions that operate on `calc()` expressions—would be good to know what the future-proof naming convention is

```scss
@function calc(){ @return 'hello world'; }
@function -foo-calc(){ @return 'hello world'; }
@function foo-calc(){ @return 'hello world'; }
@function calc-foo(){ @return 'hello world'; }

.test {
  out: calc(); // won't be processed
  out: -foo-calc(); // won't be processed
  out: foo-calc(); // ok?
  out: calc-foo(); // ok?
}```
```css
.test {
  out: calc();
  out: -foo-calc();
  out: "hello world";
  out: "hello world";
}
```
