### ISSUE TITLE
Strange behaviour with unicode

### ISSUE THREAD

**Issue by evilebottnawi** [sass/libsass#1717]
My code:
```sass
$ie8screen: "\0screen";
.vjs-default-skin.vjs-user-inactive.vjs-playing .vjs-control-bar :before {
    @media #{$ie8screen} {
        content: "";
    }
}
```

Output:
```css
@media ï¿½screen {
  .vjs-default-skin.vjs-user-inactive.vjs-playing .vjs-control-bar :before {
    content: "";
  }
}
```
It is normal, i think it is not working in ie8 or I'm wrong?
