### ISSUE TITLE
Comments into rules

### ISSUE THREAD

**Issue by LeusMaximus** [sass/libsass#1718]
Hi. Is it possible don't delete comments into css-rules after compiling?
Like this:
```css
.block {
  font-size: 20px /* rtl:10px*/;
}
```
