### ISSUE TITLE
Error when commenting out part of a declaration that includes an interpolation

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1726]
Basically, this error happens for any declaration that includes both a comment and an interpolation.  It doesn't matter if the comment appears before or after the interpolation.

Input SCSS:
```SCSS
.item {
    background: #{2px} 2px /*red*/;
}
```

Libsass Output: (v3.2.5)
```
Error: error parsing interpolated value
        on line 2 of test.scss
>>     background: #{2px} 2px /*red*/;
```

Ruby SASS: (3.4.19)
```CSS
.item {
  background: 2px 2px;
}
```

Works fine when the interpolation appears within brackets, though:

Input SCSS:
```SCSS
.item {
    transform: skewx(#{25deg}) /* translatex(150px) */;
}
```

Libsass Output:
```CSS
.item {
  transform: skewx(25deg);
}
```
