### ISSUE TITLE
multiple nth-child selector with @extend inside only complies the first one

### ISSUE THREAD

**Issue by hyunchulkwak** [sass/libsass#1729]
example
```scss
%place-to-go {
  font-size: 1em;
}

.where-i-am {
  &:nth-child(1){
    @extend %place-to-go;
  }
  &:nth-child(2){
    @extend %place-to-go;
  }
  &:nth-child(3){
    @extend %place-to-go;
  }
}
```

expected
```css
.where-i-am:nth-child(1),
.where-i-am:nth-child(2),
.where-i-am:nth-child(3) {
  font-size: 1em;
}
```

result
```css
.where-i-am:nth-child(1) {
  font-size: 1em;
}
```

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/609

**Comment by mgreter** [comment]
Bare bone spec would be:
```scss
%place-to-go {
  font-size: 1em;
}

:nth-child(1){
  @extend %place-to-go;
}
:nth-child(2){
  @extend %place-to-go;
}
:nth-child(3){
  @extend %place-to-go;
}
```
