### ISSUE TITLE
Including a `@mixin` when outside of selector still outputs properties

### ISSUE THREAD

**Issue by ezekg** [sass/libsass#1732]
As mentioned in https://github.com/ezekg/flint/issues/40#issuecomment-156465316 and similar to https://github.com/sass/libsass/issues/1585.

### Reproducable test case:
```scss
@mixin a {
  b: c;
}

@include a();
```

### Compiling with Ruby Sass results in:

```
Error: Properties are only allowed within rules, directives, mixin includes, or other properties.
```

Cmd: `sass test.scss` 

### Compiling with Libsass results in:

```css
b: c;
```

Cmd: `sassc test.scss`

**Comment by xzyfer** [comment]
Thanks for the report @ezekg.

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/613

**Comment by mgreter** [comment]
This is a bit more complicated since the check cannot be done in parser, since the following is valid:

```scss
@mixin a {
  b: c;
}
foo {
  @include a();
}
```

So we need to do this check after the mixin is expanded.
