### ISSUE TITLE
Hex codes aren't being compressed properly

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1733]
``` scss
foo {
  color: #FF6600
}
```

Ruby Sass

``` css
foo{color:#f60}
```

LibSass 3.3.2

``` css
foo{color:#FF6600}
```

Spec added https://github.com/sass/sass-spec/pull/614
##

**Comment by mgreter** [comment]
Looks like a ruby sass bug to me:
```scss
foo {
  color: #FFFFFF;
  color: #FFFFFF
}
```

Results in:
```css
foo{color:#FFFFFF;color:#fff}
```
