### ISSUE TITLE
Using appended list of selectors as a selector throws error

### ISSUE THREAD

**Issue by AlbertoElias** [sass/libsass#1740]
So I'd expect this to work:

```scss
$selectors: null;
$selectors: append($selectors, #{'.my-class'}, comma);
#{$selectors} {
    display: block;
}
```

But instead I get an `invalid selector after  ` (whitespace included) error.

The output of `append` should just be `.my-class` and using regular interpolation on that does work fine:

```scss
$selectors: #{'.my-class'};
#{$selectors} {
    display: block;
}
```

Does work fine with Ruby Sass.

I can't seem to save it as a gist in Sassmeister, so sorry for not sharing that.
