### ISSUE TITLE
ampersands in :not selector

### ISSUE THREAD

**Issue by blimmer** [sass/libsass#1741]
In the process of upgrading to libsass 3.3.x, I noticed that a (potentially incorrect) selector I was using before was no longer working.

### Sass in question
```sass
.header {
  .nav-text-link:not(&.popover-link) {
    margin: 10px;
  }
}
```

### Libsass 3.3.2 (invalid css)
```css
.header .nav-text-link:not(&.popover-link) {
  margin: 10px; }
```

### Libsass 3.2.5
```css
.header .nav-text-link:not(.popover-link) {
  margin: 10px;
}
```

However, I realized that my use of the ampersand character in that `:not` selector was actually incorrect from the beginning. What I wanted was really:

```scss
.header {
  .nav-text-link:not(.popover-link) {
    margin: 10px;
  }
}
```

### Ruby 3.4.14 
Out of curiosity I ran the original sass (with the ampersand) against Ruby 3.4.14 and got this output:
```css
.nav-text-link:not(.header.popover-link) {
  margin: 10px;
}
```

So there's definitely (at least) a bug with libsass leaving an ampersand in compiled css. Then there's the issue of what the "correct" interpretation of a nested ampersand in a `:not` selector is.
