### ISSUE TITLE
nested styles refer to top-level parent in sourcemap line number

### ISSUE THREAD

**Issue by tehOPEologist** [sass/libsass#1747]
### i'm creating this issue here to get more visibility on an issue i originally opened in the node-sass repo.  link here: https://github.com/sass/node-sass/issues/1206

i'm having an issue where my nested styles' sourcemap line number in chrome is referencing the top-most parent selector line and not the line that the nested selector starts.

```
body {
  h1 {
    background: #f00;
  }
}
```

will show file.scss:1 instead of file.scss:2 for the h1

i've tried outputting the map file to a separate file and embedding it, all the same.

***
***

just ran a test with the latest ruby sass and it's sourcemapping nested children on the child's line and not the top-most parent like it should be.  this is definitely a bug and isn't working as intended.

### Ruby Sass 3.4.19:
```scss
body {
  h1 {
    background: red;
  }
}
```
#### compiles to:
```css
body h1 {
  background: red; }

/*# sourceMappingURL=core.css.map */
```
#### core.css.map:
```json
{
"version": 3,
"mappings": "AACE,OAAG;EACD,UAAU,EAAE,GAAG",
"sources": ["core.scss"],
"names": [],
"file": "core.css"
}
```
---
### node-sass 3.4.1:
```scss
body {
  h1 {
    background: red;
  }
}
```
#### compiles to:
```css
body h1 {
  background: red; }

/*# sourceMappingURL=core.css.map */
```
#### core.css.map:
```json
{
	"version": 3,
	"file": "core.css",
	"sources": [
		"core.scss"
	],
	"mappings": "AAAA,IAAI,CACF,EAAE,CAAC;EACD,UAAU,EAAE,GAAI,GACjB",
	"names": []
}
```
