### ISSUE TITLE
Media feature required in media query expression

### ISSUE THREAD

**Issue by chicoxyzzy** [sass/libsass#1753]
processing fails on node-sass 3.4.2 (libsass 3.3.2)
```
  @media #{map-get($mappy-map, type)} and #{map-get($mappy-map, media-string)} {
         ^
      Media feature required in media query expression
```
on [this line](https://github.com/zellwk/mappy-breakpoints/blob/master/_mappy-breakpoints.scss#L47) of https://github.com/zellwk/mappy-breakpoints

**Comment by xzyfer** [comment]
I'm unable to reproduce locally. This suggest the issue is with the values within $mappy-map. Please provide a **small** working example Sass file that produces this error.

**Comment by mgreter** [comment]
Closing this as not reproducible. Re-open if you can provide a working self contained example. Thanks!

**Comment by greypants** [comment]
I ran into the same issue on `3.4.2`, but can confirm this is fixed in the most recent release.

This was the previously failing code:

```scss
$breakpoints: (
  "small"  : "(min-width: 480px)",
  "medium" : "(min-width: 680px)",
  "large"  : "(min-width: 900px)",
  "max"    : "(max-height: 1200px)"
);

@mixin breakpoint($key) {
  @media #{map-get($breakpoints, $key)} {
    @content
  }
}
```
