### ISSUE TITLE
bug with & (parent-selector) and @each directive in 3.3.2

### ISSUE THREAD

**Issue by lunelson** [sass/libsass#1757]
-- edit --
The following regression has been identified by @xzyfer as having to do with the `@each` directive. Current workaround is to use a `@for` loop instead.

```scss
@function last-sels() {
  $out: ();
  @each $list in & {
    $last: nth($list, length($list));
    @if not index($out, $last) {
      $out: append($out, $last, 'comma');
    }
  }
  @return $out;
}

.test .nest {
  content: inspect(last-sels());
}

.test, .other {
  content: inspect(last-sels());
}
```

resulted in this in 3.2.5

```css
.test .nest {
  content: (.nest,);
}

.test, .other {
  content: .test, .other;
}
```

but in 3.3.2 does this

```css
.test .nest {
  content: .test .nest;
}

.test, .other {
  content: .other;
}
```

**Comment by xzyfer** [comment]
This appears to be a bug with `@each` and `&`. The following changes fixes your issue.

```
-  @each $list in & {
+  @for $i from 1 through length(&) {
+    $list: nth(&, $i);
```

**Comment by lunelson** [comment]
ah good catch! I can work with that, shall I update the title of this issue?

**Comment by xzyfer** [comment]
Yea please.

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/637

**Comment by xzyfer** [comment]
Added to the 3.4 milestone since there is a viable workaround.

**Comment by jakob-e** [comment]
Maybe this is related (for loop does not seem to fix it):

````SCSS
@mixin nth-child($values...){
  $sel:();
  @each $value in $values {
    $sel: append($sel, unquote('#{&}:nth-child(#{$value})'), comma); 
  }
  @at-root { 
    #{$sel}{ @content; } 
  }
}

li {
    @include nth-child(4, 3n){
      background-color:tomato;
    }
}

// Ruby output
li:nth-child(4), li:nth-child(3n) {
  background-color: tomato;
}

// Libsass output
li li:nth-child(4), li li:nth-child(3n) {
  background-color: tomato;
}

`````
http://sassmeister.com/gist/47a05fb54973156119b3
