### ISSUE TITLE
String Interpolation incorrectly quoted when used as parent selector

### ISSUE THREAD

**Issue by petebrowne** [sass/libsass#1770]
Input SCSS:

``` scss
@function returns-string() {
  @return "selector";
}

#{"selector"} {
  color: red;
}

#{returns-string()} {
  color: red;
}

#{"selector"} selector2 {
  color: red;
}

#{returns-string()} selector2 {
  color: red;
}
```

Ruby Sass output:

``` css
selector {
  color: red; }

selector {
  color: red; }

selector selector2 {
  color: red; }

selector selector2 {
  color: red; }
```

Libsass (via node-sass)

``` css
selector {
  color: red; }

selector {
  color: red; }

selector selector2 {
  color: red; }

"selector" selector2 {
  color: red; }
```
