### ISSUE TITLE
@at-root on interpolated selector 

### ISSUE THREAD

**Issue by jakob-e** [sass/libsass#1775]
@at-root on interpolated selector seems to fail in v.3.2.5 
http://sassmeister.com/gist/47a05fb54973156119b3
````SCSS
// ----
// libsass (v3.2.5)
// ----

@mixin nth-child($values...){
  $sel:();
  @each $value in $values {
    $sel: append($sel, unquote('#{&}:nth-child(#{$value})'), comma); 
  }
  @at-root { 
    #{$sel}{ @content; } 
  }
}


ul {
  li {
      @include nth-child(4, 3n){
        background-color:tomato;
      }
  }
}

// Ruby output
ul li:nth-child(4), ul li:nth-child(3n) {
  background-color: tomato;
}

// Libsass output
ul li ul li:nth-child(4), ul li ul li:nth-child(3n) {
  background-color: tomato;
}

`````
