### ISSUE TITLE
No errors thrown for random values after "@"

### ISSUE THREAD

**Issue by ctigelaar** [sass/libsass#1784]
When you use ```@extends .someclass``` instead of ```@extend .someclass```, no error is returned. Even if you use ```@foobar .someclass``` it will not give me an error on running sass. This way I can't see if the result of my build is as I expected it would be. I would expect it would give me a syntax error or something like that.

I tested it using ```node-sass@3.4.2``` which uses libsass. I think it's a libsass issue, as ```node-sass``` is just a libsass wrapper for node.

**Comment by xzyfer** [comment]
I'm currently away for the weekend. Does Ruby Sass throw an error? We must
do what they do.

**Comment by davidkpiano** [comment]
Ruby Sass does not throw an error, but the outputs are inconsistent:

**Test**
```scss
.bar {
  color: green;
}

.foo {
  @extends .bar;
}
```

**Ruby Sass output**
```css
.bar {
  color: green;
}

.foo {
  @extends .bar;
}
```

**Libsass + Node Sass output**
```css
.bar {
  color: green;
}

@extends .bar;
```
