### ISSUE TITLE
Append function doesn't appear to append correctly inside loops

### ISSUE THREAD

**Issue by cimmanon** [sass/libsass#1796]
Tested against Sassmeister (running 3.3.2) and [3.3.1-52-gf89e](http://libsass.ocbnet.ch/srcmap/)

```scss
.parent {
	.brother, .sister, .cousin {
		color: green;
		sel: &;

		$new-sel: ();
		@each $s in & {
			$last: nth($s, -1);
			$new-sel: append($new-sel, $s #{'+'} $last, comma);
			x: $new-sel;
		}
		@at-root #{$new-sel} {
			debug: foo;
		}
	}
}
```

Ruby Sass Output:

```css
.parent .brother, .parent .sister, .parent .cousin {
  color: green;
  x: .parent .brother + .brother;
  x: .parent .brother + .brother, .parent .sister + .sister;
  x: .parent .brother + .brother, .parent .sister + .sister, .parent .cousin + .cousin;
}
.parent .brother + .brother, .parent .sister + .sister, .parent .cousin + .cousin {
  debug: foo;
}
```

LibSass Output:

```css
.parent .brother, .parent .sister, .parent .cousin {
  color: green;
  x: .parent .brother, .parent .sister, .parent .cousin + .parent .cousin;
}

.parent .brother, .parent .sister, .parent .cousin + .parent .cousin {
  debug: foo;
}
```

Note how LibSass doesn't show the intermediate values inside the loop (property `x`) and only the very last element in the list contains our adjacent sibling selector.
