### ISSUE TITLE
@extend only applied to first element in @for loop when variable is used as a selector argument

### ISSUE THREAD

**Issue by nathanielw** [sass/libsass#1805]
Easier to show this one before explaining:

[Code](http://www.sassmeister.com/gist/aad0b523a22cf6f86df3)

```scss
%test {
 color: red; 
}

@for $i from 1 through 4 {
  *:nth-child(#{$i}) {
    @extend %test;
  }
}
```

Actual (libsass 3.3.2):
```css
*:nth-child(1) {
  color: red;
}
```

Expected (as given by Ruby Sass):
```css
*:nth-child(1), *:nth-child(2), *:nth-child(3), *:nth-child(4) {
  color: red;
}
```

If the variable is used as part of the selector (e.g. `.item-#{$i} { ... }`) this works fine, but it seems that if the variable is given as an argument to a pseudo-class, then libsass only applies the extension on the first iteration (I'm guessing it's trying to optimize, but only checks if variables are in the selector itself, not its arguments).
