### ISSUE TITLE
Single quotes are removed in data uri during compilation

### ISSUE THREAD

**Issue by BboyKeen** [sass/libsass#1806]
Hi,

I've just encontered a bug when using inlined SVG

```css
div {
    background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' version='1.1' width='32' height='24' viewBox='0 0 32 24'><polygon points='0,0 32,0 16,24' style='fill: rgb%2851, 51, 51%29'></polygon></svg>");
}
```
produces 

```css
div {
    background-image: url("data:image/svg+xml;utf8,<svg xmlns=http://www.w3.org/2000/svg version=1.1 width=32 height=24 viewBox=0 0 32 24><polygon points=0,0 32,0 16,24 style=fill: rgb%2851, 51, 51%29></polygon></svg>");
}
```

You'll notice that all single quotes are removed after compilation, which results in bad SVG.

When using base64 encoded resource, there is no problem.

I'm using 
```
node-sass	3.4.2	(Wrapper)	[JavaScript]
libsass  	3.3.2	(Sass Compiler)	[C/C++]
```
