### ISSUE TITLE
Regression in variable scoping causing segfault

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1813]
@mgreter #1748 introduced a regression with variable scoping / environments.

```scss
@function foo($value) {
  $a: bar($value);
  @debug($value);
  @return null;
}

@function bar($list) {
  @while (true) {
    @return true;
  }
}

$map: ('a': 1, 'b': 2, 'c': 3);
$b: foo($map);
```
Ruby Sass
```
test.scss:5 DEBUG: true
test.scss:6 DEBUG: ("a": 1, "b": 2, "c": 3)
```
LibSass
```
/Users/michael/Projects/Sass/libsass/test.scss:5 DEBUG: true
[1]    77502 segmentation fault  /Users/michael/Projects/Sass/sassc/bin/sassc test.scss
```

**Comment by xzyfer** [comment]
Removing the `debug` results in an undefined variable error

```scss
@function foo($value) {
  $a: bar($value);
  @return $value;
}
```
```
Error: Undefined variable: "$value".
        on line 5 of test.scss
>>   @return $value;
   ----------^
```
