### ISSUE TITLE
libsass chokes on sass-bootstrap mixin

### ISSUE THREAD

**Issue by ain** [sass/libsass#182]
Something that succeeds in `grunt-contrib-compass`, fails in `grunt-sass` relying on libsass:

> Warning: app/bower_components/sass-bootstrap/lib/mixins:712: error: invalid selector after ,

ln 708-712 in mixins:

``` scss
@mixin make-lg-column-pull($columns) {
  @media (min-width: $screen-lg-min) {
    right: percentage(($columns / $grid-columns));
  }
}
```

See also the respective (closed) [grunt-sass ticket](https://github.com/sindresorhus/grunt-sass/issues/47).
