### ISSUE TITLE
Error incorrectly thrown for `&__` selector

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1825]
Originally reported https://github.com/sass/node-sass/issues/1329.

Turns out this is valid Sass.

```sass
foo {
  &-- {
    &baz {
      color: red;
    } } } 
```
Ruby Sass
```css
foo--baz {
  color: red;
}
```
LibSass
```
Error: Invalid CSS after "foo {": expected "}", was "&-- {"
        on line 25 of test.scss
>> foo {
   -----^
```
****
It's worth noting that `&__` compiles correctly.

```sass
foo {
  &__ {
    &baz {
      color: red;
    } } }
```
```css
foo__baz {
  color: red;
}
```
Spec https://github.com/sass/sass-spec/pull/670

**Comment by mgreter** [comment]
Reason why `__` works, is because the following is valid
```scss
__ {
  foo: bar;
}
```

While the following is not:
```scss
-- {
  foo: bar;
}
```

Knowing that a fix should be pretty simple.
