### ISSUE TITLE
Extend inside root block should error

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#1873]
Continued from https://github.com/sass/libsass/issues/1651

```scss
.a {
  display: block;
}

.b {
  @at-root (with: media) {
    @extend .a;
  }
}
```

Should error:
```
Error: Extend directives may only be used within rules.
```

Error is disabled for now until we figure out how to handle `with` and `without` correctly
