### ISSUE TITLE
Segfault on empty url()

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1886]
```scss
body { 
  background: url()
}
```
LibSass 3.3.2
```css
body {
  background: url(url(); }
```
LibSass 3.3.3
```css
[1]    46392 segmentation fault  /Users/michael/Projects/Sass/sassc/bin/sassc test.scss
```
Ruby Sass
```css
body {
  background: url(); }
```
