### ISSUE TITLE
@at-root (without: media) selector outside from wapper

### ISSUE THREAD

**Issue by sou-lab** [sass/libsass#1890]
When use "@at-root (without: media)".
`.box` is outside from `.wrap`

``` scss
.wrap {
  @media (min-width: 480px) { 
    display: block;
    @at-root (without: media){ 
      .box { 
        display: inline-block;
      }
    } 
  }
}
```

LibSass

``` css
@media (min-width: 480px) {
  .wrap {
    display: block;
  }
}

.box {
  display: inline-block;
}

```

Ruby Sass 3.4

``` css
@media (min-width: 480px) {
  .wrap {
    display: block;
  }
}
.wrap .box {
  display: inline-block;
}
```

Spec added https://github.com/sass/sass-spec/pull/749
##

**Comment by sou-lab** [comment]
if `.box` at root

```scss
.wrap {
  @media (min-width: 480px) { 
    display: block;
    @at-root (without: media rule) {
    // or  @at-root (without: all) {
      .box { 
        display: inline-block;
      }
    } 
  }
}
```
