### ISSUE TITLE
3.3.3 regression with &:not(...)

### ISSUE THREAD

**Issue by asottile** [sass/libsass#1901]
Input:

```scss
a, b {
    &:not(c) {
        d: e;
    }
}
```

libsass 3.3.2
```css
a:not(c), b:not(c) {
  d: e; }
```

libsass 3.3.3
```css
a:not(c, c), b:not(c, c) {
  d: e; }
```

ruby-sass 3.4.20: https://gist.github.com/asottile/262b30c2d4e41b88dfd2
