### ISSUE TITLE
multiple comma-delimited selectors having nested &:nth-*(n) outputs multiple n inside parenthesis

### ISSUE THREAD

**Issue by tehOPEologist** [sass/libsass#1908]
looks like libsass 3.3.3 is introducing a weird error with &:nth-child/&:nth-of-type selectors inside of comma-delimited parents.  example below:

**test.scss:**
```scss
html,
body {
  &:nth-child(2) {
    background: #f00;
  }
}
```

**test.css should be:**
```css
html:nth-child(2),
body:nth-child(2) {
  background: #f00;
}
```

**libsass v3.3.3 with node-sass v3.5.0-beta.1 compiles to test.css:**
```css
html:nth-child(2, 2),
body:nth-child(2, 2) {
  background: #f00;
}
```

the additional numbers inside the parenthesis seems to be directly affected by how many parent selectors are comma delimited.

**eg: test.scss:**
```scss
html,
body,
h1 {
  &:nth-child(2) {
    background: #f00;
  }
}
```

**test.css:**
```css
html:nth-child(2, 2, 2),
body:nth-child(2, 2, 2),
h1:nth-child(2, 2, 2) {
  background: #f00;
}
```
