### ISSUE TITLE
Debug comments output absolute file paths (libsass) rather than relative (Sass gem)

### ISSUE THREAD

**Issue by johnbacon** [sass/libsass#191]
In contrast to the official Ruby gem, debug file paths are output as absolutes rather than relatives. e.g.:

libsass

``` css
/* line 35, c:/wnmp/html/gigsalad/static_components/sass/components/gigsalad/_gig-salad-icons.scss */

[class*="icon--"]:hover {
    color: #666666;
    color: rgba(0, 0, 0, 0.54);
}
```

Sass gem

``` css
/* line 35, ../../static_components/sass/components/gigsalad/_gig-salad-icons.scss */

[class*="icon--"]:hover {
    color: #666666;
    color: rgba(0, 0, 0, 0.54);
}
```

This is an issue with committing on team projects, as the absolute file path changes with every committer. Some of us operate in Linux, some in Windows, some in OSX, and even if the operation system is shared, the absolute file path is rarely shared, meaning each new generation of css creates countless changes to debug comments.

In both cases, the Sass is being called from Grunt, and we're not actually sure if that's what is calling/creating the comment.

Thanks!
