### ISSUE TITLE
&+& selector error

### ISSUE THREAD

**Issue by b1rdex** [sass/libsass#1913]
```sass
.accordion-item
  &+&
    margin-top: 7px
  &.in .accordion-item-header:before
    background-position-y: 8px
```

Ruby parses this good and produces
```css
.accordion-item + .accordion-item {
  margin-top: 7px;
}
.accordion-item.in .accordion-item-header:before {
  background-position-y: 8px;
}
```

Libsass 3.2.5 on playground http://sassmeister.com/ says `invalid property name`.
