### ISSUE TITLE
@extend outer selector from within @media should error via @content

### ISSUE THREAD

**Issue by kenyakodaira** [sass/libsass#1923]
Note: this sample should error but does not so currently:

```scss
%btnBase {
  display: none;
}

@mixin mobile {
  @media only screen and (min-width:300px) {
    @content;
  }
}

@include mobile {
  a {
    @extend %btnBase;
  }
}
```

Sorry!!!
I have poor English.

Look so described the problem under.

```
%btnBase {
  display: none;
}

// Scope error
@media only screen and (min-width:300px) {
  a {
    @extend %btnBase;
  }
}

@mixin mobile {
  @media only screen and (min-width:300px) {
    @content;
  }
}

// Why Success??
@include mobile {
  a {
    @extend %btnBase;
  }
}
```
