### ISSUE TITLE
Support maps in list context (index, nth, etc)

### ISSUE THREAD

**Issue by madlandproject** [sass/libsass#1930]
Example file, sasstest.scss : 

```scss
$test-map : (
        mykey    : 10px,
        otherKey : 20px,
        moarKey  : 30px
);


@mixin testMixin($key-name) {

  // get index in map
  $item-value : map-get($test-map, $key-name);
  $item-index : index($test-map, ($key-name $item-value) );

  @debug $item-index;

}

@include testMixin(otherKey);
```

Expected output (using ruby sass 3.4.21) :
sasstest.scss:14 DEBUG: 2

Output with libsass : 
sasstest.scss:14 DEBUG: null

**Comment by mgreter** [comment]
I do see the difference, but wonder if this is actually indended behavior. IMHO this is quite a "funky" feature so to speak (never seen any similar "index" function with "hash-maps") //CC @chriseppstein 

```scss
$test-map : (
  key : 20px,
);

foo {
  bar: index($test-map, ("key" 20px) );
  baz: index($test-map, ("key", 20px) );
  ibar: inspect(index($test-map, ("key" 20px) )); // 1
  ibaz: inspect(index($test-map, ("key", 20px) )); // null
}
```

Yields in ruby sass:
```
foo {
  bar: 1;
  ibar: 1;
  ibaz: null; }
```
