### ISSUE TITLE
Incorrect handling of empty variable argument list

### ISSUE THREAD

**Issue by antmorozov** [sass/libsass#1932]
It seems like Libsass ignores keyword arguments in function calls if they follow an empty variable argument.

For example, I have a function which accepts two arguments and have default values for them:

```sass
@function func($a: 1px, $b: 1) {
  @return $a * $b;
  }
```

And I call it like this:

```sass
.foo {
  $args: (1px);
  width: func($args..., $b: 2);
  }

.bar {
  $args: ();
  width: func($args..., $b: 2);
  }
```

It should return "2px" in both cases, and Ruby sass does it right:

```css
.foo {
  width: 2px; }

.bar {
  width: 2px; }
```

But Libsass returns "1px" in the second case:

```css
.foo {
  width: 2px; }

.bar {
  width: 1px; }
```

I use node-sass@3.4.2.
