### ISSUE TITLE
libsass chokes on Compass stylesheet's "prefix-usage(" call

### ISSUE THREAD

**Issue by ochafik** [sass/libsass#1936]
Not sure if that's Compass not abiding by Scss syntax, or some bug in libsass.

Repro: given `foo.scss`:
```scss
@import 'compass/css3/flexbox';
.foo {
  @include display-flex(inline-flex);
}
```

The following command:
```
gem install sass compass
sassc -I `gem environment gemdir`/gems/compass-core-1.0.3/stylesheets foo.scss
```

Yields this error:
```
Error: may only compare numbers
        on line 323 of ../../.rvm/gems/jruby-1.7.19/gems/compass-core-1.0.3/stylesheets/compass/_support.scss
>>   $usage: prefix-usage($prefix, $capability, $capability-options);
   ----------^
```
See [corresponding line in Compass' github source](https://github.com/Compass/compass/blob/stable/core/stylesheets/compass/_support.scss#L323).

(this is blocking a large migration from Ruby Sass to SassC, as migrating to more libsass-friendly mixin libraries like Bourbon is a larger investment)

Output of `sassc --version`:
```
sassc: 3.3.0
libsass: 3.3.3
sass2scss: 1.0.5
```

**Comment by ochafik** [comment]
Mmh, ok, that error message was a red herring, the root cause is the line below, which looks like #1451. Probably because `prefix-usage` is a Compass builtin :-(
```
  $usage: prefix-usage($prefix, $capability, $capability-options);
  @if $usage > $threshold {
```

**Comment by ochafik** [comment]
The right way to go might just be to use [autoprefixer](https://github.com/postcss/autoprefixer) and hard code some constant `prefix-usage` to trick the Compass stylesheets into not using prefixes at all.

Closing this issue.

**Comment by laomatt** [comment]
just to add what finally worked for me, i tried to look for the source code, but this function isn't shared on compasses website.  Its an old code base that hasn't been updated in a long time, so I finally just had to make the function myself:
```scss
@function prefix-usage($prefix, $capability, $capability-options: $default-capability-options) {
  $result: ();
  @each $prefix in browser-prefixes($supported-browsers) {
    $result: append($result, 3);
  }
  @return length($result);
}
```
