### ISSUE TITLE
Interpolated functions that return a list are called twice

### ISSUE THREAD

**Issue by danielguillan** [sass/libsass#1944]
This one is quite interesting: when interpolating a `function` that returns anything other than a `string` (e.g., a `list`) into a selector, the function **gets called twice**.

### Simplified test case
```scss
$count: 0;

@function foo() {
    $count: $count + 1 !global;
    $selector: ('.bar' 'baz');
    @return $selector;
}


#{foo()} {
    count: $count;
}
```

### Expected output
```css
.bar .baz {
  count: 1;
}
```
### Current output
```css
.bar .baz {
  count: 2;
}
```

Also, this behavior does not occur if the interpolation happens **after** a selector:

```scss
.baz #{foo()} { ... }
``` 

Works as expected in Ruby Sass.
