### ISSUE TITLE
selector interpolation quoted and out of order in 3.3.3

### ISSUE THREAD

**Issue by lunelson** [sass/libsass#1947]
In [this gist](https://gist.github.com/lunelson/db71097b2185f8827129), you can see expected corrected output; but currently with `node-sass 3.5.0-beta.1` / `libsass 3.3.3` I am getting selector interpolation like this for the same code (possible relations: #1633, #1925), which seems to be regression since `3.3.2`:

```css
"a".wrap-- {
  debug: 'hello';
}

"b".wrap-- {
  debug: 'hello';
}

"a-b".wrap-- {
  debug: 'hello';
}

"c".wrap-- {
  debug: 'hello';
}

"a-c".wrap-- {
  debug: 'hello';
}

"b-c".wrap-- {
  debug: 'hello';
}

"a-b-c".wrap-- {
  debug: 'hello';
}

"d".wrap-- {
  debug: 'hello';
}

"a-d".wrap-- {
  debug: 'hello';
}

"b-d".wrap-- {
  debug: 'hello';
}

"a-b-d".wrap-- {
  debug: 'hello';
}

"c-d".wrap-- {
  debug: 'hello';
}

"a-c-d".wrap-- {
  debug: 'hello';
}

"b-c-d".wrap-- {
  debug: 'hello';
}

"a-b-c-d".wrap-- {
  debug: 'hello';
}
```

**Comment by xzyfer** [comment]
This appears to be a combination of both #1901 and #1907. Will confirm.

**Comment by xzyfer** [comment]
I am unable to reproduce the out of order selectors on 3.3.3. However the broken quoting is reproducible.

**Comment by xzyfer** [comment]
The patch to #1907 doesn't appear to fix the quoting issue seen here. This is a different issue.

**Comment by xzyfer** [comment]
This is another instance of `#{}` no stripping quotes. Reduced test case

```sass
.a-#{quote('' + b)} {
  c: d;
}
```

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/735

**Comment by lunelson** [comment]
> I am unable to reproduce the out of order selectors on 3.3.3.

Yeah I got the out-of-order selectors with `node-sass` latest release (`v3.5.0-beta.1`), plugged in to my fork of `sintaxi/terraform` which plugs in to my fork of `sintaxi/harpjs`, and I also get the error also if I use [this build system](https://github.com/blitzrk/sublime_libsass) in sublime text, which [seems to be pointing at the latest version of sassc](https://github.com/blitzrk/sublime_sassc/releases/tag/3.3.4); however if I clone and run sassc as of right now, I don't get the error. I also don't get it when I switch `node-sass` back to `v3.4.2`.

**Comment by lunelson** [comment]
@xzyfer I think I've identified what's going on, there's a series of bugs at work: it's not a problem of `#{}` not stripping quotes as much as a problem of double-quotes resulting from the `quote()` function and causing havoc with `#{}`, particularly when combined with `@extend`

Re `quote()`:

```scss
.test {
  /* should quote */
  out: inspect(quote(b));
  /* should not double quote */
  out: inspect(quote('' + b));
  /* should fail, because input is a list (unrelated) */
  out: inspect(quote(a b c));
}
```
```css
.test {
  /* should quote */
  out: "b";
  /* should not double quote */
  out: '"b"';
  /* should fail, because input is a list (unrelated) */
  out: "a b c"; }
```

...and when trying to interpolate that:

```scss
/* this is ok */
.foo--#{quote(bar)} { c: d; }
/* this is not ok */
.foo--#{quote('' + bar)} { c: d; }
/* this is just weird */
.foo--#{quote('' + bar)} { @extend %baz; }
%baz { c: d; }
```
```css
/* this is ok */
.foo--bar {
  c: d; }

/* this is not ok */
.foo--"bar" {
  c: d; }

/* this is just weird */
"bar".foo-- {
  c: d; }
```

**Comment by mgreter** [comment]
Fix might be quite simple?

```diff
--- "a/functions-c6921c4-left.cpp"
+++ "b/functions.cpp"
@@ -902,6 +902,10 @@ namespace Sass {
     BUILT_IN(sass_quote)
     {
       AST_Node* arg = env["$string"];
+      if (String_Quoted* qstr = dynamic_cast<String_Quoted*>(arg)) {
+        qstr->quote_mark('*');
+        return qstr;
+      }
       std::string str(quote(arg->to_string(ctx.c_options), String_Constant::double_quote()));
       String_Quoted* result = SASS_MEMORY_NEW(ctx.mem, String_Quoted, pstate, str);
       result->is_delayed(true);
```

Seems to fix the double quote problems and selector interpolations looks better too?

```css
/* this is ok */
.foo--bar {
  c: d; }

/* this is not ok */
.foo--bar {
  c: d; }

/* this is just weird */
.foo--bar {
  c: d; }
```
