### ISSUE TITLE
Bug in extending pseudo elements with the universal selector

### ISSUE THREAD

**Issue by TxHawks** [sass/libsass#1965]
The following:
```scss
%foo {
  &,
  &:before,
  &:after {
    bar: baz;
  }
}

* {
  @extend %foo;
}
```

Produces:
```scss
*,
:before,    // Notice the missing `*`
:after {
  bar: baz;
}
```

Expected result:
```scss
*,
*:before,
*:after {
  bar: baz;
}
```

Versions tested: libsass 3.3.2 (gulp-sass 2.2.0) libsass 3.3.3 (node-sass 3.5.0)
