### ISSUE TITLE
Pseudo class with multiple parent selectors compilation error

### ISSUE THREAD

**Issue by ElManouche** [sass/libsass#1968]
I have an error with the following
```scss
.test {
  // this works
  .test__elem {
    &:not(.active) {
      opacity: 0.5;
    }
  }

  // this creates a bug in the 'not' pseudo class
  .test__item,
  .test__item2 {
    &:not(.active) {
      opacity: 0.5;
    }
  }
}
```

is compiled to:
```scss
.test .test__elem:not(.active) {
  opacity: 0.5;
}

.test .test__item:not(.active, .active),
.test .test__item2:not(.active, .active) {
  opacity: 0.5;
}
```

I use sassc 1.9.0 for rails which uses the last version of libsass.
I opened [a case in sassc-rails](https://github.com/sass/sassc-rails/issues/60#issuecomment-203311448) as well
