### ISSUE TITLE
%placeholders selectors aren't removed when using @supports

### ISSUE THREAD

**Issue by robsonsobral** [sass/libsass#1971]
Hi!

When there's a `@supports` inside or around a placeholder selector, it isn't removed.

Considering:

```sass
%foo1 {
  @supports (flex-wrap: wrap) {
    flex: auto;
  }
}

@supports (flex-wrap: wrap) {
  %foo2 {
    flex: auto;
  }
}

.bar {
  @extend %foo1;
  @extend %foo2;
}
```

LibSass 3.3.2 renders as:

```css
@supports (flex-wrap: wrap) {
  %foo1, .bar {
    flex: auto;
  }
}

@supports (flex-wrap: wrap) {
  %foo2, .bar {
    flex: auto;
  }
}
```

Which makes the entire rule being ignored by the browser.

While both Sass 3.3.14 and 3.4.21 render as expected:

```css
@supports (flex-wrap: wrap) {
  .bar {
    flex: auto;
  }
}

@supports (flex-wrap: wrap) {
  .bar {
    flex: auto;
  }
}
```

Thank you!
