### ISSUE TITLE
Comments with interpolation output nested selectors

### ISSUE THREAD

**Issue by Cleecanth** [sass/libsass#1996]
This is kind of hard to explain so I'll just put the code here and explain after.

```scss
$foo: "bar";

%class //#{$foo}
{
  &_baz {
    color: red;
  }
}
```
Ruby Sass outputs nothing (as expected).

Libsass outputs this:
```css
_baz {
  color: red;
}
```
[Sassmeister Link](http://sassmeister.com/gist/2f08021f9676ed93c89dc38f320faac0)

Removing the interpolation in the comment fixes the issue.

I found a block of code in an old project that uses this hacky technique to switch between a silent class plus a regular class or just a silent class (by changing the `//` to a `, .` via a mixin). 

It's a terrible technique and will definitely be changed, but its output is at least an interesting inconsistency between the two versions of Sass. 

Worth fixing? Not sure, but it may point to a deeper issue.
