### ISSUE TITLE
selector lists access with `nth` should not return a list

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#2020]
test:
```scss
form {
  $selector: nth(&, 1);
  sel: inspect($selector);
  $selector: nth($selector, 1);
  sel: inspect($selector);
} 
```

ruby sass:
```css
form {
  sel: form;
  sel: form; }
```

libsass:
```css
form {
  sel: (form,);
  sel: form; }
```

**Comment by mgreter** [comment]
IMO I already seen the root for this before and I still consider it inconsistent behavior by ruby sass:

```
list {
  $p: (1,);
  type: type-of($p);
  parents: inspect($p);
  $selector: nth($p, 1);
  sel: inspect($selector);
  type: type-of($selector);
  $selector: nth($selector, 1);
  sel: inspect($selector);
  type: type-of($selector);
}

selector {
  $p: &;
  type: type-of($p);
  parents: inspect($p);
  $selector: nth($p, 1);
  sel: inspect($selector);
  type: type-of($selector);
  $selector: nth($selector, 1);
  sel: inspect($selector);
  type: type-of($selector);
}
```

libsass vs ruby sass
```
list {                   list {                 
  type: list;              type: list;          
  parents: (1,);           parents: (1,);       
  sel: 1;                  sel: 1;              
  type: number;            type: number;        
  sel: 1;                  sel: 1;              
  type: number; }          type: number; }      
                                          
selector {               selector {             
  type: list;              type: list;             
  parents: (selector,);    parents: (selector,);
  sel: (selector,);        sel: selector;       
  type: list;              type: list;          
  sel: selector;           sel: selector;       
  type: string; }          type: string; }      
```

It looks like a special rule that complex selectors (converted to strings btw) are of type list, but are not printed as `(%s,)` as with other lists. I think I should be able to patch this, but we need a status flag on lists to indicate that special behavior. //CC @chriseppstein

**Comment by xzyfer** [comment]
@mgreter this not an inconsistency in Sass, it's an important part of Sass semantics around selector lists. 

```
selector {
  $p: &;
}
```

In this `$p` is a list of selector lists, which are themselves lists. 

```sass
selector {
  $p: &;
  
  a: $p;
  b: length($p);
  c: nth($p, 1);
  d: length(nth($p, 1));
  e: nth(nth($p, 1), 1);
}

selector1, selector2 {
  $p: &;
  
  a: $p;
  b: length($p);
  c: nth($p, 1);
  d: length(nth($p, 1));
  e: nth(nth($p, 1), 1);
}

selector1 subselector1, selector2 subselector2 {
  $p: &;
  
  a: $p;
  b: length($p);
  c: nth($p, 1);
  d: length(nth($p, 1));
  e: nth(nth($p, 1), 1);
}
```
Should produce
```css
selector {
  a: selector;
  b: 1;
  c: selector;
  d: 1;
  e: selector;
}

selector1, selector2 {
  a: selector1, selector2;
  b: 2;
  c: selector1;
  d: 1;
  e: selector1;
}

selector1 subselector1, selector2 subselector2 {
  a: selector1 subselector1, selector2 subselector2;
  b: 2;
  c: selector1 subselector1;
  d: 2;
  e: selector1;
}
```

****
Give this information the following makes sense.
```
selector {
  a: nth($p, 1);
}
```
```
selector {
  a: selector;
}
```

`$p` is a list of lists `((selector,),)`.
`nth($p, 1)` is the first list `(selector,)`
which when print to css is `selector`

***

I'm happy to work you answering any questions about Sass semantics if you're unsure why something is happening. It's better to take the time to fully understand an issue so an appropriate fix can be implemented. Add small hacks just results is more edge cases that aren't really edge cases.
