### ISSUE TITLE
Extending inner of :not can lead to invalid css

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#2031]
Continued from https://github.com/sass/libsass/issues/1960 (related to https://github.com/sass/node-sass/issues/1464 and https://github.com/sass/libsass/issues/2017).

Sample:
```scss
:not(.asd, .qwe) {
  content: test;
}
:not(.foo) {
  content: test;
}
.bar, .baz {
  @extend .foo;
}
```

libsass 3.5.5+:
```css
:not(.asd, .qwe) { content: test; }
:not(.foo):not(.bar):not(.baz) { content: test; }
```

libsass 3.3.2 (sassmeister):
```css
:not(.asd, .qwe) { content: test; }
:not(.foo) { content: test; }
```

ruby sass:
```css
:not(.asd, .qwe) { content: test; }
:not(.foo):not(.bar):not(.baz) { content: test; }
```

Before 3.3.5 we were silently dropping the additional selectors inside `:not`.
Test cases should also test for other pseudo selectors and include linked issues.

**Comment by mgreter** [comment]
The following sample gives some insight what's happening behind the scenes:
```scss
test {
  content: selector-extend(":not(.foo)", ".foo", ".bar");
}
```

yields
```css
test {
  content: :not(&.foo, &.bar); }
```
