### ISSUE TITLE
Regression: Call function does not destructure variables

### ISSUE THREAD

**Issue by TxHawks** [sass/libsass#2034]
When doing:
```scss
$args: mix, #fff, #000, 20%;

.foo {
  color: call($args...);
}
```

Ruby Sass will output:
```css
.foo {
  color: #333333; 
}
```

But Libsass will output:
```css
.foo {
  color: mix, #fff, #000, 20%...(); 
}
```

This is happening with: `node-sass 3.5.3` wrapping `libsass 3.3.5`.

**Comment by mgreter** [comment]
This is because an early check was added in function call evaluation, since it was needed to avoid the evaluation of the arguments for `calc` functions (`call(calc, ...)`). The normal function evaluation has a very messed up logic to deduct the arguments for the ast node (`Argument_List`, restargs, etc). It probably makes sense to refactor the whole list handling including https://github.com/sass/libsass/issues/1930#issuecomment-213189134, instead of reimplementig the whole argument deduction logic for call invokations.

**Comment by xzyfer** [comment]
I refactored the argument logic to match Ruby Sass in 3.3.3. It should be correct. The issue is more likely which how we're evaling `call`.

**Comment by mgreter** [comment]
Bug happens here: https://github.com/sass/libsass/blob/master/src/eval.cpp#L842

**Comment by mgreter** [comment]
This is a more complete spec test:
```scss
$args: mix, #fff, #000, 20%;
$params: #fff, #000, 20%;

.foo {
  test: call($args...);
  test: mix(#fff, #000, 20%);
  test: call(mix, #fff, #000, 20%);
  test: call(mix, $params...);
}
```

Currently yields:
```
.foo {
  test: mix, #fff, #000, 20%...();
  test: #333333;
  test: #333333;
  test: #333333; }
```

Expected is:
```css
.foo {
  test: #333333;
  test: #333333;
  test: #333333;
  test: #333333; }
```

So we can probably get away here with one additional check. @xzyfer I also do not like to add such patches, but I see it as a legit way to add the needed behavior until someone (mostly me) gets around to do the actual refactoring. And it has proven to help to have these patches in place, specially if they are documented accordingly. The only small thing that worries me a little is that this pattern may break lazy evaluation as fixed in https://github.com/sass/libsass/pull/1986. To put it short we tend to get away with those patches quite far (and I do keep cleaning up after them).
