### ISSUE TITLE
Passing arglists between functions is now broken in 3.3.5

### ISSUE THREAD

**Issue by stowball** [sass/libsass#2049]
This may be related to https://github.com/sass/libsass/issues/2034, but in LibSass v3.3.2, I could create helper functions to pass arglists around - now in v3.3.5 I can't, as my final function returns null.

input.scss
```scss
@function get($map, $keys...) {
    @each $key in $keys {
        $map: map-get($map, $key);
    }

    @return $map;
}

@function color($keys...) {
    @return get($colors, $keys);
}

$colors: (
    blue: (
        robins-egg: #00cdcb
    ),
    green: (
        fruit-salad: #51a351
    )
);

a {
    background: get($colors, blue, robins-egg);
    color: color(green, fruit-salad);
}
```

libsass 3.3.5
```css
a {
  background: #00cdcb; }
```

libsass 3.3.2 and ruby sass 3.4.21
```css
a {
  background: #00cdcb;
  color: #51a351; }
```

Notice that using `color()` now fails.

A somewhat annoying workaround is for `$keys` to no longer be an arglist, and to pass a space-separated list between the functions, like so:

```scss
@function get($map, $keys) {
    @each $key in $keys {
        $map: map-get($map, $key);
    }

    @return $map;
}

@function color($keys) {
    @return get($colors, $keys);
}

$colors: (
    blue: (
        robins-egg: #00cdcb
    ),
    green: (
        fruit-salad: #51a351
    )
);

a {
    background: get($colors, blue robins-egg);
    color: color(green fruit-salad);
}
```

version info:
```cmd
$ node-sass --version
node-sass       3.5.3   (Wrapper)       [JavaScript]
libsass         3.3.5   (Sass Compiler) [C/C++]
```

**Comment by mgreter** [comment]
When I enter your example into sassmeister, I get
```css
a {
  background: #00cdcb; }
```

But you seem to say you get
```css
a {
  background: #00cdcb;
  color: #51a351; }
```

Can you please re-check!

**Comment by xzyfer** [comment]
I can confirm the code supplied does not work as expected in Ruby Sass. It may have previously erroneously worked in LibSass due a to a bug that has since been fixed.

Update your `color` function as shown below for get the behaviour you expect.

```sass
@function color($keys...) {
    @return get($colors, $keys...);
}
```

**Comment by mgreter** [comment]
I [opened an issue] [1] with sassmeister I think could have lead OP to assume output for sass 3.4.21.

[1]: https://github.com/jedfoster/SassMeister/issues/172

**Comment by stowball** [comment]
Sorry, there was a typo in the `color()` function. It now matches my example output in Ruby Sass

**Comment by xzyfer** [comment]
Given the updated `color()` I get the expected output in LibSass 3.3.5

```css
a {
  background: #00cdcb;
  color: #51a351; }
```
