### ISSUE TITLE
Using variables containing "\" in the value breaks soucemap

### ISSUE THREAD

**Issue by TonyBogdanov** [sass/libsass#2050]
### Using variables containing "\" in the value breaks sourcemap

input.scss
```scss
$content: "\f000";
works { content: "\f000"; }
doesnt { content: $content; }
```

[libsass 3.3.6] [1]
```css
works {
  content: "\f000"; }

doesnt {
  content: ""; }
```

version info:
```cmd
$ sassc --version
sassc: 3.3.6
libsass: 3.3.6-10-g4d0b
sass2scss: 1.0.6
```

[1]: http://libsass.ocbnet.ch/srcmap/#JGNvbnRlbnQ6ICJcZjAwMCI7Cgp3b3JrcyB7IGNvbnRlbnQ6ICJcZjAwMCI7IH0KZG9lc250IHsgY29udGVudDogJGNvbnRlbnQ7IH0=
