### ISSUE TITLE
Bus error: 10 in a mixed global-local extend

### ISSUE THREAD

**Issue by ckknight** [sass/libsass#2051]
`node-sass` version: ~~3.8.3~~ 3.6.0, using included `libsass`
On Mac OS X 10.11
Using either Node.js 4.2 or 5.6
Configured to use local CSS modules by default.
----

Input code:
```scss
:global(.thing) {
    color: red;
}

:global(.thing[disabled]) {
    @extend .thing;
    background: blue;
}
```

Result: `Bus error: 10`

----
Both the following work without issue:
```scss
:global(.thing) {
    color: red;
}

:global(.thing[disabled]) {
    @extend :global(.thing);
    background: blue;
}
```

```scss
.thing {
    color: red;
}

.thing[disabled] {
    @extend .thing;
    background: blue;
}
```
****
Spec added https://github.com/sass/sass-spec/pull/849

**Comment by xzyfer** [comment]
I'm confused, there is no node-sass 3.8.3. Please read their documentation
to determine your correct version.

**Comment by ckknight** [comment]
Sorry about that. It's `3.6.0`. I read the wrong number.

**Comment by xzyfer** [comment]
Thanks for the report @ckknight. You're correct that the first example causes a segfault.

It's also worth noting that neither of your examples are valid Sass. When we patch this segfault both your examples will return the expect error.

```
Error: Invalid CSS after ":global(": expected pseudo_expr, was ".thing)"
        on line 13 of test.scss
  Use --trace for backtrace.
```

**Comment by xzyfer** [comment]
For more information on why this will stop working please read medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9

If you think this should be supported in Sass please open an issue with the [official Sass project](https://github.com/sass/sass/issues).

**Comment by mgreter** [comment]
This exhibits a tricky one that seems somewhat related to #1392:
It can also be triggered by this valid code:

```scss
:not(.thing) {
    color: red;
}
:not(.thing[disabled]) {
    @extend .thing;
    background: blue;
}
```

ruby sass:
```
:not(.thing) {
  color: red; }
:not(.thing[disabled]):not([disabled]:not(.thing[disabled])) {
  background: blue; }
```

The problem is that libsass tries to extend `.thing` of the wrapped selector itself (and finds another `@extend` inside), so it goes in an endless loop until the call stack is exhausted.

A related test case would therefore be:
```scss
.thing {
    color: red;
}
.thing[disabled] {
    @extend .thing;
    background: blue;
}
```

It exhibits a similar problem as reported in #1392:

ruby sass:
```css
.thing, .thing[disabled] {
  color: red; }
.thing[disabled] {
  background: blue; }
```

libsass:
```css
.thing, .thing[disabled] {
  color: red; }
[disabled].thing {
  background: blue; }
```

**Comment by mgreter** [comment]
The failing test can also be written as:
```scss
:not(.thing) {
    color: red;
}
:not(.bar) {
    @extend .thing;
    background: blue;
}
```

[Produces] [1]:
```css
:not(.thing):not(:not(.bar)) {
  color: red; }
:not(.bar) {
  background: blue; }
```

But should be:
```css
:not(.thing) {
  color: red; }
:not(.bar) {
  background: blue; }
```

I wonder if ruby sass actually just removes the invalidly nested `:not` selector.
Otherwise from what I know about extend, the result in theory doesn't look incorrect!?

[1]: http://libsass.ocbnet.ch/srcmap/#Om5vdCgudGhpbmcpIHsKICAgIGNvbG9yOiByZWQ7Cn0KOm5vdCguYmFyKSB7CiAgICBAZXh0ZW5kIC50aGluZzsKICAgIGJhY2tncm91bmQ6IGJsdWU7Cn0=
