### ISSUE TITLE
Extending self can lead to non-semanticly different output

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#2053]
``` scss
.foo[disabled] {
    @extend .foo;
    background: blue;
}
.bar[disabled] {
  foo {
    @extend .bar;
    background: blue;
  }
}
foo {
  .baz[disabled] {
    @extend .baz;
    background: blue;
  }
}
```

ruby sass:

``` css
.foo[disabled] { background: blue; }
.bar[disabled] foo { background: blue; }
foo [disabled].baz { background: blue; }
```

libsass with #2052 

``` css
[disabled].foo { background: blue; }
.bar[disabled] foo { background: blue; }
foo [disabled].baz { background: blue; }
```

//CC @chriseppstein any idea why ruby sass differs in `.bar[disabled]` vs `[disabled].baz`?
##

**Comment by chriseppstein** [comment]
@mgreter I'm no expert in the extend code. But it seems like this is the reason:
https://github.com/sass/sass/blob/stable/lib/sass/selector/simple_sequence.rb#L193-L195

This is a non-semantic difference in a corner case where the `@extend` is pointless (it's extending itself). I wouldn't even bother to write a test for this. Just whistle and walk away.

**Comment by xzyfer** [comment]
Rescoping this to 3.4.1 since it shouldn't block 3.4.0.

**Comment by mgreter** [comment]
Input:
```scss
.bar.baz {
  @extend .bar;
  background: blue;
}
```

Expected:
```css
.bar.baz {
  background: blue;
}
```

Current:
```css
.baz.bar {
  background: blue;
}
```

Reason:
```ruby
if modified_original || !replace || groups.empty?
  # First Law of Extend: the result of extending a selector should
  # (almost) always contain the base selector.
  # See https://github.com/nex3/sass/issues/324.
  original = Sequence.new([SimpleSequence.new(members, @subject, source_range)])
  original.add_sources! sources
  groups.unshift original
end
```
