### ISSUE TITLE
Extending inner of :not can lead to invalid css

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#2054]
Extracted from https://github.com/sass/libsass/issues/2051

```scss
:not(.thing) {
    color: red;
}
:not(.bar) {
    @extend .thing;
    background: blue;
}
```

[Produces] [1]:
```css
:not(.thing):not(:not(.bar)) {
  color: red; }
:not(.bar) {
  background: blue; }
```

But should be:
```css
:not(.thing) {
  color: red; }
:not(.bar) {
  background: blue; }
```

I wonder if ruby sass actually just removes the invalidly nested `:not` selector.
Otherwise from what I know about extend, the result in theory doesn't look incorrect!?

[1]: http://libsass.ocbnet.ch/srcmap/#Om5vdCgudGhpbmcpIHsKICAgIGNvbG9yOiByZWQ7Cn0KOm5vdCguYmFyKSB7CiAgICBAZXh0ZW5kIC50aGluZzsKICAgIGJhY2tncm91bmQ6IGJsdWU7Cn0=
