### ISSUE TITLE
Extending inner of :has or :not can lead to invalid css

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#2055]
Closely related to https://github.com/sass/libsass/issues/2054

With the "support" of extending wrapped selectors, we opened a lot of previousely "unreachable" issues. I was pretty aware that these would surface at some point since I know from the ruby code that there are a few special rules regarding wrapped selectors. Probably the most prominent (not sure if there are even others) are `:not` and `:has`.

https://github.com/sass/libsass/pull/2052 should fix the most urgent issues, but will not fix this one here:

``` scss
:has(.thing) {
    color: red;
}
:has(.thing[disabled]) {
    @extend .thing;
    background: blue;
}
```

Should produce

``` css
:has(.thing, :has(.thing[disabled])) {
  color: red; }
:has(.thing[disabled], [disabled]:has(.thing[disabled])) {
  background: blue; }
```

Note that this is very different from what `:not` would produce.

Spec https://github.com/sass/sass-spec/pull/915
##

**Comment by mgreter** [comment]
@chriseppstein @xzyfer I guess there are a few todo specs for this already in sass-spec, but probably not for very complex cases. To implement this properly (which will not be easy) we pretty sure need a more complete test set, containing tests as the following:

```scss
:not(.thing) {
    color: red;
}
:not(.thing[disabled]) {
    @extend .thing;
    background: blue;
}
:has(:not(.thing[disabled])) {
    @extend .thing;
    background: blue;
}
```

At the moment it is very easy to trip off libsass with anything beside the most basic cases with wrapped selectors. This may even warrant a rewrite of extend, as it currently does not fit the rest of the libsass code base (implementation is a [one to one] [1] conversion from ruby sass code)

[1]: https://github.com/sass/libsass/blob/master/src/extend.cpp#L1539-L1666
