### ISSUE TITLE
Generic wrapped selector should only accept pseudo expressions

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#2056]
Continued from https://github.com/sass/libsass/issues/2051

``` scss
:foobar(.baz) {
    color: red;
}
```

libsass and ruby sass 3.3.14

``` css
:foobar(.baz) {
  color: red; }
```

ruby sass 3.4.21

``` css
Invalid CSS after ":foobar(": expected pseudo_expr, was ".baz)"
```

Expected pseudo expressions seem to be at least `identifier` and `2n+1`.
This is probably different for specific wrapped selector as `:not` and `:has`.
Fixing this will affect users that rely on the old ruby sass 3.3 behavior :exclamation: 

Spec added https://github.com/sass/sass-spec/pull/914
##
