### ISSUE TITLE
Traditional CSS import is too aggressive

### ISSUE THREAD

**Issue by kennethormandy** [sass/libsass#208]
I doubt this is very common at all, but if you try and import an SCSS file with `.css` somewhere in its path (not the file extension), the traditional `@import url(' … ');` will still be used instead of Sass’ `@import`. For example, with:

``` scss
@import "components/necolas-normalize.css/normalize";
```
#### Expected Output

``` css
article ,aside ,details ,figcaption ,figure ,footer ,header ,hgroup ,main ,nav ,section ,summary {display:block;}audio …
```
#### Actual Output

``` css
@import url("components/necolas-normalize.css/normalize");
```

If I rename the folder without `.css` in the name, it works, or if I explicitly reference `normalize` as `normalize.scss`, it also works.
