### ISSUE TITLE
libsass throws 'failed to @extend' error when ruby sass doesn't

### ISSUE THREAD

**Issue by dafyddPrys** [sass/libsass#2083]
version info

```
gulp-sass version : 2.3.1
node-sass version : 3.7.0
libsass version : 3.3.6
node version : v5.7.0
npm version : 3.6.0
ruby sass version : 3.4.22
```

When I run `gulp build-css` I get the following error:
```
Error in plugin 'gulp-sass'
Message:
    assets/scss/core/_button.scss
Error: ".button--dropdown" failed to @extend ".icon--font".
       The selector ".icon--font" was not found.
       Use "@extend .icon--font !optional" if the extend should be able to fail.
        on line 338 of assets/scss/core/_button.scss
>>   @extend .icon--font;
   --^
```

However, if I compile this with native (ruby) sass, I don't get any errors:

`sass assets/scss/main.scss:assets/css/test.css`

The file containing the .icon--font is @imported into the main.scss file before the partial containing the .button--dropdown class.
main.scss
```scss
@import "core/icon";
@import "core/button";
```

_icon.scss
```scss
.icon--font {
  &:before {
    font-family: 'icons';
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;

    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
}
```
_button.scss
```scss
.button--dropdown {
  @extend .icon--font;
  position: relative;
  z-index: 998;
  @include rem(min-width, 100);

  &:before {
    float: right;
    @include rem(margin, 4 -7 0 9);
  }
}
```

#### Results:

[libsass 3.5.5] [1]
```css
// nothing
```

ruby sass 3.4.21
```css
.icon--font:before,  .button--dropdown:before {
  font-family: 'icons';
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale; }
```
