### ISSUE TITLE
Bug or feature? 3n + 4 => 7n

### ISSUE THREAD

**Issue by fatso83** [sass/libsass#2102]
### Unitless number promoted to having unit in arithmetic expr

After trying out `nth` in SassMeister I see that [all Sass engines produce the same weird output](http://www.sassmeister.com/gist/8b352671c54cde4285b4d79a0510dc4b) for the `nth()` function. For some reason Sass decides to promote the unitless `4` to `4n` so that it can add it to `3n`. I cannot find this behavior [documented on the Sass site](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#number_operations), which just has this to say on adding incompatible units

>  just like in real life, you cannot work on numbers with incompatible units (such as adding a number with px and em)

I would normally think that `3n` and `4` would be incompatible, but this does not align with Sass' views, unfortunately. Is this a bug or a feature?

input.scss
```scss
$list1 : (1, 2, 3, 3n + 4, 5);

// string concatenation hack to avoid arithmetic processing
$list2 : (1, 2, 3, #{3n}+#{4}, 5);

.foo {
  content: nth($list1, 4 );
  content: nth($list2, 4 );
}
```

[libsass 3.3.6-34-ge330] [1]
```css
.foo {
  content: 7n;
  content: 3n+4; }
```

sassc: 3.3.0
```css
.foo {
  content: 7n;
  content: 3n+4; }
```

ruby sass 3.4.22
```css
Error: Invalid CSS after "..., 3, 3n + 4, 5)": expected expression (e.g. 1px, bold), was ";"
        on line 1 of test
```

version info:
```cmd
$ sassc --version
sassc: 3.3.0
libsass: 3.3.4
sass2scss: 1.0.5
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
