### ISSUE TITLE
Support embedding other selectors

### ISSUE THREAD

**Issue by gligoran** [sass/libsass#2104]
It would be very handy to have an alternative to `@extend`, that imports the ruleset from another selector. LESS does this this way:

```less
.wrap {
  text-wrap: wrap;
  white-space: -moz-pre-wrap;
  white-space: pre-wrap;
  word-wrap: break-word;
}

pre { .wrap }
```

Output:
```css
.wrap {
  text-wrap: wrap;
  white-space: -moz-pre-wrap;
  white-space: pre-wrap;
  word-wrap: break-word;
}
pre {
  text-wrap: wrap;
  white-space: -moz-pre-wrap;
  white-space: pre-wrap;
  word-wrap: break-word;
}
```

P.S. I hope this is not a duplicate, but I didn't find a name for this functionality, so it was rather had to search for it.
