### ISSUE TITLE
API to parse SCSS portions?

### ISSUE THREAD

**Issue by dryoma** [sass/libsass#2110]
### API to parse SCSS portions?

Does Libsass expose any funcitons to parse some custom input strings and return several info on their contents?

Right now I need to parse some SCSS input and tell whether operators indise it (`+`, `-`, `/`) are part of a string, a sign or a CSS slash, e.g:

```scss
a {
  font: 10px/10px; // A CSS slash, compiles to `font: 10px/10px;`
  font: (10px/10px); // A math operation, compiles to `font: 1;`
  font: 10px +10px; // A list, compiles to `font: 10px +10px;`
  font: 10px+ 10px; // A math operation, compiles to `font: 20px;`
}
```

So some interface like this would help a lot:
```
libsass.parse("10px+ 10px")
// output:
// { nodes: [ { type: "value-with-unit", value: "10px" }, { type: "math-operator", value: "+"}, { type: "space", value: " " }, { type: "value-with-unit", value: "10px" } ]
```

Does Libsass have anything like this? 

This is needed for [a linter project](https://github.com/kristerkari/stylelint-scss). Of cource it all can be done from scratch, but I hoped to be able to cut some corners here if something similar is already implemented, and maybe use it via `node-sass` :)
