### ISSUE TITLE
change-color with $hue different between libsass and sass

### ISSUE THREAD

**Issue by HMUDesign** [sass/libsass#2112]
input.scss
```scss
$color: #1caf9a;

body {
  background: change-color($color, $hue: 120);
}
```

[libsass 3.3.6] [1]
```css
body {
  background: #af1d1c;
}
```

ruby sass 3.4.21
```css
body {
  background: #1caf1c;
}
```

version info:
```cmd
$ node-sass --version
node-sass       3.8.0   (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
