### ISSUE TITLE
if() function does not correctly evaluate the parent selector in the condition

### ISSUE THREAD

**Issue by danielguillan** [sass/libsass#2116]
input.scss
```scss
@function foo() {
  @return if(& != null, green, red);
}

test {
  color: foo();
}
```

libsass 3.5.5
```css
test {
  color: red; }
```

ruby sass 3.4.21
```css
test {
  color: green; }
```
