### ISSUE TITLE
Parse error when a url is protocoll-less

### ISSUE THREAD

**Issue by hhofstaetter** [sass/libsass#2123]
Parsing of the input does not work if there is no space between `:` and `url(` when the url is protocol (`//foo.com`) and not enclosed in quotes. 

``` css
foo {
  bar:url(//foo.bar/favicon.ico);}
```

Ruby Sass

``` css
foo {
  bar: url(//foo.bar/favicon.ico); }
```

LibSass

```
Error: Invalid CSS after "...r/favicon.ico)}": expected ")", was ""
        on line 3 of test.scss
>>   bar:url(//foo.bar/favicon.ico)}
```

Spec added https://github.com/sass/sass-spec/pull/879
##
