### ISSUE TITLE
Conditionnal parent selector

### ISSUE THREAD

**Issue by tzi** [sass/libsass#2124]
I use a conditionnal parent selector in some mixin, [a trick](https://github.com/sass/sass/issues/1873#issuecomment-152293725) shared by @chriseppstein.

I know it's a bad pattern, but it prevents from having the following error: "Base-level rules cannot contain the parent-selector-referencing character '&'". 
This technic doesn't seem to work with libsass 3.3.6, see [a demon on SassMeister](http://www.sassmeister.com/gist/b905f8662229fffc14ee52b27767c318).

```scss
@mixin with-js() {
  .js:root #{if(&, '&', '')} {
    @content;
  }
}

@include with-js() {
  .bou {
    content: 'bar';
  }
}

.bou {
  @include with-js() {
    .bar {
      content: 'baz';
    }
  }
}
```

libsass 3.3.6
```css
.js:root .bou {
  content: 'bar';
}

.bou .js:root .bar {
  content: 'baz';
}
```

ruby sass 3.4.21
```css
.js:root .bou {
  content: 'bar';
}

.js:root .bou .bar {
  content: 'baz';
}
```
