### ISSUE TITLE
`@extend`ing `selector` & `:not(selector)` won't compile

### ISSUE THREAD

**Issue by jdsteinbach** [sass/libsass#2130]
### `@extend`ing `selector` & `:not(selector)` won't compile

[View in Sassmeister](http://www.sassmeister.com/gist/c03c05d6966c58ce84c1e7910b321322)

Yes, I realize the code below isn't logical. :) I worked around it & my code compiles fine now. 

But in Ruby Sass, it compiles without error as I expected. In libsass (running in `gulp-sass`), I got a `bus error`. Sassmeister also hangs when I attempt to use its libsass (3.5.6) compiler.

input.scss
```scss
.section-title {
  text-transform: uppercase;
}

.section {
  h2:not(.section-title) {
    @extend .section-title;
  }
}
```

[libsass 3.5.6] [1]
```css
bus error / no completion
```

ruby sass 3.4.21
```css
.section-title, .section h2:not(.section-title) {
  color: #444;
}
```

version info:
```cmd
gulp-sass@2.3.2
node-sass@3.8.0
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
