### ISSUE TITLE
str-slice not working similar to ruby-sass

### ISSUE THREAD

**Issue by danez** [sass/libsass#2132]
### str-slice not working similar to ruby-sass

Additional spec tests: https://github.com/sass/sass-spec/pull/886

input.scss
```scss
test {
  content: str-slice('A', 1, -1)
}
```

libsass 3.3.6
```css
test {
  content: ''; }
```

ruby sass 3.4.21, 3.3.14, 4.0.0.alpha.1
```css
test {
  content: 'A'; }
```

version info: tested on http://www.sassmeister.com/
