### ISSUE TITLE
Better CSS variables support

### ISSUE THREAD

**Issue by mzdr** [sass/libsass#2138]
Hey there! 

I was wondering if you guys are planning to improve the support of native CSS variables for example in combination with the Sass [color functions](http://sass-lang.com/documentation/Sass/Script/Functions.html#hsl_functions).

Check out this example:

input.scss
```scss
:root {
    --red: #900;
    --light-red: lighten(var(--red), 20%);
}
```

```cmd
Error: $color: "var(--red)" is not a color for `lighten'
        on line 3 of input.scss
```

Is this something you consider implementing or do you want to keep this strictly apart? Meaning you always have to use Sass variables.
