### ISSUE TITLE
Invalid :not selector generated with @extend

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2139]
Originally reported by @dreyks in https://github.com/sass/sassc/issues/180. Possibly a duplicate of #2055.

``` scss
 .base-class {
   color: #FFF;
 }

 .parent-class {
   .child-class {
     @extend .base-class;
     border: '1px';
   }
 }

 *:not(.base-class) {
   display: none;
 }
```

LibSass 3.3.6 (c6685d7)

``` css
.base-class, .parent-class .child-class {
  color: #FFF; }

.parent-class .child-class {
  border: '1px'; }

*:not(.base-class):not(.parent-class .child-class) {
  display: none; }
```

Sass 3.4.21

``` css
.base-class, .parent-class .child-class {
  color: #FFF; }

.parent-class .child-class {
  border: '1px'; }

*:not(.base-class) {
  display: none; }
```

``` cmd
sassc: 3.3.3-3-ge054
libsass: 3.3.6-90-gc6685
sass2scss: 1.0.6
```

Spec added https://github.com/sass/sass-spec/pull/888
