### ISSUE TITLE
Custom properties with colour names shouldn't be substituted for hex values

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2140]
Originally reported by @alisamar in https://github.com/sass/node-sass/issues/1624

```sass
:root {
  --teal: #444;
}

a { content: var(--teal) }
b { content: (- red) }
c { content: (+- blue) }
d { content: (-green) }
e { content: (+ yellow) }
```

Ruby Sass 3.4.21
```css
:root {
  --teal: #444; }

a {
  content: var(--teal); }

b {
  content: -red; }

c {
  content: +-blue; }

d {
  content: -green; }

e {
  content: +yellow; }
```

LibSass 3.3.7
```css
:root {
  --teal: #444; }

a {
  content: var(--#008080); }

b {
  content: -#ff0000; }

c {
  content: +-#0000ff; }

d {
  content: -#008000; }

e {
  content: +#ffff00; }
```

Spec added https://github.com/sass/sass-spec/pull/889
