### ISSUE TITLE
/ interpreted as division instead of separator

### ISSUE THREAD

**Issue by chriseppstein** [sass/libsass#2149]
### Title: bare `/` should not be interpreted as division with bare literals

Originally filed:
https://github.com/sass/sass/issues/2118

For more info see:
https://github.com/sass/sass/issues/667#issuecomment-14086477

input.scss
```scss
.foo {
  background: url('background.png') -10px -10px/110% no-repeat
}
```

[libsass 3.5.5] [1]
```txt
// error
{
  "formatted": "Error: -0.09091px/% isn't a valid CSS value.\n        on line 2 of foo.scss\n>>   background: url('background.png') -10px -10px/110% no-repeat\n   ------------------------------------------^\n",
  "message": "-0.09091px/% isn't a valid CSS value.",
  "column": 43,
  "line": 2,
  "file": "/Users/ceppstei/Projects/broccoli-multi-filter/foo.scss",
  "status": 1
}
```

ruby sass 3.4.22
```css
.foo {
  background: url("background.png") -10px -10px/110% no-repeat; }
```

version info:
```cmd
$ node-sass --version
node-sass      	3.8.0  	(Wrapper)      	[JavaScript]
libsass        	3.3.6  	(Sass Compiler)	[C/C++]
```

Spec added https://github.com/sass/sass-spec/pull/909

**Comment by gakimball** [comment]
The compiler seems to only try division if one or both of the operands is negative.

This will compile as-is:

```scss
.selector {
  background: #fff url('') 100px 20px / 100%;
}
```

This will produce an error:

```scss
.selector {
  background: #fff url('') 100px -20px / 100%;
}
```

For anyone who needs a temporary workaround, you can interpolate the negative value to bypass the error.

```scss
.selector {
  background: #fff url('') 100px #{-20px} / 100%;
}
```
