### ISSUE TITLE
Extending a placeholder from a media query outputs nothing

### ISSUE THREAD

**Issue by dustindowell22** [sass/libsass#2150]
input.scss
```scss
@media (min-width: 100px) {
  .parent > %child {
    color: blue;
  }
}

.foo {
  @extend %child;
}
```

[libsass 3.5.5] 
```css
```

ruby sass 3.4.21
```css
@media (min-width: 100px) {
  .parent > .foo {
    color: blue;
  }
}
```
Spec added sass/sass-spec#894
