### ISSUE TITLE
Segfault parsing multiple operations in calc

### ISSUE THREAD

**Issue by smoogly** [sass/libsass#2151]
input.scss
```scss
div {
        $v: 1px;
        min-height: calc( #{$v} + #{$v} + #{$v} + #{$v} + #{$v} );
}
```

libsass 3.3.6
`segmentation fault`

ruby sass 3.4.21
```css
div {
  min-height: calc( 1px + 1px + 1px + 1px + 1px );
}
```

version info:
```cmd
node-sass	3.7.0	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
```

Notice following compiles properly:
```scss
div {
        $v: 1px;
        min-height: calc( #{$v} + #{$v} + #{$v} );
}
```
