### ISSUE TITLE
Empty nested media query causes remaining output in containing media query to not render

### ISSUE THREAD

**Issue by stepmr** [sass/libsass#2154]
### Title: Empty nested media query causes remaining output in containing media query to not render

input.scss
```scss
@media (min-width: 1px) {
  .first {
    font-weight: 100;

    @media (min-width: 2px) {}
  }
  .second {
    font-weight: 200;
  }
}
```

libsass 3.3.6
```css
@media (min-width: 1px) {
  .first {
    font-weight: 100;
  }
}
```

ruby sass 3.4.21
```css
@media (min-width: 1px) {
  .first {
    font-weight: 100;
  }
  .second {
    font-weight: 200;
  }
}
```

version info:
```cmd
$ node-sass --version
node-sass      	3.8.0  	(Wrapper)      	[JavaScript]
libsass        	3.3.6  	(Sass Compiler)	[C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
