### ISSUE TITLE
CSS comment inside of @supports incorrect CSS output

### ISSUE THREAD

**Issue by zachleat** [sass/libsass#2158]
Input:
```scss
@supports ( box-shadow: none ) {
	/* Shadow on first body column */
	.sizechart {
		position: relative;
	}
}
```

libsass 3.3.6
```css
@supports (box-shadow: none) { {
    /* Shadow on first body column */
  }
  .sizechart {
    position: relative;
  }
}
```

Sass 3.4.21
```css
@supports (box-shadow: none) {
  /* Shadow on first body column */
  .sizechart {
    position: relative;
  }
}
```

[Sassmeister Link](http://www.sassmeister.com/gist/47391852c9759e6e0dd7e15cfc3fcfd8)
