### ISSUE TITLE
Property with null value only should be stripped from output

### ISSUE THREAD

**Issue by MoOx** [sass/libsass#216]
Here is a simple issue:

Input

``` scss
$stuff: null;
selector {
  prop: $stuff;
}
```

**original Sass output** : _nothing_

**libsass (via node-sass)**: 

``` css
selector {
  prop: ;
}
```

...which is invalid CSS.
