### ISSUE TITLE
Weird compilation bug

### ISSUE THREAD

**Issue by matthias-vogt** [sass/libsass#2168]
input.scss
```scss
@function test($a, $b) {
  @return "#{$a}" + "#{$b}" + "bar" + "bol";
}

foo {
  content: test('bim', 'baz');
}
```

Errors in libsass 3.3.6 (on sassmeister) and node-sass 3.10.7 (Edit: actually 3.8.0) on macOS 10.12 Beta (16A313a) with `Illegal instruction: 4` (error code 132)
