### ISSUE TITLE
at-root does not work if there is an internal if statement

### ISSUE THREAD

**Issue by speedplane** [sass/libsass#2185]
### `at-root` does not work if there is an internal `if` statement

input.scss
```
$bar: true;
p {
	@if $bar {
		@at-root {
			div {
				width: 100px;
			}
		}
	}
	
	@at-root {
		@if $bar {
			div {
				height: 100px;
			}
		}
	}
}
```

[libsass 3.5.5] [1]
```
div {
  width: 100px;
}

p div {
  height: 100px;
}
```

Expected result:
```
div {
  width: 100px;
}

div {
  height: 100px;
}
```
[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==

**Comment by mgreter** [comment]
Updated the test to also include all? other similar statements:

```scss
$bar: true;

@mixin mixin() {
    mix: in;
}

@mixin include() {
    @content;
}

p {
    @at-root {
        @if $bar {
            #if {
                height: 100px;
            }
        }
        @if (not $bar) {
        } @elseif($bar) {
            #elseif {
                width: 100px;
            }
        }
        @if (not $bar) {
        } @else {
            #else {
                width: 100px;
            }
        }
        @for $i from 1 through 1 {
            #for {
                foo: bar#{$i};
            }
        }
        $i: 0;
        @while ($i == 0) {
            $i: $i + 1;
            #while {
                foo: bar#{$i};
            }
        }
        @each $i in (1) {
            #each {
                foo: bar#{$i};
            }
        }
        #inc {
            @include mixin();
            @include include() {
                inc: lude;
            }
        }
        @supports (display: flex) {
            display: flex;
        }
        @foo {
           bar: bat;
        }
    }
}
```
