### ISSUE TITLE
Variables defined within an if/else fall out of scope.

### ISSUE THREAD

**Issue by speedplane** [sass/libsass#2194]
### Variables first defined in an if / else, and used outside fall outside of scope and fail to compile

input.scss
```scss
@mixin my_mixin($foo) {
 // $bar: 0px; // <--- uncommenting this line will fix it, but I don't believe it should be necessary.
 @if ($foo > 10) {
   $bar: 100px;
 } @else {
   $bar: 200px;
 }
 width: $bar;
}

test {
  @include my_mixin(0);
  @include my_mixin(11);
}
```

[libsass 3.5.5] [1]
Fails to compile

Here is the example with the line uncommented (you can't save links that fail to compile):
http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
