### ISSUE TITLE
Output differences in named color values

### ISSUE THREAD

**Issue by tregagnon** [sass/libsass#220]
Take this code:

``` scss
$black: #000000;
$gray: lighten($black, 50%);

.test {
  color: $gray;
}
```

Sass outputs

``` css
.test {
  color: gray; }
```

but libsass outputs 

``` css
.test {
  color: grey; }
```

The two values `grey` and `gray` are valid CSS values. But `grey` was supported in Internet Explorer starting with version 8.
Other named color values share the grey/gray problem in IE7, please refer to this page to know their names http://msdn.microsoft.com/en-us/library/ie/aa358802%28v=vs.85%29.aspx

This difference in output creates bugs in IE7.

This bug was identified while using [node-sass](https://github.com/andrew/node-sass).
