### ISSUE TITLE
Regression with @extend breaks foundation

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2200]
#2052 introduced a regression (d83f879) which is breaking foundation.

```scss
.media-object-section:last-child:not(:nth-child(2)) {
  color: blue;
}

%orbit-control {
  color: red;
}

.orbit-previous {
  @extend %orbit-control;
}
```

LibSass 3.4 RC
```css
.media-object-section:last-child {
  color: blue; }

.orbit-previous {
  color: red; }
```

LibSass 3.3.6
```css
.media-object-section:last-child:not(:nth-child(2)) {
  color: blue; }

.orbit-previous {
  color: red; }
```
Spec added https://github.com/sass/sass-spec/pull/939
