### ISSUE TITLE
Cannot parse at rule with no definition

### ISSUE THREAD

**Issue by BarryThePenguin** [sass/libsass#2202]
input.scss
```scss
@customAtRule;
test {
  content: bar
}
```

[libsass 3.5.5] [1]
```css
// most def after "@customAtRule", was: ";" on line 1 at column 1
```

ruby sass 3.4.21
```css
@customAtRule;
test {
  content: bar;
}
```

version info:
```cmd
$ node-sass --version
node-sass	3.10.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
