### ISSUE TITLE
Incorrect evaluation of arithmetic inside interpolation

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2203]
The behaviour of this changed LibSass 3.4. Interestingly in this case Ruby Sass' output is also incorrect. A bug has been filed with Ruby Sass also https://github.com/sass/sass/issues/2160.

``` sass
foo {
  a: #{5% / 2};
  b: #{+5% / 2};
  c: #{-5% / 2};
}
```

Expected output

``` css
foo {
  a: 5%/2;
  b: 5%/2;
  c: -5%/2;
}
```

LibSass 3.4 RC

``` css
foo {
  a: 2.5%;
  b: 2.5%;
  c: -2.5%;
}
```

Ruby Sass 3.4.21

``` css
foo {
  a: 5%/2;
  b: 5%/2;
  c: -2.5%;
}
```

Spec https://github.com/sass/sass-spec/pull/940
##
