### ISSUE TITLE
Unclosed parenthesis in media query expression when using variable without #{}

### ISSUE THREAD

**Issue by bencergazda** [sass/libsass#2223]
### Unclosed parenthesis in media query expression when using variable without #{}

We cannot use variables in `@media` queries without the #{$variable_name} formula. This compiles perfectly under (Ruby) SASS v3.4.21, but not under LibSass v3.3.6. Fails on SourceMap Inspector as well. Link to reduced test case on Sassmeister: http://www.sassmeister.com/gist/efebdb5362a32d0a0f42977fed2eef0b

The issue reminds to #2117, but the code environment is less complicated than there.

input.scss
```scss

$brp1: 10px;
$brp2: "min-width: " ($brp1 + 1);

h1 {
  color: red;

  @media ($brp2) {
    color: green;
  }
}
```

[libsass 3.3.6] [1]
```css
unclosed parenthesis in media query expression on line 5 at column 4
```

ruby sass 3.4.21
```css
h1 {
  color: red;
}
@media (min-width: 11px) {
  h1 {
    color: green;
  }
}
```

version info:
```cmd
$ node-sass --version
node-sass       3.10.8
libsass         3.10.8
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
