### ISSUE TITLE
SourceMaps lines offset for interpolated selectors 

### ISSUE THREAD

**Issue by rodneyrehm** [sass/libsass#2224]
The SourceMaps generation seems to trip over multi-line selectors if they contain interpolations (`#{$variable}`). In the demo SCSS below the generated CSS `.zulu-delta` is referenced to line 17, while it should be line 19. This does not happen for non-interpolated multi-line selectors. A single interpolation in the selector string causes the lines to collapse before the mutation could be tracked in SourceMaps. The offset is not recovered from, so all SCSS content *after* such an interpolated selector is affected by the shift in line number.

input.scss ([SourceMap](http://libsass.ocbnet.ch/srcmap/#JHByZWZpeDogenVsdTsKCi5hbHBoYSwKLmJyYXZvLAouY2hhcmxpZSB7CiAgY29sb3I6IHJlZDsKfQoKLmRlbHRhIHsKICBjb2xvcjogYmx1ZTsKfQoKLiN7JHByZWZpeH0tYWxwaGEsCi4jeyRwcmVmaXh9LWJyYXZvLAouI3skcHJlZml4fS1jaGFybGllIHsKICBjb2xvcjogcmVkOwp9CgouI3skcHJlZml4fS1kZWx0YSB7CiAgY29sb3I6IGJsdWU7Cn0KCi5lY2hvIHsKICBjb2xvcjogZ3JlZW47Cn0=))
```scss
$prefix: zulu;

.alpha,
.bravo,
.charlie {
  color: red;
}

.delta {
  color: blue;
}

.#{$prefix}-alpha,
.#{$prefix}-bravo,
.#{$prefix}-charlie {
  color: red;
}

.#{$prefix}-delta {
  color: blue;
}

.echo {
  color: green;
}
```

version info:
```cmd
$ node-sass --version
node-sass	3.11.0	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
```
