### ISSUE TITLE
How can I target the syntactical parent when using the ampersand?

### ISSUE THREAD

**Issue by helmus** [sass/libsass#2227]
I'm trying to remove some duplication in my scss selector.

```scss
    .container {
      .operation {
        color: green;
      }
      .row.is-active &,
      .row:hover & {
        .operation {
          color: inherit;
        }
      }
    }
```
I tried rewriting it like this:
```scss
    .container {
      .operation {
        color: green;
      }
      .row & {
        &.is-active, &:hover {
          .operation {
            color: inherit;
          }
        }
      }
    }
```
However, this causes `.is-active` to be applied to `.container` instead of `.row`

How can I target the syntactical parent when using the ampersand ?

**Note:**
I asked this question on stack overflow first but did not get an answer: 
http://stackoverflow.com/questions/40164651/how-can-i-target-the-syntactical-parent-when-using-the-ampersand?noredirect=1#comment68212337_40164651

**Comment by xzyfer** [comment]
You'l have to do this on case by case basis using [selector functions](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_functions).

**Comment by xzyfer** [comment]
It's not clear what you're trying to achieve. Assuming you're trying to remove the nested `.container` selector you could do either.

Stop nesting unnecessarily
```sass
.container .operation {
  color: green;
}
.row {
  &.is-active, &:hover {
    .operation {
      color: inherit;
    }
  }
 }
```

If you insisting on nesting you can use `at-root` to break out of nested rules, but can cause issue if this block is itself nested in other selectors, or used in a mixin.
```sass
.container {
  .operation {
    color: green;
  }

  @at-root(without: rule) {
    .row.is-active,
    .row:hover {
      .operation {
        color: inherit;
      }
    }
   }
}
```

Both of these produce
```css
.container .operation {
  color: green; }

.row.is-active .operation,
.row:hover .operation {
  color: inherit; }
```

**Comment by helmus** [comment]
I am attempting to remove one `.row` selector. Right now I have to repeat it in my first code example ( shown below again ). 
Off course in this example this selector is very small, but that's for the sake of the example. 

Sometimes this selector might be bigger, and the ability to nest it under a single `.row &` selector would be nice

    .container {
      .operation {
        color: green;
      }
      // duplication of .row selector here
      .row.is-active &,
      .row:hover & {
        .operation {
          color: inherit;
        }
      }
    }

**Comment by xzyfer** [comment]
Can you not just combine the row selectors?

```
row.is-active:hover & {
 ...
}
```

**Comment by xzyfer** [comment]
There is no way for Sass to magically combine selectors for you. No tool can safely do this because the CSS cascade can cause side effects depending on your DOM structure.

**Comment by helmus** [comment]
Isn't the point of nesting selectors to combine them ? 😄 
Just wanna make extra clear that the below scss currently works for me, it does exactly what I want. 
I just wanted to reduce the fact that I have to write two `.row` selectors.


    .container {
      .operation {
        color: green;
      }
      .row.is-active &,
      .row:hover & {
        .operation {
          color: inherit;
        }
      }
    }

**Comment by xzyfer** [comment]
> Isn't the point of nesting selectors to combine them ?

No. It appends selectors, but it won't rewrite them to be "cleaner" because it's impossible to do safely. It will just append nested selectors to the parent.

>I just wanted to fix the fact that I have to write two .row selectors.

```
row.is-active:hover & {
 ...
}
```

**Comment by helmus** [comment]
Thanks for your help, it does look like this won't be possible then. Your proposed solution there is a different selector tough; it requires both `.is-active` and `:hover` condition to be true, while my selector needs only 1 of those conditions to be true.

**Comment by pawlufelice** [comment]
I think I have a similar issue. I have:
```
.a, .b {
    &-c {
        color: hotpink;
    }
}
```
and I get
```
.a-c,
.b-c {
  color: hotpink; }
```
So far so good. Then I do this:
```
.a, .b {
    & &-c {
        color: hotpink;
    }
}
```
and get
```
.a .a-c,
.b .a-c, .a
.b-c,
.b
.b-c {
  color: hotpink; }
```
but I want this:
```
.a .a-c,
.b .b-c {
  color: hotpink; }
```
Any help please?
thanks

**Comment by xzyfer** [comment]
@pawlufelice the output is correct. To do what you want you can do

```scss
.a {
    & &-c {
        color: hotpink;
    }
}
b {
    & &-c {
        color: hotpink;
    }
}
```

You also try to get creative with the [Sass selector functions](http://sass-lang.com/documentation/Sass/Script/Functions.html).
