### ISSUE TITLE
Omitted semicolon produces weird output instead of compile error

### ISSUE THREAD

**Issue by jleclanche** [sass/libsass#2228]
```
% sassc --version
sassc: na
libsass: na
sass2scss: 1.0.6
sass: 3.4
```

input.scss
```scss
#test {
        color: blue
        #child {
                color: red;
        }
}
```

Output:
```css
#test {
  color: blue #child;
    color-color: red; }
```

This doesn't look right at all. I think it should just error out.

**Comment by xzyfer** [comment]
This is a Sass feature called nested properties. See http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_properties

The intention for uses like

```sass
.foo {
  border: {
    width: 1px
    color: red;
    style: solid;
  }
}
```
```css
foo {
  border-width: 1px;
  border-color: red;
  border-style: solid;
}
```

**Comment by jleclanche** [comment]
@xzyfer I must be missing how one becomes the other? There's invalid syntax after that colon.

**Comment by xzyfer** [comment]
It's not a syntax error to Sass.

```sass
#test {
        color: blue
        #child {
                color: red;
        }
}
```
Is treated as
```
#test {
        color: blue #child {
                color: red;
        }
}
```
which as I've showed above is treated as a nested property
```css
#test {
  color: blue #child
  color- color: red;
}
```
