### ISSUE TITLE
Bare CSS color names should not be compressed when used in string expressions

### ISSUE THREAD

**Issue by bwbuchanan** [sass/libsass#2232]
Upstream issue: https://github.com/sass/sass/issues/2196

```scss
.#{'b-' + black} {
  background: black;
}
```

LibSass 3.4.0-RC1
```css
.b-#000{background:black}
```

Ruby Sass 3.4.22
```css
.b-#000{background:black}
```
