### ISSUE TITLE
different output on windows and linux

### ISSUE THREAD

**Issue by 593273894** [sass/libsass#2256]
input.scss
```scss
@function px2rem($px) {
    @return ($px / 64)+rem;
}

div {
    width: px2rem(5);
}
```

windows 10
```css
div {
  width: 0.07813rem; }

```
ubuntu 14.04.4
```css
div {
  width: 0.07812rem; }

```

version info:
```cmd
$ node-sass --version
node-sass       4.1.0   (Wrapper)       [JavaScript]
libsass         3.4.0   (Sass Compiler) [C/C++]
```

**Comment by mgreter** [comment]
This is a rounding error within reasonable margins. The calculation `5 / 64` results in exactly `0.078125`. Not much we can do due to the nature of how [floats are stored on computers] [1]. I was already aware of this; I mostly saw it with 32 vs 64 bit builds.

[1]: https://en.wikipedia.org/wiki/Floating_point#Accuracy_problems

**Comment by mgreter** [comment]
FWIW. this is the underlying "issue":
```c++
std::stringstream strm;
strm.precision(5);
strm << std::fixed << (5.0 / 64.0);
std::cerr << strm.str() << "\n";
// prints 0.07812
```

**Comment by 593273894** [comment]
Thank you for you reply. The difference results in the different file hash so I can not distinguish the file version. There are many numbers in my code like 25/64 45/64 61/64 will cause this issue. Is there any solutiion of this?

**Comment by saper** [comment]
Rounding it yourself?

**Comment by xzyfer** [comment]
You could try setting the precision setting to a small enough value.
Otherwise you'll need to implement your own rounding function with a very
small epsilon.

**Comment by 593273894** [comment]
Thank you for your help! I use this as a workaround:
```scss
@function px2rem($px) {
    @return ceil($px * 10000 / 64) / 10000+rem;
}
```
same output:
```css
div {
  width: 0.0782rem; }
```
