### ISSUE TITLE
3.4: @content inside @at-root block throws an error

### ISSUE THREAD

**Issue by TxHawks** [sass/libsass#2260]
### Title: 3.4: @content inside @at-root block throws an error

Including a `@content` statement inside an `@at-root` block (inside a mixin, of course) throws an error. This worked fine in `3.3.6`.

Here is a reduced test case:

input.scss
```scss
@mixin test() {
  @at-root {
    @content;
  }
}

@include test {
  .test {
    property: value;
   }
 }
```

libsass 3.4.0:
Throws an error:
```sh
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.

  Backtrace:
    input.scss:8, in mixin `@content`
    input.scss:3, in mixin `test`
    input.scss:7
 on line 8 of input.scss:7
```
ruby sass 3.4.21
```css
.test {
  property: value;
}
```

version info:
```sh
$ node-sass --version
node-sass       4.1.1   (Wrapper)       [JavaScript]
libsass         3.4.0   (Sass Compiler) [C/C++]
```
