### ISSUE TITLE
Interpolated parent selectors don't nest properly if parent is a list

### ISSUE THREAD

**Issue by schmod** [sass/libsass#2291]
I would expect to be able to use interpolation to achieve the same results as [`&-suffix`](https://github.com/sass/sass/issues/1055) by writing `#{&}-suffix`.  

This does not work correctly if the parent that `&` is referencing is a list of selectors.  In the output, `-suffix` is only appended to the final selector in the list.

## input.scss
```scss
.a {
  .b, .c, .d {
    color: blue;        
    #{&}-foo {
      color: red;
    }
  }
}
```

## Expected
```css
.a .b, .a .c, .a .d {
  color: blue; }
  .a .b-foo, .a .c-foo, .a .d-foo {
    color: red; }
```
This is the output I'd get (and would expect to get) if I substitute `#{&}-foo` for `&-foo` in the above example.

## libsass 3.4.3
```css
.a .b, .a .c, .a .d {
  color: blue; }
  .a .b, .a .c, .a .d-foo {
    color: red; }
```
The nested selector references `.a .b` and `.a .c` -- one would reasonably expect these to be `.a .b-foo` and `.a .c-foo` instead.

## ruby sass 3.4.21
```css
.a .b, .a .c, .a .d {
  color: blue;
}
.a .b .a .b, .a .b .a .c, .a .b .a .d-foo, .a .c .a .b, .a .c .a .c, .a .c .a .d-foo, .a .d .a .b, .a .d .a .c, .a .d .a .d-foo {
  color: red;
}
```
Different... and also seemingly wrong!  I think I can understand why there might be some sort of combinatoric expansion happening with the fully-qualified parent selector, but would expect to see `.b-foo`, and `.c-foo` somewhere in the output if that were actually the case.

## version info:
```cmd
$ sassc --version

sassc: 3.4.1
libsass: 3.4.3
sass2scss: 1.1.0
sass: 3.4
```

---

Unless I'm understanding the documentation incorrectly, in the above examples, I'd (roughly) expect `&-suffix` to produce the same output as `#{&}-suffix`.  However, the output that I get with the interpolation syntax seems like it would be difficult to justify or explain under any set of circumstances.

This is obviously a contrived example, as there is already a perfectly-acceptable workaround.  However, the current behavior seems difficult to justify, differs substantially from Ruby Sass, and may be causing issues elsewhere (where similar workarounds are not available).

[Sassmeister link](http://www.sassmeister.com/gist/9c40d650a4e55155fb651997ee52d9f9)

**Comment by schmod** [comment]
Aside: The above example works fine if the parent selector is _not_ a list.

## input.scss
```scss
.a {
  .b {
    color: blue;
    #{&}-foo {
      color: red;
    }
  }
}
```

## output.css
```css
.a .b {
  color: blue;
}

.a .b-foo {
  color: red;
}
```

**Comment by mgreter** [comment]
Thanks for your report, I can confirm this issue.

**Comment by mgreter** [comment]
The problem is how we handle String_Schema, or to be precise, that Selector_Schema internally uses a String_Schema. Please see the adjusted spec test below for illustration:

```scss
A {
  .b, .c, .d {
    #{&}-foo {
      parent: &bar;
      itpl: #{&}bar;
    }
  }
}
```

The selector `#{&}-foo` is a Selector Schema, while `&bar` and `#{&}bar` are String Schemas. As being said, internally a Selector Schema uses a String Schema, so when it gets evaluated, it produces the same result for both (which is only "correct" for the later).

Expected result:
```css
A .b-foo, A .c-foo, A .d-foo {
  parent: A .b-foo, A .c-foo, A .d-foo bar;
  itpl: A .b-foo, A .c-foo, A .d-foobar; }
```

Actual result:
```css
A .b A .b, A .b A .c, A .b A .d-foo, A .c A .b, A .c A .c, A .c A .d-foo, A .d A .b, A .d A .c, A .d A .d-foo {
  parent: A .b A .b, A .b A .c, A .b A .d-foo, A .c A .b, A .c A .c, A .c A .d-foo, A .d A .b, A .d A .c, A .d A .d-foo bar;
  itpl: A .b A .b, A .b A .c, A .b A .d-foo, A .c A .b, A .c A .c, A .c A .d-foo, A .d A .b, A .d A .c, A .d A .d-foobar; }
```

I think this is a regression from fixing the second use case (parent selector in properties). And I think I should be able to come up with a fix for that. Probably just needs a flag for String Schema to differ slightly when coming from a Selector Schema.

**Comment by mgreter** [comment]
Note that sassmeister for libsass 3.3.6 produces:
```css
.a .b, .a .c, .a .d {
  color: blue;
}

.a .b, .a .c, .a .d-foo {
  color: red;
}
```

So this does not seem to be a regression. Fix is comming up!

**Comment by mgreter** [comment]
Btw. this seems to be one of the specs I "somewhat" knew we were missing. I've commented a few code blocks in the past that were not hit by CI. While debugging this case I was able to trigger a few of them and removed them once proven not to be needed. PR is in https://github.com/sass/libsass/pull/2292

**Comment by mgreter** [comment]
Also worth noting that the behavior of ruby sass is expected, as one can see in the following sample :

```scss
A, B {
  #{&}-foo#{&}-bar {
    color: blue;
  }
  #{"A, B"}-foo#{"A, B"}-bar {
    color: blue;
  }
}
```
