### ISSUE TITLE
Unexpected results for lighten and darken functions

### ISSUE THREAD

**Issue by mattfaces** [sass/libsass#2294]
***input.scss***

```scss
.test-case {
  color: lighten(#333333, 10%);
  background-color: darken(#4d4d4d, 10%);
}
```

***Existing behavior***

Using:

```cmd
  node-sass 3.13.1
  libsass   3.3.6
```

Expected output (matches SassMeister v3.4.21):

```css
.test-case {
  color: #4d4d4d;
  background-color: #343434; }
```

***New and unexpected behavior***

Using:

```cmd
  node-sass 4.2.0
  libsass   3.4.3
```

Unexpected output:

```css
.test-case {
  color: #4d4c4c;
  background-color: #343333; }
```
