### ISSUE TITLE
Wrong ouptut using conditionals on partial stylesheets

### ISSUE THREAD

**Issue by frontday** [sass/libsass#2295]
### Wrong ouptut using conditionals on partial stylesheets

I am experiencing what seems to be a compilation bug when i use some conditional statements on partial stylesheets.

input.scss
```scss
$include-foo: true !default;
.my-scope {
  .bar {  display: none; }
  @if ($include-foo) {
    .foo { display: none; }
  }
  @import 'input-bug';
}
```

_input-bug.scss
```scss
$include-foo: true !default;
.bar { display: none; }
@if ($include-foo) {
  .foo { display: none; }
}
```

libsass 3.4.3
```css
.my-scope .bar {
  display: none; }
.my-scope .foo {
  display: none; }
.my-scope .bar {
  display: none; }
.foo {
  display: none; }
```

ruby sass 3.4.22
```css
.my-scope .bar {
  display: none; }
.my-scope .foo {
  display: none; }
.my-scope .bar {
  display: none; }
.my-scope .foo {
  display: none; }
```

Seems to be working as expected on older version of libsass

libsass 3.3.6
```css
.my-scope .bar {
  display: none; }
.my-scope .foo {
  display: none; }
.my-scope .bar {
  display: none; }
.my-scope .foo {
  display: none; }
```

version info:
```cmd
node-sass       4.3.0   (Wrapper)       [JavaScript]
libsass         3.4.3   (Sass Compiler) [C/C++]
```
