### ISSUE TITLE
:not() selector and @extend can produce wrong CSS

### ISSUE THREAD

**Issue by cmaart** [sass/libsass#2301]
input.scss
```scss
.loading {
    &:not(.button):before {
        background-color: #ffffff;
    }
}

.button {
    color: red;
}

.popover {
    .close-button {
        @extend .button;
        font-weight: bold;
    }
}
```

[libsass 3.4.3] [1]
```css
/* THIS IS INVALID */
.loading:not(.button):not(.popover .close-button):before {
  background-color: #ffffff;
}

.button, .popover .close-button {
  color: red;
}

.popover .close-button {
  font-weight: bold;
}
```

version info:
```cmd
$ node-sass --version
node-sass       4.3.0   (Wrapper)       [JavaScript]
libsass         3.4.3   (Sass Compiler) [C/C++]
```
