### ISSUE TITLE
Nested import of a module with if condition loses nesting

### ISSUE THREAD

**Issue by Kos** [sass/libsass#2303]
### Nested import of a module with if condition loses nesting

main.scss
```scss
.wrapper-class {
  @import 'module';
}
```

_module.scss
```scss
.okay {
  background: green;
}

@if true {
  .broken {
    background: red;
  }
}
```

### output:

libsass 3.4.3 (wrong)
```
.wrapper-class .okay {
  background: green; }

.broken {
  background: red; 
```

libsass 3.3.6 (ok)
```css
.wrapper-class .okay {
  background: green; }

.wrapper-class .broken {
  background: red; }
```

ruby sass 3.4.21 (ok)
```css
.wrapper-class .okay {
  background: green; }
.wrapper-class .broken {
  background: red; }
```

version info:
```cmd
$ node-sass --version
node-sass	4.3.0	(Wrapper)	[JavaScript]
libsass  	3.4.3	(Sass Compiler)	[C/C++]
```
