### ISSUE TITLE
Error: url(fn("str"))

### ISSUE THREAD

**Issue by glebm** [sass/libsass#231]
I am working on making bootstrap-sass compatible with libsass. libsass breaks on the following snippet:

``` scss
// test.scss:
a {
  background-image: url(fn("s"));
}
```

libsass error:

``` bash
node-sass test.scss --stdout
test.scss:2: error: non-terminal statement or declaration must end with ';'
```

ruby output:

``` scss
a {
  background-image: url(fn("s")); }
```

I am using the latest npm node-sass bindings.

---

The actual snippet where we use this:

``` scss
@mixin img-retina($file-1x, $file-2x, $width-1x, $height-1x) {
  background-image: url(if($bootstrap-sass-asset-helper, twbs-image-path("#{$file-1x}"), "#{$file-1x}"));
  ... 
}
```
##
