### ISSUE TITLE
Incorrectly interprets native CSS mixins as nested rules

### ISSUE THREAD

**Issue by tony19** [sass/libsass#2311]
See https://github.com/sass/sass/issues/2235

input.scss
```scss
$color: #f00;
my-view1 {
  --view1-card: {
    border: solid 1px #{$color};
    opacity: 0.5;
  };
}
```

libsass 3.5.0.beta.2
```css
my-view1 {
  --view1-card-border: solid 1px #f00;
  --view1-card-opacity: 0.5;
}
```

ruby sass 3.4.21
```css
my-view1 {
  --view1-card-border: solid 1px #f00;
  --view1-card-opacity: 0.5;
}
```

version info:
```cmd
$ node-sass --version
node-sass	4.4.0	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
