### ISSUE TITLE
index variable reference issues in for loops within functions

### ISSUE THREAD

**Issue by meodai** [sass/libsass#2330]
### index variable reference issues in for loops within functions

Looks like index variables within loops, within functions are references. Since all the map entries contain the last $index.

http://www.sassmeister.com/gist/965a577f60fd8f8e45d21235edb7cc9a

input.scss
```scss
@function test () {
  $m: ();
  $abc: a b c d e f g h i j k;
  
  @for $index from 1 through length($abc) {;
    $m: map-merge($m, (nth($abc, $index):$index) );
  }
  
  @return $m;
}

test {
  content: #{test()};
}
```

libsass 3.5.0.beta.2
```css
(a: 11, b: 11, c: 11, d: 11, e: 11, f: 11, g: 11, h: 11, i: 11, j: 11, k: 11)
```

ruby sass 3.4.21
```css
(a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10, k: 11)
```
