### ISSUE TITLE
Inspect issue with lists in maps

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#2333]
input.scss
```scss
test {
  test: inspect((a:1,b:(foo,bar),c:3));
}
```

[libsass 3.4.3][1]
```css
test {
  test: (a: 1, b: foo, bar, c: 3); }
```

ruby sass 3.4.23
```css
test {
  test: (a: 1, b: (foo, bar), c: 3); }
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgdGVzdDogaW5zcGVjdCgoYToxLGI6KGZvbyxiYXIpLGM6MykpOwp9
