### ISSUE TITLE
Media queries and @extend with sass functions

### ISSUE THREAD

**Issue by kenborge** [sass/libsass#2341]
I discovered a strange bug with extending and media queries when using a function to calculate the media query value.

The following code produces an error with libsass using both node-sass and sassc but works fine using ruby sass. 
```scss
@function aFunction() {
    @return 1em;
}

@media (max-width: 1em) {
    %placeholder {
        color: red;
    }
}

@media (max-width: aFunction()) {
    .test {
        @extend %placeholder;
    }
}
```

```
Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive.
       From "@extend %placeholder" on line 13 of ../../privateonline/test.scss
        on line 6 of ../../privateonline/test.scss
>>     %placeholder {
   ----^
```

Ruby sass generates the expected css
```css
@media (max-width: 1em) {
  .test {
    color: red; } }
```

And replacing the function call with the value makes libsass compile correct as well
```scss
@media (max-width: 1am) {
    .test {
        @extend %placeholder;
    }
}
```

version info:
```cmd
./sassc --version
sassc: 3.4.1-3-g36eb
libsass: 3.5.0.beta.3-2-g58fa
sass2scss: 1.1.0
sass: 3.5

node-sass --version
node-sass	4.5.0	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]

sass --version
Sass 3.4.23 (Selective Steve)
```
