### ISSUE TITLE
BEM w/ nth-child compiles unexpectedly

### ISSUE THREAD

**Issue by fuckingdigital** [sass/libsass#2344]
input.scss
```scss
.block {
    &:nth-child(even) {
        &__element {
            width: 9999px;
        }
    }
}
```
compiles to
output.css
```scss
.block:nth-child(even)__element {
    width: 9999px;
}
```

but I would expect
```scss
.block:nth-child(even) .block__element {
    width: 9999px;
}
```

version info:
```cmd
$ sass --version
Sass 3.4.22 (Selective Steve)
```

Am I wrong with this suggestion? What do you think?

Use case: Sometimes you define a component, but want to change its style on special pages e.g. home page.

**Comment by obendev** [comment]
```sass
.block {
    $root: &;

    &:nth-child(even) {

        #{$root}__element {
            width: 9999px;
        }
    }
}
```

Output:

```css
.block:nth-child(even) .block__element {
    width: 9999px;
}
```

Maybe this helps someone who stumbles upon this question.
