### ISSUE TITLE
Variable arguments with non-string keys that match a color keyword cause a segmentation fault

### ISSUE THREAD

**Issue by lachlanmcdonald** [sass/libsass#2352]
### Variable arguments with non-string keys that match a color keyword cause a segmentation fault

Only occurs when a map key is also a color keyword that is not wrapped as a string. For example, a key of `car` does not cause the segmentation fault, nor does `"green"`, but `green` does.

input.scss
```scss
$theme: (red: #D700EE);

@function test($args...) {
	@return #000;
}

.test {
	color: test($theme...);
}
```

libsass 3.4.3
```
Segmentation fault: 11
```

ruby sass 3.4.23
```
Error: Variable keyword argument map must have string keys.
       #ff0000 is not a string in (red: #D700EE).
        on line 8 of test.scss
  Use --trace for backtrace.
```

version info:
```cmd
sassc: 3.4.1
libsass: 3.4.3
sass2scss: 1.1.0
sass: 3.4
```
