### ISSUE TITLE
Error in @for loop in @function after manual incrementation 

### ISSUE THREAD

**Issue by NicolasGraph** [sass/libsass#2356]
input.scss
```scss
@function foo() {
  $value: false;

  @for $i from 1 through 5 {
    @if $i < 5 {
      $i: $i + 1;
      $value: 'broken';
    }
  }
  
  @return $value;
}

.foo {
  width: foo();
}
```

libsass 3.5.0.beta.2 returns nothing or the following error:
```css
Undefined operation: "broken lt 5". on line 5 at column 9
```

ruby sass 3.4.21 or 4.0.0.alpha.1 work as expected:
```css
.foo {
  width: "broken";
}
```

If I do the same without the use of a function, it works with libsass.

input.scss
```scss
$value: false;

@for $i from 1 through 5 {
  @if $i < 5 {
    $i: $i + 1;
    $value: 'broken';
  }
}

.foo {
  width: $value;
}
```

libsass 3.5.0.beta.2:
```css
.foo {
  width: "broken";
}
```

version info:
```cmd
$ node-sass --version
node-sass	4.5.0	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
