### ISSUE TITLE
Interpolations in CSS comments should not be evaluated in compressed mode

### ISSUE THREAD

**Issue by zaycakitayca** [sass/libsass#2359]
The following compiled in compressed mode

```scss
/*
$variable: 0;
.classname {
	width: #{$variable};
}
*/
```
LibSass 3.5.0.beta.2
```
Error: Undefined variable: "$variable".
```
Ruby Sass 3.4.21
```
```
