### ISSUE TITLE
Unnecessary space in compressed output of @media query

### ISSUE THREAD

**Issue by adrian5** [sass/libsass#2364]
I don't know if this has been fixed already and my version is just outdated, but I noticed the following:

```css
@media screen and (min-width: 500px) {
  body { color: blue; }
}
```
outputs to (compressed):
```css
@media screen and (min-width: 500px){body{color:blue}}
```
The space after `min-width` could be gotten rid of. My apologies, if this is already fixed in the current codebase; disregard my issue in that case.
