### ISSUE TITLE
extra comma after rule should raise syntax error but compiles unnoticed

### ISSUE THREAD

**Issue by NickWhiu** [sass/libsass#2365]
### extra comma after rule should raise syntax error but compiles unnoticed

When there is a comma after a rule (a syntax error) libsass appears to compile happily anyway, producing unexpected output when a syntax error should be raised. Notice the comma after the b{ ... } rule.

I tried this example with sassc after noticing this with a tool that uses node-sass. With the (official?) sass command line tool, it is correctly reported as a syntax error.

input.scss
```scss
a {
    b {
        color: red;
    },
    c {
        color: blue;
    }
}
```

[Expected output]
```
Error: Invalid CSS after rule:  expected selector, was "," on line 4
```

[Actual output - with sassc 3.5.0]
```css
a b {
  color: red; }

a,
a c {
  color: blue; }
```

version info:
```cmd
sassc           3.4.1-5-g5909-dirty
libsass        3.5.0.beta.3-25-ge14ca
```

Cheers,
love your work
