### ISSUE TITLE
@each is skipping over certain items in a map such as "yellow", "black" and "white"

### ISSUE THREAD

**Issue by TheColorRed** [sass/libsass#2374]
Install `node-sass` (it installs libsass `3.5.0.beta.2`):
```
npm install node-sass -g
```

I create a file with a map, `@each` and `@for` like this:

input.scss
```scss
$colors: (
    yellow: #ffeb3b
);
@each $name, $color in $colors {
    $amount: 40;
    @for $i from 0 through 9 {
        .#{$name}-#{($i*100)} { background-color: lighten($color, $amount) };
        $amount: $amount - 2;
    }
}
```

Once it is compiled I get an empty output file like this:

[libsass 3.5.0.beta.2]
```css
```

If I modify the `$colors` map by removing the `w` in `yellow` to become `yello`, I get a proper output as follows:

```css
.yello-0{background-color:#fff}
.yello-100{background-color:#fffffd}
.yello-200{background-color:#fffef3}
.yello-300{background-color:#fffde8}
.yello-400{background-color:#fffcde}
.yello-500{background-color:#fffbd4}
.yello-600{background-color:#fffaca}
.yello-700{background-color:#fff9c0}
.yello-800{background-color:#fff7b5}
.yello-900{background-color:#fff6ab}
```

version info:
```cmd
$ node-sass --version
node-sass       3.3.3   (Wrapper)       [JavaScript]
libsass         3.2.5   (Sass Compiler) [C/C++]
```

**Comment by xzyfer** [comment]
CSS colour names i.e red, black, yellpw, are considered Color objects in
Sass, not strings. This is why the string concatenation isn't working as
expected. If you quote the maps keys is should work.

I'll need to look into whether we're meant to be providing an error for
this case.

**Comment by TheColorRed** [comment]
Ahh, okay. Adding the quotes around the colors works.

**Comment by silvandiepen** [comment]
I use them in my projects with capitals in maps. Use Yellow instead of yellow. I would do it as following: 

``
$colors: (
    Yellow: #ffeb3b
);
@each $name, $color in $colors {
    $amount: 40;
    @for $i from 0 through 9 {
        .#{to-lower-case($name)}-#{($i*100)} { background-color: lighten($color, $amount) };
        $amount: $amount - 2;
    }
}

**Comment by xzyfer** [comment]
So I've done some digging into into this and I am unable to reproduce this issue with the code supplied on libsass 3.5.0.beta.2.

input
```scss
$colors: (
    yellow: yellow,
    red: red,
    blue: blue,
    
);
@each $name, $color in $colors {
    @for $i from 0 through 2 {
        .#{$name}-#{($i*100)} { 
          background-color: lighten($color, 10) 
          
        };
    }
}
```

output
```css
.yellow-0 {
  background-color: #ffff33; }

.yellow-100 {
  background-color: #ffff33; }

.yellow-200 {
  background-color: #ffff33; }

.red-0 {
  background-color: #ff3333; }

.red-100 {
  background-color: #ff3333; }

.red-200 {
  background-color: #ff3333; }

.blue-0 {
  background-color: #3333ff; }

.blue-100 {
  background-color: #3333ff; }

.blue-200 {
  background-color: #3333ff; }
```
