### ISSUE TITLE
[Bug] The /deep/ selector alias '>>>' is parsed incorrectly

### ISSUE THREAD

**Issue by luchillo17** [sass/libsass#2378]
### `node-sass` and thus `libsass` doesn't support the `>>>` selector.
Check this issue for meaningful history:
https://github.com/webpack-contrib/sass-loader/issues/456

input.scss
```scss
ul >>> li {
  background: lightblue;
}
```

output.css
```css
ul > > > li {
  background: lightblue; }
```

version info:
```cmd
$ node-sass --version
node-sass       4.5.2   (Wrapper)       [JavaScript]
libsass         3.5.0   (Sass Compiler) [C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
