### ISSUE TITLE
Custom function not reported as undefined

### ISSUE THREAD

**Issue by ogonkov** [sass/libsass#2398]
### Custom function not reported as undefined

input.scss
```scss
test {
  margin: bar(10)
}
```

[libsass 3.3.6] [1]
```css
test {
  margin: bar(10); }
```

ruby sass 3.4.21
```css
test {
  margin: bar(10); }
```

version info:
```cmd
$ node node_modules/.bin/node-sass --version
node-sass	3.13.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgbWFyZ2luOiBiYXIoMSk7IH0K
