### ISSUE TITLE
@extend with wrapped selectors has combinatorial explosion of selectors

### ISSUE THREAD

**Issue by uberska** [sass/libsass#2399]
### @extend with wrapped selectors has combinatorial explosion of selectors

input.scss
```scss
.thing {
	color: black;
}

.a,
.b,
.c,
.d,
.e {
	&:not(.thing) { @extend .thing; }
}
```

libsass 3.5.0.beta.3-20-g9eb7b333 via SourceMap Inspector [1]
```css
.thing, .a:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)))):not(
.e:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)))):not(
.d:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing))):not(
.e:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)))):not(
.c:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing))):not(
.d:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing))):not(
.e:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing))),
.b:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)),
.c:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)),
.d:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)),
.e:not(.thing):not(.a:not(.thing)):not(
.b:not(.thing)):not(
.c:not(.thing)):not(
.d:not(.thing)):not(
.e:not(.thing)) {
  color: black; }
```

ruby sass 3.4.21 via SassMeister
```css
.thing, .a:not(.thing),
.b:not(.thing),
.c:not(.thing),
.d:not(.thing),
.e:not(.thing) {
  color: black;
}
```

[1]: http://libsass.ocbnet.ch/srcmap/#LnRoaW5nIHsKCWNvbG9yOiBibGFjazsKfQoKLmEsCi5iLAouYywKLmQsCi5lIHsKCSY6bm90KC50aGluZykgeyBAZXh0ZW5kIC50aGluZzsgfQp9Cg==
