### ISSUE TITLE
String concatenation breaks with whitespace or quotations marks

### ISSUE THREAD

**Issue by jgebhardt** [sass/libsass#240]
I'm running into the following issue using node-sass 0.7.0:

``` scss
$STATIC_ROOT: 'foo/bar/';

.this-works {
 background: url( #{$STATIC_ROOT}lalala.png );
}
/* output: background: url(foo/bar/lalala.png); }*/

.this-breaks-in-libsass {
 background: url( $STATIC_ROOT + 'lalala.png');
}
/* output: background: url( $STATIC_ROOT + 'lalala.png'); }*/
```

The second example works fine in ruby sass.
