### ISSUE TITLE
Handle placeholders in selector pseudos more semantically

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2422]
Issue https://github.com/sass/sass/issues/2228
PR https://github.com/sass/sass/pull/2314
Spec https://github.com/sass/sass-spec/pull/1143

**Comment by mgreter** [comment]
```scss
a:matches(%b) {x: a}
a:matches(%b, c) {x: b}
a:not(%b) {x: c}
a:not(%b, c) {x: d}
:not(%b) {x: e}
```
