### ISSUE TITLE
[Media queries] Negation is ignored when nested media queries exist

### ISSUE THREAD

**Issue by yivo** [sass/libsass#2425]
__libsass 3.5.0.beta.3-54-gdebb1e32__

http://libsass.ocbnet.ch/srcmap/#LmJsb2NrIHsKICBAbWVkaWEgbm90IHByaW50IHsKICAgIEBtZWRpYSAobWluLXdpZHRoOiA2MDBweCkgewogICAgICBjb2xvcjogZ3JlZW47CiAgICB9CiAgfQp9

## input.scss

```scss
.block {
  @media not print {
    @media (min-width: 600px) {
      color: green;
    }
  }
}
```

## Actual results
```css
@media print and (min-width: 600px) {
  .block {
    color: green; } }
```

## Expected result
```css
@media not print and (min-width: 600px) {
  .block {
    color: green; } }
```

**Comment by yivo** [comment]
__Sass 3.4.24 (Selective Steve)__

Not error, not output at all :)

**Comment by yivo** [comment]
It works well if `@media not print` is nested.
```scss
.block {
  @media (min-width: 600px) {
    @media not print {
      color: green;
    }
  }
}
```

**Comment by nschonni** [comment]
Since Ruby Sass doesn't print anything at all, this is likely a bug that libsass is outputing anything at all.

Found another odd case while testing it out though https://www.sassmeister.com/gist/e1ccf7eb83bf43f20915eab65abb54d3

```scss
.block {
  @media not print {
    backgroud: red;
    @media (min-width: 600px) {
      color: green;
    }
  }
}
```
Libsass: Not that the second `@media` has dropped the `not`
```css
@media not print {
  .block {
    backgroud: red;
  }
}

@media print and (min-width: 600px) {
  .block {
    color: green;
  }
}
```
Ruby 3.4
```
@media not print {
  .block {
    backgroud: red;
  }
}
```
3.5+ produces nothing again.
