### ISSUE TITLE
SASS variables don't compile properly, unexpected math expression result

### ISSUE THREAD

**Issue by nop33** [sass/libsass#2426]
[todo]: # (Title: Be as meaningful as possible)
[todo]: # (Title: Try to use 60 or less chars)

[todo]: # (This is only a template!)
[todo]: # (remove unneeded bits)
[todo]: # (use github preview!)

## input.scss

```scss
$default-margin: 10px;

body {
    margin: $default-margin -$default-margin -$default-margin -$default-margin;
}

```

## Actual results

[libsass 3.X.y][1]
```css
body {
  margin: -20px; }
```

## Expected result

```css
body {
  margin: 10px -10px -10px -10px; }
```

version info:
```cmd
$ node-sass --version
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#CiRkZWZhdWx0LW1hcmdpbjogMTBweDsKCmJvZHkgewogICAgbWFyZ2luOiAkZGVmYXVsdC1tYXJnaW4gLSRkZWZhdWx0LW1hcmdpbiAtJGRlZmF1bHQtbWFyZ2luIC0kZGVmYXVsdC1tYXJnaW47Cn0KCg==

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. We're closing this issue since Ruby Sass produces the same output. In the future please confirm that LibSass' output differs from Ruby Sass before opening an issue.

**Comment by xzyfer** [comment]
You can work around this with interpolation

```
$default-margin: 10px;

body {
    margin: $default-margin #{-$default-margin} #{-$default-margin} #{-$default-margin};
}
```

**Comment by nop33** [comment]
This also works, what's the correct approach?
```sass
$default-margin: 10px;

body {
    margin: #{$default-margin} -#{$default-margin} -#{$default-margin} -#{$default-margin};
}
```

**Comment by xzyfer** [comment]
I don't this there is a "right" way. What I would do is assign the negative value to another variable first.

```css
$default-margin: 10px;
$negative-margin: -10px;

body {
    margin: $default-margin $negative-margin $negative-margin $negative-margin;
}
```
