### ISSUE TITLE
regression: input[type=url] { ... } fails to parse

### ISSUE THREAD

**Issue by asottile** [sass/libsass#2429]
## input.scss

```scss
input[type=url] {
  content: bar
}
```

### libsass 3.4.5 and libsass 3.5.0.beta.3-64-g5cb5
```
Error: Invalid CSS after "i": expected 1 selector or at-rule, was "input[type=url] {"
        on line 1 of test.scss
>> input[type=url] {
   ^
```

### libsass 3.4.4
```css
input[type=url] {
  color: red; }
```

May also be related to: https://github.com/sass/libsass/issues/2427

From bisect it appears to be this commit:

10398ed299bffa7ccc32aace50dacbe1a51379a2

```
10398ed299bffa7ccc32aace50dacbe1a51379a2 is the first bad commit
commit 10398ed299bffa7ccc32aace50dacbe1a51379a2
Author: Marcel Greter <marcel.greter@ocbnet.ch>
Date:   Sat May 20 19:01:04 2017 +0200

    Fix parser for urls looking like ruleset selectors (#2376)
```
