### ISSUE TITLE
Extending and :not selectors generating invalid css

### ISSUE THREAD

**Issue by kenborge** [sass/libsass#2431]
Libsass is compiling invalid css when extending classes that are used  in :not() pseudo selectors.

If a class is used in a not selector and something extends that class then it output another css selector with a not selector where the original class is replaced with the extending selector.
This can create invalid css like ```:not(.page .new-btn)``` that causes Chrome and Firefox to just ignore that entire rule. 

## input.scss

```scss
.btn {
    display: block;
}

.page .new-btn {
    @extend .btn;
}

.link:not(.btn) {
    @extend .btn;
}
```

## Actual results
libsass 3.4.X or 3.5.X
```css
.btn, .page .new-btn, .link:not(.btn):not(.page .new-btn):not(.link:not(.btn)) {
  display: block; }
```

## Expected result

[todo]: # (update version info!)

ruby sass 3.4.24
```css
.btn, .page .new-btn, .link:not(.btn) {
  display: block; }
```
## version info
```cmd
sassc      3.4.5
libsass    3.4.X and 3.5.X
ruby sass 3.4.24
```
