### ISSUE TITLE
color name keywords as keys in maps return empty on map-get

### ISSUE THREAD

**Issue by maniqui** [sass/libsass#2442]
When using color keywords as keys in maps, and then trying to access them using `map-get`, I'm getting empty output. 
In this example, I've used `white` and `black` as keys in `$badColors` map. They return empty on `map-get`.
The workaround is wrapping the keys with quotes (ie. `"white"` and `"black"`), and that's enough for `map-get` to work as expected.

Here is a [gist on SassMeister](https://www.sassmeister.com/gist/3f27aa9b65055370fccf8da5d035ca23) to test (I couldn't load the libsass.ocbnet.ch/srcmap tool, as it seems there is an issue with DNS records for that page). 

Just in case, here are the input and output too.

## input.scss

```scss
$badColors: (
  white: #fff,
  black: #000
);

$goodColors: (
  "white": #fff,
  "black": #000
);

.test-bad {
 color: map-get($badColors, "white");
 background-color: map-get($badColors, "black");
}

.test-good {
 color: map-get($goodColors, "white");;
 background-color: map-get($goodColors, "black");
}
```

## Actual results

[todo]: # (update version info!)

libsass 3.5.0-beta2
```css
.test-good {
  color: #fff;
  background-color: #000;
}

```

## Expected result

```css
.test-bad {
  color: #fff;
  background-color: #000;
}

.test-good {
  color: #fff;
  background-color: #000;
}
```
version info:
```cmd
$ node-sass --version
node-sass	4.5.3	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

Note: I've searched the existing issues and couldn't find this particular issue already reported, but I've seen there were already a few other issues with color name keywords.

**Comment by xzyfer** [comment]
Duplicate of #2409. Please the the issue fully for an explanation and
solution.

**Comment by maniqui** [comment]
Yes, I saw that issue before posting this one, and although probably caused by the same misunderstanding, I though it would be better to create a new issue.

By the way, I found another workaround, which you can see [in this gist](https://www.sassmeister.com/gist/f1c3f2e6a788a081802e627359c324ad).

Passing an unquoted `key` argument to `map-get` is enough to work. I though that the argument had to be a string, but it seems a "naked" `key` is fine, and probably, correct. Right?

## input.scss

```scss
$badColors: (
  white: #fff,
  black: #000
);

$goodColors: (
  "white": #fff,
  "black": #000
);

.test-bad {
   color: map-get($badColors, white); #Unquoted key
   background-color: map-get($badColors, black); #Unquoted key
}

.test-good {
   color: map-get($goodColors, "white");;
   background-color: map-get($goodColors, "black");
}
```

## Actual and expected output

```css
.test-bad {
  color: #fff;
  background-color: #000;
}

.test-good {
  color: #fff;
  background-color: #000;
}
```
