### ISSUE TITLE
Bug with negative variables in margin/padding longhand

### ISSUE THREAD

**Issue by arempe93** [sass/libsass#2443]
right/bottom rules removed when using negative variables in margin/padding/etc

## input.scss

```scss
$size: 20px;

.no-variables {
  margin: -20px 0 0 -20px;
}

.positive-variables {
  margin: $size 0 0 $size;
}

.negative-variables {
  margin: -$size 0 0 -$size;
}
```

## Actual results

[libsass 3.5.0.beta.2][1]
```css
.no-variables {
  margin: -20px 0 0 -20px; }

.positive-variables {
  margin: 20px 0 0 20px; }

.negative-variables {
  margin: -20px 0 -20px; }
```

## Expected result

```css
.no-variables {
  margin: -20px 0 0 -20px; }

.positive-variables {
  margin: 20px 0 0 20px; }

.negative-variables {
  margin: -20px 0 0 -20px; }
```

version info:
```cmd
$ node-sass --version
node-sass	4.5.0	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#JHNpemU6IDIwcHg7Cgoubm8tdmFyaWFibGVzIHsKICBtYXJnaW46IC0yMHB4IDAgMCAtMjBweDsKfQoKLnBvc2l0aXZlLXZhcmlhYmxlcyB7CiAgbWFyZ2luOiAkc2l6ZSAwIDAgJHNpemU7Cn0KCi5uZWdhdGl2ZS12YXJpYWJsZXMgewogIG1hcmdpbjogLSRzaXplIDAgMCAtJHNpemU7Cn0=
