### ISSUE TITLE
@supports fails when passing variables

### ISSUE THREAD

**Issue by jhpratt** [sass/libsass#2452]
## input.scss

```scss
@mixin supports($prop, $val) {
  @supports ($prop: $val) {
    $prop: $val;
  }
}

div {
  @include supports(display, flow-root);
}
```

## Actual results

node-sass 4.5.3 **(via gulp)**
```
Error: Invalid CSS after "  @supports (": expected "}", was "$prop: $val) {"
        on line 2 of css/all.scss
>>   @supports ($prop: $val) {
   ------------^
```

## Expected result

[todo]: # (update version info!)

ruby sass 3.5.1
```css
@supports (display: flow-root) {
  div {
    display: flow-root; } }
```

Spec https://github.com/sass/sass-spec/pull/1219

**Comment by nschonni** [comment]
Trying with Ruby 3.4.21 on sassmeister doesn't output anything.

To find the version of node-sass installed with gulp-sass, try `npm ls node-sass`

**Comment by jhpratt** [comment]
@nschonni node-sass is 4.5.3.

**Comment by nschonni** [comment]
Can you also confirm the Ruby Sass version as well, since I didn't get any output when trying on Sassmeister.

**Comment by jhpratt** [comment]
Just running `sass --version`, which is what I think you want, gives 3.5.1, which is the current release.

**Comment by nschonni** [comment]
I'm not :100: that the variables in the support query is supported, but using the `@supports` without the mixin works in both Ruby and Node so I'll update the title
```scss
div {
  @supports(display: flow-root) {
    display: flow-root;
  }
}
```

**Comment by jhpratt** [comment]
Ah, gotcha. It works using regular compilation, that's why I couldn't figure out why it wasn't working. Thanks for figuring that out! Hopefully this can be resolved at some point.

**Comment by meduzen** [comment]
I encountered this blocking situation while writing a `@mixin`. I have a `@supports` declaration with logic. Basically, and a bit shortened, what I’d like to do is this, which seems  impossible at the moment:
```
@each $offset, $val in $offsets {
  @supports(#{$prop}-#{$offset}: unquote('max(0px)')) {
    #{$prop}-#{$offset}: unquote('max(constant(safe-area-inset#{$offset}), #{$value})');
  }
}
```

**Comment by hitautodestruct** [comment]
This issue is occurring for me on node-sass v4.7.2 any ideas if this will be fixed?

**Comment by xzyfer** [comment]
The issue here is that Sass does not support `$variables` as the prop in `@supports`. 

```scss
$prop: display;
$val: flow-root;

div {
  @supports ($prop: $val) {
    $prop: $val;
  }
}
```

The following works as expected.

```scss
$val: flow-root;

div {
  @supports (display: $val) {
    display: $val;
  }
}
```

There are a couple things here:
- Dart and Ruby produce no output (@nex3 can you please comment on whether this is intended?)
- LibSass throws an error (it should either do nothing, or do something, but not error)

**Comment by nex3** [comment]
@xzyfer The Dart/Ruby output is intended. The issue isn't that `@supports ($prop: $val)` doesn't work (it does); the issue is that the `$prop: $val;` in the body is a variable assignment, not a property declaration. If you wrote instead

```scss
$prop: display;
$val: flow-root;

div {
  @supports ($prop: $val) {
    #{$prop}: $val;
  }
}
```

Ruby and Dart Sass will both produce

```css
@supports (display: flow-root) {
  div {
    display: flow-root;
  }
}
```
