### ISSUE TITLE
Host selector regression in 3.4.5 (since 3.4.0): :host(:not(.foo))

### ISSUE THREAD

**Issue by ochafik** [sass/libsass#2464]
The following works in 3.4.0 but not in 3.4.5:
```scss
:host(:not(.foo)) {
  left: 0;
}
```

(3.4.5 outputs `{left:0}` here!)
