### ISSUE TITLE
@extend breaks :matches()/:-moz-any()/:-webkit-any()

### ISSUE THREAD

**Issue by JD342** [sass/libsass#2468]
## input.scss
```css
%test {
    :matches(oh, no) {
        x: 1;
        y: 2;
    }
}
test {
    @extend %test;
}
```

## Actual result
```css
test :matches(oh):matches(no) {
  x: 1;
  y: 2; }
```

## Expected result
```css
test :matches(oh, no) {
  x: 1;
  y: 2; }
```

It works with the Ruby version `sass (3.4.24)`.

## Version Info
Tried both with `sassc 3.4.2`/`libsass: 3.4.3` (installed in the system) and `sassc 3.4.5`/`libsass 3.5.0.beta.3-81-g4f74` (cloned and built).
