### ISSUE TITLE
Encoding issue with code literals (again)

### ISSUE THREAD

**Issue by sinuhepop** [sass/libsass#2474]
I have an encoding issue with different implementations of libsass. For example, writing:

```
$var: "\f045"; 
.c1 { content: $var; } 
.c2 { content: "\f045"; }
```

And I get:

```
@charset "UTF-8";
.c1 { content: ""; }
.c2 { content: "\f045"; }
```

So it seems that this problem appears when using variables. It is very similar to other issues ([1](https://github.com/sass/libsass/issues/1231), [2](https://github.com/sass/libsass/issues/1235), [3](https://github.com/sass/libsass/issues/102), [4](https://github.com/sass/libsass/issues/1237)) already [solved](https://github.com/sass/libsass/pull/1534). 

I tried with different [implementations](https://github.com/sass/libsass/blob/master/docs/implementations.md): [libsass-maven-plugin](https://github.com/warmuuh/libsass-maven-plugin), [jsass](https://github.com/bit3/jsass) and [node-sass](https://github.com/sass/node-sass).

**Comment by mgreter** [comment]
This is the way how ruby sass does it, and libsass tries to mimic ruby sass behavior whenever possible. The `.c2` case is not changed to a unicode code-point because it's a static optimization by ruby sass (input is keept untouched). If you think this is a bug, please open an issue on upstream ruby sass directly. I think there is already a similar ticket open to get rid of the static optimization, since it also complicates other cases (like trailing semicolons etc.).

```scss
$var: "\f045"; 
.c1 { content: $var; } 
.c2 { content: "\f045"; }
.c3 { content: ("\f045"); }
```

```css
@charset "UTF-8";
.c1 { content: ""; }
.c2 { content: "\f045"; }
.c3 { content: ""; }
```
