### ISSUE TITLE
@supports are printed even if it was only an unused transparent mixing inside of them

### ISSUE THREAD

**Issue by wesleytodd** [sass/libsass#2488]
## input.scss

```scss
%foo {
  @supports (mask-repeat: repeat-x) {
     mask-image: url(foo.svg);
  }
}
```

## Actual results [1]

```css
@supports (mask-repeat: repeat-x) { }
```

## Expected result

```
// No output
```

version info:
```cmd
$ node-sass --version
node-sass	4.5.3	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#JWZvbyB7CiAgQHN1cHBvcnRzIChtYXNrLXJlcGVhdDogcmVwZWF0LXgpIHsKICAgICBtYXNrLWltYWdlOiB1cmwoZm9vLnN2Zyk7CiAgfQp9

Edit: I am willing to put in the PR for this if someone would point me in the right direction.
