### ISSUE TITLE
Compile error: env(safe-area-inset-left) is not a number for max()

### ISSUE THREAD

**Issue by janfryauf** [sass/libsass#2510]
Hi,
I wanted to use a new webkit feature for iPhone X (safe-area-inset-left) but getting error from compiler because of the function max()

## input.scss

```scss
@supports(padding: max(0px)) {
     padding-left: max(15px, env(safe-area-inset-left));
     padding-right: max(15px, env(safe-area-inset-right));
}
```

## Error
```
"env(safe-area-inset-left)" is not a number for `max'
```

version info:
```cmd
$ node-sass --version
node-sass       4.6.1   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2   (Sass Compiler) [C/C++]
```
