### ISSUE TITLE
BUG: Duplicate Key Error When Looping Through Function Parameter

### ISSUE THREAD

**Issue by daniel-nagy** [sass/libsass#2518]
[todo]: # (Title: Be as meaningful as possible)
[todo]: # (Title: Try to use 60 or less chars)

[todo]: # (This is only a template!)
[todo]: # (remove unneeded bits)
[todo]: # (use github preview!)

When passing a parameter to a function and using that parameter in a `@for` loop to generate a map with numeric keys you get a duplicate key error.

I tested this in SourceMap Inspector and I think it was working as expected in 3.5.0.beta.3-118-g4d83681e.

Workaround in beta 2 is to quote the key.

## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
@function create-row($columns) {
  $cells: ();
  
  @for $i from 1 through $columns {
    // need to quote the key or else libsass will error
    // Duplicate key 2 in map ((2: (isEmpty: true), 2: (isEmpty: true)))
    // $cells: map-merge($cells, (#{$i}: (isEmpty: true)));
    $cells: map-merge($cells, ($i: (isEmpty: true)));
  }
  
  @return $cells;
}

div {
  @for $i from 1 through 3 {
    // content: map-get(map-get(create-row(3), (#{$i})), "isEmpty");
    content: map-get(map-get(create-row(3), ($i)), "isEmpty");
  }
}

// this works perfectly fine however
$columns: 3;
$cells: ();

@for $i from 1 through $columns {
  $cells: map-merge($cells, ($i: (isEmpty: true)));
}

div {
  @for $i from 1 through 3 {
    content: map-get(map-get($cells, ($i)), "isEmpty");
  }
}
```

## Actual results

[todo]: # (update version info!)

[libsass 3.5.0.beta.2][1]
```css
Duplicate key 2 in map ((2: (isEmpty: true), 2: (isEmpty: true)))
```

## Expected result

[todo]: # (update version info!)

ruby sass 3.X.y
```css
map ((1: (isEmpty: true), 2: (isEmpty: true), 3: (isEmpty: true)))
```

[todo]: # (update version info!)
[todo]: # (example for node-sass!)

version info:
```cmd
$ node-sass --version
node-sass       3.X.y   (Wrapper)       [JavaScript]
libsass         3.X.y   (Sass Compiler) [C/C++]
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==

**Comment by xzyfer** [comment]
Tested this with the latest Ruby Sass, Dart Sass, and LibSass and confirmed the output is the same.

```css
div {
  content: true;
  content: true;
  content: true;
}

div {
  content: true;
  content: true;
  content: true;
}
```

Closing this as fixed on master.
