### ISSUE TITLE
Inconsistent/broken behaviour when using ampersand selector compared with Ruby Sass

### ISSUE THREAD

**Issue by esr360** [sass/libsass#2520]
I have come across a few bugs which are difficult to isolate, but I've pinpointed it down to how `&` functions compared with Ruby Sass.

Here are my versions:

```
node-sass	4.5.3	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

I have a very complicated setup, so I haven't been able to reproduce the problem in only a few lines of code, I have however created a SassMeister which contains all the various functions and mixins which are used to contribute to the issue (7 functions and 4 mixins, so not _too_ crazy), and some code which demonstrates the issues.

The first SassMeister is what I originally had using Ruby Sass, which throws the following error with LibSass:

```
>> Error: index out of bounds for `nth($list, $n)`
>>         on line 21 of ../../Synergy/src/scss/mixins/_component.scss
>> >>     $namespace: nth(module-tree(&), length(module-tree(&)));
```

This is referring to line 147 on this SassMeister: https://www.sassmeister.com/gist/01ac27d4dbaa46ff48a4e75441cff5d7

The error can be suppressed by changing the culpable line to:

```scss
$this: &;
$tree: module-tree($this);
$namespace: nth($tree, length($tree));
```

As seen on the second SassMeister: https://www.sassmeister.com/gist/b550ccf7dd5043e7b75fe97cc28b5c57

From here, the Sass compiles, but the result is incorrect.

Expected result (as shown on SassMeister):

```css
.button__group, 
[class*="button__group-"] {
  content: 'fizzbuzz';
}

.button__group .button,
.button__group [class*="button--"], 
[class*="button__group-"] .button, 
[class*="button__group-"] [class*="button--"] {
  margin-left: 1em;
}

.button__group .button:first-child, 
.button__group [class*="button--"]:first-child, 
[class*="button__group-"] .button:first-child, 
[class*="button__group-"] [class*="button--"]:first-child {
  margin-left: 0;
}

[class*="modal--"][class*="--animate"][class*="--zoom"] {
  content: "fizzbuzz";
}
```

Actual result:

```css
.button__group, 
[class*="button__group-"] {
  content: 'fizzbuzz';
}

.button__group .button, 
.button__group [class*="button--"], 
[class*="button__group-"] .button, 
[class*="button__group-"] [class*="button--"] {
  margin-left: 1em;
}

.button__group .button__group .button:first-child, 
.button__group .button__group [class*="button--"]:first-child, 
.button__group [class*="button__group-"] 
.button:first-child, 
.button__group [class*="button__group-"] 
[class*="button--"]:first-child, 
[class*="button__group-"] .button__group .button:first-child, 
[class*="button__group-"] .button__group [class*="button--"]:first-child, 
[class*="button__group-"] [class*="button__group-"] .button:first-child, 
[class*="button__group-"] [class*="button__group-"] [class*="button--"]:first-child {
  margin-left: 0;
}

[class*="modal--"] [class*="modal--"][class*="--animate"][class*="--zoom"] {
  content: "fizzbuzz";
}
```

As you can see the actual output differs from the expected output.

Focussing on just this part:

```scss
[class*="modal--"] [class*="modal--"][class*="--animate"][class*="--zoom"] {
  content: "fizzbuzz";
}
```

This can be fixed by caching `&` as `$this` in the `modifier` mixin, and passing the result inside `@at-root`, as seen in this third SassMeister (lines 206 - 234): https://www.sassmeister.com/gist/d0edb2a466353cfdf9e47cf1f8c49a23

The above will now correctly output as:

```scss
[class*="modal--"][class*="--animate"][class*="--zoom"] {
  content: "fizzbuzz";
}
```

This still leaves unwanted behaviour in the rest of the output.

Inside the `this()` function, you will see the following piece of code ([lines 96 - 113](https://www.sassmeister.com/gist/d0edb2a466353cfdf9e47cf1f8c49a23)):

```scss
  $this: &;

  @if length($this) > 0 {
    @if str-index(inspect(nth($this, 1)), '%') == 1 {
      $debug: false;
    }
  }

  @if $debug and not $value and $value != false {
      @warn '#{$options} not found in #{$module} config';
  }
```

Duplicating the `$this: &;` line to give:

```scss
  $this: &;
  $this: &;

  @if length($this) > 0 {
    @if str-index(inspect(nth($this, 1)), '%') == 1 {
      $debug: false;
    }
  }

  @if $debug and not $value and $value != false {
      @warn '#{$options} not found in #{$module} config';
  }
```

...now results in this even more bloated output:

```css
.button__group, 
[class*="button__group-"] {
  content: 'fizzbuzz';
}

.button__group .button, 
.button__group [class*="button--"], 
[class*="button__group-"] .button, 
[class*="button__group-"] [class*="button--"] {
  margin-left: 1em;
}

.button__group .button__group .button__group .button:first-child, 
.button__group .button__group .button__group [class*="button--"]:first-child, 
.button__group .button__group [class*="button__group-"] .button:first-child, 
.button__group .button__group [class*="button__group-"] [class*="button--"]:first-child,
.button__group [class*="button__group-"] .button__group .button:first-child, 
.button__group [class*="button__group-"] .button__group [class*="button--"]:first-child, 
.button__group [class*="button__group-"] [class*="button__group-"] .button:first-child, 
.button__group [class*="button__group-"] [class*="button__group-"] [class*="button--"]:first-child, 
[class*="button__group-"] .button__group .button__group .button:first-child, 
[class*="button__group-"] .button__group .button__group [class*="button--"]:first-child, 
[class*="button__group-"] .button__group [class*="button__group-"] .button:first-child, 
[class*="button__group-"] .button__group [class*="button__group-"] [class*="button--"]:first-child, 
[class*="button__group-"] [class*="button__group-"] .button__group .button:first-child, 
[class*="button__group-"] [class*="button__group-"] .button__group [class*="button--"]:first-child, 
[class*="button__group-"] [class*="button__group-"] [class*="button__group-"] .button:first-child, 
[class*="button__group-"] [class*="button__group-"] [class*="button__group-"] [class*="button--"]:first-child {
  margin-left: 0;
}

[class*="modal--"][class*="--animate"][class*="--zoom"] {
  content: "fizzbuzz";
}
```

This final issue can be fixed by simply commenting out the culpable code, which luckily (and ironically) only serves to aid debugging and doesn't provide any functionality:

```scss
@function this($options...) {
  $value: map-get($config, $options...);
  $debug: true;

  //$this: &;

  //@if length($this) > 0 {
  //  @if str-index(inspect(nth($this, 1)), '%') == 1 {
  //    $debug: false;
  //  }
  //}

  //@if $debug and not $value and $value != false {
  //    @warn '#{$options} not found in #{$module} config';
  //}

  @return $value;
}
```

Once again I apologise for not being able to provide a more cut down reproduction of the issues, but I have been struggling with these issues for literally over 2 years so I'm hoping someone can help me get to the bottom of it.

But the main thing for me is I was able to find work arounds, so I can finally start using Libsass and Node-Sass! For further transparency, you can view the git diff of the changes I've had to make to make my app compatible with Libsass:

https://github.com/esr360/Synergy/commit/8e3e692719e419550a29f2f62401a731fb008a7b
