### ISSUE TITLE
CSS environment variables throwing error when used with max()

### ISSUE THREAD

**Issue by fsaenger** [sass/libsass#2535]
## input.scss

```scss
@supports(padding: max(0px)) {
  .test {
    padding-left: max(12px, env(safe-area-inset-left));
    padding-right: max(12px, env(safe-area-inset-right));
  }
}
```

## Actual results

[todo]: # (update version info!)

[libsass 3.5.0.beta.3][1]
```
Error: "env(safe-area-inset-left)" is not a number for `max'
        on line 3 of stdin
>>     padding-left: max(12px, env(safe-area-inset-left));
   ------------------^
```

## Expected result

```css
@supports(padding: max(0px)) {
  .test {
    padding-left: max(12px, env(safe-area-inset-left));
    padding-right: max(12px, env(safe-area-inset-right));
  }
}
```

version info:
Same as used in SourceMap Inspector, linked above, libsass 3.5.0.beta.3.

First ran into error with:
```cmd
$ node-sass --version
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

## Why this should work

This is the recommended syntax by the WebKit team to adjust CSS for iPhone X, see:
https://webkit.org/blog/7929/designing-websites-for-iphone-x/

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
