### ISSUE TITLE
LibSass interprets `false` as non-false?

### ISSUE THREAD

**Issue by andyfriesen** [sass/libsass#254]
The following SCSS produces different output when run through sassc and scss (the Ruby implementation):

``` scss

@function compact($vars...) {
    $list: ();
    @each $var in $vars {
        @if $var {
            $list: append($list, $var, comma);
        }
    }
    @return $list;
}

div {
    $foo-1: notfalse;
    $foo-2: notfalse;
    $foo-3: false;

    $list: ();

    @if false {
        // Inline the compact function.
        // Ruby scss and libsass produce the same output if this codepath is used.
        $list: ($foo-1, $foo-2, $foo-3);
        @each $var in $list {
            @if $var {
                $list: append($list, $var, comma);
            }
        }

    } @else {
        // scss and libsass disagree what happens here.
        // scss considers a "false" when passed to a function as false.
        // libsass considers the "false" to actually be a truthy value
        // and appends another element to the list.
        //
        // With the Ruby implementation, the third argument is considered
        // to be "falsey" and $list recieves a list of length 2.
        //
        // When using libsass, the third argument is considered to be "truthy,"
        // resulting in a list that is 3 elements long.

        $list: compact(
            $foo-1,
            $foo-2,
            $foo-3
        );
    }

    @warn Final length is length($list);
}
```

Ruby output:

```
WARNING: Final length is 2
         on line 48 of /path/to/test.scss
```

libsass output:

```
WARNING: Final length is 3
     /path/to/test.scss:48
```
