### ISSUE TITLE
@page wrapped around a class will output the wrong selection

### ISSUE THREAD

**Issue by stephenbe** [sass/libsass#2548]
I know this is a tad weird because you should not need to wrap the @page selector in any situation, but we are wrapping bootstrap in a class. Bootstrap uses the page in the middle of a few selectors : 
https://github.com/twbs/bootstrap/blob/v4.0.0/scss/_print.scss#L86-L91

So when we do 

```scss
.abc {
  @import "print";
}
```

The css is compiled with the parent class, thus making the minification confused and break.

## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
.abc {
  @print {
    .random {
      color:red;
    }
    @page {
      size: a3;
    }
  }
}
```

## Actual results

[todo]: # (update version info!)

I am using node-sass 4.7.2
```css
@print {
  .abc .random {
    color: red;
  }
  @page {
    .abc {
      size: a3;
    }
  }
}

```

## Expected result
I just want the class to be stripped.

node-sass 4.7.2
```css
@print {
  .abc .random {
    color: red;
  }
  @page {
      size: a3;    
  }
}
```

version info:
```cmd
$ node-sass --4.7.2

**Comment by nschonni** [comment]
Did you try this with Ruby Sass?

**Comment by stephenbe** [comment]
I have not. Would you want me to try it and report back ?

**Comment by nschonni** [comment]
Yes please, because if Ruby has the same behaviour, it's a feature not a bug 😉

**Comment by stephenbe** [comment]
Lol but what does that mean? I don't know the history of ruby sass and it seems like you are alluring to something

**Comment by xzyfer** [comment]
```scss
// Ruby Sass
@print {
  .abc .random {
    color: red; }
  @page {
    .abc {
      size: a3; } } }

// Dart Sass
@print {
  .abc .random {
    color: red;
  }
  @page {
    .abc {
      size: a3;
    }
  }
}

// LibSass
@print {
  .abc .random {
    color: red; }
  @page {
    .abc {
      size: a3; } } }
```
