### ISSUE TITLE
CSS custom properties with HSL color definitions in scss do not compile

### ISSUE THREAD

**Issue by necccc** [sass/libsass#2552]
Using CSS custom properties with HSL color definitions in scss files cause an error when trying to compile it.

Example code:
## input.scss

```scss
.foo {
    --hue: 70;

    background-image: linear-gradient(
        hsl(var(--hue), 100%, 50%),
        hsl(0, 100%, 50%)
    );
}
```

## Actual results

libsass 3.5.0.beta.2

```bash
Error: argument `$hue` of `hsl($hue, $saturation, $lightness)` must be a number
```

## Expected result

ruby sass 3.5.5
```css
.foo {
  --hue: 70;
  background-image: linear-gradient(hsl(var(--hue), 100%, 50%), red); 
}
```

[todo]: # (update version info!)
[todo]: # (example for node-sass!)

version info:
```cmd
$ node-sass --version
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass 3.5.0.beta.2 (Sass Compiler) [C/C++]
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

http://libsass.ocbnet.ch/srcmap/#Ci5mb28gewogICAgLS1odWU6IDcwOwoKICAgIGJhY2tncm91bmQtaW1hZ2U6IGxpbmVhci1ncmFkaWVudCgKICAgICAgICBoc2wodmFyKC0taHVlKSwgMTAwJSwgNTAlKSwKICAgICAgICBoc2woMCwgMTAwJSwgNTAlKQogICAgKTsKfQ==
