### ISSUE TITLE
3.4.9: regression dividing away units

### ISSUE THREAD

**Issue by asottile** [sass/libsass#2560]
Originally reported: https://github.com/sass/libsass-python/issues/233

## input.scss

```scss
$x: 5px;
$y: $x / 14px;

a {
    font-size: #{$y} rem;
}
```

## Actual results

libsass 3.4.9
```console
$ pysassc test.scss 
pysassc: error: Error: 0.35714 isn't a valid CSS value.
        on line 2 of test.scss
>> $y: $x / 14px;

   ----^
```

## Expected result

[ruby sass 3.4.21](https://gist.github.com/asottile/b324b4784faf69c802b7054decd1b324)
```css
a {
  font-size: 0.35714 rem;
}
```

version info:
```cmd
$ pysassc --version
pysassc 0.13.7 (sass/libsass 3.4.9)
```
