### ISSUE TITLE
CSS custom properties with rgba cause an error

### ISSUE THREAD

**Issue by ArielGueta** [sass/libsass#2561]
Using CSS custom properties with rgba in scss files cause an error when trying to compile it.

Example code:

```css
.foo {
  color: rgba(var(--colorvar), 1)
}
```

> Error: argument `$color` of `rgba($color, $alpha)` must be a color

$ node-sass --version
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass 3.5.0.beta.2 (Sass Compiler) [C/C++]
