### ISSUE TITLE
Indented syntax loud comment formatting is different than Dart Sass

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2566]
There are a few cases where LibSass's formatting of loud comments in the indented syntax differs from Dart Sass's (and Ruby Sass's):

* Asterisks aren't added on each line. For example, for:

  ```sass
  /* foo
     bar
  ```

  Dart and Ruby Sass produce

  ```css
  /* foo
   * bar */
  ```

  but LibSass produces

  ```css
  /* foo
     bar */
  ```

* Comments that don't start on the same line as the opening `/*` have an empty line at the beginning. For example, for:

  ```sass
  /*
     foo
  ```

  Dart and Ruby Sass produce

  ```css
  /* foo */
  ```

  but LibSass produces

  ```css
  /*
     foo */
  ```

* Empty lines aren't preserved. For example, for:

  ```sass
  /* foo

     bar
  ```

  Dart and Ruby Sass produce

  ```css
  /* foo
   *
   * bar */
  ```

  but LibSass produces

  ```css
  /* foo
     bar */
  ```

I'm adding specs for this in sass/sass-spec#1215.

**Comment by nex3** [comment]
It's worth noting that these are aesthetic rather than semantic concerns, so if you feel like your output is better you're allowed to leave it as-is. But it's probably *better* to align the implementations where possible.

**Comment by mgreter** [comment]
Might be related to https://github.com/sass/libsass/issues/1026

**Comment by mgreter** [comment]
Can you elaborate a bit how the formatting works? I fail to see the logic behind it! 

# no intial indentation
```scss
div { a {
/*************
       * a
       * multiline
       * comment
       */
      top: 10px;
} }```
```css
div a {
  /*************
         * a
         * multiline
         * comment
         */
  top: 10px;
}
```

# three spaces as indentation
```scss
div { a {
   /*************
       * a
       * multiline
       * comment
       */
      top: 10px;
} }
```
```css
div a {
  /*************
      * a
      * multiline
      * comment
      */
  top: 10px;
}
```

# five spaces indentation
```scss
div { a {
     /*************
       * a
       * multiline
       * comment
       */
      top: 10px;
} }
```

```css
div a {
  /*************
    * a
    * multiline
    * comment
    */
  top: 10px;
}
```

# seven spaces indentation
```scss
div { a {
       /*************
       * a
       * multiline
       * comment
       */
      top: 10px;
} }
```
```css
div a {
  /*************
  * a
  * multiline
  * comment
  */
  top: 10px;
}
````

As you can see the lines following the initial comment have different indentation every time! But I have no clue what logic this follows!

**Comment by mgreter** [comment]
BTW. the test were made with scss syntax!

**Comment by mgreter** [comment]
I tested with dart-sass and ruby sass and it mostly seem to correspond:
One case where it differs is with ten spaces initial indentation:

```scss
div { a {
          /*************
       * a
       * multiline
       * comment
       */
      top: 10px;
} }
```
- ruby sass
```css
div a {
   /*************
* a
* multiline
* comment
*/
  top: 10px; }
```
- dart-sass:
```css
div a {
  /*************
  * a
  * multiline
  * comment
  */
  top: 10px;
}
```

**Comment by mgreter** [comment]
AFAIR LibSass only adjusts the initial line to indent according to the scope and keeps the rest as is.

**Comment by nex3** [comment]
For loud comments that come from SCSS, the *relative indentation* of each line of the comment should be preserved. In your examples in https://github.com/sass/libsass/issues/2566#issuecomment-373906449, the subsequent lines of the comment are indented seven, four, two, and zero levels deeper than the opening line, and that relative depth is preserved in the output when the entire comment is re-indented so that the shallowest line appears at the current indentation level.

In cases like https://github.com/sass/libsass/issues/2566#issuecomment-373906863, where the first line is deeper than the subsequent lines, it looks like neither Ruby nor Dart Sass handle that ideally. I'd expect this output:

```css
div a {
     /*************
  * a
  * multiline
  * comment
  */
  top: 10px; }
```

which preserves the relative indentation and places the shallowest line at the current indentation level. But I think these types of comments are unlikely to appear in practice, so I wouldn't sweat their formatting too much.
