### ISSUE TITLE
Possible to output invalid CSS with a @function

### ISSUE THREAD

**Issue by chriscoyier** [sass/libsass#2569]
## input.scss

```scss
@function test() {
  @if (false) {
    @return 0;
  } @else {
    opacity: 1;
  }
}

.my-module {
  opacity: test();
}
```

## Actual results

Libsass 3.5

```css
.my-module {
  opacity:   opacity: 1; }
```

## Expected result

Throw an error like 

> Functions can only contain variable declarations and control directives.

http://libsass.ocbnet.ch/srcmap/#QGZ1bmN0aW9uIHRlc3QoKSB7CiAgQGlmIChmYWxzZSkgewogICAgQHJldHVybiAwOwogIH0gQGVsc2UgewogICAgb3BhY2l0eTogMTsKICB9Cn0KCi5teS1tb2R1bGUgewogIG9wYWNpdHk6IHRlc3QoKTsKfQo=

Spec https://github.com/sass/sass-spec/pull/1218
