### ISSUE TITLE
Incorrect handling of `not` in media query

### ISSUE THREAD

**Issue by YodasWs** [sass/libsass#2576]
Not noticing at first a finer point about the `not` operator in a media query, I attempted the following:

## input.scss

```scss
input {
  @media not (pointer: fine) {
    background: red;
  }
}
```

## Actual results

[todo]: # (Use link [libsass 3.5.0.beta.2][1])

libsass 3.5.0.beta.2
```css
@media (pointer: fine) {
  input {
    background: red;
  }
}
```

:warning: Notice that libsass has removed the `not` operator! This is the exact opposite of what I wanted.

## Expected result

From [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media):
> If you use the `not` operator, you _must_ specify an explicit media type.

So the correct media query is in fact this:
```css
@media not screen and (pointer: fine) {
```

:information_source: I don't expect Sass or libsass to output the above, just an error would suffice.

## version info:
```cmd
$ node-sass --version
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/
