### ISSUE TITLE
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.

### ISSUE THREAD

**Issue by FezVrasta** [sass/libsass#2581]
## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss

@mixin bmd-form-color($label-color, $label-color-focus, $border-color) {
    // bg image is always there, we just need to reveal it
    &,
    .is-focused & {
      background-image: $underline-background-image;
    }

    &:invalid {
      background-image: $underline-background-image-invalid;
    }

    &:read-only {
      background-image: $underline-background-image-readonly;
    }

    @include bmd-disabled() {
      background-image: $underline-background-image-disabled;
      background-repeat: repeat-x;
      background-size: 3px 1px;
    }

    // allow underline focus image and validation images to coexist
    &.form-control-success {
      &,
      .is-focused & {
        background-image: $underline-background-image, $form-icon-success;
      }
    }
    &.form-control-warning {
      &,
      .is-focused & {
        background-image: $underline-background-image, $form-icon-warning;
      }
    }
    &.form-control-danger {
      &,
      .is-focused & {
        background-image: $underline-background-image, $form-icon-danger;
      }
    }
  }

  .is-focused,
  // may or may not be a form-group or bmd-form-group
  &.is-focused {
    // on focus set borders and labels to the validation color

    // Use the BS provided mixin for the bulk of the color
    @include form-validation-state("valid", $label-color);

    [class^='bmd-label'],
    [class*=' bmd-label'] {
      color: $label-color-focus;
    }

    .bmd-label-placeholder {
      color: $label-color; // keep the placeholder color
    }

    // Set the border and box shadow on specific inputs to match
    .form-control {
      border-color: $border-color;
    }

    // Set validation states also for addons
    //.input-group-addon {
    //  border-color: $border-color;
    //}

    .bmd-help {
      color: $bmd-label-color-inner-focus;
    }
  }
}
```

## Actual results

Error: Base-level rules cannot contain the parent-selector-referencing character '&'.

## Expected result

No errors

version info:
```cmd
$ node-sass --version
node-sass       4.8.2   (Wrapper)       [JavaScript]
libsass         latest   (Sass Compiler) [C/C++]
```

With 4.5.3 it worked just fine, now it throws this error, no major versions were released so I'm wondering what happened?

Originally reported here: https://github.com/FezVrasta/bootstrap-material-design/issues/1300
