### ISSUE TITLE
Futura drops unit in some additions

### ISSUE THREAD

**Issue by gilbsgilbs** [sass/libsass#2582]
Prior to Futura, adding `+ n em` to a numeric value would consistently cast the value to `em`. This is not always the case in Futura.  This sounds like an incorrect optimization or a breaking change. (I'm unsure whether the spec allows this optimization or not)

## input.scss

```scss
.foo { font-size: (16px / 16px) + 0em; }
```

## Actual results

[libsass 3.5.0][1]
```css
.foo {
  font-size: 1; }
```

## Expected result

```css
.foo {
  font-size: 1em; }
```

version info:
```cmd
$ node-sass --version
node-sass	4.8.1	(Wrapper)	[JavaScript]
libsass  	3.5.0	(Sass Compiler)	[C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#LmZvbyB7IGZvbnQtc2l6ZTogKDE2cHggLyAxNnB4KSArIDBlbTsgfQ==
