### ISSUE TITLE
Custom properties and variables breaking change

### ISSUE THREAD

**Issue by pascalduez** [sass/libsass#2585]
Hi,

where this previously worked, it's no longer the case from version 3.5.0, so this is a breaking change, and should be noted as such in the Changelog IMO.

## input.scss

```scss
$foo: blue;

:root {
  --foo: $foo;
}

.test {
  color: var(--foo);
}
```

## Actual results

[libsass 3.5.0][1]
```css
:root {
  --foo: $foo;
}

.test {
  color: var(--foo);
}
```

## Expected result

```css
:root {
  --foo: blue;
}

.test {
  color: var(--foo);
}
```

version info:
```cmd
$ node-sass --version

node-sass       4.8.1   (Wrapper)       [JavaScript]
libsass         3.5.0   (Sass Compiler) [C/C++]     
```

[1]: http://libsass.ocbnet.ch/srcmap/#JGZvbzogYmx1ZTsKCjpyb290IHsKICAtLWZvbzogJGZvbzsKfQoKLnRlc3QgewogIGNvbG9yOiB2YXIoLS1mb28pOwp9

Note escaping the Sass variable works, but BC... :)

```css
:root {
  --foo: #{$foo};
}

.test {
  color: var(--foo);
}
```

```css
:root {
  --foo: blue;
}

.test {
  color: var(--foo);
}
```
