### ISSUE TITLE
String interpolation doesn't work in CSS style comments (/* */)

### ISSUE THREAD

**Issue by matthew-andrews** [sass/libsass#259]
http://sassmeister.com/gist/8458935

Input:

``` sass
$test: #FFF1E0;

.test {
  background-color: $test;
  color: #{$test};
}

/* .test {
  background-color: $test;
  color: #{$test};
} */
```

Output from SASS 3.3.0.rc.1:-

``` css
.test {
  background-color: #fff1e0;
  color: #fff1e0;
}

/* .test {
  background-color: $test;
  color: #fff1e0;
} */
```

Output from SASS 3.2.13:-

``` css
.test {
  background-color: #fff1e0;
  color: #fff1e0;
}

/* .test {
  background-color: $test;
  color: #fff1e0;
} */
```

Output from Libsass

``` sass
.test {
  background-color: #fff1e0;
  color: #fff1e0; }

/* .test {
  background-color: $test;
  color: #{$test};
} */
```

This probably isn't the highest priority bug in the world but it is inconsistent with sass :-).  (Some credit to @orangemug for finding this)
