### ISSUE TITLE
Applying darken function gives different result in libsass 3.5.0 and sass 3.4.21

### ISSUE THREAD

**Issue by 40in** [sass/libsass#2604]
[todo]: # (This is only a template!)
[todo]: # (remove unneeded bits)
[todo]: # (use github preview!)

Here is the full Gist of the range colors `#FFFFFF - #EEEEEE`: [libsas](https://gist.github.com/40in/6c58a95745b9e1ae5d3b12f7834a0742) and [sass](https://gist.github.com/40in/199cd182142ec969eecb7cf8905fa198) versions

The same example without `darken` function gives all white, thus expected result here is the same output color. In fact, we have 2 different values going back and forth.

## input.scss
```scss
test {
  border-top-color: darken(lighten(desaturate(#ffffff, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#fefefe, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#fdfdfd, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#fcfcfc, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#fbfbfb, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#fafafa, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#f9f9f9, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#f8f8f8, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#f7f7f7, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#f6f6f6, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#f5f5f5, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#f4f4f4, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#f3f3f3, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#f2f2f2, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#f1f1f1, 15.7%), 33.5%), 14.625%);
  border-top-color: darken(lighten(desaturate(#f0f0f0, 15.7%), 33.5%), 14.625%);
}
```

## Actual results

[libsass v3.5.2][1]
```css
test {
  border-top-color: #dadada;
  border-top-color: #dadada;
  border-top-color: #dadada;
  border-top-color: #b4ffff;
  border-top-color: #dadada;
  border-top-color: #b4ffff;
  border-top-color: #dadada;
  border-top-color: #b4ffff;
  border-top-color: #dadada;
  border-top-color: #b4ffff;
  border-top-color: #b4ffff;
  border-top-color: #dadada;
  border-top-color: #dadada;
  border-top-color: #b4ffff;
  border-top-color: #b4ffff;
  border-top-color: #dadada;
}
```

## Expected result

sass v3.4.21
```css
test {
  border-top-color: #dadada;
  border-top-color: #dadada;
  border-top-color: #dadada;
  ...
  border-top-color: #dadada; 
}
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#QGltcG9ydCAiaHR0cDovL2Nkbi5yYXdnaXQuY29tL3Rob3VnaHRib3QvYm91cmJvbi9tYXN0ZXIvYXBwL2Fzc2V0cy9zdHlsZXNoZWV0cy9ib3VyYm9uIjsKCi5zcGVjaWFsIHsKYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZmZmZmZmLCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZmVmZWZlLCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZmRmZGZkLCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZmNmY2ZjLCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZmJmYmZiLCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZmFmYWZhLCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZjlmOWY5LCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZjhmOGY4LCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZjdmN2Y3LCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZjZmNmY2LCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZjVmNWY1LCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZjRmNGY0LCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZjNmM2YzLCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZjJmMmYyLCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZjFmMWYxLCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7CiAgYm9yZGVyLXRvcC1jb2xvcjogZGFya2VuKGxpZ2h0ZW4oZGVzYXR1cmF0ZSgjZjBmMGYwLCAxNS43JSksIDMzLjUlKSwgMTQuNjI1JSk7Cn0=

**Comment by mgreter** [comment]
Thanks, here a better test case showing the underlying issue:
```scss
test {
  $col: desaturate(#fcfcfc, 15.7%);
  test-col: desaturate($col, 15.7%);
  test-hut: hue(lighten($col, 33.5%));
  test-sat: saturation(lighten($col, 33.5%));
  test-lig: lightness(lighten($col, 33.5%));
  test-hsl: darken(hsl(0deg, 0%, 100%), 14.625%);
  combined: darken(lighten($col, 33.5%), 14.625%);
}
```
