### ISSUE TITLE
Arithmetic fails on interpolated values

### ISSUE THREAD

**Issue by sovanyio** [sass/libsass#2605]
This issue has been mitigated in my project by using `$em * 1em` rather than interpolating the string, but I think it is reasonable to expect arithmetic to work on an interpolated value.

## input.scss

```scss
$s-typography--base-font-size: 16px;

@function tool-px-to-em($size, $base: $s-typography--base-font-size) {
  @if tool-is-pixel-value($size) {
    $em: $size / $base; // assuming this is the base font-size
    @return #{$em}em;
  } @else {
    // scss-lint:disable DebugStatement
    @debug 'Wrong type specified for value "#{$size}". Did you use px?'
  }
}

$s-units--base-spacing: tool-px-to-em(6px); 

.test-o-container {
  width: 100%;
  padding-left: 3 * $s-units--base-spacing;
  padding-right: 3 * $s-units--base-spacing;
}
```

## Actual results
```css
Error in plugin 'sass'
Message:
    path/to/_file.scss
Error: Undefined operation: "3 times 0.375em".
        on line 18 of path/to/_file.scss
        from line 15 of path/to/parent.scss
>>   padding-left: 3 * $s-units--base-spacing;
```

## Expected result

[todo]: # (update version info!)

libsass 3.5.2 using $em * 1em in @function tool-px-to-em
```css
.test-o-container {
  width: 100%;
  padding-left: 1.125em;
  padding-right: 1.125em; }
```

version info:
```cmd
$ node-sass --version
node-sass       4.8.3   (Wrapper)       [JavaScript]
libsass         3.5.2   (Sass Compiler) [C/C++]
```

No libsass.ocbnet.ch link due to the above code not compiling.
