### ISSUE TITLE
Variables can not be used directly

### ISSUE THREAD

**Issue by VdustR** [sass/libsass#2609]
## input.scss

```scss
$value: #111;
:root {
  --abc: $value;
}
```

## Actual results
```css
:root {
  --abc: $value; }
```

## Expected result
```css
:root {
  --abc: #111; }
```

version info:
`node-sass >= 4.8.1` got issue,
`node-sass <= 4.7.2` works fine

I can write scss like this to fix this temporary:
```scss
$value: #111;
:root {
  --abc: #{$value};
}
```

but according to [sass-lang guide](https://sass-lang.com/guide), variable should be able to be used directly.

* Related to https://github.com/vuematerial/vue-material/issues/1619
