### ISSUE TITLE
CSS custom properties(variables) not rendered correctly in libsass 3.5.2

### ISSUE THREAD

**Issue by simongcc** [sass/libsass#2620]
The sass $variable is not recognized and being output directly in the libsas 3.5.2.
Details as follow:

## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
$theme-primary: 0,0,0;
:root {
  --TEST: $theme-primary;

  // example use case
  // background: RGBA(var(--TEST), 0.7); // where RGBA is in capital letter as work around suggested in #2244
}
```
Reference: [#2244]

## Actual results

[todo]: # (update version info!)

[libsass 3.5.2][1]
```css
:root {
  --TEST: $theme-primary;
}
```

## Expected result

[libsass 3.5.0.beta.2][1]
```css
:root {
  --TEST: 0, 0, 0;
}
```

[todo]: # (update version info!)
[todo]: # (example for node-sass!)

version info:
```cmd
$ node-sass --version
node-sass	4.8.3	(Wrapper)	[JavaScript]
libsass  	3.5.2	(Sass Compiler)	[C/C++]
```

Last known good version
```cmd
$ node-sass --version
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
