### ISSUE TITLE
Regression in :not()

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2630]
Originally reported in https://github.com/sass/node-sass/issues/2330

This is a regression between 3.5.0.beta.2 and 3.5.0.

*Note:* Formatted for readability.

## input.scss

```scss
.btn,
.button {
  &.disabled:not(&-default):not(&-outline),
  &:disabled:not(&-default):not(&-outline) {
    background: #fefefe !important;
    color: #111111 !important;
  }
}
```

## LibSass 3.5.0+

```css
.btn.disabled, 
.btn:disabled,
.button.disabled,
.button:disabled 
{
  background: #fefefe !important;
  color: #111111 !important; 
}
```

## LibSass 3.5.0.beta.2
Semantically correct but with duplicate selectors in `:not()`

```css
.btn.disabled
  :not(.btn-default, .button-default, .btn-default, .button-default)
  :not(.btn-outline, .button-outline, .btn-outline, .button-outline), 
.btn:disabled
  :not(.btn-default, .button-default, .btn-default, .button-default)
  :not(.btn-outline, .button-outline, .btn-outline, .button-outline), 
.button.disabled
  :not(.btn-default, .button-default, .btn-default, .button-default)
  :not(.btn-outline, .button-outline, .btn-outline, .button-outline),
.button:disabled
  :not(.btn-default, .button-default, .btn-default, .button-default)
  :not(.btn-outline, .button-outline, .btn-outline, .button-outline) 
{
  background: #fefefe !important;
  color: #111111 !important; 
}
```

## Expected result

Dart Sass
```css
.btn.disabled
  :not(.btn-default, .button-default)
  :not(.btn-outline, .button-outline), 
.btn:disabled
  :not(.btn-default, .button-default)
  :not(.btn-outline, .button-outline),
.button.disabled
  :not(.btn-default, .button-default)
  :not(.btn-outline, .button-outline),
.button:disabled
  :not(.btn-default, .button-default)
  :not(.btn-outline, .button-outline) 
{
  background: #fefefe !important;
  color: #111111 !important;
}
```

**Comment by juliancarrivick** [comment]
If it helps, I think I'm being hit by a similar (same?) bug with using `:not()` with nested elements. I would expect that the following Sass: 
``` sass
.parent:not(.a, .b) {
    color: blue;

    .child {
        color: red;
    }
}
```
would compile to the following:
``` css
.parent:not(.a, .b) {
  color: blue;
}
.parent:not(.a, .b) .child {
  color: red;
}
```
However, using libsass it outputs:
``` css
.parent:not(.a, .b) {
  color: blue;
}

.parent .child {
  color: red;
}
```

It seems to be an issue with the multiple elements in the `:not()` clause because when I compile it with a single selector in the `:not()` it outputs correctly:
``` sass
.parent:not(.a) {
    color: blue;

    .child {
        color: red;
    }
}
```
Compiles to:
``` css
.parent:not(.a) {
  color: blue;
}

.parent:not(.a) .child {
  color: red;
}
```

I verified this using https://www.sassmeister.com/ (nice little tool!).

**Comment by timomayer** [comment]
Will this be fixed soon? It breaks some of our projects

**Comment by glebm** [comment]
I think this has been fixed by #2736.

Here is the output I get now for the first example in the original post:

```css
.btn.disabled:not(.btn-default,
.button-default):not(.btn-outline,
.button-outline), .btn:disabled:not(.btn-default,
.button-default):not(.btn-outline,
.button-outline),
.button.disabled:not(.btn-default,
.button-default):not(.btn-outline,
.button-outline),
.button:disabled:not(.btn-default,
.button-default):not(.btn-outline,
.button-outline) {
  background: #fefefe !important;
  color: #111111 !important; }
```
