### ISSUE TITLE
Segfault with @extends

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2632]
Reported via HackerOne. 

The parser should have bailed out long before it selector was extended. I did some quick digging and the segfault is not in the extend path, but due to the resulting `Complex_Selector` node.

## input.scss

```scss
a(b(x)) {
  color: red;
  @extend x;
}
```

## Actual results

LibSass 3.5.2
```css
test {
  content: bar; }
```

## Expected result

Ruby Sass 3.5
```css
Error: Invalid CSS after "a": expected selector, was "(b(x))"
        on line 1 of test.scss
  Use --trace for backtrace.
```
