### ISSUE TITLE
selector-unify: Wrong result if selector contains relationship combinator

### ISSUE THREAD

**Issue by Feuerfuchs** [sass/libsass#2633]
selector-unify seems unable to handle selectors that contain relationship combinators such as '+', '~' or '>'. It doesn't matter if that's the case for just one of the selectors or both.

## input.scss

```scss
$sel1: '.something__child + .something__child--mod1';
$sel2: '.something__child ~ .something__child--mod2';
$result1: selector-unify($sel1, $sel2);

#{$result1} {
  /* nothing */
}
```

## Actual results

[libsass 3.5.2][1]
```css
+ .something__child--mod1 .something__child ~ .something__child--mod2 .something__child--mod1.something__child--mod2, ~ .something__child--mod2 .something__child--mod1.something__child--mod2 .something__child + .something__child--mod1 {
  /* nothing */
}
```

## Expected result

ruby sass 3.4.21
```css
.something__child + .something__child--mod1.something__child--mod2 {
  /* nothing */
}
```

version info:
```cmd
$ node-sass --version
node-sass       4.8.3   (Wrapper)       [JavaScript]
libsass         3.5.2   (Sass Compiler) [C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#JHNlbDE6ICcuc29tZXRoaW5nX19jaGlsZCArIC5zb21ldGhpbmdfX2NoaWxkLS1tb2QxJzsKJHNlbDI6ICcuc29tZXRoaW5nX19jaGlsZCB+IC5zb21ldGhpbmdfX2NoaWxkLS1tb2QyJzsKJHJlc3VsdDE6IHNlbGVjdG9yLXVuaWZ5KCRzZWwxLCAkc2VsMik7CgojeyRyZXN1bHQxfSB7CiAgLyogbm90aGluZyAqLwp9Cg==

**Comment by lunelson** [comment]
I've run in to this too, and noticed there is at least one combination which will cause a crash. I've made a repo for this test case, but the results are also copied below.

https://github.com/lunelson/node-sass-selector-unify-test

First, this compiles incorrectly:

```scss
.a {
  color: blue;
  & > * {
    @at-root #{selector-unify(&, '.b')} {
      color: red;
    }
  }
}
```
```css
/* dart-sass / ruby-sass result */

.a {
  color: blue;
}
.a > .b {
  color: red;
}
```
```css
/* libsass result */

.a {
  color: blue;
}

*.b .a > {
  color: red;
}
```
And this will cause the compiler to crash:
```scss
.a, .b {
  color: blue;
  & > * {
    @at-root #{selector-unify(&, '.c, .d')} {
      color: red;
    }
  }
}
```
```css
/* dart-sass / ruby-sass result */
.a, .b {
  color: blue;
}
.a > .c, .a > .d, .b > .c, .b > .d {
  color: red;
}
```
```sh
# libsass crash result
Assertion failed: (l_last_head && "lhs head is null"), function unify_with, file ../src/libsass/src/ast.cpp, line 1005.
Abort trap: 6
```
