### ISSUE TITLE
Using selector-nest inside @at-root modifies &

### ISSUE THREAD

**Issue by Feuerfuchs** [sass/libsass#2634]
## input.scss

```scss
.something {
  @at-root .something__child {
    /* nothing */
        
    &:hover {
      /* nothing */
      
      $noop: selector-nest(&, '.something__child--mod');
      
      & {
        /* nothing */
      }
    }
  }
}
```

This input probably looks like it makes no sense, but it captures what my BEM mixins produce: A lot of nested `@at-root` directives and selector-nest calls. This is just the most compact example that triggers the bug.

The result will become correct if you:
- remove the `$noop: ...` line. (!!!)
- move `.something__child` to its own rule without `@at-root`.
- prefix `&:hover` with an `@at-root`.

The & selector after `$noop: ...` can be any other selector, I just wanted to emphasize the fact that & clearly gets modified by selector-nest. The result of selector-nest is also affected.

## Actual results

[libsass 3.5.2][1]
```css
.something__child {
  /* nothing */
}

.something__child:hover {
  /* nothing */
}

.something__child .something__child:hover {
  /* nothing */
}
```

## Expected result

[todo]: # (update version info!)

ruby sass 3.4.21
```css
.something__child {
  /* nothing */
}
.something__child:hover {
  /* nothing */
}
.something__child:hover {
  /* nothing */
}
```

version info:
```cmd
$ node-sass --version
node-sass       4.8.3   (Wrapper)       [JavaScript]
libsass         3.5.2   (Sass Compiler) [C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#LnNvbWV0aGluZyB7CiAgQGF0LXJvb3QgLnNvbWV0aGluZ19fY2hpbGQgewogICAgLyogbm90aGluZyAqLwogICAgICAgIAogICAgJjpob3ZlciB7CiAgICAgIC8qIG5vdGhpbmcgKi8KICAgICAgCiAgICAgICRub29wOiBzZWxlY3Rvci1uZXN0KCYsICcuc29tZXRoaW5nX19jaGlsZC0tbW9kJyk7CiAgICAgIAogICAgICAmIHsKICAgICAgICAvKiBub3RoaW5nICovCiAgICAgIH0KICAgIH0KICB9Cn0K
