### ISSUE TITLE
Custom properties with Sass variables not compiling

### ISSUE THREAD

**Issue by gcmznt** [sass/libsass#2635]
It seems that the compiler is not working correctly when assigning a scss variable to a css custom props.
With string interpolation on property name or around scss variable it works as expected.

I have found the regression passing from `node-sass 4.7.2` to `node-sass 4.8.1`

## input.scss

```scss
test {
  $test: red;

  background: $test;
  --background: $test;
  --background: #{$test};
  #{'--background'}: $test;
}
```

## Actual results

[libsass 3.5.0][1]

```cmd
node-sass	4.8.1	(Wrapper)	[JavaScript]
libsass  	3.5.0	(Sass Compiler)	[C/C++]
```

```css
.header {
  background: red;
  --background: $test;
  --background: red;
  --background: red; }
```

## Expected result

```cmd
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

```css
.header {
  background: red;
  --background: red;
  --background: red;
  --background: red; }
```

[1]: http://libsass.ocbnet.ch/srcmap/#LmhlYWRlciB7CiAgJHRlc3Q6IHJlZDsKCiAgYmFja2dyb3VuZDogJHRlc3Q7CiAgLS1iYWNrZ3JvdW5kOiAkdGVzdDsKICAtLWJhY2tncm91bmQ6ICN7JHRlc3R9OwogICN7Jy0tYmFja2dyb3VuZCd9OiAkdGVzdDsKfQoK
