### ISSUE TITLE
selector-nest produces duplicates if parent selector consists of multiple parts

### ISSUE THREAD

**Issue by Feuerfuchs** [sass/libsass#2640]
To trigger this bug, just use a selector that consists of multiple parts (so something like `.class1, .class2`) as first argument for `selector-nest`. The function will act as if the parent selector contained all parts twice, and so the result consists of duplicates.

## input.scss

```scss
.theme1, .theme2 {
  .something {
    /* nothing */
  }
}

$sel: selector-nest('.theme1, .theme2', '.something');
  
#{$sel} {
  /* nothing */
}
```

## Actual results

[libsass 3.5.4][1]
```css
.theme1 .something, .theme2 .something {
  /* nothing */
}

.theme1 .something, .theme2 .something, .theme1 .something, .theme2 .something {
  /* nothing */
}
```

## Expected result

ruby sass 3.4.25
```css
.theme1 .something, .theme2 .something {
  /* nothing */
}

.theme1 .something, .theme2 .something {
  /* nothing */
}
```

version info:
```cmd
$ node-sass --version
node-sass       4.9.0   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#LnRoZW1lMSwgLnRoZW1lMiB7CiAgLnNvbWV0aGluZyB7CiAgICAvKiBub3RoaW5nICovCiAgfQp9Cgokc2VsOiBzZWxlY3Rvci1uZXN0KCcudGhlbWUxLCAudGhlbWUyJywgJy5zb21ldGhpbmcnKTsKICAKI3skc2VsfSB7CiAgLyogbm90aGluZyAqLwp9
