### ISSUE TITLE
CSS custom property value is not interpolated

### ISSUE THREAD

**Issue by MichalErlebach** [sass/libsass#2641]
See this example:

## input.scss

```scss
div {
  $VAR: red;
  --color: $VAR;
  color: $VAR;
}
```

## Actual results

[libsass 3.5.3][1]
```css
div {
  --color: $VAR;
  color: red;
}
```

## Expected result

ruby sass 3.4.25
```css
div {
  --color: red;
  color: red;
}
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#ZGl2IHsKICAkVkFSOiByZWQ7CiAgLS1jb2xvcjogJFZBUjsKICBjb2xvcjogJFZBUjsKfQ==
