### ISSUE TITLE
Addition pixel value from map with pixel value does not sum up anymore

### ISSUE THREAD

**Issue by marvinhuebner** [sass/libsass#2647]
After upgrading to libsass 3.5.0 it is no longer possible to sum up a value from a map together with a pixel value

## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
$breakpoints: (
  md: 992px,
  lg: 1200px
);

@mixin minimal-desktop {
  @media (min-width: #{map-get($breakpoints, lg)} + 1px) {
    @content;
  }
}

@debug #{map-get($breakpoints, lg)} + 1px;

@include minimal-desktop {
  .test {
    background: red;
  }
}
```

## Actual results

[libsass 3.5.0][1]
```css
@media (min-width: 1200px + 1px) {
  .test {
    background: red;
  }
}
```

## Expected result

[todo]: # (update version info!)

libsass 3.5.0.beta.2
```css
@media (min-width: 1201px) {
  .test {
    background: red;
  }
}
```

version info:
```cmd
$ node-sass --version
node-sass       4.9.0   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#JGJyZWFrcG9pbnRzOiAoCiAgbWQ6IDk5MnB4LAogIGxnOiAxMjAwcHgKKTsKCkBtaXhpbiBtaW5pbWFsLWRlc2t0b3AgewogCUBtZWRpYSAobWluLXdpZHRoOiAje21hcC1nZXQoJGJyZWFrcG9pbnRzLCBsZyl9ICsgMXB4KSB7CiAgICAJQGNvbnRlbnQ7CiAgCX0KfQoKQGRlYnVnICN7bWFwLWdldCgkYnJlYWtwb2ludHMsIGxnKX0gKyAxcHg7CgpAaW5jbHVkZSBtaW5pbWFsLWRlc2t0b3AgewogIC50ZXN0IHsKICAgIGJhY2tncm91bmQ6IHJlZDsKICB9Cn0KCkBtZWRpYSAobWluLXdpZHRoOiAxMjAwcHggKyAxcHgpIHsKICAudGVzdCB7CiAgICBiYWNrZ3JvdW5kOiByZWQ7CiAgfQp9
