### ISSUE TITLE
LibSass should not import files without an extension

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2672]
If I have these files:

```scss
// test.scss
@import "other"

// other
a {b: c}
```

Ruby Sass and Dart Sass will fail to import `other`, but LibSass will import it as SCSS. This is incorrect behavior (since there's no way to tell which syntax the user intends to use), and it should be deprecated and eventually removed.
