### ISSUE TITLE
Sass Variables need interpolation inside CSS variables

### ISSUE THREAD

**Issue by sturobson** [sass/libsass#2685]
Original source of issue:

https://codepen.io/leaverou/pen/ZRPqMZ?editors=0100#0

https://twitter.com/LeaVerou/status/1014046898670333952

## input.scss

```scss
$magenta: hsl(330, 100%, 50%);

div {
	color: $magenta;
	--color: $magenta;
	--color: #{$magenta};
}
```

## Actual results

[todo]: # (update version info!)

[libsass 3.5.3][1]
```css
div {
  color: #ff0080;
  --color: $magenta;
  --color: #ff0080;
}
```

## Expected result

[todo]: # (update version info!)

ruby Sass 3.4.2
```css
div {
  color: #ff0080;
  --color: #ff0080;
  --color: #ff0080;
}
```

## Other Sass Versions 

Ruby Sass 3.5.5 [issue here](https://github.com/sass/sass/issues/2532)

```css
div {
  color: #ff0080;
  --color: $magenta;
  --color: #ff0080;
}
```

Dart Sass 1.6.2 [issue here](https://github.com/sass/dart-sass/issues/396)

```css
div {
  color: #ff0080;
  --color: $magenta;
  --color: #ff0080;
}
```

(above tested via Sassmeister)

http://libsass.ocbnet.ch/srcmap/#JG1hZ2VudGE6IGhzbCgzMzAsIDEwMCUsIDUwJSk7CgpkaXYgewoJY29sb3I6ICRtYWdlbnRhOwoJLS1jb2xvcjogJG1hZ2VudGE7CgktLWNvbG9yOiAjeyRtYWdlbnRhfTsKfQ==
