### ISSUE TITLE
Carriage return left in CSS when compiling multiline rules on windows

### ISSUE THREAD

**Issue by c99pjn** [sass/libsass#2693]
[todo]: # (Title: Be as meaningful as possible)
[todo]: # (Title: Try to use 60 or less chars)

[todo]: # (This is only a template!)
[todo]: # (remove unneeded bits)
[todo]: # (use github preview!)

## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
item {
  padding-left: calc(
    24px
  )
}
```

With control characters

```scss
item {<CR><LF>
  padding-left: calc(<CR><LF>
    24px<CR><LF>
  )<CR><LF>
}
```

## Actual results (as printed in cmd)

[todo]: # (update version info!)

[libsass 3.5.2-72-g38f4-dirty][1]
sassc 3.4.8-5-g6a64-dirty

```css
item {
 24px); }-left: calc(
```

Written to file with control characters

```css
item{padding-left:calc(<CR>
 24px)}<LF>
```

## Expected result

[todo]: # (update version info!)

```css
item{padding-left:calc(24px)} <LF>
```

[todo]: # (update version info!)
[todo]: # (example for node-sass!)

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
