### ISSUE TITLE
Incorrect media query merging edge case

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2695]
The following input:

```scss
@media print {
  @media not screen and (color) {x {y: z}}
}
```

produces `@media print and (color)`, where it should just produce `@media print`, since the `not` in `not screen and (color)` applies to `(color)` as well as `screen`.
