### ISSUE TITLE
`:not()` clause ignored completely

### ISSUE THREAD

**Issue by adamreisnz** [sass/libsass#2697]
This has started failing once we updated `gulp-sass` which indirectly updated `libsass` to 3.5.4.

## input.scss
```scss
.Card {
  &:not(.is-open, .is-static) {
    .CardContents {
      display: none;
    }
  }
}
```

## Actual results

[libsass 3.5.3][1]
```css
.Card .CardContents {
    display: none;
}
```

## Expected result

E.g. [DartSass 1.6.2, Sass 3.5.6](https://www.sassmeister.com/):
```css
.Card:not(.is-open, .is-static) .CardContents {
  display: none;
}
```

version info: I don't have the CLI versions installed to output the version, as we're using gulp-sass. But the problem is easily reproducible with libsass.ocbnet.ch or sassmeister.com.

[1]: http://libsass.ocbnet.ch/srcmap/#LkNhcmQgewogICY6bm90KC5pcy1vcGVuLCAuaXMtc3RhdGljKSB7CiAgICAuQ2FyZENvbnRlbnRzIHsKICAgICAgZGlzcGxheTogbm9uZTsKICAgIH0KICB9Cn0=
