### ISSUE TITLE
..fr/px isn't a valid CSS value

### ISSUE THREAD

**Issue by liubko** [sass/libsass#2706]
Can't use variables in `grid-template` after `/`

## input.scss

```scss
$toolbox-width: 220px;
.App {
  grid-template:
    "header  header  header" 48px
    "toolbox content setting" 1fr
    / $toolbox-width 1fr 260px;
}
```

## Actual results

[libsass 3.5.3][1]
```css
0.0045454545fr/px isn't a valid CSS value.
  stdin 4:5  root stylesheet on line 4 at column 5
```

## Expected result

ruby sass 3.5.3
```css
.App {
  grid-template: "header  header  header" 48px "toolbox content setting" 1fr/220px 1fr 260px;
}
```

version info:
```cmd
$ node-sass --version
node-sass       4.9.2   (Wrapper)       [JavaScript]
```

[1]: http://libsass.ocbnet.ch/srcmap/#JHRvb2xib3gtd2lkdGg6IDIyMHB4OwouQXBwIHsKICBncmlkLXRlbXBsYXRlOgogICAgImhlYWRlciAgaGVhZGVyICBoZWFkZXIiIDQ4cHgKICAgICJ0b29sYm94IGNvbnRlbnQgc2V0dGluZyIgMWZyCiAgICAvICR0b29sYm94LXdpZHRoIDFmciAyNjBweDsKfQ==
