### ISSUE TITLE
placeholder renders if defined twice

### ISSUE THREAD

**Issue by jamesarosen** [sass/libsass#2712]
If a file containing CSS rules imports a file containing only placeholders that has already been imported, the rules are rendered by both the placeholder file and the CSS file. Note that I'm not importing a file containing any CSS twice.

## input.scss

```scss
// top.scss
@import './placeholder';
/* in-between */
@import './utility';
```

```scss
// _placeholder.scss
%green { color: green; }
```

```scss
// _utility.scss
@import './placeholder'; // omitting this eliminates the duplication in output
.green { @extend %green; }
```

## Actual results

```bash
$ node_modules/node-sass/bin/node-sass top.scss
```

```css
.green {
  color: green; }

/* in-between */
.green {
  color: green; }
```

## Expected result

```css
/* in-between */
.green {
  color: green; }
```

version info:
```cmd
$ node_modules/node-sass/bin/node-sass --version
node-sass	4.9.3	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
```

**Comment by jamesarosen** [comment]
Adding an unused placeholder has no effect on output:
```scss
// _placeholder.scss
%green { color: green; }
%purple { color: purple; }
```
```css
.green {
  color: green; }

.green {
  color: green; }
```

**Comment by jamesarosen** [comment]
Defining the placeholder twice and doing no imports has the same effect:
```scss
// top.scss
%green { color: green; }
%green { color: green; }
.green { @extend %green; }
```
```css
.green {
  color: green; }

.green {
  color: green; }
```

**Comment by jamesarosen** [comment]
Adding some comments shows that the CSS is being emitted by the placeholder both times and never by the actual CSS rule.

### Input
```scss
/* a */
%green { color: green; }
/* b */
%green { color: green; }
/* c */
.green { @extend %green; }
/* d */
```

#### Actual Output
```css
/* a */
.green {
  color: green; }

/* b */
.green {
  color: green; }

/* c */
/* d */
```

#### Expected Output
```css
/* a */
/* b */
/* c */
.green {
  color: green; }
/* d */
```

**Comment by nschonni** [comment]
Didn't try with separate files yet, but I see the same results for the Reference Ruby version (although selector order is different).

**Comment by xzyfer** [comment]
I think the behaviour is intended. Can you confirm by trying with dart-sass?

**Comment by jamesarosen** [comment]
> Can you confirm by trying with dart-sass?

```bash
$ node_modules/.bin/sass --version
1.13.0 compiled with dart2js 2.0.0
```
```css
$ node_modules/.bin/sass top.scss
/* a */
.greener, .green {
  color: green;
}

/* b */
.greener, .green {
  color: green;
}

/* c */
.greener {
  font-weight: bold;
}

/* d */
```

> I think the behaviour is intended.

From the [sass-lang documentation](https://sass-lang.com/documentation/file.SASS_REFERENCE.html#placeholder_selectors_foo):

> On their own, without any use of @extend, rulesets that use placeholder selectors will not be rendered to CSS.

That's ambiguous and I can see how one interpretation might be

> placeholder selectors render in-place when rulesets reference them

But I think it would be equally valid to assume they act like mixins:

```scss
/* a */
@mixin green { color: green; }
/* b */
@mixin green { color: green; }
/* c */
.green { @include green; }
.greener { @include green; font-weight: bold; }
/* d */
```

```css
$ node_modules/.bin/sass top.scss
/* a */
/* b */
/* c */
.green {
  color: green;
}

.greener {
  color: green;
  font-weight: bold;
}

/* d */
```
