### ISSUE TITLE
Precision Should Apply to All Numbers

### ISSUE THREAD

**Issue by bdkjones** [sass/libsass#2718]
See: https://github.com/sass/sass/issues/2562#issuecomment-422888741

@nex3 states that the reason the precision option didn’t apply to static values was originally to improve performance in the Ruby implementation of Sass. She suggests that Libsass change precision to affect all numbers, not just those produced by math operations.

**Comment by bdkjones** [comment]
Related issue with examples: #2717

**Comment by mgreter** [comment]
This seems to be fixed by now (probably by https://github.com/sass/libsass/pull/2789). IMO static values cannot gain anything from being evaluated. I believe this is indirectly reporting the same bug as @nex3 did in https://github.com/sass/libsass/issues/2788. I currently get the following for you linked example:

```css
#myDiv {
  width: 1.234858939558593rem;
  height: 1.4482873633;
  margin-top: 5.58585938428; }
```

Please reopen if you can reproduce with latest master.
