### ISSUE TITLE
error when using filter:chroma

### ISSUE THREAD

**Issue by joelanman** [sass/libsass#274]
``` css
input[type=submit],
input[type=reset],
input[type=button]
{
       filter:chroma(color=#000000);
}
```

this IE fix raises an error in libsass:

```
error reading values after color
```
