### ISSUE TITLE
Wrong line calculation when multi-line comments and imports are present

### ISSUE THREAD

**Issue by lucascosta** [sass/libsass#284]
I'm getting some pretty weird behaviour on the souce line calculation when comments and imports are present. It seems to depend on the number of lines of the comment...

``` css
/* 1
2
3
4
5 Line mapping for ".main-content p": style.scss:6 */
.main-content p { color: red; }
@import 'assets/_font';
```

``` css
/* 1
2
3
4
5
6 Line mapping for ".main-content p": _font.scss:2 */
.main-content p { color: red; }
@import 'assets/_font';
```
