### ISSUE TITLE
content-exists() is not working.

### ISSUE THREAD

**Issue by chriseppstein** [sass/libsass#2842]
I get this error if the function `content-exists()` is in the mixin, whether or not the mixin is invoked.

## input.scss

```scss
@mixin test-content-exists() {
  @if content-exists() {
    @content;
  }
  @else {
    content: missing;
  }
}

.foo {
  @include test-content-exists();
}

.bar {
  @include test-content-exists() {
    content: present;
  }
}
```

## Actual results

[libsass 3.5.2][1]
```
Cannot call content-exists() except within a mixin. on line 2 at column 7
```

## Expected result

[todo]: # (update version info!)

ruby sass 3.5.6
```css
.foo {
  content: missing;
}

.bar {
  content: present;
}
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==
