### ISSUE TITLE
Can't use css variables within rgb() and rgba()

### ISSUE THREAD

**Issue by finnhvman** [sass/libsass#2878]
node-sass throws an error on valid CSS when using var() in rgb() or rgba(), most probably an issue in libsass

[Issue in node-sass](https://github.com/sass/node-sass/issues/2610)

## input.scss

```scss
.test {
  --my-var: 255, 0, 0;
  color: rgb(var(--my-var));
}
```

## Actual results

node-sass 4.11.0  libsass 3.5.4
```
{ Error: Function rgb is missing argument $green.
    at options.error (/Users/bszabo/WS/sass-test/node_modules/node-sass/lib/index.js:291:26)
  status: 1,
  file: '/Users/bszabo/WS/sass-test/test.scss',
  line: 3,
  column: 10,
  message: 'Function rgb is missing argument $green.',
  formatted: 'Error: Function rgb is missing argument $green.
        on line 3 of test.scss
>>   color: rgb(var(--my-var));
   ---------^
' }
```

## Expected result

dart-sass 1.17.4
```css
.test {
  --my-var: 255, 0, 0;
  color: rgb(var(--my-var));
}
```

version info:
```cmd
$ node-sass --version
node-sass       4.11.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```
