### ISSUE TITLE
:any() pseudo-class not supported

### ISSUE THREAD

**Issue by blackfalcon** [sass/libsass#288]
Tried to use prefixed versions of the :any() pseudo-class to get a `error: unterminated argument to :-any(...)`

You can throw the following sample code into SassMeister and see the error. 

``` scss
:-webkit-any(article,aside,nav,section) {
  h1 {
    color: orange !important;
  }
}
```
