### ISSUE TITLE
Case-insensitive selectors messed up when used with @extend

### ISSUE THREAD

**Issue by SagePtr** [sass/libsass#2884]
## input.scss

```scss
$titles: "foo", "bar", "BaZ";

%border {
        border: 1px solid;
}

@mixin border-red {
        border-color: red;
}

@mixin border-blue {
        border-color: blue;
}

@each $t in $titles {
        p[title="#{$t}" i] {
                @extend %border;
                @include border-red;
        }
        p[title="#{$t}"] {
                @extend %border;
                @include border-blue;
        }
}
```

## Actual results

[libsass 3.5.4][1]
```css
p[title="foo" i], p[title="bar" i], p[title="BaZ" i] {
  border: 1px solid; }

p[title="foo" i] {
  border-color: red; }

p[title="foo" i] {
  border-color: blue; }

p[title="bar" i] {
  border-color: red; }

p[title="bar" i] {
  border-color: blue; }

p[title="BaZ" i] {
  border-color: red; }

p[title="BaZ" i] {
  border-color: blue; }
```

## Expected result

ruby sass 3.7.4
```css
p[title="foo" i], p[title="foo"], p[title="bar" i], p[title="bar"], p[title="BaZ" i], p[title="BaZ"] {
  border: 1px solid; }

p[title="foo" i] {
  border-color: red; }

p[title="foo"] {
  border-color: blue; }

p[title="bar" i] {
  border-color: red; }

p[title="bar"] {
  border-color: blue; }

p[title="BaZ" i] {
  border-color: red; }

p[title="BaZ"] {
  border-color: blue; }
```
version info:
```cmd
$ node-sass --version
node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```
[1]:
http://libsass.ocbnet.ch/srcmap/#JHRpdGxlczogImZvbyIsICJiYXIiLCAiQmFaIjsKCiVib3JkZXIgewogICAgICAgIGJvcmRlcjogMXB4IHNvbGlkOwp9CgpAbWl4aW4gYm9yZGVyLXJlZCB7CiAgICAgICAgYm9yZGVyLWNvbG9yOiByZWQ7Cn0KCkBtaXhpbiBib3JkZXItYmx1ZSB7CiAgICAgICAgYm9yZGVyLWNvbG9yOiBibHVlOwp9CgpAZWFjaCAkdCBpbiAkdGl0bGVzIHsKICAgICAgICBwW3RpdGxlPSIjeyR0fSIgaV0gewogICAgICAgICAgICAgICAgQGV4dGVuZCAlYm9yZGVyOwogICAgICAgICAgICAgICAgQGluY2x1ZGUgYm9yZGVyLXJlZDsKICAgICAgICB9CiAgICAgICAgcFt0aXRsZT0iI3skdH0iXSB7CiAgICAgICAgICAgICAgICBAZXh0ZW5kICVib3JkZXI7CiAgICAgICAgICAgICAgICBAaW5jbHVkZSBib3JkZXItYmx1ZTsKICAgICAgICB9Cn0=

**Comment by SagePtr** [comment]
Additional info: if I don't use @extend, but only mixins, case-insensitive flag is not messed up. Example of correctly working code which doesn't use extend:
http://libsass.ocbnet.ch/srcmap/#JHRpdGxlczogImZvbyIsICJiYXIiLCAiQmFaIjsKCkBtaXhpbiBib3JkZXItcmVkIHsKICAgICAgICBib3JkZXI6IDFweCBzb2xpZCByZWQ7Cn0KCkBtaXhpbiBib3JkZXItYmx1ZSB7CiAgICAgICAgYm9yZGVyOiAxcHggc29saWQgYmx1ZTsKfQoKQGVhY2ggJHQgaW4gJHRpdGxlcyB7CiAgICAgICAgcFt0aXRsZT0iI3skdH0iIGldIHsKICAgICAgICAgICAgICAgIEBpbmNsdWRlIGJvcmRlci1yZWQ7CiAgICAgICAgfQogICAgICAgIHBbdGl0bGU9IiN7JHR9Il0gewogICAgICAgICAgICAgICAgQGluY2x1ZGUgYm9yZGVyLWJsdWU7CiAgICAgICAgfQp9

**Comment by xzyfer** [comment]
Sounds like a bug with extends rather than the case insensitive selector

**Comment by mgreter** [comment]
This should be fixed by https://github.com/sass/libsass/pull/2908. Current output by libsass:
```css
p[title="BaZ" i], p[title="bar" i], p[title="foo" i] {
  border: 1px solid; }

p[title="foo" i] {
  border-color: red; }

p[title="foo"] {
  border-color: blue; }

p[title="bar" i] {
  border-color: red; }

p[title="bar"] {
  border-color: blue; }

p[title="BaZ" i] {
  border-color: red; }

p[title="BaZ"] {
  border-color: blue; }
```

Interestingly dart sass gives:

```css
p[title=BaZ], p[title=BaZ i], p[title=bar], p[title=bar i], p[title=foo], p[title=foo i] {
  border: 1px solid;
}

p[title=foo i] {
  border-color: red;
}

p[title=foo] {
  border-color: blue;
}

p[title=bar i] {
  border-color: red;
}

p[title=bar] {
  border-color: blue;
}

p[title=BaZ i] {
  border-color: red;
}

p[title=BaZ] {
  border-color: blue;
}
```

IMO libsass is correct that it unified `p[title=BaZ], p[title=BaZ i]` to `p[title=BaZ i]`.
Not sure if this is purely by accident though. //CC @nex3
