### ISSUE TITLE
map-reject() should reject a combination of positional and named keys

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2927]
In LibSass, `map-remove((c: d, e: f), c, $key: e)` currently returns the empty map. It should fail, since the `$key` parameter is being passed by both position and name.

**Comment by mgreter** [comment]
```scss
@mixin a($a) {
  b {
    c: keywords($a);
  }
}
  
d {
  @include a((1, 2));
}
```
