### ISSUE TITLE
Evaluation of if-conditional does not stop after an untrue condition followed by "and not"

### ISSUE THREAD

**Issue by kkriehl** [sass/libsass#293]
If I have an if conditional with several and-connected conditions, once a condition fails the subsequent conditions shouldn't be evaluated. For example this should compile:

``` scss
$value: auto;

@if type-of($value) == number and not unitless($value) {
    body {
        background-color: red;
    }
}
```

As $value is not a number the first condition fails and the second condition shouldn't be evaluated, but instead the compilation fails with this error:

```
test.scss:3: error: argument `$number` of `unitless($number)` must be a number
Backtrace:
    test.scss:3, in function `unitless`
    test.scss:3
```
