### ISSUE TITLE
keywords() should throw an error when passed a list that's not an argument list

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2937]
If the `keywords()` function is passed a list that didn't come from a `...` declaration in a mixin or function name, it should throw an error. Currently in LibSass, it just returns an empty map.

**Comment by mgreter** [comment]
```scss
@mixin a($a) {
  b {
    c: keywords($a);
  }
}
  
d {
  @include a((1, 2));
}
```
