### ISSUE TITLE
libsass throws on non-selector psuedo selector params

### ISSUE THREAD

**Issue by jquense** [sass/libsass#2944]
## input.scss

This is a hacky syntax that `css-modules` uses to define dependecies across files, in general we'd want sass to ignore it, which is what the other sasses do.

```scss
:import("./foo") {
  color: red;
}
```

## Actual results
libsass 3.5.4

```css
Invalid CSS after ":import(": expected selector, was '"./foo") {' on line 1 at column 1
```

## Expected result

This is what dart and ruby sass compile to
```css
:import("./foo") {
  color: red;
}
```
