### ISSUE TITLE
Feature Request for Multi-line Indented Properties

### ISSUE THREAD

**Issue by 9ae8sdf76** [sass/libsass#2958]
## input.sass

```sass
body
  main
    display: grid
    grid-template-columns: repeat(6, 1fr)
    grid-template-rows: repeat(6, 1fr)
    grid-gap: 10px

    align-items: center
    justify-items: center

    grid-template-areas:
      - "top-left top-left top-center top-center top-right top-right"
      - "top-left top-left top-center top-center top-right top-right"
      - "middle-left middle-left middle-center middle-center middle-right middle-right"
      - "middle-left middle-left middle-center middle-center middle-right middle-right"
      - "bottom-left bottom-left bottom-center bottom-center bottom-right bottom-right"
      - "bottom-left bottom-left bottom-center bottom-center bottom-right bottom-right"
```

## Actual results

Get error about invalid CSS and/or unexpected token depending on who you ask. Naturally, as this is not a part of the spec (yet).

## Expected result

```css
body main {
    display: grid;
    grid-template-columns: repeat(6, 1fr);
    grid-template-rows: repeat(6, 1fr);
    grid-gap: 10px;
    align-items: center;
    justify-items: center;
    grid-template-areas: "top-left top-left top-center top-center top-right top-right" "top-left top-left top-center top-center top-right top-right" "middle-left middle-left middle-center middle-center middle-right middle-right" "middle-left middle-left middle-center middle-center middle-right middle-right" "bottom-left bottom-left bottom-center bottom-center bottom-right bottom-right" "bottom-left bottom-left bottom-center bottom-center bottom-right bottom-right"; }
```

## Justification

I ran across #2379, and I appreciate @nex3's answer in that current SASS does not support multi-line indented properties. However, I accidentally discovered that SASS does support the following:

from:
```sass
foo:
  bar: "foo"
  baz: "bar"
```

to:
```css
foo-bar: "foo";
foo-baz: "bar";
```

And it got me thinking that what if SASS could support a similar syntax that would be parsed into indented multi-line properties? A dash to denote an "array"-like structure that simply becomes a concatenated value separated by spaces, as in my example above with `grid-template-areas`. One drawback, which may or may not be an issue, is that there is not a good way to denote what the delimiter should be (are there CSS properties that use other delimiters?)

Another idea that could take into account arbitrary delimiters (now or into the future) may be to use a more array-like structure by including square brackets:

from:
```sass
main
  grid-template-areas: [
      "top"
      "middle"
      "bottom"
  ]
```

to:
```css
body main {
    grid-template-areas: "top" "middle" "bottom"; }
```

And whatever delimiter is used between items would be the delimiter. Essentially, this example would do nothing more than collapse the newlines into one line:

from:
```sass
main
  grid-template-areas: [
      "top",
      "middle",
      "bottom"
  ]
```

to:
```css
main {
      grid-template-areas: "top", "middle", "bottom"; }
```
(assuming this is valid CSS, of course)

All but the very first example (the one under Expected Results) are all contrived, of course. I am working on a project that may have a very intricate and complex grid, and it would be a nightmare to have to maintain it as one line. 

My hope here is to get (and keep) a discussion going with the developers and the community about addressing this elephant in the room so that we can all move on to bigger and better things. :)

Thank you!

version info:
```cmd
$ node-sass --version
node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```
