### ISSUE TITLE
@extend ignores @mixin

### ISSUE THREAD

**Issue by GottZ** [sass/libsass#2959]
## input.scss

```scss
%color {
  color: blue;
}

@mixin getOverridedSelector {
  &#{&} {
    @content;
  }
}

.foo {
  @include getOverridedSelector {
    @extend %color;
  }
}

.bar {
  @include getOverridedSelector {
    color: red;
  }
}

```

## Actual results

[libsass 3.6.0][1]  
Ruby Sass 3.7.4  
as well as on [codepen](https://codepen.io/GottZ/pen/EqoBmb) (probably libsass)
```css
.foo {
  color: blue;
}

.bar.bar {
  color: red;
}
```

## Expected result

dart sass 1.22.6-1 (Archlinux AUR)
```css
.foo.foo {
  color: blue;
}

.bar.bar {
  color: red;
}
```

[1]: http://libsass.ocbnet.ch/srcmap/#JWNvbG9yIHsKICBjb2xvcjogYmx1ZTsKfQoKQG1peGluIGdldE92ZXJyaWRlZFNlbGVjdG9yIHsKICAmI3smfSB7CiAgICBAY29udGVudDsKICB9Cn0KCi5mb28gewogIEBpbmNsdWRlIGdldE92ZXJyaWRlZFNlbGVjdG9yIHsKICAgIEBleHRlbmQgJWNvbG9yOwogIH0KfQoKLmJhciB7CiAgQGluY2x1ZGUgZ2V0T3ZlcnJpZGVkU2VsZWN0b3IgewogICAgY29sb3I6IHJlZDsKICB9Cn0=

source that found this problem: https://stackoverflow.com/questions/57376896
