### ISSUE TITLE
unary dash in @mixin uses same value every @include

### ISSUE THREAD

**Issue by schl3ck** [sass/libsass#2975]
Hi,

I've noticed that the unary dash `-` with a string in a mixin always uses its first computed value in the following calls. Note the recurring `.test-b-asdf` rule in the actual results.

LibSass processes `@include test("foo2");` by removing the quotes in the output, in contrast to dart-sass which outputs an error. Because of this the two lines are commented out below.

Tested locally and with https://www.sassmeister.com/

##  input.scss
```scss

@mixin test($name: false) {
    $a: "";
    $b: "";
    @if $name {
        $a: "-#{$name}";    // works as expected
        $b: -$name;         // here occurs the bug
    } @else {
        $a: "";
        $b: "";
    }
    
    .test-a#{$a} {
        display: block;
    }
    .test-b#{$b} {
        display: block;
    }
}

@include test;
@include test(asdf);
@include test(foo1);
@include test(bar1);
// @include test("foo2");
// @include test("bar2");

```

## Actual results
[libsass 3.5.4][1]
```css
.test-a {
  display: block;
}

.test-b {
  display: block;
}

.test-a-asdf {
  display: block;
}

.test-b-asdf {
  display: block;
}

.test-a-foo1 {
  display: block;
}

.test-b-asdf {
  display: block;
}

.test-a-bar1 {
  display: block;
}

.test-b-asdf {
  display: block;
}
```

## Expected result
dart-sass 1.12.0
```css
.test-a {
  display: block;
}

.test-b {
  display: block;
}

.test-a-asdf {
  display: block;
}

.test-b-asdf {
  display: block;
}

.test-a-foo1 {
  display: block;
}

.test-b-foo1 {
  display: block;
}

.test-a-bar1 {
  display: block;
}

.test-b-bar1 {
  display: block;
}
```

## Version info
```cmd
$ node-sass --version
node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```

OS: Windows 10 Enterprise 1803 x64
Environment: node.js v6.16.0

Thank you!

[1]: http://libsass.ocbnet.ch/srcmap/#CkBtaXhpbiB0ZXN0KCRuYW1lOiBmYWxzZSkgewogICAgJGE6ICIiOwogICAgJGI6ICIiOwogICAgQGlmICRuYW1lIHsKICAgICAgICAkYTogIi0jeyRuYW1lfSI7ICAgIC8vIHdvcmtzIGFzIGV4cGVjdGVkCiAgICAgICAgJGI6IC0kbmFtZTsgICAgICAgICAvLyBoZXJlIG9jY3VycyB0aGUgYnVnCiAgICB9IEBlbHNlIHsKICAgICAgICAkYTogIiI7CiAgICAgICAgJGI6ICIiOwogICAgfQogICAgCiAgICAudGVzdC1hI3skYX0gewogICAgICAgIGRpc3BsYXk6IGJsb2NrOwogICAgfQogICAgLnRlc3QtYiN7JGJ9IHsKICAgICAgICBkaXNwbGF5OiBibG9jazsKICAgIH0KfQoKQGluY2x1ZGUgdGVzdDsKQGluY2x1ZGUgdGVzdChhc2RmKTsKQGluY2x1ZGUgdGVzdChmb28xKTsKQGluY2x1ZGUgdGVzdChiYXIxKTsKLy8gQGluY2x1ZGUgdGVzdCgiZm9vMiIpOwovLyBAaW5jbHVkZSB0ZXN0KCJiYXIyIik7Cg==
