### ISSUE TITLE
unexpected behavior calling if() function

### ISSUE THREAD

**Issue by syedsameerali** [sass/libsass#2980]
I would like to report unexpected behavior regarding the result of an `if()` function called within an `@each` loop. The result of the `if()` function is expected to be unique on each iteration of the loop, but this is not the actual result while compiling with node-sass/libsass. 

In the compiled results below please note the generated class names which are determined by the value of the `$infix` variable (ie, the value of `$break-point-name`) on each iteration of the loop. Compiling with libsass, all generated class names are `.foo-sm`, when they are expected to be named `.foo-sm`, `.foo-md`, `.foo-lg` respectively, as shown when compiled with ruby sass or dart sass.

I am new to the SASS language (computer programming in general) and was hoping if someone could please explain the cause of this behavior and if there might be an alternative way to approach this problem while using node-sass/libsass.

With much thanks and appreciation,

## input.scss

```
$config: (
        phone: (
                break-point-width:0px,
                break-point-name: xs
        ),
        tablet: (
                break-point-width:600px,
                break-point-name: sm
        ),
        laptop: (
                break-point-width:900px,
                break-point-name: md
        ),
        desktop: (
                break-point-width:1200px,
                break-point-name:lg
        ),
);

@each $key, $map in $config {
  $break-point-width: map_get($map, break-point-width);
  $break-point-name: map_get($map, break-point-name);
  $infix: if($break-point-width == 0px, null, -$break-point-name);
      .foo#{$infix} {
        content: '#{$break-point-name}';
      }
 }

```
## Actual results

[http://libsass.ocbnet.ch/srcmap](http://libsass.ocbnet.ch/srcmap/#JGNvbmZpZzogKAogICAgICAgIHBob25lOiAoCiAgICAgICAgICAgICAgICBicmVhay1wb2ludC13aWR0aDowcHgsCiAgICAgICAgICAgICAgICBicmVhay1wb2ludC1uYW1lOiB4cwogICAgICAgICksCiAgICAgICAgdGFibGV0OiAoCiAgICAgICAgICAgICAgICBicmVhay1wb2ludC13aWR0aDo2MDBweCwKICAgICAgICAgICAgICAgIGJyZWFrLXBvaW50LW5hbWU6IHNtCiAgICAgICAgKSwKICAgICAgICBsYXB0b3A6ICgKICAgICAgICAgICAgICAgIGJyZWFrLXBvaW50LXdpZHRoOjkwMHB4LAogICAgICAgICAgICAgICAgYnJlYWstcG9pbnQtbmFtZTogbWQKICAgICAgICApLAogICAgICAgIGRlc2t0b3A6ICgKICAgICAgICAgICAgICAgIGJyZWFrLXBvaW50LXdpZHRoOjEyMDBweCwKICAgICAgICAgICAgICAgIGJyZWFrLXBvaW50LW5hbWU6bGcKICAgICAgICApLAopOwoKQGVhY2ggJGtleSwgJG1hcCBpbiAkY29uZmlnIHsKICAkYnJlYWstcG9pbnQtd2lkdGg6IG1hcF9nZXQoJG1hcCwgYnJlYWstcG9pbnQtd2lkdGgpOwogICRicmVhay1wb2ludC1uYW1lOiBtYXBfZ2V0KCRtYXAsIGJyZWFrLXBvaW50LW5hbWUpOwogICRpbmZpeDogaWYoJGJyZWFrLXBvaW50LXdpZHRoID09IDBweCwgbnVsbCwgLSRicmVhay1wb2ludC1uYW1lKTsKICAgICAgLmZvbyN7JGluZml4fSB7CiAgICAgICAgY29udGVudDogJyN7JGJyZWFrLXBvaW50LW5hbWV9JzsKICAgICAgfQogfQo=)

libsass 3.5.4
```css
.foo {
  content: "xs";
}

.foo-sm {
  content: "sm";
}

.foo-sm {
  content: "md";
}

.foo-sm {
  content: "lg";
}

```

## Expected result

ruby sass 3.5.6
```css
.foo {
  content: "xs";
}

.foo-sm {
  content: "sm";
}

.foo-md {
  content: "md";
}

.foo-lg {
  content: "lg";
}

```
dart sass 1.1.8
```css
.foo {
  content: "xs";
}

.foo-sm {
  content: "sm";
}

.foo-md {
  content: "md";
}

.foo-lg {
  content: "lg";
}

```

## version info:
```cmd
$ node-sass --version
node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]

```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==

**Comment by mgreter** [comment]
Thanks for the thorough bug report.
This seems to be a bug with the unary expression (`-$break-point-name`).
As a quick fix you can convert this to a [string concatenation][1] (`"-"+$break-point-name`).

[1]: http://libsass.ocbnet.ch/srcmap/#JGNvbmZpZzogKAogICAgICAgIHBob25lOiAoCiAgICAgICAgICAgICAgICBicmVhay1wb2ludC13aWR0aDowcHgsCiAgICAgICAgICAgICAgICBicmVhay1wb2ludC1uYW1lOiB4cwogICAgICAgICksCiAgICAgICAgdGFibGV0OiAoCiAgICAgICAgICAgICAgICBicmVhay1wb2ludC13aWR0aDo2MDBweCwKICAgICAgICAgICAgICAgIGJyZWFrLXBvaW50LW5hbWU6IHNtCiAgICAgICAgKSwKICAgICAgICBsYXB0b3A6ICgKICAgICAgICAgICAgICAgIGJyZWFrLXBvaW50LXdpZHRoOjkwMHB4LAogICAgICAgICAgICAgICAgYnJlYWstcG9pbnQtbmFtZTogbWQKICAgICAgICApLAogICAgICAgIGRlc2t0b3A6ICgKICAgICAgICAgICAgICAgIGJyZWFrLXBvaW50LXdpZHRoOjEyMDBweCwKICAgICAgICAgICAgICAgIGJyZWFrLXBvaW50LW5hbWU6bGcKICAgICAgICApLAopOwoKQGVhY2ggJGtleSwgJG1hcCBpbiAkY29uZmlnIHsKICAkYnJlYWstcG9pbnQtd2lkdGg6IG1hcF9nZXQoJG1hcCwgYnJlYWstcG9pbnQtd2lkdGgpOwogICRicmVhay1wb2ludC1uYW1lOiBtYXBfZ2V0KCRtYXAsIGJyZWFrLXBvaW50LW5hbWUpOwogICRpbmZpeDogaWYoJGJyZWFrLXBvaW50LXdpZHRoID09IDBweCwgbnVsbCwgIi0iKyRicmVhay1wb2ludC1uYW1lKTsKICAuZm9vI3skaW5maXh9IHsKICAgIGNvbnRlbnQ6ICcjeyRicmVhay1wb2ludC1uYW1lfSc7CiAgfQp9Cg==

```scss
$config: (
        phone: (
                break-point-width:0px,
                break-point-name: xs
        ),
        tablet: (
                break-point-width:600px,
                break-point-name: sm
        ),
        laptop: (
                break-point-width:900px,
                break-point-name: md
        ),
        desktop: (
                break-point-width:1200px,
                break-point-name:lg
        ),
);

@each $key, $map in $config {
  $break-point-width: map_get($map, break-point-width);
  $break-point-name: map_get($map, break-point-name);
  $infix: if($break-point-width == 0px, null, "-"+$break-point-name);
  .foo#{$infix} {
    content: '#{$break-point-name}';
  }
}
```
