### ISSUE TITLE
[Bug] Convert hex color to string 

### ISSUE THREAD

**Issue by kytosai** [sass/libsass#2981]
I have hex color . I want to covert hex color to string. 
- webpack 4
- sass-loader 7.3.1
- node-sass 4.9.2

I have code:
![alt](https://i.imgur.com/Wjka78M.png)

When i code with development enviroment
![alt](https://i.imgur.com/8behYBa.png)

When i build with production enviroment
![alt](https://i.imgur.com/sPX0XMV.png)

Why #3399ff conver to #39f in production enviroment ?
How to disable it in production enviroment ?

**Comment by mgreter** [comment]
We don't see how your  `str-remove-whitespace` function looks like, so I [can't reproduce][1] your case.

[1]: http://libsass.ocbnet.ch/srcmap/#JGNvbG9yOiAjMzM5OWZmOwokc3RyLWNvbG9yOiAjMzM5OWZmICsgJyAnOwpmb28gewogICBAZGVidWcgImNvbCAiICAkc3RyLWNvbG9yOwp9

**Comment by mgreter** [comment]
For reference (from sass meister):

input (with compressed/compact output):
```
foo {
   a: "col "  + inspect(#3399ff);
   b: "col "  + inspect(#3399ff + ' ');
}
```

sass 3.4.25:
```css
foo{a:"col #39f";b:'col "#39f "'}
```

Sass 3.5.6.
```
foo{a:"col #39f";b:'col "#39f "'}
```

LibSass 3.5.4:
```
foo{a:"col #3399ff";b:"col #39f "}
```

Dart-Sass 1.18.0
```css
foo{a:"col #3399ff";b:'col "#3399ff "'}
```` 

LibSass seems undecided due to static declaration optimization. What is the canonical?

My latest refactoring seem to agree with dart-sass
```css
foo {
  a: "col #3399ff";
  b: "col #3399ff ";
}
```
