### ISSUE TITLE
Compressed style should not remove meaningful space between selectors

### ISSUE THREAD

**Issue by zengabor** [sass/libsass#2988]
## input.scss

```scss
.foo .bar {
  top: 0;
}
```

## Actual results (output style: compressed)

```css
.foo.bar{top:0}
```

The combinator space between `.foo` and `.bar` is incorrectly removed.

## Expected result (output style: compressed)

```css
.foo .bar{top:0}
```

There is a space between `.foo` and `.bar` as in the source (meaning that the rule is valid in case `.bar` is a descendant of `.foo`).
## Version info

```cmd
$ sassc -v
sassc: 3.6.1-5-g507f0
libsass: 3.6.1-36-geb54
sass2scss: 1.1.1
sass: 3.5
```
