### ISSUE TITLE
outer scope breaks @font-face

### ISSUE THREAD

**Issue by GottZ** [sass/libsass#3003]
hey there. it's me again.

## input.scss

```scss
#top {
  @font-face {
    font-family: suchfontsospecial;
    src: url("/foo.eot");
  }
}
```

## Actual results

[libsass v3.6.2](https://libsass.ocbnet.ch/srcmap/#I3RvcCB7CiAgQGZvbnQtZmFjZSB7CiAgICBmb250LWZhbWlseTogc3VjaGZvbnRzb3NwZWNpYWw7CiAgICBzcmM6IHVybCgiL2Zvby5lb3QiKTsKICB9Cn0=)  
libsass v3.3.1 on https://sass.js.org
Ruby Sass 3.7.4  
dart sass 1.23.0-1 (Archlinux AUR)  
ruby sass 3.5.6 on [codepen](https://codepen.io/GottZ/pen/QWWwGBg?editors=0100)
http://beautifytools.com/scss-compiler.php (unknown compiler)
```css
@font-face {
  #top {
    font-family: suchfontsospecial;
    src: url("/foo.eot");
  }
}
```

## Expected result

https://www.cssportal.com/scss-to-css/ (i assume scssphp)
```css
@font-face {
  font-family: suchfontsospecial;
  src: url("/foo.eot");
}
```
