### ISSUE TITLE
@mixin argument not expanded in CSS custom property

### ISSUE THREAD

**Issue by majewsky** [sass/libsass#3012]
According to <https://www.sassmeister.com/>, Sass v3.4.25 generates the correct result, but Sass v3.5.6 doesn't, so this is probably a regression.

## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
@mixin m($val) {
  padding-left: $val;   // this works
  --my-variable: $val;  // this breaks
}

main {
  @include m(1rem);
}
```

## Actual results

[libsass 3.6.2][1]
```css
main {
  padding-left: 1rem;
  --my-variable: $val;
}
```

## Expected result

```css
main {
  padding-left: 1rem;
  --my-variable: 1rem;
}
```

## Version info

Reproducible on my machine with:

```cmd
$ sassc --version
sassc: na
libsass: 3.5.5
sass2scss: 1.1.1
sass: 3.5
```

[1]: http://libsass.ocbnet.ch/srcmap/#QG1peGluIG0oJHZhbCkgewogIHBhZGRpbmctbGVmdDogJHZhbDsgICAvLyB0aGlzIHdvcmtzCiAgLS1teS12YXJpYWJsZTogJHZhbDsgIC8vIHRoaXMgYnJlYWtzCn0KCm1haW4gewogIEBpbmNsdWRlIG0oMXJlbSk7Cn0=
