### ISSUE TITLE
Whitespace discrepancies between 3.6.1 and 3.6.2 for rule blocks in nested mode

### ISSUE THREAD

**Issue by gnarmedia** [sass/libsass#3018]
I apologize if this isn't the best examples, this was tricky difficult to represent. The spacing around the / and the missing tab indent are what I'm trying to represent, but I suspect there are more issues than this, like rules having new lines between them along with no indentation. I'd recommend checking the output of multiple long stylesheets like Bootstrap to see the differences between 3.6.1 and 3.6.2.  I've currently resolved this by downgrading to 3.6.1. Thanks for all the good work you're doing on the project!

## input.scss

```scss
#articles p {
	color: $_medium-dark-gray;
	font:normal 1.13px/1.18 $content-one-font; /* 11px/13px */
}
#clearAllFacets {
	.clear-facets-label {
		margin-right: -12px;
	}
}
```

## Actual results

libsass 3.6.2
```css
#articles p {
  color: #676767;
  font: normal 1.13px / 1.18 Arial, Helvetica, "Helvetica Neue", sans-serif;
  /* 11px/13px */ }
  #clearAllFacets .clear-facets-label,
#clearAllFacets .clear-facets-icon {
    cursor: pointer; }
```

## Expected result

libsass 3.6.1
```css
#articles p {
  color: #676767;
  font: normal 1.13px/1.18 Arial, Helvetica, "Helvetica Neue", sans-serif;
  /* 11px/13px */ }
  #clearAllFacets .clear-facets-label,
  #clearAllFacets .clear-facets-icon {
    cursor: pointer; }
```

version info:
```cmd
$ sassc -v
sassc: 3.6.1
libsass: 3.6.2
sass2scss: 1.1.1
sass: 3.5
```

**Comment by mgreter** [comment]
[I can't reproduce this][1] !? 

[1]: http://libsass.ocbnet.ch/srcmap/#JF9tZWRpdW0tZGFyay1ncmF5OiAjNjc2NzY3OwokY29udGVudC1vbmUtZm9udDogQXJpYWwsIEhlbHZldGljYSwgIkhlbHZldGljYSBOZXVlIiwgc2Fucy1zZXJpZjsKI2FydGljbGVzIHAgewoJY29sb3I6ICRfbWVkaXVtLWRhcmstZ3JheTsKCWZvbnQ6bm9ybWFsIDEuMTNweC8xLjE4ICRjb250ZW50LW9uZS1mb250OyAvKiAxMXB4LzEzcHggKi8KfQojY2xlYXJBbGxGYWNldHMgewoJLmNsZWFyLWZhY2V0cy1sYWJlbCB7CgkJbWFyZ2luLXJpZ2h0OiAtMTJweDsKCX0KfQ==

**Comment by mgreter** [comment]
IMO it works as expected, since we changed the extend logic to match dart sass, some whitespace differences that exist in dart sass vs ruby sass are now also present in libsass.

https://github.com/sass/dart-sass/blob/master/differences.md

> newlines are never preserved within complex selectors

I have no idea how OP got the spaces around the dash ` / ` ...

**Comment by saper** [comment]
Shouldn't 3.6.2 be 3.7.0 really?

**Comment by mgreter** [comment]
Why? There shouldn't be any breaking changes.

Only white-space issue I found when comparing bootstrap with nested mode is:

```scss
input,
button {
  content: outer;
  &:focus {
    content: inner;
  }
}
```

There we seem to loose the indentation for the preserved newline.

**Comment by mgreter** [comment]
Found another case which looses indentation

```scss
.container {
  content: outer;
  @media (min-width: 30px) {
    content: inner;
  }
}
```

Conclusion: we urgently need to get output mode specific spec tests back.
