### ISSUE TITLE
sassc using large amount of memory with libsass 3.6.3

### ISSUE THREAD

**Issue by phmccarty** [sass/libsass#3033]
I am attempting to build the latest release of [arc-theme](https://github.com/arc-design/arc-theme), which has a build dependency on sassc/libsass.

With libsass 3.6.2, the build was hanging, very likely due to [this issue](https://github.com/sass/libsass/issues/3006). With libsass 3.6.3, sassc starts to consume large amounts of memory. I don't know if the build would successfully complete, because my system was about to run out of memory; sassc was using about 14 GB of RAM when I killed the process.

Steps to reproduce:

```
git clone https://github.com/arc-design/arc-theme
cd arc-theme/common/gtk-3.0/3.20
sassc sass/gtk.scss gtk.css
```

**Comment by saper** [comment]
node-sass using libsass 3.5.5 compiled it under 2 seconds:

````
> time node-sass sass/gtk.scss sass/gtk.css
Rendering Complete, saving .css file...
Wrote CSS to /home/saper/sw/arc-theme/common/gtk-3.0/3.20/sass/gtk.css

real    0m2,02s
user    0m1,60s
sys     0m0,19s
````

**Comment by saper** [comment]
With libsass master (d91105 which is 3.6.3 plus 4 commit) there are lots of warnings:

    Compound selectors may no longer be extended.

**Comment by xzyfer** [comment]
This is a deprecation notice we introduced.

**Comment by saper** [comment]
@xzyfer but is this feature still supported? it seems that extension process is causing trouble here (according to the debugger)

**Comment by mgreter** [comment]
Has anyone tried it with dart sass, I suspect it will run into the same issue.

**Comment by mgreter** [comment]
AFAIR that gtk theme has quite a few `@extend *` which seems to cause long runtime.

**Comment by saper** [comment]
Nope, dart is not even [running on my system](https://github.com/dart-lang/sdk/issues/10260#issuecomment-372138711).

**Comment by saper** [comment]
Does it ever finish? I poked around it with a debugger and it seems to jump around extending stuff; it also does not seem to endlessly recurse.

**Comment by mgreter** [comment]
I believe it will finish if you have an absurd amount of RAM. It seems to even exhaust 64GB. But the real issue is that the extend rules for this theme are really getting out of hand and probably don't work as they have been intended. Not sure exactly how or why older libsass extend was working but I suspect that we didn't obey the 3rd law of extend (It trims redundant selectors as much as possible, while still ensuring that the specificity is greater than or equal to that of the extender). Dart-sass seems to behave exactly the same, albeit slower accumulating memory.

FWIW I was able to compile `_common.scss` and it alone produced a 6MB big css file. 

![image](https://user-images.githubusercontent.com/282293/68336862-95d9b000-00df-11ea-88c1-c88da39a1dd0.png)

**Comment by lazka** [comment]
Same problem with the default gtk CSS theme: https://gitlab.gnome.org/GNOME/gtk/issues/2237

sassc used to create a 192kb CSS file and starting with 3.6.3 (3.6.2 didn't build at all) the resulting CSS is 70MB large.

**Comment by mgreter** [comment]
It seems to boil down to some usage pattern like these:
```scss
%undecorated_button {
  box-shadow: none;
}

button:link:hover, button:visited:hover,
button:link:active, button:visited:active,
button:link:checked, button:visited:checked {
  @extend %undecorated_button;
}

headerbar {
  @extend %header_widgets;
}

%header_widgets {

  &.selection-mode button {

    &, &.flat {
      asd: qwe;
    }
    &:active, &:checked { @extend :active; }

    &:disabled {
      @extend :disabled;

      &:checked, &:active { @extend :disabled, :checked; }
    }
  }
}
```

I would suggest to take this upstream to dart-sass, as it suffers from the same issue.

**Comment by lazka** [comment]
Here is an example which produces a bogus result starting with 3.6.2:

```scss
*:hover {
  *:visited {
    color: green;
  }
}

button {
  @extend *:hover;
}
```
