### ISSUE TITLE
Variables are not replaced/computed in SVG variable definitions

### ISSUE THREAD

**Issue by semond** [sass/libsass#3036]
# Variables in SVG variables are not replaced

SVG supports variables, defined as:

```css
.something {
  --a-variable: value;
}
```
that can be used in the SVG definition:

```svg
<line ... stroke="var(--a-variable)" />
```

When defining re-usable objects, and re-using them with `<use ...>`, it's pretty much the only way to target the items inside the shadowed dom.

libsass does not replace the SCSS variable placed on lines beginning with "--".

## input.scss

```scss
test {
  $c1: #777;
  --color-c1: $c1;
  color: #777;
}
```

## Actual results

[libsass 3.6.3][1]
```css
test {
  --color-c1: $c1;
  color: #777; }
```

## Expected result

```css
test {
  --color-c1: #777;
  color: #777;
}
```

version info:
```cmd
$ pysassc --version
pysassc 0.19.4 (sass/libsass 3.6.3)
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgJGMxOiAjNzc3OwogIC0tY29sb3ItYzE6ICRjMTsKICBjb2xvcjogJGMxOwp9
