### ISSUE TITLE
Nested decendent selector becomes unested (regresssion)

### ISSUE THREAD

**Issue by byoungb** [sass/libsass#3046]
## input.scss
From bootstrap 3
```scss
@mixin table-row-variant($state, $background) {
  .table > thead > tr,
  .table > tbody > tr,
  .table > tfoot > tr {
    > td.#{$state},
    > th.#{$state},
    &.#{$state} > td,
    &.#{$state} > th {
      background-color: $background;
    }
  }
}
@include table-row-variant(active, green);
```

## Actual results
libsass 3.6.2
[libsass 3.6.3][1]
```css
> td.active, 
> th.active, 
.table > thead > tr.active > td, 
.table > thead > tr.active > th, 
.table > tbody > tr.active > td, 
.table > tbody > tr.active > th, 
.table > tfoot > tr.active > td, 
.table > tfoot > tr.active > th {
    background-color: green;
}
```

## Expected result
libsass 3.6.1
```css
.table > thead > tr > td.active, 
.table > thead > tr > th.active, 
.table > thead > tr.active > td, 
.table > thead > tr.active > th, 
.table > tbody > tr.active > td, 
.table > tbody > tr.active > th, 
.table > tfoot > tr.active > td, 
.table > tfoot > tr.active > th {
    background-color: green;
}
```

version info:
*libsass-python*
Bad
```cmd
$ sassc --version
sassc 0.19.4 (sass/libsass 3.6.3)
```
Bad
```cmd
$ sassc --version
sassc 0.19.3 (sass/libsass 3.6.2)
```
Good
```cmd
$ sassc --version
sassc 0.19.2 (sass/libsass 3.6.1)
```
[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#QG1peGluIHRhYmxlLXJvdy12YXJpYW50KCRzdGF0ZSwgJGJhY2tncm91bmQpIHsKICAudGFibGUgPiB0aGVhZCA+IHRyLAogIC50YWJsZSA+IHRib2R5ID4gdHIsCiAgLnRhYmxlID4gdGZvb3QgPiB0ciB7CiAgICA+IHRkLiN7JHN0YXRlfSwKICAgID4gdGguI3skc3RhdGV9LAogICAgJi4jeyRzdGF0ZX0gPiB0ZCwKICAgICYuI3skc3RhdGV9ID4gdGggewogICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAkYmFja2dyb3VuZDsKICAgIH0KICB9Cn0KQGluY2x1ZGUgdGFibGUtcm93LXZhcmlhbnQoYWN0aXZlLCBncmVlbik7
