### ISSUE TITLE
@use function implementation

### ISSUE THREAD

**Issue by The-Code-Monkey** [sass/libsass#3051]
My colors.scss maps over a set of default colours which, spits out scss variables in darker and lighter forms aswell as css variables for use in the newer styled-components.

The problem I am facing is the fact that I currently have to use @import which is causing 'colours.scss' to be imported and thus the @each run for each implementation of the '_variables.scss' file.

The project is a mono repo so having one central file for all the sass to be imported into isn't an option.

```scss
@use 'colours.scss'
```

## Actual results

```css
:root {
  --blue: #0000FF,
  --green: #00FF00,
  --red #FF0000:
}
:root {
  --blue: #0000FF,
  --green: #00FF00,
  --red #FF0000:
}
:root {
  --blue: #0000FF,
  --green: #00FF00,
  --red #FF0000:
}
:root {
  --blue: #0000FF,
  --green: #00FF00,
  --red #FF0000:
}
```

## Expected result

```css
:root {
  --blue: #0000FF,
  --green: #00FF00,
  --red #FF0000:
}
```

version info:
```cmd
node-sass       4.13.0
libsass         3.5.4
```
