### ISSUE TITLE
calc() function within the max() function should not return an error

### ISSUE THREAD

**Issue by markvanwijnen** [sass/libsass#3052]
## input.scss

```scss
test {
  padding-right: max( 0px, calc( 12px + 13px ) );
}
```

## Actual results

**Libsass: Error: "calc( 12px + 13px)" is not a number for `max'**

## Expected result

Libsass compiled successfully.
AutoPrefixer ran successfully.

## Notes

When you use unquote() to bypass the SASS compiler, the CSS will work in the browser.
