### ISSUE TITLE
Regression compiling nested > selectors in [affects bootstrap]

### ISSUE THREAD

**Issue by raphaelm** [sass/libsass#3053]
We've noticed a regression apparently introduced when compiling twitter bootstrap-sass v3.x. It leads to some selectors being compiled to invalid CSS and therefore some rules going missing. We were able to pinpoint that it works in 3.6.1 but not in 3.6.2, so it might have been broken in the refactorings happening in 3.6.2. Happy to provide further info if needed.

## input.scss

```scss
@mixin table-row-variant($state, $background) {
  // Exact selectors below required to override `.table-striped` and prevent
  // inheritance to nested tables.
  .table > thead > tr,
  .table > tbody > tr,
  .table > tfoot > tr {
    > td.#{$state},
    > th.#{$state},
    &.#{$state} > td,
    &.#{$state} > th {
      background-color: $background;
    }
  }

}
@include table-row-variant('success', #d4e9da);

```

[SourceMap Inspector](http://libsass.ocbnet.ch/srcmap/#QG1peGluIHRhYmxlLXJvdy12YXJpYW50KCRzdGF0ZSwgJGJhY2tncm91bmQpIHsKICAvLyBFeGFjdCBzZWxlY3RvcnMgYmVsb3cgcmVxdWlyZWQgdG8gb3ZlcnJpZGUgYC50YWJsZS1zdHJpcGVkYCBhbmQgcHJldmVudAogIC8vIGluaGVyaXRhbmNlIHRvIG5lc3RlZCB0YWJsZXMuCiAgLnRhYmxlID4gdGhlYWQgPiB0ciwKICAudGFibGUgPiB0Ym9keSA+IHRyLAogIC50YWJsZSA+IHRmb290ID4gdHIgewogICAgPiB0ZC4jeyRzdGF0ZX0sCiAgICA+IHRoLiN7JHN0YXRlfSwKICAgICYuI3skc3RhdGV9ID4gdGQsCiAgICAmLiN7JHN0YXRlfSA+IHRoIHsKICAgICAgYmFja2dyb3VuZC1jb2xvcjogJGJhY2tncm91bmQ7CiAgICB9CiAgfQoKfQpAaW5jbHVkZSB0YWJsZS1yb3ctdmFyaWFudCgnc3VjY2VzcycsICNkNGU5ZGEpOw==)

## Actual result

libsass 3.6.2 / libsass-python 0.19.3

```css
> td.success,
> th.success, .table > thead > tr.success > td, .table > thead > tr.success > th,
.table > tbody > tr.success > td,
.table > tbody > tr.success > th,
.table > tfoot > tr.success > td,
.table > tfoot > tr.success > th {
  background-color: #d4e9da; }
```

## Expected result

libsass 3.6.1 / libsass-python 0.19.2

```css
.table > thead > tr > td.success,
.table > thead > tr > th.success,
.table > thead > tr.success > td,
.table > thead > tr.success > th,
.table > tbody > tr > td.success,
.table > tbody > tr > th.success,
.table > tbody > tr.success > td,
.table > tbody > tr.success > th,
.table > tfoot > tr > td.success,
.table > tfoot > tr > th.success,
.table > tfoot > tr.success > td,
.table > tfoot > tr.success > th {
  background-color: #d4e9da; }
```

## Further info

It works if some explicit ``&`` are inserted. However, as far as I can see, they should not be necessary.

```css
@mixin table-row-variant($state, $background) {
  // Exact selectors below required to override `.table-striped` and prevent
  // inheritance to nested tables.
  .table > thead > tr,
  .table > tbody > tr,
  .table > tfoot > tr {
    & > td.#{$state},
    & > th.#{$state},
    &.#{$state} > td,
    &.#{$state} > th {
      background-color: $background;
    }
  }

}
@include table-row-variant('success', #d4e9da);
```
