### ISSUE TITLE
"Incompatible units" when using min() function with vh and px

### ISSUE THREAD

**Issue by tkondrashov** [sass/libsass#3061]
## input.scss

```scss
.App {
  font-size: min(5.5vh, 30px);
}
```

## Actual results

[libsass 3.5.4][1]
```Failed to compile.
./src/App.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/App.scss)
SassError: Internal Error: Incompatible units: 'px' and 'vh'.
```

## Expected result

```css
.App {
  font-size: min(5.5vh, 30px);
}
```

version info:
```cmd
$ node-sass -v
node-sass	4.13.1	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#Ci5BcHAgewogIGZvbnQtc2l6ZTogbWluKDUuNXZoLCAzMHB4KTsKfQ==
