### ISSUE TITLE
You may not @extend an outer selector from within @media.

### ISSUE THREAD

**Issue by peter-gribanov** [sass/libsass#3065]
[todo]: # (Title: Be as meaningful as possible)
[todo]: # (Title: Try to use 60 or less chars)

[todo]: # (This is only a template!)
[todo]: # (remove unneeded bits)
[todo]: # (use github preview!)

This problem was mentioned many times, but i still could not find a solution that would help me. All decisions come down to transferring styles to the mixins and using it in the future, but in my case this is not possible since the styles are declared in a external library (Bootstrap).

## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
// external code
// @import '../../../node_modules/bootstrap/scss/_button-group.scss';
// example from _button-group.scss
.btn-group,
.btn-group-vertical {
  position: relative;
  display: inline-flex;
}

.btn-group-vertical {
  flex-direction: column;
  align-items: flex-start;
  justify-content: center;
}

// my code

.btn-group-responsive {
  @extend .btn-group;
}

@media (max-width: 767px) {
  .btn-group-responsive {
    @extend .btn-group-vertical;
  }
}
```

## Actual results

[todo]: # (update version info!)

```
Error in plugin "sass"
Message:
    node_modules/bootstrap/scss/_button-group.scss
Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive.
       From "@extend .btn-group-vertical" on line 12 of assets/scss/include/_btn-group.scss
        on line 5 of node_modules/bootstrap/scss/_button-group.scss
>> .btn-group-vertical {
```

## Expected result

[todo]: # (update version info!)

```css
// external code

.btn-group,
.btn-group-vertical,
.btn-group-responsive {
  position: relative;
  display: inline-flex;
}

.btn-group-vertical {
  flex-direction: column;
  align-items: flex-start;
  justify-content: center;
}

// my code

@media (max-width: 767px) {
  .btn-group-responsive {
    position: relative;
    display: inline-flex;
    flex-direction: column;
    align-items: flex-start;
    justify-content: center;
  }
}
```

[todo]: # (update version info!)
[todo]: # (example for node-sass!)

version info:
```cmd
$ sass -v
Sass 3.5.5 (Bleeding Edge)
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==

**Comment by peter-gribanov** [comment]
I did not find any other way but to copy all the styles from the external library.

```scss
// external code
// @import '../../../node_modules/bootstrap/scss/_button-group.scss';
// example from _button-group.scss
.btn-group,
.btn-group-vertical {
  position: relative;
  display: inline-flex;
}

.btn-group-vertical {
  flex-direction: column;
  align-items: flex-start;
  justify-content: center;
}

// my code

.btn-group-responsive {
  @extend .btn-group;
}

@media (max-width: 767px) {
  .btn-group-responsive {
    // copy/paste .btn-group-vertical;
    flex-direction: column;
    align-items: flex-start;
    justify-content: center;
  }
}
```
