### ISSUE TITLE
Variable in CSS selector fails when value is a color name

### ISSUE THREAD

**Issue by arian** [sass/libsass#308]
For example

``` scss
$zzz: orange;
.#{$zzz} { a: b; }
```

Fails, while https://github.com/hcatlin/sass-spec/blob/master/spec/scss/selector_interpolation_at_class_begininng/input.scss seems to work.

The expected output, would be

``` css
.orange { a: b; }
```

And this is indeed the output by Ruby Sass.

Tested with 236f1ad4 and sassc
