### ISSUE TITLE
wrong :before position

### ISSUE THREAD

**Issue by ahorek** [sass/libsass#3084]
Hi, was this change intentional or is it a bug? Probably it's not a bug, but I just want to be sure.

## input.scss

```scss
.red-icon {
  color: #e50026;
}

a.nested:before {
  &.error {
    @extend .red-icon;
  }
}
```

## Actual results

[libsass 3.6.3][1]
```css
.red-icon, a.nested:before.error {
  color: #e50026; }
```

dart sass also have this behavior

in this case ```<div class="red-icon">text</div>``` isn't red.

## Expected result

[libsass 3.6.1][1]
```css
.red-icon, a.nested.error:before {
  color: #e50026; }
```

[1]: http://libsass.ocbnet.ch/srcmap/#LnJlZC1pY29uIHsKICBjb2xvcjogI2U1MDAyNjsKfQoKYS5uZXN0ZWQ6YmVmb3JlIHsKICAmLmVycm9yIHsKICAgIEBleHRlbmQgLnJlZC1pY29uOwogIH0KfQ==
