### ISSUE TITLE
Variable in Attribute Selector is not evaluated

### ISSUE THREAD

**Issue by arian** [sass/libsass#309]
``` scss
$zzz: zzz;
a[data-foo="#{$zzz}"] { a: b; }
```

Is expected to compile to

``` css
a[data-foo="zzz"] {
  a: b; }
```

As is done by Ruby Sass.

Tested with 236f1ad4 and sassc
