### ISSUE TITLE
Issue with glob plugin when path ends with slash

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#3091]
```scss:foo1.scss
asd {
  qwe: $PI;
}
```

```scss:foo2.scss
asd {
  qwe: foo2;
}
```

```scss:test.scss
@import "foo*.scss";
```

sassc test.scss -P "C:\Program Files\libsass\plugin"
```
asd {
  qwe: 3.1415926536; }

asd {
  qwe: foo2; }
```

D:\>sassc test.scss -P "C:\Program Files\libsass\plugin\"
```
Error: File to import not found or unreadable: foo*.scss.
        on line 1:1 of /test.scss
>> @import "foo*.scss";
   ^
```
