### ISSUE TITLE
Variables set to name of any color is always printed as its hex value.

### ISSUE THREAD

**Issue by utkarshkukreti** [sass/libsass#311]
Input:

``` scss
$a: red;
#{$a} {
  foo: bar;
  baz: #{$a};
}
```

Output:

``` css
#ff0000 {
  foo: bar;
  baz: #ff0000; }
```

Expected output / Ruby Sass's output

``` css
red {
  foo: bar;
  baz: red; }
```
