### ISSUE TITLE
SourceMap result is wrong when using asian characters

### ISSUE THREAD

**Issue by constantin-v** [sass/libsass#3110]
## input.scss

```scss
body {
  font-family: 'Microsoft JhengHei', '微軟正黑體', 'PingFang TC', '蘋方-繁', 'PingFang HK','蘋方-港', 'Apple LiGothic Medium', '蘋果儷中黑', sans-serif;
}

.someCss {
    align-items: center;
	height:200px;
    background-size: cover;
    display: flex;
}

.myDivStyle {
    align-items: center;
    background-color:red;
	height:200px;
    background-size: cover;
    display: flex;
}

```

## Actual results

> I was not able to use http://libsass.ocbnet.ch/srcmap/ because of the non Latin1 characters. When I try to bookmark I got this error : Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range. I linked the result of the node-sass compilation that I uploaded on github

[libsass 3.5.4][1]
```css
body{font-family:'Microsoft JhengHei', '微軟正黑體', 'PingFang TC', '蘋方-繁', 'PingFang HK','蘋方-港', 'Apple LiGothic Medium', '蘋果儷中黑', sans-serif}.someCss{align-items:center;height:200px;background-size:cover;display:flex}.myDivStyle{align-items:center;background-color:red;height:200px;background-size:cover;display:flex}

/*# sourceMappingURL=test.css.map */
```
As you can see on screenshot, the sourcemap is broken as it give me the wrong line when I'm using the sourcemap with Chrome dev tools

![Sass1](https://github.com/constantin-v/node-sass-source-map/blob/master/notWorking/devtools1.jpg?raw=true)
![Sass2](https://github.com/constantin-v/node-sass-source-map/blob/master/notWorking/devtools2.jpg?raw=true)

## Expected result

Using asian characters shouldn't break SourceMap.

As an example, replacing asian chars by latin is working fine.
See:

![Sass](https://github.com/constantin-v/node-sass-source-map/blob/master/working/devtools1.jpg?raw=true)
![Sass](https://github.com/constantin-v/node-sass-source-map/blob/master/working/devtools2.jpg?raw=true)

version info:
```
node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```

For more files / screenshots please see [this repo](https://github.com/constantin-v/node-sass-source-map).

Thanks

[1]: https://github.com/constantin-v/node-sass-source-map/blob/master/notWorking/test.css.map
