### ISSUE TITLE
type-of(1 * 1#{$unit}) should be a number

### ISSUE THREAD

**Issue by Anthony-Gaudino** [sass/libsass#3111]
In my code, using the latest version of `node-sass` I'm trying to add a unit to a number like bellow, which is resulting in a `string` type. I expected it to be a `number` type.

Minimal example:
## input.scss
```scss
$unit: "px";
@debug type-of(1 * 1#{$unit});  // string
```

## Actual results
`string`

## Expected result
`number`

On this website http://beautifytools.com/scss-compiler.php I get the expected `number` result using the following code:
```scss
$unit: "em";
$res: 1 * 1#{$unit};

a {
  resttype: type-of($res);
  res: $res;
}
``` 

```css
a {
	resttype: number;
	res: 1em;
}
```

[todo]: # (Title: Be as meaningful as possible)
[todo]: # (Title: Try to use 60 or less chars)

[todo]: # (This is only a template!)
[todo]: # (remove unneeded bits)
[todo]: # (use github preview!)

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
test {
  content: bar
}
```

[todo]: # (update version info!)

[todo]: # (update version info!)

ruby sass 3.X.y
```css
test {
  content: bar; }
```

[todo]: # (update version info!)
[todo]: # (example for node-sass!)

version info:
```cmd
$ node-sass --version
node-sass       3.X.y   (Wrapper)       [JavaScript]
libsass         3.X.y   (Sass Compiler) [C/C++]
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#JHVuaXQ6ICJlbSI7CiRyZXM6IDEgKiAxI3skdW5pdH07CgphIHsKICByZXN0dHlwZTogdHlwZS1vZigkcmVzKTsKICByZXM6ICRyZXM7Cn0=
