### ISSUE TITLE
@supports selector() not supported

### ISSUE THREAD

**Issue by Ariane-B** [sass/libsass#3116]
`@supports selector(.some-selector)` does not appear to be supported by either Libsass or Dart Sass. In the mean time, is there a way I can "fake" it? The query is in a mixin in my case.
## input.scss
```scss
div {
  @supports selector( *:focus-visible ) {
    color: red;
  }
}
```

## Actual results
[libsass 3.6.4-r1](http://libsass.ocbnet.ch/srcmap/#ZGl2IHsKCUBzdXBwb3J0cyAoY29sb3I6cmVkKSB7CgkJY29sb3I6IHJlZDsKCX0KfQ==)
```css
Error: Invalid CSS after "	@supports ": expected @supports condition (e.g. (display: flexbox)), was "selector( *:focus-v"
```

## Dart Sass result

dart sass 1.26.9
```css
Error: Expected "not".
  ╷
2 │   @supports selector( *:focus-visible ) {
  │             ^
```

## Actually expected result
```css
@supports selector(*:focus-visible) {
  div {
    color: red; } }
```

version info:
```cmd
$ node-sass --version
node-sass       4.14.1  (Wrapper)       [JavaScript]
libsass         3.5.5   (Sass Compiler) [C/C++]
```
