### ISSUE TITLE
It's possible to override variables dynamically when compile the scss/sass file?

### ISSUE THREAD

**Issue by Folyd** [sass/libsass#3117]
Give an instance, we have an scss file:
```scss
// index.scss

$primary-color: #abcdef;

body {
    background-color: $primary-color;
}
```

Just wonder can we override the variable `$primary-color` to another value in the compile phase?

For example, can we add an extra parameter which is a custom variable map to the function `sass_compile_file_context(Sass_File_Context* file_ctx)`?
