### ISSUE TITLE
String interpolation not working in @for loop

### ISSUE THREAD

**Issue by techniq** [sass/libsass#312]
The following `@for` loop does not interpolate `#{$i}` correctly but instead renders it out.  I checked with the Ruby-based sass and it outputs as expected

`example.scss`

``` sass
@for $i from 0 through 10 {
    .foo [index = "#{$i}"] {
        transform: translateY($i * 100%);
    }
}
```

---

`$ sassc example.scss`

``` css
.foo [index="#{$i}"] {
  transform: translateY(0%); }

.foo [index="#{$i}"] {
  transform: translateY(100%); }

.foo [index="#{$i}"] {
  transform: translateY(200%); }

...
```

---

`$ sass example.scss`

``` css
.foo [index="0"] {
  transform: translateY(0%); }

.foo [index="1"] {
  transform: translateY(100%); }

.foo [index="2"] {
  transform: translateY(200%); }

...
```
