### ISSUE TITLE
@use not implemented

### ISSUE THREAD

**Issue by stefanloerwald** [sass/libsass#3121]
`@use` rules seem to be not implemented:

foo.scss:
```css
body {
    color: green;
}
```

bar.scss:
```css
@use "foo";
```

I would expect the result to be

bar.css:
```css
body {
    color: green;
}
```

However, I get

```css
@use "foo";
```

I use the [C# compiler frontend](https://github.com/Taritsyn/LibSassHost) which uses version 3.6.4 of libsass.
