### ISSUE TITLE
Placeholder selectors (%foo) and CSS all selector (*) don't work together

### ISSUE THREAD

**Issue by caesar** [sass/libsass#315]
The following produces no output:

``` scss
*, *:before, *:after,
%border-box {
    -webkit-box-sizing: border-box;
       -moz-box-sizing: border-box;
            box-sizing: border-box;
}
```

However, the following works as expected:

``` scss
%border-box {
    -webkit-box-sizing: border-box;
       -moz-box-sizing: border-box;
            box-sizing: border-box;
}
*, *:after, *:before {
    @extend %border-box;
}
```

And the following also works as expected:

``` scss
img,
%content-box {
    -webkit-box-sizing: content-box;
       -moz-box-sizing: content-box;
            box-sizing: content-box;
}
```
