### ISSUE TITLE
SassError: media query expression must begin with '('

### ISSUE THREAD

**Issue by PeterlitsZo** [sass/libsass#3159]
## input.scss

This is the input scss, I run it with `create-react-app` (sorry I have not idea to get the version of SCSS):
``` SCSS
// For other devides
@media screen and not (max-width: 500px) {
    .forPhone {
        display: none !important;
    }
}
```

This is the report:
```
./src/App.scss
SassError: media query expression must begin with '('
        on line 351 of src/App.scss
>> @media screen and not (max-width: 500px) {

   --------------^
```

The url of bookmark: http://libsass.ocbnet.ch/srcmap/#Ci8vIEZvciBvdGhlciBkZXZpZGVzCkBtZWRpYSBzY3JlZW4gYW5kIG5vdCAobWF4LXdpZHRoOiA1MDBweCkgewogICAgLmZvclBob25lIHsKICAgICAgICBkaXNwbGF5OiBub25lICFpbXBvcnRhbnQ7CiAgICB9Cn0KCg==

But this code can run well in CSS...
