### ISSUE TITLE
extend does not extend all values

### ISSUE THREAD

**Issue by dracos** [sass/libsass#3162]
## input.scss

```scss
.one {
  color: red;
  .foo, .bar { color: yellow; }
  &, &:link, &:visited { color: green; }
  &:hover { color: blue; }
}
.two {
  @extend .one;
}
```

## Actual results

[libsass 3.6.5][1]
```css
.one, .two {
  color: red; }
  .one .foo, .two .foo, .one .bar, .two .bar {
    color: yellow; }
  .one, .two, .one:link, .one:visited {       
    color: green; }
  .one:hover, .two:hover {
    color: blue; }
```

## Expected result

ruby sass 3.7.4
```css
.one, .two {
  color: red; }
  .one .foo, .two .foo, .one .bar, .two .bar {
    color: yellow; }
  .one, .two, .one:link, .two:link, .one:visited, .two:visited {
    color: green; }
  .one:hover, .two:hover {
    color: blue; }
```
version info:
```cmd
libsass-python 0.21.0 [Python]
libsass 3.6.5   (Sass Compiler) [C/C++]
```

[1]: http://libsass.ocbnet.ch/srcmap/#Lm9uZSB7CiAgY29sb3I6IHJlZDsKICAuZm9vLCAuYmFyIHsgY29sb3I6IHllbGxvdzsgfQogICYsICY6bGluaywgJjp2aXNpdGVkIHsgY29sb3I6IGdyZWVuOyB9CiAgJjpob3ZlciB7IGNvbG9yOiBibHVlOyB9Cn0KLnR3byB7CiAgQGV4dGVuZCAub25lOwp9Cg==
