### ISSUE TITLE
Should throw error when root selector has "&"

### ISSUE THREAD

**Issue by nschonni** [sass/libsass#325]
In the Ruby Sass 3.2/3.3 the following will throw the error "Base-level rules cannot contain the parent-selector-referencing character '&'."
```scss
&.bar {
  color: red;
}
```
