### ISSUE TITLE
Problem with browser built-in prefixed values

### ISSUE THREAD

**Issue by paweltin** [sass/libsass#332]
``` scss
input {
    outline: 5px auto -webkit-focus-ring-color;
}
```

Above code is compiled to:

``` css
input {
  outline: 5px auto-webkit-focus-ring-color; }
```

(compass compilation is correct).
