### ISSUE TITLE
@extend not honoring nested selectors

### ISSUE THREAD

**Issue by forestbelton** [sass/libsass#336]
When trying to compile the following SASS:

``` sass
.a {
  & > .child {
    color: #fff;
  }
}

.b { @extend .a; }
```

I get the following output from libsass 1.0.1 / SassC (installed via brew):

``` css
.a > .child {
  color: #fff; }
```

which disagrees with the output from sass (version 3.2.1):

``` css
.a > .child, .b > .child {
  color: #fff; }
```

Is this expected?
