### ISSUE TITLE
RGBA value doesn't work

### ISSUE THREAD

**Issue by omar-jalalzada** [sass/libsass#34]
This code:

``` css
$mw_box_shadow: 0 1px 3px rgba(0,0,0,0.9);
div{
  -webkit-box-shadow: $mw_box_shadow;
}
```

spits out this error:

```
Segmentation fault: 11
```

But this works:

``` css
$mw_box_shadow: 0 1px 3px #333;
div{
  -webkit-box-shadow: $mw_box_shadow;
}
```

Running both of the above as an inline command without supplying the output file:

``` css
$ sassc main.scss
```
