### ISSUE TITLE
Bug with nested %-style extends

### ISSUE THREAD

**Issue by Paxa** [sass/libsass#343]
libsass does not work with `%something` fragments

``` scss
%red {
  color: #f00;
}

%red-and-small {
  @extend %red;
  font-size: 10px;
}

body {
  @extend %red;
}

table {
  border: 3px;
  @extend %red-and-small;
}
```

Should become:

``` css
table, body {
  color: #f00; }

table {
  font-size: 10px; }

table {
  border: 3px; }
```

But with libsass it becomes:

``` css
%red-and-small, body {
  color: #f00; }

table {
  font-size: 10px; }


table {
  border: 3px; }
```
