### ISSUE TITLE
Interpolation of media features errors

### ISSUE THREAD

**Issue by JakeChampion** [sass/libsass#346]
Here's a [snippet](http://sassmeister.com/gist/11435180) to replicate the issue.

I've added the input and output to this issue for future reference.

Input:
``` sass
$mediaquery: 'and (min-width: 300px)';

@media all #{$mediaquery} {
  div {
    display: block;
  }
}
```

Output:
``` css
source string:3: error: expected '{' in media query
```

Expected output:
``` css
@media all and (min-width: 300px) {
  div {
    display: block; } }

```
