### ISSUE TITLE
Errors out on valid gradient syntax

### ISSUE THREAD

**Issue by omar-jalalzada** [sass/libsass#35]
Looks like it doesn't recognize a non-prefixed syntax 

``` css
div {
  // works:
  background-image: -webkit-linear-gradient(top, #2F2727, #1a82f7);
  // breaks:
  background-image: linear-gradient(top, #2F2727, #1a82f7);
  @include background-image(linear-gradient(top, $color1, $color1));
}
```

Error message:

``` md
Segmentation fault: 11
```
