### ISSUE TITLE
Variable (splat) arguments are not correctly passed to aliased function

### ISSUE THREAD

**Issue by lunelson** [sass/libsass#351]
##### edit: this seems rather to be a problem with function aliasing; original post at bottom

Passing a list as splat arguments to a function breaks when that function is an alias of another one. The last line in the test will not compile in libsass but does compile in ruby sass. Example:

``` scss
@function sum($a, $b) {
  @return $a + $b;
}

@function sum2($a, $b, $c) {
  @return $a + $b + $c
}

@function s2($args...) { @return sum2($args...); }

$arglist: 2 3;

.test {
  out: sum(2,3);
  out: sum($arglist...);
  out: sum2(1, 2, 3);
  out: sum2(1, $arglist...);
//  out: s2(1, $arglist...); // THIS line would cause compiler to fail
}
```

``` css
.test {
  out: 5;
  out: 5;
  out: 6;
  out: 6; }
```

See also http://sassmeister.com/gist/14bd5c69681a806c8c8a

---
##### (original post)

A function receiving a variable-length arglist does not pass these arguments on correctly when calling a subsequent function. Example:

``` scss
@function foo($incoming...) { @return bar($something, $incoming...); }
```

The following gist compiles correctly in sass 3.2 but not in libsass:

http://sassmeister.com/gist/11560891
