### ISSUE TITLE
Implement @at-root selectors [$15]

### ISSUE THREAD

**Issue by Ne-Ne** [sass/libsass#353]
I have noticed that when using:

    @at-root

With this code:

	@at-root{
		.list-date{
			float: left;
			display: block;
			width: 90px;
			height: 80px;
			margin-right:25px;
			color:white;
			background:url(/images/list-date-bg.svg) center no-repeat;

				.no-svg &{
					background-images:url(/images/list-date-bg.png);
				}

				[class^='date-']{
					display: block;
					width: 100%;
					text-align: center;
				}

				.date-day{
					margin-top:6px;
					@include font-size(5.4,5.4);
				}

				.date-month{
					@include font-size(1.5,1.5);
				}
		}
	}

The code gets compiled correctly but Autoprefixer breaks, however this does not happen when running Sass 3.3.5. I am currently using Codekit 2.0.4

Mixin Above:

	@mixin font-size($size:1.6, $line: $size * 1.5){
	    line-height: ($line * 10) + px;
	    font-size:   ($size * 10) + px;
	}

Can someone double check this.

**Comment by xzyfer** [comment]
Specs added https://github.com/sass/sass-spec/pull/175

**Comment by wintercounter** [comment]
SassMeister was using 3.1 beta for a little bit and tried it.

Test Code:
```scss
.outer {
  content: 'outer';
  
  @at-root {
    .inner {
      content: 'inner';
    }
  }
}
```

Wrong Output:
```css
.outer {
  content: 'outer';
  @at-root {
    .inner {
      content: 'inner'; } }
 }
```

Expected:
```css
.outer {
  content: 'outer';
}
.inner {
  content: 'inner';
}
```
