### ISSUE TITLE
Allow trailing commas in lists

### ISSUE THREAD

**Issue by lunelson** [sass/libsass#359]
It's a convenience thing; but ruby-sass allows lists to have commas after the last item. In fact, it is the most concise way to force a single-item list to be recognized as a list, which has many uses and avoids dumb syntax errors. It throws an error in libsass however. In ruby sass it works as follows:

``` scss
$mylist: (alpha, beta, gamma,);
$my-single-item-list: (alpha,);
.test { out: length($my-single-item-list); }
```

``` css
.test { out: 1; }
```
