### ISSUE TITLE
Unexpected color conversion in selector interpolation.

### ISSUE THREAD

**Issue by bfanger** [sass/libsass#360]
## Sass

``` scss
@each $color in (red, green, blue) {
    .bg-#{$color} {
        background-color: $color;
    }
}
```
## Generated CSS

``` css
.bg-#ff0000 {
  background-color: red; }

.bg-#008000 {
  background-color: green; }

.bg-#0000ff {
  background-color: blue; }
```
## Expected output:

``` css
.bg-red {
  background-color: red; }

.bg-green {
  background-color: green; }

.bg-blue {
  background-color: blue; }
```

I'm using gulp-sass
