### ISSUE TITLE
variable substitution error

### ISSUE THREAD

**Issue by bennyschudel** [sass/libsass#379]
``` scss
@mixin module (
    $name : 'module'
) {
    .#{$name}--hidden {
        display : none;
    }
}

@include module();
```

gives me error: invalid property name

anyone else having this problem?
