### ISSUE TITLE
Syntax: Multiline comments break for unsupported features

### ISSUE THREAD

**Issue by am11** [sass/libsass#424]
While testing this issue: https://github.com/madskristensen/WebEssentials2013/issues/1162, I came across a bug with multiline comments.

This code:

``` scss
footer {
    color: red;
}

// Ampersand in SassScript:
/*.button {
    &-primary {
        background: orange;
    }

    &-secondary {
        background: blue;
    }
}*/

// Output:
.button-primary {
    background: orange;
}

.button-secondary {
    background: blue;
}
```

compiles to:

``` css
footer {
  color: red; }

/*.button {
    &-primary {
        background: orange;
    }

    &-secondary {
        background: blue;
    }
}*/
.button-primary {
  background: orange; }

.button-secondary {
  background: blue; }
```

But this:

``` scss
footer {
    color: red;
}

/*@each $header, $size in (h1: 2em, h2: 1.5em, h3: 1.2em) {
    #{$header} {
        font-size: $size;
    }
}*/

// Ampersand in SassScript:
/*.button {
    &-primary {
        background: orange;
    }

    &-secondary {
        background: blue;
    }
}*/

// Output:
.button-primary {
    background: orange;
}

.button-secondary {
    background: blue;
}
```

<I><b>throws on compile</b> (as maps with multi-vars are not supported yet: #394).</I>

But with single-line comments:

``` scss
footer {
    color: red;
}

///*@each $header, $size in (h1: 2em, h2: 1.5em, h3: 1.2em) {
//    #{$header} {
//        font-size: $size;
//    }
//}*/

// Ampersand in SassScript:
/*.button {
    &-primary {
        background: orange;
    }

    &-secondary {
        background: blue;
    }
}*/

// Output:
.button-primary {
    background: orange;
}

.button-secondary {
    background: blue;
}
```

it compiles to:

``` css
footer {
  color: red; }

/*.button {
    &-primary {
        background: orange;
    }

    &-secondary {
        background: blue;
    }
}*/
.button-primary {
  background: orange; }

.button-secondary {
  background: blue; }
```

(Also note: multi-line comments are retained in the output, while single-line comments are not. I think they can be transformed to multi-line comments syntax for CSS valid output)
