### ISSUE TITLE
Placeholder selector issues

### ISSUE THREAD

**Issue by errorx666** [sass/libsass#439]
I have the following mixins designed to emulate `:nth-child(even)` and `:nth-child(odd)` in IE8.  I am having two problems that do not occur in the default Sass implementation:

```scss
@mixin odd( $selector: '*', $n: 50 ) {
	$local-sel: '&';
	$local-uniq: unique_id();

	#{$selector}:nth-child(odd) { @content }

	%#{$local-uniq} { @content; }

	#{$selector}:first-child {
		@for $i from 1 through $n {
			#{$local-sel} { @extend %#{$local-uniq}; }

			$local-sel: $local-sel + ' + ' + $selector + ' + ' + $selector;

		}

	}

}

@mixin even( $selector: '*', $n: 50 ) {
	$local-sel: '&';
	$local-uniq: unique_id();

	#{$selector}:nth-child(even) { @content }

	%#{$local-uniq} { @content; }

	#{$selector}:first-child + #{$selector} {
		@for $i from 1 through $n {
			#{$local-sel} { @extend %#{$local-uniq}; }

			$local-sel: $local-sel + ' + ' + $selector + ' + ' + $selector;

		}

	}

}
```

An example use-case is:
```scss
ul > {
  @include odd( li, 5 ) { background: #ccc;  }
}
```
Which in Sass 3.3.9 produces:
```css
ul > li:nth-child(odd) {
  background: #ccc;
}
ul > li:first-child, ul > li:first-child + li + li, ul > li:first-child + li + li + li + li, ul > li:first-child + li + li + li + li + li + li, ul > li:first-child + li + li + li + li + li + li + li + li {
  background: #ccc;
}
```

In LibSass I get: `source string:7: error: invalid selector after %unique-id`

---
The unique ID is needed to stop successive invocations from using the same placeholder selector.

If I replace the unique ID, I get a successful compile, but the selectors do not match the Sass implementation:

```scss
@mixin odd( $selector: '*', $n: 50 ) {
	$local-sel: '&';

	#{$selector}:nth-child(odd) { @content }

	%foo { @content; }

	#{$selector}:first-child {
		@for $i from 1 through $n {
			#{$local-sel} { @extend %foo; }

			$local-sel: $local-sel + ' + ' + $selector + ' + ' + $selector;

		}

	}

}

ul > {
  @include odd( li, 5 ) { background: #ccc;  }
}
```

Expected:
```css
ul > li:nth-child(odd) {
  background: #ccc;
}
ul > li:first-child, ul > li:first-child + li + li, ul > li:first-child + li + li + li + li, ul > li:first-child + li + li + li + li + li + li, ul > li:first-child + li + li + li + li + li + li + li + li {
  background: #ccc;
}
```

Actual:
```css
ul > li:nth-child(odd) {
  background: #ccc; }
ul > ul > li:first-child, ul > ul > li:first-child + li + li, ul > ul > li:first-child + li + li + li + li, ul > ul > li:first-child + li + li + li + li + li + li, ul > ul > li:first-child + li + li + li + li + li + li + li + li {
  background: #ccc; }
```

Note the `ul > ul >` which should not appear.  This may be related to the ampersand in the selector.

**Comment by xzyfer** [comment]
This spec for this issue is passing, however it does not cover the issue at hand. I've update the now failing spec https://github.com/sass/sass-spec/pull/242.

**Comment by xzyfer** [comment]
It's worth mentioning `unique-id` has now been implemented but it is not the cause of the issue.

**Comment by mgreter** [comment]
Btw. I currently get these results for libsass 3.2.4 and ruby sass 3.4.13 (stripped down):
```css
ul > li:first-child, ul > li:first-child + ul > li + li, ul > li:first-child + li + li + ul > li + li, ul > li:first-child + li + li + li + li + ul > li + li, ul > li:first-child + li + li + li + li + li + li + ul > li + li // libsass
ul > li:first-child, ul > li:first-child + li + li, ul > li:first-child + li + li + li + li, ul > li:first-child + li + li + li + li + li + li, ul > li:first-child + li + li + li + li + li + li + li + li // ruby sass
```

I'm pretty sure that this is solved once we implement `is_superselector` correctly.

**Comment by mgreter** [comment]
I was able to further reduce the test case. Once I followed all the calls by comparing to ruby sass, I was able to locate the error, which was a simple copy paste error from converting that sass code.
```scss
@mixin odd() {
    %test { background: #ccc; }
    P {
      #{'UL > div + DIV'} { @extend %test; }
    }
}

UL > {
  @include odd();
}
```
