### ISSUE TITLE
Dot in front of SassScript, inside @each loop fails

### ISSUE THREAD

**Issue by paazmaya** [sass/libsass#445]
The following Sass:

``` sass
$selector: body

.#{$selector}
  display: none

@each $color in red, green, blue
  .#{$color}
    color: rebeccapurple
```

produces the following CSS when compiled via latest release of Ruby Sass, `sass segmentation-fault.sass segmentation-fault.css`:

``` css
.body {
  display: none; }

.red {
  color: rebeccapurple; }

.green {
  color: rebeccapurple; }

.blue {
  color: rebeccapurple; }
```

While using the latest dev versions of libsass and sassc, `sassc segmentation-fault.sass segmentation-fault.css`:

``` sh
segmentation-fault.sass:7: error: invalid selector after 
```

It seems to fail on the dot `.` which is placed inside the `@each`, in front of the SassScript block.

In case the dot is removed, the output is following:

``` css
.body {
  display: none; }

#ff0000 {
  color: rebeccapurple; }

#008000 {
  color: rebeccapurple; }

#0000ff {
  color: rebeccapurple; }
```

The expected behaviour would be to provide same output as the Ruby version, as libsass seems to until getting inside the `@each` loop.
