### ISSUE TITLE
@extend is broken with nested selectors

### ISSUE THREAD

**Issue by bradrobertson** [sass/libsass#449]
I've made [this repo](https://github.com/bradrobertson/libsass-extend) to show the discrepancy between libsass and sass-ruby.

`src/` contains the sass files and `assets/` contains the compiled css files, done through both libsass and ruby-sass. I did this through gulp, but it also fails through `sassc` so I'm guessing it falls on libsass's plate rather than gulp-sass.

TL;DR the difference in sass compilations is this:

This is the original sass code

``` scss
// util/_extensions.scss
.menu {
  display: inline-block;
}
.menu ul {
  list-style: none;
}

// app.scss
.my-nav {
  @extend .menu;
}
```

Compiled by ruby-sass, we get:

``` css
.menu, .my-nav {
  display: inline-block; }

.menu ul, .my-nav ul {
  list-style: none; }
```

Which is correct, but compiled by libsass (using gulp-sass) we get:

``` css
.menu, .my-nav {
  display: inline-block; }

.menu ul, .menu .my-nav {
  list-style: none; }
```

Which clearly is wrong. And using the `sassc` command line:

``` ruby
.menu, .my-nav {
  display: inline-block; }

.menu ul {
  list-style: none; }
```

Which is super wrong.

Looks like nested rules are broken with libsass?
