### ISSUE TITLE
Breaks on CSS Variables

### ISSUE THREAD

**Issue by mgol** [sass/libsass#453]
The following valid CSS:

``` css
div {
    --a: 2px;
    top: var(--a);
}
```

breaks when passed through libsass with an error:

```
error: invalid property name
```

CSS Variables are already supported by Firefox 31 that was released a few days ago. They're available without any prefix. libsass shouldn't break this valid CSS.

See also: https://github.com/sass/sass/issues/1128
