### ISSUE TITLE
Sass maps cause a segmentation fault

### ISSUE THREAD

**Issue by mgol** [sass/libsass#454]
I have a main `styles.scss` file containing `@import`s from many SCSS files in the project. One of them is:

``` scss
$z-index: (
    modal: 10000,
    tooltip: 9000,
    item-pane-full: 8000,
    header-element: 7000,
    dropdown: 6000,
    header: 5000,
    footer: 4000,
    item-pane: 3000,
    flatpage: 2000,
    item-pane-shown: 1000,
    content: 0
);

@mixin on-layer($identifier, $delta: 0) {
    z-index: map-get($z-index, $identifier) + $delta;
}
```

Compiling such a structure using [grunt-sass](https://github.com/sindresorhus/grunt-sass) which uses [node-sass](https://github.com/sass/node-sass) which uses libsass causes a segmentation fault.

Now, I realise libsass doesn't support maps yet but it should just error on invalid syntax then instead of segfaulting.
