### ISSUE TITLE
CSS file imports compiled in wrong order

### ISSUE THREAD

**Issue by renestalder** [sass/libsass#469]
What my SCSS file looks like

```scss
/*!
Theme URI: http://mywebsite.com
Description: my theme description
Author: whatwedo GmbH
Template: Meola
Version: 0.1
*/

// Parent Theme
@import url("../meola/style.css");

// Thirt Party Components
@import '../../bower_components/bourbon/dist/bourbon';

...
```

What the compiled CSS output looks like

```css
@import url("../meola/style.css");
/*!
Theme URI: http://mywebsite.com
Description: my theme description
Author: whatwedo GmbH
Template: Meola
Version: 0.1
*/
body {
  font-family: 'Ek Mukta', 'Helvetica Neue', 'Helvetica', sans-serif;
  font-weight: 300; }

a, .entry-header h2.entry-title a:hover, .widget-area .widget_meola_recentposts h3.entry-title a:hover, .widget-area .widget_twitter h3.widget-title a:hover {
  color: #0699a6; }

...
```

The regular CSS import should be bellow the code comment.

In addition, It seems like in compressed mode, instead of the import statement I get the code of the source file. Is this the wanted behaviour?
