### ISSUE TITLE
@supports blocks cause parse error

### ISSUE THREAD

**Issue by mgol** [sass/libsass#483]
The following Sass mixin:

``` scss
@mixin will-change($properties: transform, $transform: "") {
    transform: translateZ(0) #{$transform};
    @supports (will-change: $properties) {
        will-change: $properties;
        @if ($transform != "") {
            transform: $transform;
        } @else {
            transform: none;
        }
    }
}
```

breaks `libsass` with an error message:

```
file:3: error: error reading values after will-change
```

This is `node-sass` 0.9.4, using `libsass` from commit 0aa6621, i.e. the newest one.
