### ISSUE TITLE
Suppress empty `@media` queries

### ISSUE THREAD

**Issue by lunelson** [sass/libsass#513]
In certain mixin routines (of mine at least) it is possible to end up generating `@media` blocks with no content. In Ruby sass these are simply suppressed but in libsass they are output. 

Such empty declarations should be suppressed, similar to the logic of `null` values on properties.

``` scss
.foo {
  @media screen {}
  @media print {
    bar: baz;
  }
}
```

``` css
@media screen { }
@media print {
  .foo {
    bar: baz; } }
```
