### ISSUE TITLE
If source map is generated, there should be no source line comments

### ISSUE THREAD

**Issue by mgol** [sass/libsass#551]
With libsass 3.0.0 even if source maps are generated, the resulting CSS file still contains source line comments like:

``` css
  /* line 137, /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/app/core-styles/lists */
```

This is unnecessary; Ruby Sass doesn't generate these comments. An example:

The following SCSS:

``` scss
a,
div {
    top: 0;
}
```

is generated by Sass 3.4.5 to the following CSS (when output style is set to nested):

``` css
a,
div {
  top: 0; }

/*# sourceMappingURL=styles.css.map */
```

Meanwhile, libsass 3.0 converts it to:

``` css
/* line 2, /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/app/styles.scss */
a, div {
  top: 0; }

/*# sourceMappingURL=styles.css.map */
```

Note the comment line

Another issue with this example: #552
