### ISSUE TITLE
map-merge() fails when maps share a key

### ISSUE THREAD

**Issue by mirisuzanne** [sass/libsass#554]
Map-merge breaks when both maps have the same key — which leaves you no way to update the value of a key.

``` scss
// input
$test: map-merge((foo: 1, bar: 2), (foo: 3));

.test {
  @each $key in map-keys($test) {
    #{$key}: map-get($test, $key);
  }
}

// output
.test {
  foo: 1;
  bar: 2;
  foo: 1; }
```

There's a hack that kinda works, but it get's the order wrong:

``` scss
@function map-please-merge($map1, $map2) {
  $return: $map1;

  @each $key in map-keys($map2) {
    $return: map-remove($return, $key);
  }

  @return map-merge($return, $map2);
}

.test {
  bar: 2;
  foo: 3; }
```
