### ISSUE TITLE
map equality check is more strict than ruby sass

### ISSUE THREAD

**Issue by mirisuzanne** [sass/libsass#556]
Ruby Sass doesn't compare the order of key/value pairs.

``` scss
// input
$test: (
  one: 1,
  two: 2,
);

$expect: (
  two: 2,
  one: 1,
);

.test {
  equal: $test == $expect;
}

// ruby output
.test {
  equal: true; }

// libsass output
.test {
  equal: false; }
```
