### ISSUE TITLE
Broken behavior with media queries

### ISSUE THREAD

**Issue by dahlia** [sass/libsass#56]
The following SCSS cause segmentation fault:

``` scss
@media (min-width: 980px) {
    a {
        color: red;
    }
}
```

``` console
$ bin/sassc t.scss 
Segmentation fault: 11
```

It seems a regression, because it worked well at least when it’s 322edca.

(Forwarded from dahlia/libsass-python#2.)
