### ISSUE TITLE
Media Query rule-sets are removed when using compressed outputStyle

### ISSUE THREAD

**Issue by tylergaw** [sass/libsass#566]
Seems this is the same underlying issue as #560, but it's more widespread than the title of that issue. This issue effects all Media queries.

Using `node-sass 1.0.1`
#### node-sass setup:

``` javascript
var sass = require('node-sass');
sass.renderFile({
  file: 'app.scss',
  outFile: 'app.css',
  outputStyle: 'compressed',
  success: function (outFile) {
    console.log('Compiled to', outFile);
  }
```
#### SCSS:

``` scss
@media screen and (min-width: 400px) {
  body {
    background-color: purple;
  }
}
```
#### Compiled CSS:

``` css
@media screen and (min-width: 400px){}
```
#### Expected Compiled CSS:

``` css
@media screen and (min-width: 400px){body{background-color:purple}}
```

Sample project: https://github.com/tylergaw/libsass-mq-issue
