### ISSUE TITLE
Broken interpolation in map keys

### ISSUE THREAD

**Issue by mirisuzanne** [sass/libsass#574]
``` scss
// input
$flow: left;

$map: (
  margin-#{$flow}: 3em,
  foo: bar,
);

.test {
  margin-left: map-get($map, margin-left);
}

// error:
// line 5: unclosed parenthesis
```
