### ISSUE TITLE
Can't define a map inside `@if` conditions

### ISSUE THREAD

**Issue by mirisuzanne** [sass/libsass#575]
``` scss
// Input
.test {
  @if (foo: bar) == (foo: bar) {
    foo: bar;
  }
}

// Error:
// Line 3: error reading values after )
```
