### ISSUE TITLE
Map loops break inside functions

### ISSUE THREAD

**Issue by mirisuzanne** [sass/libsass#577]
`@each` loops are working great for me... until I put them in a function. Then the `$value` side of the pair no longer gets assigned properly. Very odd.

``` scss
// Input
@function map-each($map) {
  $values: ();

  @each $key, $value in $map {
    $values: append($values, $value);
  }

  @return $values;
}

$map: (foo: bar);

.test {
  -map-test: map-each($map);
}

// Error
// Line 6: unbound variable $value
```
