### ISSUE TITLE
Maps don't work as variable arguments

### ISSUE THREAD

**Issue by mirisuzanne** [sass/libsass#579]
Variable arguments are supported and work well with expanded lists, but don't work yet with maps:

``` scss
// Input
$map: (
  foo: fump,
  bar: bump,
);

@mixin vararg-test($foo, $bar) {
  foo: $foo;
  bar: $bar;
}

.test {
  @include vararg-test($map...);
}

// Output
// Line 3: mixin vararg-test has no parameter named ?AX?
```
