### ISSUE TITLE
Number comparison is different to ruby sass

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#590]
I've was looking the current failing specs and noticed a common theme of broken number comparisons. A bunch of outstanding bugs boil down to the following evaluating to `true` in ruby sass and `false` in libsass.

``` scss
a { 
  a: 1/2;
  b: 0.5;
  c: (1/2);
  d: 1/2 == 0.5;
  e: (1/2) == 0.5;
}
```

Output in Sass 3.4

``` css
a {
  a: 1/2;
  b: 0.5;
  c: 0.5;
  d: true;
  e: true; }
```

Output in Libsass 3.0.0

``` css
a {
  a: 1/2;
  b: 0.5;
  c: 0.5;
  d: false;
  e: true; }
```

Specs added https://github.com/sass/sass-spec/pull/137.

**Comment by ericam** [comment]
@xzyfer This bug seems to be only partially fixed in 3.1 (I haven't tested against 3.2). The problem still exists when you retrieve a fraction from a map. See [my example on SassMeister](http://sassmeister.com/gist/343bdc4fca70f77007ca).

**Comment by xzyfer** [comment]
I can confirm this issue is fixed in 3.2 @ericam 

```css
.test {
  integer: true;
  decimal: true;
  fraction: true; }
```
