### ISSUE TITLE
Deep @extend specificity problems

### ISSUE THREAD

**Issue by mzgol** [sass/libsass#592]
The following SCSS input:
```scss
%a {
    &::-webkit-scrollbar {
        color: green;
    }
}
%b {
    @extend %a;
}

.a {
    .b {
        @extend %a;
    }

    .c {
        .b {
            @extend %b;
        }
    }
}
```
is compiled via Ruby Sass (3.4.5) to:
```css
.a .c .b::-webkit-scrollbar, .a .b::-webkit-scrollbar {
  color: green; }
```

and via libsass (using node-sass 1.1.4) to:
```css
.a .b::-webkit-scrollbar {
  color: green; }
```
