### ISSUE TITLE
Loss of spaces in interpolated selectors

### ISSUE THREAD

**Issue by mzgol** [sass/libsass#593]
The following:
```scss
h1:nth-of-type(#{2 + 'n + 1'}) {
    color: red;
}
```
is transformed by libsass to:
```css
h1:nth-of-type(2n+1) {
  color: red; }
```
As you can see, spaces around the `+` are lost. Ruby Sass (3.4.5) preserves them.

**Comment by mgreter** [comment]
This actually seems to be simpler than expected, as it probably has nothing to do with interpolation

```CSS
h1:nth-of-type(2n + 1) {
    color: red;
}
```

This show the same difference between ruby sass and libsass. For me it looks like ruby sass parses the `2n + 1` as a static value, since I saw pretty much the same thing with other static values.
