### ISSUE TITLE
semi-colon triggers an error

### ISSUE THREAD

**Issue by mgol** [sass/libsass#595]
The following SCSS:

``` scss
a {
    color: red;
};
```

is compiled by Ruby Sass 3.4.5 to:

``` css
a {
    color: red;
}
```

libsass gives an error:

```
styles.scss:3: invalid top-level expression
```
