### ISSUE TITLE
@charset is ignored

### ISSUE THREAD

**Issue by kwliou** [sass/libsass#604]
The `@charset` is not getting output.

``` scss
// test.scss
@charset "UTF-8"; // this line is actually optional for Ruby Sass
.icon-check:before {
  content: "✓";
}
```

``` css
/* Sass 3.4 output */
@charset "UTF-8";
.icon-check:before {
  content: "✓"; }
```

``` css
/* sassc output */
.icon-check:before {
  content: "✓"; }
```
