### ISSUE TITLE
Nested output style is incorrect for @-queries without selectors

### ISSUE THREAD

**Issue by mgol** [sass/libsass#622]
The following input:

``` scss
@media screen {
    a {
        color: red;
    }
}
```

is transformed by libsass to:

``` css
@media screen {
  a {
    color: red; }
 }
```

Ruby Sass returns (in nested mode):

``` css
@media screen {
  a {
    color: red; } }
```
