### ISSUE TITLE
nth() doesn't handle maps

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#643]
> This can return the nth pair in a map as well. - http://sass-lang.com/documentation/Sass/Script/Functions.html#nth-instance_method

``` scss
$map: (foo: bar, bar: baz);

foo {
  a: nth($map, 2);
}
```

Expected output

``` css
foo {
  a: bar baz;
}
```

Actual output

``` css
stdin:4: index out of bounds for `nth($list, $n)`
```
