### ISSUE TITLE
`map-merge()` error: error reading values after ...

### ISSUE THREAD

**Issue by flovan** [sass/libsass#656]
I am having a problem when trying to use @at-import's [toolkit](https://github.com/at-import/toolkit). After ploughing my way through previous issues from this repo, as well as various blogposts, etc, I found no real solution and decided to just post an issue before switching back to the Ruby implementation :sadface:

I am using a specific part of Toolkit to generate and extend placeholder classes:

``` css
$Private-Toolkit-Placeholders: ();

//////////////////////////////
// Placeholder Get/Set
//////////////////////////////
@function toolkit-placeholder-set($id) {
  $unique-id: unique-id();
  $Private-Toolkit-Placeholders: map-merge($Private-Toolkit-Placeholders, ($id: $unique-id)) !global;
  @return $unique-id;
}

@function toolkit-placeholder-get($id) {
  @return map-get($Private-Toolkit-Placeholders, $id);
}

//////////////////////////////
// Generate Placeholder Class and Extend
//////////////////////////////
@mixin dynamic-extend($id) {
  $placeholder-id: toolkit-placeholder-get($id);

  @if $placeholder-id == null {
    $placeholder-id: toolkit-placeholder-set($id);
    @at-root %#{$placeholder-id} {
      @content;
    }
  }
  @extend %#{$placeholder-id};
}
```

The error thrown is the following:

```
[16:19:13] [gulp-sass] /Applications/MAMP/htdocs/test/assets/sass/base/functions:74: error: error reading values after $id
```

Which is caused by this line:

``` css
$Private-Toolkit-Placeholders: map-merge($Private-Toolkit-Placeholders, ($id: $unique-id)) !global;
```

I am using [gulp-sass](https://github.com/dlmanning/gulp-sass) v1.2.3 which uses [node-sass](https://github.com/sass/node-sass) v1.0 (but I'm unsure which version of libsass is used by that one). I am seriously considering dropping this way of generating placeholder classes, even though it reduces the amount of generated css. Speed over size, or maybe there's a solution?
