### ISSUE TITLE
Not expression incorrectly evaluated in declarations

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#660]
Under some circumstances not expressions need to be evaluated in declarations.

``` scss
$foo: true;
div {
  blah: $foo; }

div {
  blah: not $foo; }

div {
  blah: not (true); }

div {
  blah: not true; }
```

Expected output

``` css
div {
  blah: true; }

div {
  blah: false; }

div {
  blah: false; }

div {
  blah: not true; }
```

Actual output

``` css
div {
  blah: true; }

div {
  blah: not true; }

div {
  blah: not true; }

div {
  blah: not true; }
```

Specs added https://github.com/sass/sass-spec/pull/143.
