### ISSUE TITLE
keywords($args) does not default to empty map

### ISSUE THREAD

**Issue by jakob-e** [sass/libsass#672]
When passing non-keyword-arguments keyword function trows 
Error: basic_string::basic_string rather than creating an empty map 

``` SCSS

@mixin mixin($arglist...){
    $map: keywords($arglist);
}

.test {
    // As expected 
    // $map: (width: 200px, height: 100px);  
   @include mixin( $width: 200px, $height: 100px);

   // As expected 
   // $map: ();
   @include mixin( );

    // Throws: "Error: basic_string::basic_string"
    // Expected $map: ();  
   @include mixin( not-keyword-format );
}








```
