### ISSUE TITLE
Fractions aren't treated as numbers

### ISSUE THREAD

**Issue by mirisuzanne** [sass/libsass#682]
This seems to be a known issue and have (somewhat roundabout) tests according to #629, but I wanted to track it with an issue all it's own. :)

``` scss
// test:
.fractions {
  -test: 1/4 > 0;
}

// current output: "may only compare numbers"
```
