### ISSUE TITLE
Converting absolute lengths

### ISSUE THREAD

**Issue by jakob-e** [sass/libsass#688]
In relation to https://github.com/sass/libsass/issues/666 – absolute lengths does not convert as expected.

``` SCSS
test {
  /* Convert to px  */
  px-to-px: 0px + 1px;
  pt-to-px: 0px + 1pt;
  pc-to-px: 0px + 1pc;
  in-to-px: 0px + 1in;
  mm-to-px: 0px + 1mm;
  cm-to-px: 0px + 1cm;
  /* Convert to pt  */
  px-to-pt: 0pt + 1px;
  pt-to-pt: 0pt + 1pt;
  pc-to-pt: 0pt + 1pc;
  in-to-pt: 0pt + 1in;
  mm-to-pt: 0pt + 1mm;
  cm-to-pt: 0pt + 1cm;
  /* Convert to pc  */
  px-to-pc: 0pc + 1px;
  pt-to-pc: 0pc + 1pt;
  pc-to-pc: 0pc + 1pc;
  in-to-pc: 0pc + 1in;
  mm-to-pc: 0pc + 1mm;
  cm-to-pc: 0pc + 1cm;
  /* Convert to in  */
  px-to-in: 0in + 1px;
  pt-to-in: 0in + 1pt;
  pc-to-in: 0in + 1pc;
  in-to-in: 0in + 1in;
  mm-to-in: 0in + 1mm;
  cm-to-in: 0in + 1cm;
  /* Convert to mm  */
  px-to-mm: 0mm + 1px;
  pt-to-mm: 0mm + 1pt;
  pc-to-mm: 0mm + 1pc;
  in-to-mm: 0mm + 1in;
  mm-to-mm: 0mm + 1mm;
  cm-to-mm: 0mm + 1cm; 
  /* Convert to cm  */
  px-to-cm: 0cm + 1px;
  pt-to-cm: 0cm + 1pt;
  pc-to-cm: 0cm + 1pc;
  in-to-cm: 0cm + 1in;
  mm-to-cm: 0cm + 1mm;
  cm-to-cm: 0cm + 1cm;   
}
```

``` CSS
/* Output */
test {
  /* Convert to px  */
  px-to-px: 1px;
  pt-to-px: 1px;
  pc-to-px: 1px;
  in-to-px: 1px;
  mm-to-px: 1px;
  cm-to-px: 1px;
  /* Convert to pt  */
  px-to-pt: 1pt;
  pt-to-pt: 1pt;
  pc-to-pt: 1pt;
  in-to-pt: 1pt;
  mm-to-pt: 1pt;
  cm-to-pt: 1pt;
  /* Convert to pc  */
  px-to-pc: 1pc;
  pt-to-pc: 1pc;
  pc-to-pc: 1pc;
  in-to-pc: 1pc;
  mm-to-pc: 1pc;
  cm-to-pc: 1pc;
  /* Convert to in  */
  px-to-in: 1in;
  pt-to-in: 1in;
  pc-to-in: 1in;
  in-to-in: 1in;
  mm-to-in: 1in;
  cm-to-in: 1in;
  /* Convert to mm  */
  px-to-mm: 1mm;
  pt-to-mm: 1mm;
  pc-to-mm: 1mm;
  in-to-mm: 1mm;
  mm-to-mm: 1mm;
  cm-to-mm: 1mm;
  /* Convert to cm  */
  px-to-cm: 1cm;
  pt-to-cm: 1cm;
  pc-to-cm: 1cm;
  in-to-cm: 1cm;
  mm-to-cm: 1cm;
  cm-to-cm: 1cm; 
}
```

``` CSS
/* Expected */
test {
  /* Convert to px  */
  px-to-px: 1px;
  pt-to-px: 1.33333px;
  pc-to-px: 16px;
  in-to-px: 96px;
  mm-to-px: 3.77953px;
  cm-to-px: 37.79528px;
  /* Convert to pt  */
  px-to-pt: 0.75pt;
  pt-to-pt: 1pt;
  pc-to-pt: 12pt;
  in-to-pt: 72pt;
  mm-to-pt: 2.83465pt;
  cm-to-pt: 28.34646pt;
  /* Convert to pc  */
  px-to-pc: 0.0625pc;
  pt-to-pc: 0.08333pc;
  pc-to-pc: 1pc;
  in-to-pc: 6pc;
  mm-to-pc: 0.23622pc;
  cm-to-pc: 2.3622pc;
  /* Convert to in  */
  px-to-in: 0.01042in;
  pt-to-in: 0.01389in;
  pc-to-in: 0.16667in;
  in-to-in: 1in;
  mm-to-in: 0.03937in;
  cm-to-in: 0.3937in;
  /* Convert to mm  */
  px-to-mm: 0.26458mm;
  pt-to-mm: 0.35278mm;
  pc-to-mm: 4.23333mm;
  in-to-mm: 25.4mm;
  mm-to-mm: 1mm;
  cm-to-mm: 10mm;
  /* Convert to cm  */
  px-to-cm: 0.02646cm;
  pt-to-cm: 0.03528cm;
  pc-to-cm: 0.42333cm;
  in-to-cm: 2.54cm;
  mm-to-cm: 0.1cm;
  cm-to-cm: 1cm;
}

```
