### ISSUE TITLE
`rebeccapurple` not recognized as a color

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/libsass#699]
Test:

``` scss
.selector {
  color: invert(rebeccapurple);
}
```

Expected:

``` css
.selector {
  color: #99cc66;
}
```

Result:

``` css
stdin:2: argument `$color` of `invert($color)` must be a color
Backtrace:
    stdin:2, in function `invert`
    stdin:2
```

Ref: http://sass-compatibility.github.io/#rebeccapurple_color.
