### ISSUE TITLE
`transparent` not recognized as a color

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/libsass#700]
Test:

``` scss
.selector {
  color: invert(transparent);
}
```

Expected:

``` css
.selector {
  color: rgba(255, 255, 255, 0);
}
```

Result:

``` css
stdin:2: argument `$color` of `invert($color)` must be a color
Backtrace:
    stdin:2, in function `invert`
    stdin:2
```

Ref: http://sass-compatibility.github.io/#transparent_color.
