### ISSUE TITLE
`inspect` function not supported

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/libsass#701]
Test:

``` scss
.selector {
  content: inspect("string");
}
```

Expected:

``` css
.selector {
  content: "string";
}
```

Result:

``` css
.selector {
  content: inspect("string");
}
```

Ref: http://sass-compatibility.github.io/#inspect_function
