### ISSUE TITLE
`feature-exists` function not supported

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/libsass#702]
Test:

``` scss
.selector {
  content: function-exists("feature-exists");
}
```

Expected:

``` css
.selector {
  content: true;
}
```

Result:

``` css
.selector {
  content: false;
}
```
