### ISSUE TITLE
Decrementing for loops do not work

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/libsass#703]
Test:

``` scss
.selector {
  @for $i from 3 through 1 {
    content: $i;
  }
}
```

Expected:

``` css
.selector {
  content: 3;
  content: 2;
  content: 1;
}
```

Result:

``` css
// Empty
```

Ref: http://sass-compatibility.github.io/#downward_for
