### ISSUE TITLE
Reserved function names

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/libsass#713]
Sass should throw an error if one tries to create functions called `or`, `and` and `not`. This is an issue I opened in Sass repo a while ago: https://github.com/sass/sass/issues/1265.

Test:

``` scss
@function and() {
  @return "and";
}

@function or() {
  @return "or";
}

@function not() {
  @return "not";
}

test {
  not: not();
  or: or();
  and: and();
}

```

Expect:

``` css
Invalid function name "and".
```

Result:

``` css
test {
  not: "not";
  or: "or";
  and: "and"; }

```

Ref: http://sass-compatibility.github.io/#reserved_function_names
