### ISSUE TITLE
parsing of 'filter:' styles fails

### ISSUE THREAD

**Issue by gregtillbrook** [sass/libsass#72]
It looks like the parser has trouble with filter styles. 

Examples being;

background gradients common include things like;

``` css
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#223344', endColorstr='#112233',GradientType=0 );
```

libsass errors with  `error reading values after progid`

also, this opacity mixin;

``` css
@mixin opacity($opacity) {
    opacity: $opacity / 100;
    filter: alpha(opacity=$opacity);
}
```

causes the error  `error reading values after opacity` (referring to the filter line)

This may seem like a redundant issue given that filters were IE only and have now been dropped by microsoft in favour of CSS3 - but they're crucial for writing cross browser styles.

Cheers,
Greg
