### ISSUE TITLE
Map with quoted keys as variable arguments

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/libsass#721]
Test:

``` scss
// Test 1
@mixin test($a, $b) {
  content: $a $b;
}

test {
  @include test(("a": 1, "b": 2)...);
}
```

``` scss
// Test 2
@function test($a, $b) {
  @return $a $b;
}

test {
  content: test(("a": 1, "b": 2)...);
}
```

Expected result for both tests:

``` css
test {
  content: 1 2;
}
```

Results:

``` css
stdin:8: mixin test has no parameter named $"a"
```

``` css
stdin:8: function test has no parameter named $"a"
```
