### ISSUE TITLE
Variable length arguments "..." are not handled

### ISSUE THREAD

**Issue by gregtillbrook** [sass/libsass#73]
Hi again, 

Its not currently possible to use variable length arguments, e.g.;

``` css
@mixin box-shadow($shadow...) { 
  -webkit-box-shadow: $shadow;
     -moz-box-shadow: $shadow;
          box-shadow: $shadow;
}
```

Im assuming you folks have a feature 2do list and me listing stuff that's not working will be no surprise to you? I figure these issue's are still useful to let you know what stuff people are most interested in?? - so i'll carry on until you tell me to stop   :smile:
