### ISSUE TITLE
Bug: transparent not recognized as color

### ISSUE THREAD

**Issue by am11** [sass/libsass#730]
Consider the following code:

``` scss
article {
  color: darken(black, 50);
}
```

generates:

``` css
article {
  color: black;
}
```

but when color is set to 'transparent':

``` scss
article {
  color: darken(transparent, 50);
}
```

it throws error:

> stdin:2: argument `$color` of `darken($color, $amount)` must be a color
> Backtrace:
>     stdin:2, in function `darken`
>     stdin:2

Expected (ruby-sass v3.4.7) output:

``` css
article {
  color: transparent;
}
```

Test case at https://github.com/sass/sass-spec/pull/174.

Credit: @macrozone for https://github.com/sass/node-sass/issues/570.
