### ISSUE TITLE
Spaces around minus symbol should not be mandatory if first argument is a function call

### ISSUE THREAD

**Issue by HugoGiraudel** [sass/libsass#733]
Related: https://github.com/sass/libsass/issues/535.

Test:

```scss
@function getter() {
  @return 42px;
}
 
foo {
  content: getter()-1;
  content: getter()- 1;
  content: getter() -1;
}
```

Expect:

```css
foo {
  content: 41px;
  content: 41px;
  content: 42px -1;
}
```

Result:

```css
foo {
  content: 42px -1;
  content: 41px;
  content: 42px -1;
}
```
