### ISSUE TITLE
BEM Modifiers With Number Prefixes

### ISSUE THREAD

**Issue by MethodGrab** [sass/libsass#738]
If a Sass 3.3 style BEM modifier starts with a number, it will fail to compile in libsass with the error `invalid property name`.

Tested against libsass 3.0.2 on SassMeister. Ruby Sass 3.4.9 compiles this without error.
Note: It's just modifier (`--`) that fails, BEM elements (`__`) work fine.

For example:

``` scss
.foo {
  &--bar { color: red; }
  &--1bar { color: blue;}
}
```

Should compile to

``` css
.foo--bar { color: red; }
.foo--1bar { color: blue; }
```

This example **will** compile as expected in libsass:

``` scss
.foo {
  &--bar { color: red; }
  &__1bar { color: blue;}
}
```
