### ISSUE TITLE
!default not applying to variables with null value

### ISSUE THREAD

**Issue by raphaelschroiff** [sass/libsass#740]
According to the sass docs "Variables with null values are treated as unassigned by !default"
but libsass seems to treat null values as assigned when using !default:

``` scss
$background: null;
$background: #fff !default;

.test {
  background-color: $background;
}
```

libsass 3.02 compiles this to

``` css
.test {
   }
```

Ruby sass compiles this to:

``` css
.test {
  background-color: #fff;
}
```

http://sassmeister.com/gist/a2e8a2424c963dd72098
