### ISSUE TITLE
str-slice and str-insert should normalise quotes to double quotes

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#763]
Given

``` scss
foo {
  a: str-slice("abcd", 1, 1);
  b: str-slice('abcd', 1, 1);
  c: str-slice(abcd, 1, 1);

  d: str-insert("abcd", "X", 1);
  e: str-insert("abcd", 'X', 1);
  f: str-insert('abcd', "X", 1);
  g: str-insert('abcd', 'X', 1);
}
```

Ruby sass 3.4

``` css
foo {
  a: "a";
  b: "a";
  c: a;
  d: "Xabcd";
  e: "Xabcd";
  f: "Xabcd";
  g: "Xabcd"; }
```

Libsass 3.1.0-beta

``` css
foo {
  a: "a";
  b: 'a';
  c: a;
  d: "Xabcd";
  e: "Xabcd";
  f: 'Xabcd';
  g: 'Xabcd'; }
```

Spec added sass/sass-spec#195
