### ISSUE TITLE
Segmentation fault when content block is omittted for mixins

### ISSUE THREAD

**Issue by dahlia** [sass/libsass#77]
Libsass segfaults when a mixin takes content block but it’s not provided e.g.:

``` scss
@mixin m {
  .m {
    color: red;
    @content;
  }
}
div.a {
  @include m;
}
```
