### ISSUE TITLE
source maps ignoring commented out lines

### ISSUE THREAD

**Issue by philippkuehn** [sass/libsass#771]
Hey, i have a problem to get the source maps working.
 
```scss
@import "base/reset";
    
body {
  color: blue;
}
```

gives me for the body line 3 which is correct.

```scss
// @import "base/reset";
    
body {
  color: blue;
}
```

gives me for the body line 1 which is false.

It seems that all commented out lines are ignored in calculating the line numbers for the source map.
