### ISSUE TITLE
Invalid multiplication (px * px) crashes

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#789]
This code produces a crash with current master:

``` CSS
div {
    $a: 1px;
    $b: 2px;
    foo: $a * $b;
}
```

The test suite does not include this case!
All other math operations work correctly!
