### ISSUE TITLE
@media query with interpolant renders incorrectly

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#803]
A regression was introduced in #800 which causes @media #{foo} to render incorrect if $foo was a media query list.

```scss
$query-string: "(min-width: 0) and (max-width: 599px),  (min-width: 600px) and (max-width: 899px)";
@media #{$query-string} {
  .foo {
    content: bar;
  }
}
```

**expected**

```css
@media (min-width: 0) and (max-width: 599px), (min-width: 600px) and (max-width: 899px) {
  foo {
    bar: baz; } }
```

**actual**

```css
@media (min-width: 0) and (max-width: 599px) {
  foo {
    bar: baz; } }
```

Specs added https://github.com/sass/sass-spec/pull/223.
