### ISSUE TITLE
str-slice returns incorrect value when last $end-at is omitted

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#815]
```scss
foo {
    foo: str-slice("bar", 1, 2);
    bar: str-slice("bar", 3);
}
```

expected

```css
foo {
  foo: "ba";
  bar: "r"; }
```

actual

```css
foo {
  foo: "ba";
  bar: ""; }
```

This is a regression in 3.1.0. Specs added https://github.com/sass/sass-spec/pull/225.
