### ISSUE TITLE
Should normalize string function arguments to double quotes

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#817]
```scss
foo {
  foo: url('foo/bar.baz');
  foo: url("foo/bar.baz");
  foo: url(foo/bar.baz);
  foo: foo('foo/bar.baz');
  foo: foo("foo/bar.baz"); }
```

sass 4.1.9

```css
foo {
  foo: url("foo/bar.baz");
  foo: url("foo/bar.baz");
  foo: url(foo/bar.baz);
  foo: foo("foo/bar.baz");
  foo: foo("foo/bar.baz"); }
```

libsass 3.1.0

```css
foo {
  foo: url('foo/bar.baz');
  foo: url("foo/bar.baz");
  foo: url(foo/bar.baz);
  foo: foo('foo/bar.baz');
  foo: foo("foo/bar.baz"); }
```

Specs added https://github.com/sass/sass-spec/pull/226.
