### ISSUE TITLE
@charset not inserted if utf8 char appears in top comment

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#820]
```scss
@charset "UTF-8";
/*!  Force output of above line by adding a unicode character. ♫ */
foo {
  height: 100%; }
```

sass 3.4.9

```css
@charset "UTF-8";
/*!  Force output of above line by adding a unicode character. ♫ */
foo {
  height: 100%; }

```

Libsass master

```css
/*!  Force output of above line by adding a unicode character. ♫ */
foo {
  height: 100%; }
```

This works as expected if the comment appears after some css i.e.

```scss
@charset "UTF-8";
html, body {
  height: 100%; }
/*!  Force output of above line by adding a unicode character. ♫ */

```

Specs added https://github.com/sass/sass-spec/pull/228
***
Regression introduced in https://github.com/sass/libsass/commit/e9ef4b40a7b079ec52471e0e090e5ef9c607ab9a

/cc @mgreter
