### ISSUE TITLE
Nested @extends possible regression

### ISSUE THREAD

**Issue by LaurentGoderre** [sass/libsass#823]
This might be related to #592, the following code is compiling fine in libsass 2.1-beta but no in 3.x

```scss
%test {
    > {
        .red {
            color: #F00;
        }
    }
}

p {
    @extend %test;

    > {
        a {
            @extend %test;
        }
    }
}
```

In 2.1-beta I get

```css
p > .red, p > a > .red {
  color: #F00; 
}
```

and in 3.x I get

```css
p > .red {
  color: #F00; 
}
```
