### ISSUE TITLE
Can't use modulus operator on the result of a function

### ISSUE THREAD

**Issue by ejdyksen** [sass/libsass#857]
Here's the contents of my test sass file:

```scss
$list: "item-1" "item-2" "item-3";

#hello {
  @if length($list) % 2 == 0 {
    color: blue;
  }

  @else {
    color: red;
  }
}
```

This was working in node-sass 1.2.3 and is broken in 2.0.0-beta. So that means it was broken sometime [between 5f3558d and cf7c1d1](https://github.com/sass/libsass/compare/5f3558d...cf7c1d1).

Background:
I'm getting a segfault when compiling [Neat](https://github.com/thoughtbot/neat), using node-sass 2.0.0-beta. [This line](https://github.com/thoughtbot/neat/blob/compat/app/assets/stylesheets/grid/_media.scss#L17) and [this line](https://github.com/thoughtbot/neat/blob/compat/app/assets/stylesheets/functions/_new-breakpoint.scss#L7) test the even-ness of the length of a list using mod (`%`).
