### ISSUE TITLE
desaturate() on grey colours saturates instead of doing nothing

### ISSUE THREAD

**Issue by anlutro** [sass/libsass#864]
```scss
div { color: desaturate(#999, 50%); }
```

I'd expect the result to be `#999999` but it is actually `#66cccc`.

Calling `desaturate()` with perfect white or black works as expected.
