### ISSUE TITLE
String interpolation quotation marks

### ISSUE THREAD

**Issue by tgecho** [sass/libsass#87]
Using string interpolation in the process of creating a string seems to make the quotation marks a bit stickier then they should be.

``` scss
$bar: "bar";
$foobar: "foo#{$bar}";
#{$bar} {
  #{$bar}: #{$bar};
  #{$bar}: $bar;
}
#{$foobar} {
  #{$foobar}: #{$foobar};
  #{$foobar}: $foobar;
}
```

sass

``` css
bar {
  bar: bar;
  bar: "bar"; }

foobar {
  foobar: foobar;
  foobar: "foobar"; }
```

sassc

``` css
bar {
  bar: bar;
  bar: "bar"; }

"foobar" {
  "foobar": "foobar";
  "foobar": "foobar"; }
```
