### ISSUE TITLE
Function names prefixed with '_' fail `function-exists()`

### ISSUE THREAD

**Issue by lunelson** [sass/libsass#877]
Just noticed this, in attempting to use @Hugogiraudel 's SassyJSON library. We probably need a more robust test to see if there are any other character combinations that cause the test to fail.

```scss
@function _test() {
  @return 'hello';
}

@function -test() {
  @return 'hello';
}

@function test() {
  @return 'world';
}

.test {
  out: function-exists('_test');
  out: function-exists('-test');
  out: function-exists('test');
}
```
```css
.test {
  out: false;
  out: true;
  out: true; }
```

**Comment by lunelson** [comment]
Update: this also breaks the `call()` function
```scss
@function _test() {
  @return 'hello';
}

@function -test() {
  @return 'hello';
}

@function test() {
  @return 'world';
}

.call {
  out: call('_test');
  out: call('-test');
  out: call('test');
}
```
```css
.call {
  out: _test();
  out: 'hello';
  out: 'world'; }
```
