### ISSUE TITLE
[idea] less syntax support

### ISSUE THREAD

**Issue by tristanlins** [sass/libsass#889]
I know less vs. sass/scss is a philosophic war.
But there are a lot of people like less more than sass/scss. They write some cool stuff. But mixing both worlds is not easy and must be done with grunt, gulp or with multiple `<link>` elements. It would be much easier if libsass would support less syntax as well.

Just for explanation, a simple (and stupid) example ;-)

`base.scss`
```scss
@import "variables"; // import a sass file
@import "typography"; // import a less file
```

`_variables.sass`
```sass
$font-stack: Helvetica, sans-serif
```

`_typography.less`
```less
body {
  font-family: @font-stack; // use the variable define in _variables.sass
}
```
