### ISSUE TITLE
variable compilation bug in "margin" shorthand property

### ISSUE THREAD

**Issue by callmecavs** [sass/libsass#893]
This Sass:
```css
$gutter: 20px;

.row {
  margin: 0 -$gutter;
}
```
Compiles to this CSS with **libsass**:
```
.row {
  margin: -20px;
}
```
But with **ruby sass** compiles to this CSS:
```
.row {
  margin: 0 -20px;
}
```
This compiles as expected:
```css
$gutter: 20px;

.row {
  margin: 0 (-$gutter);
}
```
