### ISSUE TITLE
`SASS_STYLE_COMPRESSED` fails to eliminate empty rules with comments

### ISSUE THREAD

**Issue by asottile** [sass/libsass#894]
Input:

```scss
a {/**/}
b {content: 'something so I have a non-empty expected output'}
```

Expected output (ruby sass + pyscss):

```
b{content:'something so I have a non-empty expected output'}
```

Output from libsass (using HEAD of https://github.com/dahlia/libsass-python (libsass 3.1.0))
```
a{}b{content:'something so I have a non-empty expected output'}
```
