### ISSUE TITLE
@media/mixin query trouble

### ISSUE THREAD

**Issue by twhid** [sass/libsass#91]
Greetings,

I'm looking for a way to speed up my team's workflow and libsass would be an excellent addition but for this one problem. I haven't been able to find a workaround.

Summarized below. Best regards,

scss input:

``` scss
@mixin simple-media-query($max-width, $min-width) {
      @media only screen and (max-width: $max-width) and (min-width: $min-width) {
        @content;
      }
}

@mixin test($value) {
    border-color: $value;
}

body 
{
    @include test("#ccc");
    @include simple-media-query(900px, 400px) {
        border-color: black;
    }
}
```

libsass (via sassc; incorrect; variable values aren't inserted)

``` css
body {
  border-color: "#ccc"; }
  @media only screen and (max-width: $max-width) and (min-width: $min-width) {
    body {
      border-color: black; } }

```

ruby sass (expected output)

``` css
body {
  border-color: "#ccc"; }
  @media only screen and (max-width: 900px) and (min-width: 400px) {
    body {
      border-color: black; } }

```
