### ISSUE TITLE
Base-level rules cannot contain the parent-selector-referencing character '&'.

### ISSUE THREAD

**Issue by anlutro** [sass/libsass#930]
This error started popping up recently. I was able to create a couple of minimal test cases.

The last good commit seems to be 77c1b23. I can pinpoint more closely with `git bisect` if needed.

Case 1:

```scss
$n: 1;
.foo {
  &:nth-child(#{$n}) {
    color: red;
  }
}
```

Case 2:

```scss
// test1.scss
.foo { @import "test2"; }

// test2.scss
&.bar { color: red; }
```

Tested against latest master (a2a21c3).
