### ISSUE TITLE
CSS comments inside selectors yields invalid top-level expression

### ISSUE THREAD

**Issue by anlutro** [sass/libsass#941]
The following SCSS (taken from normalize.css) causes an "invalid top-level expression" error.

Removing the `/* 1 */` comment makes it work.

```css
button,
html input[type="button"], /* 1 */
input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button; /* 2 */
  cursor: pointer; /* 3 */
}
```

I can write a sass-spec PR a bit later.
