### ISSUE TITLE
@extend throws error when extended directive contains media query containing referencing parent selector

### ISSUE THREAD

**Issue by telekid** [sass/libsass#943]
test.scss
``` scss
%dog {
    @media (min-width: 10px) {
        &:hover {
            display: none;
        }
    }
}

.puppy {
    @extend %dog;
    background-color: red;
}
```

Throws error in libsass:
``` json
{
  "message": "You may not @extend an outer selector from within @media.\nYou may only @extend selectors within the same directive.\nFrom \"@extend %dog\" on line 10 of test.scss\n",
  "column": 14,
  "line": 3,
  "file": "/Users/jake/Development/bug-test/test.scss",
  "status": 1
}
```
But correctly generates the following in Ruby Sass 3.4.13 (Selective Steve):
``` css
@media (min-width: 10px) {
  .puppy:hover {
    display: none; } }

.puppy {
  background-color: red; }
```

Note that I'm using libsass 3.2.x through this fork of node-sass:
https://github.com/kaij/node-sass/commit/d2b9b889d8eb061773664de259d162c86715077e
