### ISSUE TITLE
Mixin-exists fails if mixin contains underscores

### ISSUE THREAD

**Issue by jakob-e** [sass/libsass#952]
Mixin-exists fails if mixin contains underscores

````SCSS
@mixin block(){ 
	content:'block included';
}
@mixin block_element(){ 
	content:'block__element included';
}	
@mixin block__element(){ 
	content:'block__element included';
}
@mixin block--modifier(){ 
	content:'block--modifier included';
}	

@mixin underscore_error {}     
$underscore-error: not mixin-exists(underscore_error);

test {
  underscore-error: $underscore-error;
  mixin-exists-1: mixin-exists(block);
  mixin-exists-2: mixin-exists(block_element);  /* Fails ought to be true */
  mixin-exists-2: mixin-exists(block__element); /* Fails ought to be true */
  mixin-exists-3: mixin-exists(block--modifier);
  /* Include works in all cases */
  @include block();
  @include block_element();
  @include block__element();
  @include block--modifier();
}
`````
````CSS
test {
  underscore-error: true;
  mixin-exists-1: true;
  mixin-exists-2: false; /* Fails ought to be true */
  mixin-exists-2: false; /* Fails ought to be true */
  mixin-exists-3: true;
  /* Include works in all cases */
  content: 'block included';
  content: 'block__element included';
  content: 'block__element included';
  content: 'block--modifier included'; 
}

````

**Comment by mgreter** [comment]
This is fixed on latest master (probably https://github.com/sass/libsass/pull/888)

```CSS
test {
  underscore-error: false;
  mixin-exists-1: true;
  mixin-exists-2: true;
  /* Fails ought to be true */
  mixin-exists-2: true;
  /* Fails ought to be true */
  mixin-exists-3: true;
  /* Include works in all cases */
  content: 'block included';
  content: 'block__element included';
  content: 'block__element included';
  content: 'block--modifier included'; }
```

Please try to verify issues against latest master before posting them and you should always include the version of libsass you're currently using (plus OS and other related information) ... thanks!
