### ISSUE TITLE
wrong line in error message

### ISSUE THREAD

**Issue by rodneyrehm** [sass/libsass#972]
Considering the following (invalid) input:

```scss
$foo: 123px;

.bar {
  width: $bar;
}

bad-token-test
```
I get the error reported on *line 5* (`3.2.1-beta.2`) and the formatted error message looks as follows:

```
Error: invalid top-level expression
        on line 5 of stdin
>> }
   -^
```

`3.1.0` reports the error on *line 7*
