### ISSUE TITLE
& interpolation in selector causes segfault

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#978]
This causes a segfault on the latest master.

```scss
.foo {
  [baz="#{&}"] {
    foo: bar;
  }
}
```

Results in 

>[1]    37755 segmentation fault sassc test.scss

/cc @ekskimn this may be of interest to you.
