### ISSUE TITLE
Unable to append variable-length parameters after optional parameter

### ISSUE THREAD

**Issue by davidkpiano** [sass/libsass#980]
A function that is called with an optional parameter followed by a variable-length parameter throws the error `"Optional parameters may not be combined with variable-length parameters"` despite being valid in Ruby Sass.

```scss
@function foo($value, $default: 13, $args...) {
  $res: $value + $default;
  @if length($args) != 0 {
    $res: $res + nth($args, 1);
  }
  @return $res;
}

.test {
  value: foo(3); // expected: 16
  value: foo(3, 4); // expected: 7
  value: foo(3, 4, 5, 6); // expected: 12
}

// RUBY SASS
.test {
  value: 16;
  value: 7;
  value: 12;
}

// LIBSASS
// Throws "optional parameters may not be combined with variable-length parameters"
```
