### ISSUE TITLE
Regression: String functions

### ISSUE THREAD

**Issue by Snugug** [sass/libsass#988]
`node-sass` 3.0.0-beta which gives me access to Libsass 3.2.0-beta.2 and I've discovered a regression: In Libsass 3.1, Hugo's [`str-replace` function](http://sassmeister.com/gist/1b4f2da5527830088e4d) works without a hitch. I believe it may be related to #987, but this particular function worked in 3.1 and no longer works in 3.2:

```scss
@function str-replace($string, $search, $replace: '') {
  $index: str-index($string, $search);

  @if $index {
    @return str-slice($string, 1, $index - 1) + $replace + str-replace(str-slice($string, $index + str-length($search)), $search, $replace);
  }

  @return $string;
}


$string: 'Foo Bar Baz Qux';

.foo {
  content: str-replace($string, ' ', '-');
}
```

**Original Output**

```css
.foo {
  content: "Foo-Bar-Baz-Qux"; }
```

**Regressed Output in Libsass 3.2

```css
.foo {
  content: "Foo"-Bar-Baz-Qux; }
```

How should I go about writing a test to catch this? It's not _Sass_ function, but it's a regression that should be tested for.
